posnk kernel: arch/i386/paging.c File Reference
paging.c File Reference
#include "arch/i386/paging.h"
#include "util/llist.h"
#include "kernel/heapmm.h"
#include "kernel/process.h"
#include "kernel/scheduler.h"
#include "config.h"
#include <string.h>
Data Structures
struct i386_set_pd_param
Typedefs
typedef struct i386_set_pd_param i386_set_pd_param_t
Functions
void paging_switch_dir (page_dir_t *new_dir)
void * i386_alloc_page ()
page_dir_t * paging_create_dir ()
void paging_free_dir (page_dir_t *dir)
int paging_set_pd_iterator (llist_t *node, void *param)
void paging_map (void *virt_addr, physaddr_t phys_addr, page_flags_t flags)
void paging_unmap (void *virt_addr)
void paging_tag (void *virt_addr, page_tag_t tag)
page_tag_t paging_get_tag (void *virt_addr)
void i386_paging_enable ()
void i386_init_switch_gdt (void)
void paging_init ()
uintptr_t paging_get_physical_address (void *virt_addr)
Variables
llist_t i386_page_directory_list
arch/i386/paging.c
i386_page_dir_list_t i386_page_dir_list_initial
page_dir_t i386_page_dir_initial
uint32_t i386_force_order
Typedef Documentation
typedef struct i386_set_pd_param i386_set_pd_param_t
Todo:
: Implement
Function Documentation
void* i386_alloc_page ()
Definition at line 48 of file paging.c.
References heapmm_alloc_page(), NULL, paging_active_dir, and physmm_alloc_frame().
Referenced by paging_create_dir(), and paging_init().
void i386_init_switch_gdt (void)
Referenced by paging_init().
void i386_paging_enable ()
Definition at line 220 of file paging.c.
Referenced by paging_init().
page_dir_t* paging_create_dir ()
Definition at line 55 of file paging.c.
References page_dir::content, i386_page_dir_list::dir, i386_page_dir::directory, process_mmap::flags, heapmm_alloc(), heapmm_alloc_page(), heapmm_free(), i386_alloc_page(), I386_PAGE_FLAG_NOCACHE, I386_PAGE_FLAG_PRESENT, I386_PAGE_FLAG_RW, i386_phys_copy_frame(), I386_PTADDR, llist_add_end(), memset(), NULL, i386_page_table::pages, paging_active_dir, paging_get_physical_address(), paging_handle_out_of_memory(), paging_map(), physmm_alloc_frame(), PHYSMM_NO_FRAME, PHYSMM_PAGE_SIZE, PROCESS_MMAP_FLAG_PUBLIC, and procvmm_get_memory_region().
Referenced by paging_init(), and scheduler_fork_to().
void paging_free_dir (page_dir_t * dir)
uintptr_t paging_get_physical_address (void * virt_addr)
Definition at line 265 of file paging.c.
References page_dir::content, i386_page_dir::directory, I386_ADDR_TO_PD_IDX, I386_ADDR_TO_PTEPTR, I386_PAGE_FLAG_PRESENT, and paging_active_dir.
Referenced by ata_initialize(), ata_read(), ata_write(), i386_init_mm(), paging_create_dir(), paging_switch_dir(), procvmm_unmmap(), scheduler_exsig(), and scheduler_switch_task().
page_tag_t paging_get_tag (void * virt_addr)
Definition at line 214 of file paging.c.
References I386_ADDR_TO_PTEPTR.
void paging_init ()
Definition at line 230 of file paging.c.
References page_dir::content, i386_page_dir::directory, I386_ADDR_TO_PT_IDX, i386_alloc_page(), i386_init_switch_gdt(), I386_PAGE_FLAG_GLOBAL, I386_PAGE_FLAG_NOCACHE, I386_PAGE_FLAG_PRESENT, I386_PAGE_FLAG_RW, I386_PAGE_FLAG_USER, i386_paging_enable(), llist_create(), memset(), i386_page_table::pages, paging_active_dir, and paging_create_dir().
Referenced by i386_init_mm().
void paging_map (void * virt_addr, physaddr_t phys_addr, page_flags_t flags)
Todo:
: Determine whether we have to free previously mapped frame
Definition at line 142 of file paging.c.
References page_dir::content, i386_page_dir::directory, I386_ADDR_TO_PD_IDX, I386_ADDR_TO_PT_IDX, I386_ADDR_TO_PTEPTR, I386_PAGE_FLAG_GLOBAL, I386_PAGE_FLAG_NOCACHE, I386_PAGE_FLAG_PRESENT, I386_PAGE_FLAG_RW, I386_PAGE_FLAG_USER, i386_set_pd_param::index, llist_iterate_select(), memset(), i386_page_table::pages, paging_active_dir, paging_handle_out_of_memory(), PAGING_PAGE_FLAG_NOCACHE, PAGING_PAGE_FLAG_RW, PAGING_PAGE_FLAG_USER, paging_set_pd_iterator(), physmm_alloc_frame(), PHYSMM_NO_FRAME, and i386_set_pd_param::value.
Referenced by heapmm_request_core(), i386_init_load_modules(), i386_init_mm(), paging_create_dir(), paging_handle_fault(), and procvmm_handle_fault().
int paging_set_pd_iterator (llist_t * node, void * param)
Definition at line 134 of file paging.c.
References i386_page_dir::directory.
Referenced by paging_map().
void paging_switch_dir (page_dir_t * new_dir)
Definition at line 42 of file paging.c.
References page_dir::content, paging_active_dir, and paging_get_physical_address().
void paging_tag (void * virt_addr, page_tag_t tag)
Definition at line 207 of file paging.c.
References I386_ADDR_TO_PTEPTR.
Referenced by heapmm_request_core(), i386_init_mm(), and paging_handle_fault().
void paging_unmap (void * virt_addr)
Definition at line 200 of file paging.c.
References I386_ADDR_TO_PTEPTR, and I386_PAGE_FLAG_PRESENT.
Referenced by i386_init_load_modules(), procvmm_handle_fault(), and procvmm_unmmap().
Variable Documentation
uint32_t i386_force_order
Definition at line 24 of file paging.c.
page_dir_t i386_page_dir_initial
Definition at line 22 of file paging.c.
i386_page_dir_list_t i386_page_dir_list_initial
Definition at line 21 of file paging.c.
llist_t i386_page_directory_list
arch/i386/paging.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 30-03-2014 - Created
Definition at line 20 of file paging.c.