posnk kernel: driver/block/pata/ata.c File Reference
ata.c File Reference
#include "config.h"
#include <sys/errno.h>
#include "arch/i386/x86.h"
#include "driver/block/pata/ata.h"
#include "kernel/earlycon.h"
#include "kernel/paging.h"
#include "kernel/heapmm.h"
#include "kernel/device.h"
#include "fs/mbr.h"
Functions
uint8_t ata_read_port (ata_device_t *device, uint16_t port)
void ata_write_port (ata_device_t *device, uint16_t port, uint8_t value)
void ata_write_port_long (ata_device_t *device, uint16_t port, uint32_t value)
void ata_read_data (ata_device_t *device, uint16_t port, uint8_t *buffer, size_t count)
void ata_write_data (ata_device_t *device, uint16_t port, uint8_t *buffer, size_t count)
int ata_poll_wait (ata_device_t *device)
void ata_set_interrupts (ata_device_t *device, int enabled)
int ata_irq_handler (irq_id_t irq_id, void *context)
void ata_global_initialize ()
void ata_load_partition_table (ata_device_t *device, int drive)
void ata_initialize (ata_device_t *device)
void ata_setup_lba_transfer (ata_device_t *device, int drive, ata_lba_t lba, uint16_t count)
int ata_read (ata_device_t *device, int drive, ata_lba_t lba, uint8_t *buffer, uint16_t count)
int ata_write (ata_device_t *device, int drive, ata_lba_t lba, uint8_t *buffer, uint16_t count)
int ata_blk_open (dev_t device, int fd, int options)
int ata_blk_close (dev_t device, int fd)
int ata_blk_write (dev_t device, off_t file_offset, void *buffer)
int ata_blk_read (dev_t device, off_t file_offset, void *buffer)
int ata_blk_ioctl (dev_t device, int fd, int func, int arg)
Variables
int ata_bus_number_counter = 0
driver/block/pata/ata.c
int ata_interrupt_enabled = 0
int ata_global_inited = 0
ata_device_t ** ata_buses
ata_prd_t * ata_prd_list
blk_ops_t ata_block_driver_ops
Function Documentation
int ata_blk_close (dev_t device, int fd)
Definition at line 443 of file ata.c.
int ata_blk_ioctl (dev_t device, int fd, int func, int arg)
Definition at line 498 of file ata.c.
int ata_blk_open (dev_t device, int fd, int options)
Definition at line 441 of file ata.c.
int ata_blk_read (dev_t device, off_t file_offset, void * buffer)
Definition at line 472 of file ata.c.
References ata_read(), ata_device::drives, EIO, ENODEV, ENOSPC, MAJOR, MINOR, NULL, ata_drive::partitions, partition_info::size, partition_info::start, and partition_info::type.
int ata_blk_write (dev_t device, off_t file_offset, void * buffer)
Definition at line 445 of file ata.c.
References ata_write(), ata_device::drives, EIO, ENODEV, ENOSPC, MAJOR, MINOR, NULL, ata_drive::partitions, partition_info::size, partition_info::start, and partition_info::type.
void ata_global_initialize ()
Definition at line 171 of file ata.c.
References ata_global_inited, and heapmm_alloc().
Referenced by ata_initialize().
void ata_initialize (ata_device_t * device)
Todo:
: Wait here ? osdev wiki says so but does not specify why.(no support for kernel-land sleeps yet)
Todo:
: ^^^^
Todo:
: Handle ATAPI devices
Todo:
: Hook this somewhere
Definition at line 184 of file ata.c.
References ata_block_driver_ops, ata_bus_number_counter, ATA_BUSMASTER_PRDT_PTR_PORT, ATA_CMD_IDENTIFY, ATA_COMMAND_PORT, ATA_DATA_PORT, ATA_DRIVE_ATA, ATA_DRIVE_HEAD_PORT, ATA_DRIVE_NONE, ATA_DRVSEL_CHS, ata_global_inited, ata_global_initialize(), ATA_IDENT_CAP_FLAG_DMA, ATA_IDENT_CAP_FLAG_LBA, ATA_IDENT_CAPABILITIES, ATA_IDENT_CMDSET_FLAG_LBA48, ATA_IDENT_COMMANDSETS, ATA_IDENT_CYLINDERS, ATA_IDENT_HEADS, ATA_IDENT_LLONG, ATA_IDENT_LONG, ATA_IDENT_MAX_LBA, ATA_IDENT_MAX_LBA_EXT, ATA_IDENT_MODEL, ATA_IDENT_SECTORS, ATA_IDENT_SERIAL, ATA_IDENT_SHORT, ata_interrupt_enabled, ata_irq_handler(), ata_load_partition_table(), ATA_MODE_CHS, ATA_MODE_LBA28, ATA_MODE_LBA48, ata_poll_wait(), ATA_PRD_LIST_SIZE, ata_read_data(), ata_read_port(), ata_set_interrupts(), ATA_STATUS_PORT, ata_write_port(), ata_write_port_long(), blk_dev::block_size, ata_device::bus_number, blk_dev::cache_size, ata_drive::capabilities, ata_drive::command_sets, ata_drive::cylinders, debugcon_printf, device_block_register(), ata_device::drives, ata_drive::heads, heapmm_alloc(), heapmm_alloc_alligned(), ata_drive::ident_data, ata_device::int_wait, interrupt_register_handler(), ata_device::irq, ata_drive::lba_mode, ata_device::lock, blk_dev::major, ata_drive::max_lba, blk_dev::minor_count, ata_drive::model, blk_dev::name, blk_dev::ops, paging_get_physical_address(), ata_drive::sectors_per_track, semaphore_alloc(), semaphore_up(), ata_drive::serial, and ata_drive::type.
Referenced by ata_pci_probe().
int ata_irq_handler (irq_id_t irq_id, void * context)
Definition at line 154 of file ata.c.
References ATA_BM_STATUS_FLAG_DMAGO, ATA_BM_STATUS_FLAG_IREQ, ATA_BUSMASTER_COMMAND_PORT, ATA_BUSMASTER_STATUS_PORT, ata_read_port(), ATA_STATUS_PORT, ata_write_port(), ata_device::bmio_base, ata_device::int_status, ata_device::int_wait, and semaphore_up().
Referenced by ata_initialize().
void ata_load_partition_table (ata_device_t * device, int drive)
Definition at line 177 of file ata.c.
References ata_read(), ata_device::drives, mbr_parse(), and ata_drive::partitions.
Referenced by ata_initialize().
int ata_poll_wait (ata_device_t * device)
Todo:
: Timeout
Definition at line 133 of file ata.c.
References ATA_ALTSTATUS_PORT, ata_read_port(), ATA_STATUS_FLAG_BSY, ATA_STATUS_FLAG_DF, ATA_STATUS_FLAG_DRQ, ATA_STATUS_FLAG_ERR, and ATA_STATUS_PORT.
Referenced by ata_initialize(), ata_read(), and ata_write().
int ata_read (ata_device_t * device, int drive, ata_lba_t lba, uint8_t * buffer, uint16_t count)
Todo:
: Implement a work queue
Definition at line 322 of file ata.c.
References ATA_BM_CMD_FLAG_DMA_ENABLE, ATA_BM_CMD_FLAG_READ, ATA_BM_STATUS_FLAG_ERR, ATA_BUSMASTER_COMMAND_PORT, ATA_BUSMASTER_STATUS_PORT, ATA_CMD_READ_DMA, ATA_CMD_READ_DMA_EXT, ATA_CMD_READ_PIO, ATA_CMD_READ_PIO_EXT, ATA_COMMAND_PORT, ATA_DATA_PORT, ATA_IDENT_CAP_FLAG_DMA, ata_interrupt_enabled, ATA_MODE_LBA48, ata_poll_wait(), ATA_PRD_END_OF_LIST, ata_read_data(), ata_read_port(), ata_setup_lba_transfer(), ATA_STATUS_FLAG_DF, ATA_STATUS_FLAG_DRQ, ATA_STATUS_FLAG_ERR, ata_write_port(), ata_prd::buffer_phys, ata_device::bus_number, ata_prd::byte_count, ata_drive::capabilities, debugcon_printf, ata_device::drives, ata_prd::end_of_list, ata_device::int_status, ata_device::int_wait, ata_drive::lba_mode, ata_device::lock, paging_get_physical_address(), semaphore_down(), and semaphore_up().
Referenced by ata_blk_read(), and ata_load_partition_table().
void ata_read_data (ata_device_t * device, uint16_t port, uint8_t * buffer, size_t count)
Definition at line 83 of file ata.c.
References ATA_CONTROL_PORT, ATA_DCR_FLAG_HIGHORDER, ata_write_port(), ata_device::bmio_base, ata_device::ctrl_base, ata_device::ctrl_reg, i386_inl(), and ata_device::pio_base.
Referenced by ata_initialize(), and ata_read().
uint8_t ata_read_port (ata_device_t * device, uint16_t port)
Definition at line 33 of file ata.c.
References ATA_CONTROL_PORT, ATA_DCR_FLAG_HIGHORDER, ata_write_port(), ata_device::bmio_base, ata_device::ctrl_base, ata_device::ctrl_reg, i386_inb(), and ata_device::pio_base.
Referenced by ata_initialize(), ata_irq_handler(), ata_poll_wait(), ata_read(), and ata_write().
void ata_set_interrupts (ata_device_t * device, int enabled)
Definition at line 148 of file ata.c.
References ATA_CONTROL_PORT, ATA_DCR_FLAG_INT_DIS, ata_write_port(), and ata_device::ctrl_reg.
Referenced by ata_initialize().
void ata_setup_lba_transfer (ata_device_t * device, int drive, ata_lba_t lba, uint16_t count)
Definition at line 278 of file ata.c.
References ATA_CYL_HIGH_PORT, ATA_CYL_LOW_PORT, ATA_DRIVE_HEAD_PORT, ATA_DRVSEL_CHS, ATA_DRVSEL_LBA, ATA_LBA_0_PORT, ATA_LBA_1_PORT, ATA_LBA_2_PORT, ATA_LBA_3_PORT, ATA_LBA_4_PORT, ATA_LBA_5_PORT, ATA_MODE_CHS, ATA_MODE_LBA28, ATA_MODE_LBA48, ATA_SECTOR_COUNT_HIGH_PORT, ATA_SECTOR_COUNT_LOW_PORT, ATA_SECTOR_NO_PORT, ata_write_port(), debugcon_printf, ata_device::drives, ata_drive::heads, ata_drive::lba_mode, and ata_drive::sectors_per_track.
Referenced by ata_read(), and ata_write().
int ata_write (ata_device_t * device, int drive, ata_lba_t lba, uint8_t * buffer, uint16_t count)
Todo:
: Implement a work queue
Definition at line 379 of file ata.c.
References ATA_BM_CMD_FLAG_DMA_ENABLE, ATA_BM_STATUS_FLAG_ERR, ATA_BUSMASTER_COMMAND_PORT, ATA_BUSMASTER_STATUS_PORT, ATA_CMD_CACHE_FLUSH, ATA_CMD_CACHE_FLUSH_EXT, ATA_CMD_WRITE_DMA, ATA_CMD_WRITE_DMA_EXT, ATA_CMD_WRITE_PIO, ATA_CMD_WRITE_PIO_EXT, ATA_COMMAND_PORT, ATA_DATA_PORT, ATA_IDENT_CAP_FLAG_DMA, ata_interrupt_enabled, ATA_MODE_LBA48, ata_poll_wait(), ATA_PRD_END_OF_LIST, ata_read_port(), ata_setup_lba_transfer(), ATA_STATUS_FLAG_DF, ATA_STATUS_FLAG_DRQ, ATA_STATUS_FLAG_ERR, ata_write_data(), ata_write_port(), ata_prd::buffer_phys, ata_device::bus_number, ata_prd::byte_count, ata_drive::capabilities, debugcon_printf, ata_device::drives, ata_prd::end_of_list, ata_device::int_status, ata_device::int_wait, ata_drive::lba_mode, ata_device::lock, paging_get_physical_address(), semaphore_down(), and semaphore_up().
Referenced by ata_blk_write().
void ata_write_data (ata_device_t * device, uint16_t port, uint8_t * buffer, size_t count)
Definition at line 108 of file ata.c.
References ATA_CONTROL_PORT, ATA_DCR_FLAG_HIGHORDER, ata_write_port(), ata_device::bmio_base, ata_device::ctrl_base, ata_device::ctrl_reg, i386_outl(), and ata_device::pio_base.
Referenced by ata_write().
void ata_write_port (ata_device_t * device, uint16_t port, uint8_t value)
Definition at line 51 of file ata.c.
References ATA_CONTROL_PORT, ATA_DCR_FLAG_HIGHORDER, ata_write_port(), ata_device::bmio_base, ata_device::ctrl_base, ata_device::ctrl_reg, i386_outb(), and ata_device::pio_base.
Referenced by ata_initialize(), ata_irq_handler(), ata_read(), ata_read_data(), ata_read_port(), ata_set_interrupts(), ata_setup_lba_transfer(), ata_write(), ata_write_data(), ata_write_port(), and ata_write_port_long().
void ata_write_port_long (ata_device_t * device, uint16_t port, uint32_t value)
Definition at line 67 of file ata.c.
References ATA_CONTROL_PORT, ATA_DCR_FLAG_HIGHORDER, ata_write_port(), ata_device::bmio_base, ata_device::ctrl_base, ata_device::ctrl_reg, i386_outl(), and ata_device::pio_base.
Referenced by ata_initialize().
Variable Documentation
blk_ops_t ata_block_driver_ops
Initial value:
 {
                &ata_blk_open,
                &ata_blk_close,
                &ata_blk_write,
                &ata_blk_read,
                &ata_blk_ioctl
}
Definition at line 503 of file ata.c.
Referenced by ata_initialize().
int ata_bus_number_counter = 0
driver/block/pata/ata.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 02-07-2014 - Created
Definition at line 23 of file ata.c.
Referenced by ata_initialize().
ata_device_t** ata_buses
Definition at line 27 of file ata.c.
int ata_global_inited = 0
Definition at line 25 of file ata.c.
Referenced by ata_global_initialize(), and ata_initialize().
int ata_interrupt_enabled = 0
Definition at line 24 of file ata.c.
Referenced by ata_initialize(), ata_read(), and ata_write().
ata_prd_t* ata_prd_list
Definition at line 29 of file ata.c.