posnk kernel: include/driver/block/pata/ata.h File Reference
ata.h File Reference
#include <stdint.h>
#include "kernel/interrupt.h"
#include "kernel/synch.h"
#include "fs/partition.h"
Data Structures
struct ata_drive
struct ata_device
struct ata_prd
Macros
#define ATA_DATA_PORT (0)
driver/block/pata/ata.h
#define ATA_FEATURE_PORT (1)
#define ATA_ERROR_PORT (1)
#define ATA_SECTOR_NO_PORT (3)
#define ATA_CYL_LOW_PORT (4)
#define ATA_CYL_HIGH_PORT (5)
#define ATA_DRIVE_HEAD_PORT (6)
#define ATA_SECTOR_COUNT_LOW_PORT (2)
#define ATA_SECTOR_COUNT_HIGH_PORT (8)
#define ATA_LBA_0_PORT (3)
#define ATA_LBA_1_PORT (4)
#define ATA_LBA_2_PORT (5)
#define ATA_LBA_3_PORT (9)
#define ATA_LBA_4_PORT (10)
#define ATA_LBA_5_PORT (11)
#define ATA_COMMAND_PORT (7)
#define ATA_STATUS_PORT (7)
#define ATA_CONTROL_PORT (12)
#define ATA_ALTSTATUS_PORT (12)
#define ATA_DEVADDRESS_PORT (13)
#define ATA_BUSMASTER_COMMAND_PORT (14)
#define ATA_BUSMASTER_STATUS_PORT (16)
#define ATA_BUSMASTER_PRDT_PTR_PORT (18)
#define ATA_BM_CMD_FLAG_DMA_ENABLE (1<<0)
#define ATA_BM_CMD_FLAG_READ (1<<3)
#define ATA_BM_STATUS_FLAG_SIMPLEX (1<<7)
#define ATA_BM_STATUS_FLAG_S_DMA (1<<6)
#define ATA_BM_STATUS_FLAG_M_DMA (1<<5)
#define ATA_BM_STATUS_FLAG_IREQ (1<<2)
#define ATA_BM_STATUS_FLAG_ERR (1<<1)
#define ATA_BM_STATUS_FLAG_DMAGO (1<<0)
#define ATA_STATUS_FLAG_ERR (1<<0)
#define ATA_STATUS_FLAG_DRQ (1<<3)
#define ATA_STATUS_FLAG_SRV (1<<4)
#define ATA_STATUS_FLAG_DF (1<<5)
#define ATA_STATUS_FLAG_RDY (1<<6)
#define ATA_STATUS_FLAG_BSY (1<<7)
#define ATA_ERROR_FLAG_BBK (1<<7)
#define ATA_ERROR_FLAG_UNC (1<<6)
#define ATA_ERROR_FLAG_MC (1<<5)
#define ATA_ERROR_FLAG_IDNF (1<<4)
#define ATA_ERROR_FLAG_MCR (1<<3)
#define ATA_ERROR_FLAG_ABRT (1<<2)
#define ATA_ERROR_FLAG_TK0NF (1<<1)
#define ATA_ERROR_FLAG_AMNF (1<<0)
#define ATA_DCR_FLAG_INT_DIS (1<<1)
#define ATA_DCR_FLAG_SOFTRESET (1<<2)
#define ATA_DCR_FLAG_HIGHORDER (1<<7)
#define ATA_CMD_READ_PIO (0x20)
#define ATA_CMD_READ_PIO_EXT (0x24)
#define ATA_CMD_READ_DMA (0xC8)
#define ATA_CMD_READ_DMA_EXT (0x25)
#define ATA_CMD_WRITE_PIO (0x30)
#define ATA_CMD_WRITE_PIO_EXT (0x34)
#define ATA_CMD_WRITE_DMA (0xCA)
#define ATA_CMD_WRITE_DMA_EXT (0x35)
#define ATA_CMD_CACHE_FLUSH (0xE7)
#define ATA_CMD_CACHE_FLUSH_EXT (0xEA)
#define ATA_CMD_PACKET (0xA0)
#define ATA_CMD_IDENTIFY_PACKET (0xA1)
#define ATA_CMD_IDENTIFY (0xEC)
#define ATA_IDENT_DEVICETYPE (0)
#define ATA_IDENT_CYLINDERS (2)
#define ATA_IDENT_HEADS (6)
#define ATA_IDENT_SECTORS (12)
#define ATA_IDENT_SERIAL (20)
#define ATA_IDENT_MODEL (54)
#define ATA_IDENT_CAPABILITIES (98)
#define ATA_IDENT_FIELDVALID (106)
#define ATA_IDENT_MAX_LBA (120)
#define ATA_IDENT_COMMANDSETS (164)
#define ATA_IDENT_MAX_LBA_EXT (200)
#define ATA_IDENT_SHORT(DV, DR, PT) (* ((uint16_t *) &(DV->drives[DR].ident_data[PT])))
#define ATA_IDENT_LONG(DV, DR, PT) (* ((uint32_t *) &(DV->drives[DR].ident_data[PT])))
#define ATA_IDENT_LLONG(DV, DR, PT) (* ((uint64_t *) &(DV->drives[DR].ident_data[PT])))
#define ATA_IDENT_CMDSET_FLAG_LBA48 (1<<26)
#define ATA_IDENT_CAP_FLAG_DMA (1<<8)
#define ATA_IDENT_CAP_FLAG_LBA (1<<9)
#define ATA_DRVSEL_LBA(ndrv, buppr) (0xE0 | (((ndrv)&1) << 4) | ((buppr)&0xF))
#define ATA_DRVSEL_CHS(ndrv, nhead) (0xA0 | (((ndrv)&1) << 4) | ((nhead)&0xF))
#define ATA_PRD_END_OF_LIST (0x8000)
#define ATA_DRIVE_NONE (0)
#define ATA_DRIVE_ATA (1)
#define ATA_DRIVE_ATAPI (2)
#define ATA_MODE_CHS (0)
#define ATA_MODE_LBA28 (1)
#define ATA_MODE_LBA48 (2)
#define ATA_PRD_LIST_SIZE (16)
Typedefs
typedef struct ata_device ata_device_t
typedef struct ata_drive ata_drive_t
typedef struct ata_prd ata_prd_t
typedef uint64_t ata_lba_t
Functions
uint8_t ata_read_port (ata_device_t *device, uint16_t port)
void ata_write_port (ata_device_t *device, uint16_t port, uint8_t value)
int ata_poll_wait (ata_device_t *device)
void ata_set_interrupts (ata_device_t *device, int enabled)
void ata_initialize (ata_device_t *device)
int ata_write (ata_device_t *device, int drive, ata_lba_t lba, uint8_t *buffer, uint16_t count)
int ata_read (ata_device_t *device, int drive, ata_lba_t lba, uint8_t *buffer, uint16_t count)
Macro Definition Documentation
#define ATA_ALTSTATUS_PORT (12)
Definition at line 43 of file ata.h.
Referenced by ata_poll_wait().
#define ATA_BM_CMD_FLAG_DMA_ENABLE (1<<0)
Definition at line 51 of file ata.h.
Referenced by ata_read(), and ata_write().
#define ATA_BM_CMD_FLAG_READ (1<<3)
Definition at line 52 of file ata.h.
Referenced by ata_read().
#define ATA_BM_STATUS_FLAG_DMAGO (1<<0)
Definition at line 59 of file ata.h.
Referenced by ata_irq_handler().
#define ATA_BM_STATUS_FLAG_ERR (1<<1)
Definition at line 58 of file ata.h.
Referenced by ata_read(), and ata_write().
#define ATA_BM_STATUS_FLAG_IREQ (1<<2)
Definition at line 57 of file ata.h.
Referenced by ata_irq_handler().
#define ATA_BM_STATUS_FLAG_M_DMA (1<<5)
Definition at line 56 of file ata.h.
#define ATA_BM_STATUS_FLAG_S_DMA (1<<6)
Definition at line 55 of file ata.h.
#define ATA_BM_STATUS_FLAG_SIMPLEX (1<<7)
Definition at line 54 of file ata.h.
#define ATA_BUSMASTER_COMMAND_PORT (14)
Definition at line 47 of file ata.h.
Referenced by ata_irq_handler(), ata_read(), and ata_write().
#define ATA_BUSMASTER_PRDT_PTR_PORT (18)
Definition at line 49 of file ata.h.
Referenced by ata_initialize().
#define ATA_BUSMASTER_STATUS_PORT (16)
Definition at line 48 of file ata.h.
Referenced by ata_irq_handler(), ata_read(), and ata_write().
#define ATA_CMD_CACHE_FLUSH (0xE7)
Definition at line 89 of file ata.h.
Referenced by ata_write().
#define ATA_CMD_CACHE_FLUSH_EXT (0xEA)
Definition at line 90 of file ata.h.
Referenced by ata_write().
#define ATA_CMD_IDENTIFY (0xEC)
Definition at line 93 of file ata.h.
Referenced by ata_initialize().
#define ATA_CMD_IDENTIFY_PACKET (0xA1)
Definition at line 92 of file ata.h.
#define ATA_CMD_PACKET (0xA0)
Definition at line 91 of file ata.h.
#define ATA_CMD_READ_DMA (0xC8)
Definition at line 83 of file ata.h.
Referenced by ata_read().
#define ATA_CMD_READ_DMA_EXT (0x25)
Definition at line 84 of file ata.h.
Referenced by ata_read().
#define ATA_CMD_READ_PIO (0x20)
Definition at line 81 of file ata.h.
Referenced by ata_read().
#define ATA_CMD_READ_PIO_EXT (0x24)
Definition at line 82 of file ata.h.
Referenced by ata_read().
#define ATA_CMD_WRITE_DMA (0xCA)
Definition at line 87 of file ata.h.
Referenced by ata_write().
#define ATA_CMD_WRITE_DMA_EXT (0x35)
Definition at line 88 of file ata.h.
Referenced by ata_write().
#define ATA_CMD_WRITE_PIO (0x30)
Definition at line 85 of file ata.h.
Referenced by ata_write().
#define ATA_CMD_WRITE_PIO_EXT (0x34)
Definition at line 86 of file ata.h.
Referenced by ata_write().
#define ATA_COMMAND_PORT (7)
Definition at line 40 of file ata.h.
Referenced by ata_initialize(), ata_read(), and ata_write().
#define ATA_CONTROL_PORT (12)
Definition at line 42 of file ata.h.
Referenced by ata_read_data(), ata_read_port(), ata_set_interrupts(), ata_write_data(), ata_write_port(), and ata_write_port_long().
#define ATA_CYL_HIGH_PORT (5)
Definition at line 27 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_CYL_LOW_PORT (4)
Definition at line 26 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_DATA_PORT (0)
driver/block/pata/ata.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 01-07-2014 - Created
Definition at line 20 of file ata.h.
Referenced by ata_initialize(), ata_read(), and ata_write().
#define ATA_DCR_FLAG_HIGHORDER (1<<7)
Definition at line 79 of file ata.h.
Referenced by ata_read_data(), ata_read_port(), ata_write_data(), ata_write_port(), and ata_write_port_long().
#define ATA_DCR_FLAG_INT_DIS (1<<1)
Definition at line 77 of file ata.h.
Referenced by ata_set_interrupts().
#define ATA_DCR_FLAG_SOFTRESET (1<<2)
Definition at line 78 of file ata.h.
#define ATA_DEVADDRESS_PORT (13)
Definition at line 45 of file ata.h.
#define ATA_DRIVE_ATA (1)
Definition at line 121 of file ata.h.
Referenced by ata_initialize().
#define ATA_DRIVE_ATAPI (2)
Definition at line 122 of file ata.h.
#define ATA_DRIVE_HEAD_PORT (6)
Definition at line 28 of file ata.h.
Referenced by ata_initialize(), and ata_setup_lba_transfer().
#define ATA_DRIVE_NONE (0)
Definition at line 120 of file ata.h.
Referenced by ata_initialize().
#define ATA_DRVSEL_CHS (ndrv, nhead) (0xA0 | (((ndrv)&1) << 4) | ((nhead)&0xF))
Definition at line 116 of file ata.h.
Referenced by ata_initialize(), and ata_setup_lba_transfer().
#define ATA_DRVSEL_LBA (ndrv, buppr) (0xE0 | (((ndrv)&1) << 4) | ((buppr)&0xF))
Definition at line 115 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_ERROR_FLAG_ABRT (1<<2)
Definition at line 73 of file ata.h.
#define ATA_ERROR_FLAG_AMNF (1<<0)
Definition at line 75 of file ata.h.
#define ATA_ERROR_FLAG_BBK (1<<7)
Definition at line 68 of file ata.h.
#define ATA_ERROR_FLAG_IDNF (1<<4)
Definition at line 71 of file ata.h.
#define ATA_ERROR_FLAG_MC (1<<5)
Definition at line 70 of file ata.h.
#define ATA_ERROR_FLAG_MCR (1<<3)
Definition at line 72 of file ata.h.
#define ATA_ERROR_FLAG_TK0NF (1<<1)
Definition at line 74 of file ata.h.
#define ATA_ERROR_FLAG_UNC (1<<6)
Definition at line 69 of file ata.h.
#define ATA_ERROR_PORT (1)
Definition at line 23 of file ata.h.
#define ATA_FEATURE_PORT (1)
Definition at line 22 of file ata.h.
#define ATA_IDENT_CAP_FLAG_DMA (1<<8)
Definition at line 112 of file ata.h.
Referenced by ata_initialize(), ata_read(), and ata_write().
#define ATA_IDENT_CAP_FLAG_LBA (1<<9)
Definition at line 113 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_CAPABILITIES (98)
Definition at line 101 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_CMDSET_FLAG_LBA48 (1<<26)
Definition at line 111 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_COMMANDSETS (164)
Definition at line 104 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_CYLINDERS (2)
Definition at line 96 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_DEVICETYPE (0)
Definition at line 95 of file ata.h.
#define ATA_IDENT_FIELDVALID (106)
Definition at line 102 of file ata.h.
#define ATA_IDENT_HEADS (6)
Definition at line 97 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_LLONG (DV, DR, PT) (* ((uint64_t *) &(DV->drives[DR].ident_data[PT])))
Definition at line 109 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_LONG (DV, DR, PT) (* ((uint32_t *) &(DV->drives[DR].ident_data[PT])))
Definition at line 108 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_MAX_LBA (120)
Definition at line 103 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_MAX_LBA_EXT (200)
Definition at line 105 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_MODEL (54)
Definition at line 100 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_SECTORS (12)
Definition at line 98 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_SERIAL (20)
Definition at line 99 of file ata.h.
Referenced by ata_initialize().
#define ATA_IDENT_SHORT (DV, DR, PT) (* ((uint16_t *) &(DV->drives[DR].ident_data[PT])))
Definition at line 107 of file ata.h.
Referenced by ata_initialize().
#define ATA_LBA_0_PORT (3)
Definition at line 33 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_LBA_1_PORT (4)
Definition at line 34 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_LBA_2_PORT (5)
Definition at line 35 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_LBA_3_PORT (9)
Definition at line 36 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_LBA_4_PORT (10)
Definition at line 37 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_LBA_5_PORT (11)
Definition at line 38 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_MODE_CHS (0)
Definition at line 124 of file ata.h.
Referenced by ata_initialize(), and ata_setup_lba_transfer().
#define ATA_MODE_LBA28 (1)
Definition at line 125 of file ata.h.
Referenced by ata_initialize(), and ata_setup_lba_transfer().
#define ATA_MODE_LBA48 (2)
Definition at line 126 of file ata.h.
Referenced by ata_initialize(), ata_read(), ata_setup_lba_transfer(), and ata_write().
#define ATA_PRD_END_OF_LIST (0x8000)
Definition at line 118 of file ata.h.
Referenced by ata_read(), and ata_write().
#define ATA_PRD_LIST_SIZE (16)
Definition at line 128 of file ata.h.
Referenced by ata_initialize().
#define ATA_SECTOR_COUNT_HIGH_PORT (8)
Definition at line 31 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_SECTOR_COUNT_LOW_PORT (2)
Definition at line 30 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_SECTOR_NO_PORT (3)
Definition at line 25 of file ata.h.
Referenced by ata_setup_lba_transfer().
#define ATA_STATUS_FLAG_BSY (1<<7)
Definition at line 66 of file ata.h.
Referenced by ata_poll_wait().
#define ATA_STATUS_FLAG_DF (1<<5)
Definition at line 64 of file ata.h.
Referenced by ata_poll_wait(), ata_read(), and ata_write().
#define ATA_STATUS_FLAG_DRQ (1<<3)
Definition at line 62 of file ata.h.
Referenced by ata_poll_wait(), ata_read(), and ata_write().
#define ATA_STATUS_FLAG_ERR (1<<0)
Definition at line 61 of file ata.h.
Referenced by ata_poll_wait(), ata_read(), and ata_write().
#define ATA_STATUS_FLAG_RDY (1<<6)
Definition at line 65 of file ata.h.
#define ATA_STATUS_FLAG_SRV (1<<4)
Definition at line 63 of file ata.h.
#define ATA_STATUS_PORT (7)
Definition at line 41 of file ata.h.
Referenced by ata_initialize(), ata_irq_handler(), and ata_poll_wait().
Typedef Documentation
typedef struct ata_device ata_device_t
Definition at line 130 of file ata.h.
typedef struct ata_drive ata_drive_t
Definition at line 132 of file ata.h.
typedef uint64_t ata_lba_t
Definition at line 136 of file ata.h.
typedef struct ata_prd ata_prd_t
Definition at line 134 of file ata.h.
Function Documentation
void ata_initialize (ata_device_t * device)
Todo:
: Wait here ? osdev wiki says so but does not specify why.(no support for kernel-land sleeps yet)
Todo:
: ^^^^
Todo:
: Handle ATAPI devices
Todo:
: Hook this somewhere
Definition at line 184 of file ata.c.
References ata_block_driver_ops, ata_bus_number_counter, ATA_BUSMASTER_PRDT_PTR_PORT, ATA_CMD_IDENTIFY, ATA_COMMAND_PORT, ATA_DATA_PORT, ATA_DRIVE_ATA, ATA_DRIVE_HEAD_PORT, ATA_DRIVE_NONE, ATA_DRVSEL_CHS, ata_global_inited, ata_global_initialize(), ATA_IDENT_CAP_FLAG_DMA, ATA_IDENT_CAP_FLAG_LBA, ATA_IDENT_CAPABILITIES, ATA_IDENT_CMDSET_FLAG_LBA48, ATA_IDENT_COMMANDSETS, ATA_IDENT_CYLINDERS, ATA_IDENT_HEADS, ATA_IDENT_LLONG, ATA_IDENT_LONG, ATA_IDENT_MAX_LBA, ATA_IDENT_MAX_LBA_EXT, ATA_IDENT_MODEL, ATA_IDENT_SECTORS, ATA_IDENT_SERIAL, ATA_IDENT_SHORT, ata_interrupt_enabled, ata_irq_handler(), ata_load_partition_table(), ATA_MODE_CHS, ATA_MODE_LBA28, ATA_MODE_LBA48, ata_poll_wait(), ATA_PRD_LIST_SIZE, ata_read_data(), ata_read_port(), ata_set_interrupts(), ATA_STATUS_PORT, ata_write_port(), ata_write_port_long(), blk_dev::block_size, ata_device::bus_number, blk_dev::cache_size, ata_drive::capabilities, ata_drive::command_sets, ata_drive::cylinders, debugcon_printf, device_block_register(), ata_device::drives, ata_drive::heads, heapmm_alloc(), heapmm_alloc_alligned(), ata_drive::ident_data, ata_device::int_wait, interrupt_register_handler(), ata_device::irq, ata_drive::lba_mode, ata_device::lock, blk_dev::major, ata_drive::max_lba, blk_dev::minor_count, ata_drive::model, blk_dev::name, blk_dev::ops, paging_get_physical_address(), ata_drive::sectors_per_track, semaphore_alloc(), semaphore_up(), ata_drive::serial, and ata_drive::type.
Referenced by ata_pci_probe().
int ata_poll_wait (ata_device_t * device)
Todo:
: Timeout
Definition at line 133 of file ata.c.
References ATA_ALTSTATUS_PORT, ata_read_port(), ATA_STATUS_FLAG_BSY, ATA_STATUS_FLAG_DF, ATA_STATUS_FLAG_DRQ, ATA_STATUS_FLAG_ERR, and ATA_STATUS_PORT.
Referenced by ata_initialize(), ata_read(), and ata_write().
int ata_read (ata_device_t * device, int drive, ata_lba_t lba, uint8_t * buffer, uint16_t count)
Todo:
: Implement a work queue
Definition at line 322 of file ata.c.
References ATA_BM_CMD_FLAG_DMA_ENABLE, ATA_BM_CMD_FLAG_READ, ATA_BM_STATUS_FLAG_ERR, ATA_BUSMASTER_COMMAND_PORT, ATA_BUSMASTER_STATUS_PORT, ATA_CMD_READ_DMA, ATA_CMD_READ_DMA_EXT, ATA_CMD_READ_PIO, ATA_CMD_READ_PIO_EXT, ATA_COMMAND_PORT, ATA_DATA_PORT, ATA_IDENT_CAP_FLAG_DMA, ata_interrupt_enabled, ATA_MODE_LBA48, ata_poll_wait(), ATA_PRD_END_OF_LIST, ata_read_data(), ata_read_port(), ata_setup_lba_transfer(), ATA_STATUS_FLAG_DF, ATA_STATUS_FLAG_DRQ, ATA_STATUS_FLAG_ERR, ata_write_port(), ata_prd::buffer_phys, ata_device::bus_number, ata_prd::byte_count, ata_drive::capabilities, debugcon_printf, ata_device::drives, ata_prd::end_of_list, ata_device::int_status, ata_device::int_wait, ata_drive::lba_mode, ata_device::lock, paging_get_physical_address(), semaphore_down(), and semaphore_up().
Referenced by ata_blk_read(), and ata_load_partition_table().
uint8_t ata_read_port (ata_device_t * device, uint16_t port)
Definition at line 33 of file ata.c.
References ATA_CONTROL_PORT, ATA_DCR_FLAG_HIGHORDER, ata_write_port(), ata_device::bmio_base, ata_device::ctrl_base, ata_device::ctrl_reg, i386_inb(), and ata_device::pio_base.
Referenced by ata_initialize(), ata_irq_handler(), ata_poll_wait(), ata_read(), and ata_write().
void ata_set_interrupts (ata_device_t * device, int enabled)
Definition at line 148 of file ata.c.
References ATA_CONTROL_PORT, ATA_DCR_FLAG_INT_DIS, ata_write_port(), and ata_device::ctrl_reg.
Referenced by ata_initialize().
int ata_write (ata_device_t * device, int drive, ata_lba_t lba, uint8_t * buffer, uint16_t count)
Todo:
: Implement a work queue
Definition at line 379 of file ata.c.
References ATA_BM_CMD_FLAG_DMA_ENABLE, ATA_BM_STATUS_FLAG_ERR, ATA_BUSMASTER_COMMAND_PORT, ATA_BUSMASTER_STATUS_PORT, ATA_CMD_CACHE_FLUSH, ATA_CMD_CACHE_FLUSH_EXT, ATA_CMD_WRITE_DMA, ATA_CMD_WRITE_DMA_EXT, ATA_CMD_WRITE_PIO, ATA_CMD_WRITE_PIO_EXT, ATA_COMMAND_PORT, ATA_DATA_PORT, ATA_IDENT_CAP_FLAG_DMA, ata_interrupt_enabled, ATA_MODE_LBA48, ata_poll_wait(), ATA_PRD_END_OF_LIST, ata_read_port(), ata_setup_lba_transfer(), ATA_STATUS_FLAG_DF, ATA_STATUS_FLAG_DRQ, ATA_STATUS_FLAG_ERR, ata_write_data(), ata_write_port(), ata_prd::buffer_phys, ata_device::bus_number, ata_prd::byte_count, ata_drive::capabilities, debugcon_printf, ata_device::drives, ata_prd::end_of_list, ata_device::int_status, ata_device::int_wait, ata_drive::lba_mode, ata_device::lock, paging_get_physical_address(), semaphore_down(), and semaphore_up().
Referenced by ata_blk_write().
void ata_write_port (ata_device_t * device, uint16_t port, uint8_t value)
Definition at line 51 of file ata.c.
References ATA_CONTROL_PORT, ATA_DCR_FLAG_HIGHORDER, ata_write_port(), ata_device::bmio_base, ata_device::ctrl_base, ata_device::ctrl_reg, i386_outb(), and ata_device::pio_base.
Referenced by ata_initialize(), ata_irq_handler(), ata_read(), ata_read_data(), ata_read_port(), ata_set_interrupts(), ata_setup_lba_transfer(), ata_write(), ata_write_data(), ata_write_port(), and ata_write_port_long().