posnk kernel: driver/block/pata/ata_pci.c File Reference
ata_pci.c File Reference
#include "kernel/earlycon.h"
#include "kernel/heapmm.h"
#include "kernel/drivermgr.h"
#include "driver/bus/pci.h"
#include "driver/block/pata/ata.h"
Functions
int ata_pci_probe (uint32_t bus_addr)
driver/block/pata/ata_pci.c
void ata_pci_register ()
Variables
drivermgr_interface_driver_t ata_pci_descriptor
Function Documentation
int ata_pci_probe (uint32_t bus_addr)
driver/block/pata/ata_pci.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 02-07-2014 - Created
Definition at line 18 of file ata_pci.c.
References ata_initialize(), ata_device::bmio_base, ata_device::ctrl_base, debugcon_printf, heapmm_alloc(), heapmm_free(), ata_device::irq, NULL, PCI_CONFIG_BAR0, PCI_CONFIG_BAR1, PCI_CONFIG_BAR2, PCI_CONFIG_BAR3, PCI_CONFIG_BAR4, PCI_CONFIG_INTERRUPT_LINE, pci_config_read_byte(), pci_config_read_long(), and ata_device::pio_base.
void ata_pci_register ()
Definition at line 63 of file ata_pci.c.
References drivermgr_register_interface_driver().
Referenced by i386_kmain().
Variable Documentation
drivermgr_interface_driver_t ata_pci_descriptor
Initial value:
 {
        {NULL, NULL},
        DEVICE_TYPE_PCI,
        0x010100,
        0xFFFF00,
        &ata_pci_probe
}
Definition at line 55 of file ata_pci.c.