posnk kernel: include/kernel/blkcache.h File Reference
blkcache.h File Reference
#include <sys/types.h>
#include "util/llist.h"
Data Structures
struct blkcache_cache
struct blkcache_entry
Macros
#define BLKCACHE_ENTRY_FLAG_DIRTY (1<<1)
kernel/blkcache.h
#define BLKCACHE_ENOMEM ((blkcache_entry_t *) 0xFFFFFFFF)
Typedefs
typedef struct blkcache_cache blkcache_cache_t
typedef struct blkcache_entry blkcache_entry_t
Functions
blkcache_cache_t * blkcache_create (aoff_t block_size, int max_entries)
blkcache_create - Creates a new, empty block cache
int blkcache_free (blkcache_cache_t *cache)
blkcache_free - Destroys a cache and releases all memory associated with it
blkcache_entry_t * blkcache_find (blkcache_cache_t *cache, aoff_t offset)
blkcache_find - Get a block from the cache
void blkcache_bump (blkcache_cache_t *cache, blkcache_entry_t *entry)
blkcache_bump - Notify the cache of the usage of a block
blkcache_entry_t * blkcache_get_discard_candidate (blkcache_cache_t *cache)
blkcache_get_discard_candidate - Returns the block to be discarded next
blkcache_entry_t * blkcache_get (blkcache_cache_t *cache, aoff_t offset)
blkcache_get - Get a block from the cache or create it if it does not exist yet.
Macro Definition Documentation
#define BLKCACHE_ENOMEM ((blkcache_entry_t *) 0xFFFFFFFF)
Definition at line 23 of file blkcache.h.
Referenced by blkcache_get(), device_block_fetch(), and device_block_write().
#define BLKCACHE_ENTRY_FLAG_DIRTY (1<<1)
kernel/blkcache.h
Part of P-OS kernel.
Implements a LRU cache for blocks
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 06-06-2014 - Created 01-07-2014 - Fully implemented, commented.
Definition at line 21 of file blkcache.h.
Referenced by blkcache_free(), blkcache_get(), device_block_flush(), and device_block_write().
Typedef Documentation
typedef struct blkcache_cache blkcache_cache_t
Definition at line 40 of file blkcache.h.
typedef struct blkcache_entry blkcache_entry_t
Definition at line 41 of file blkcache.h.
Function Documentation
void blkcache_bump (blkcache_cache_t * cache, blkcache_entry_t * entry)
blkcache_bump - Notify the cache of the usage of a block
Parameters
cache The cache to operate on
block The block that was used
Definition at line 147 of file blkcache.c.
References blkcache_cache::block_list, llist_add_end(), and llist_unlink().
blkcache_cache_t* blkcache_create (aoff_t block_size, int max_entries)
blkcache_create - Creates a new, empty block cache
Parameters
block_size The size of the blocks the cache will contain
max_entries The amount of blocks the cache should be limited to
Returns
The new cache or NULL if there was no memory left
blkcache_create - Creates a new, empty block cache
Part of P-OS kernel.
Implements a LRU cache for blocks
TODO: Rewrite this to be more time-efficient (stop using llist)
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 06-06-2014 - Created 01-07-2014 - Fully implemented, commented. blkcache_create - Creates a new, empty block cache
Parameters
block_size The size of the blocks the cache will contain
max_entries The amount of blocks the cache should be limited to
Returns
The new cache or NULL if there was no memory left
Definition at line 33 of file blkcache.c.
References blkcache_cache::block_list, blkcache_cache::block_size, blkcache_cache::entry_count, heapmm_alloc(), llist_create(), blkcache_cache::max_entries, and NULL.
Referenced by device_block_register().
blkcache_entry_t* blkcache_find (blkcache_cache_t * cache, aoff_t offset)
blkcache_find - Get a block from the cache
Parameters
cache The cache to get the block from
offset The offset of the block to get
Returns
The block that was requested, or NULL incase it is not in the cache
Definition at line 129 of file blkcache.c.
References blkcache_get_iterator(), blkcache_cache::block_list, and llist_iterate_select().
Referenced by blkcache_get(), device_block_flush(), device_block_read(), and device_block_write().
int blkcache_free (blkcache_cache_t * cache)
blkcache_free - Destroys a cache and releases all memory associated with it
Parameters
cache The cache to destroy
Returns
TRUE if the cache was successfully destroyed, FALSE if there are dirty blocks left in the cache
Definition at line 59 of file blkcache.c.
References BLKCACHE_ENTRY_FLAG_DIRTY, blkcache_cache::block_list, blkcache_cache::block_size, blkcache_entry::data, blkcache_entry::flags, heapmm_free(), llist_unlink(), and llist::next.
Referenced by device_block_register().
blkcache_entry_t* blkcache_get (blkcache_cache_t * cache, aoff_t offset)
blkcache_get - Get a block from the cache or create it if it does not exist yet.
Parameters
cache The cache to get the block from
offset The offset of the block to get/add
Returns
The block that was requested, or NULL incase the cache was full and the block that was to be removed was dirty. 2^32-1 is returned if there was not enough memory to add the block
Definition at line 187 of file blkcache.c.
References blkcache_entry::access_count, BLKCACHE_ENOMEM, BLKCACHE_ENTRY_FLAG_DIRTY, blkcache_find(), blkcache_get_discard_candidate(), blkcache_cache::block_list, blkcache_cache::block_size, blkcache_entry::data, blkcache_cache::entry_count, blkcache_entry::flags, heapmm_alloc(), heapmm_alloc_alligned(), heapmm_free(), llist_add_end(), llist_unlink(), blkcache_cache::max_entries, memset(), NULL, and blkcache_entry::offset.
Referenced by device_block_fetch(), and device_block_write().
blkcache_entry_t* blkcache_get_discard_candidate (blkcache_cache_t * cache)
blkcache_get_discard_candidate - Returns the block to be discarded next
Parameters
cache The cache to operate on
Returns
The block to be discarded next
Definition at line 168 of file blkcache.c.
References blkcache_cache::block_list, and llist::next.
Referenced by blkcache_get(), device_block_fetch(), and device_block_write().