posnk kernel: kernel/blkdev.c File Reference
blkdev.c File Reference
#include "kernel/heapmm.h"
#include "kernel/device.h"
#include "kernel/earlycon.h"
#include <sys/types.h>
#include <sys/errno.h>
#include <string.h>
Functions
void device_block_init ()
int device_block_register (blk_dev_t *driver)
int device_block_flush (dev_t device, aoff_t block_offset)
int device_block_fetch (dev_t device, aoff_t block_offset)
int device_block_ioctl (dev_t device, int fd, int func, int arg)
int device_block_open (dev_t device, int fd, int options)
int device_block_close (dev_t device, int fd)
int device_block_write (dev_t device, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *write_size)
int device_block_read (dev_t device, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *read_size)
Variables
blk_dev_t ** block_dev_table
kernel/blkdev.c
Function Documentation
int device_block_close (dev_t device, int fd)
Definition at line 169 of file blkdev.c.
References blk_ops::close, ENODEV, MAJOR, MINOR, blk_dev::minor_count, and blk_dev::ops.
Referenced by _sys_close_int().
int device_block_fetch (dev_t device, aoff_t block_offset)
Definition at line 119 of file blkdev.c.
References BLKCACHE_ENOMEM, blkcache_get(), blkcache_get_discard_candidate(), blk_dev::caches, blkcache_entry::data, device_block_flush(), ENOMEM, MAJOR, MINOR, blkcache_entry::offset, blk_dev::ops, and blk_ops::read.
Referenced by device_block_read(), and device_block_write().
int device_block_flush (dev_t device, aoff_t block_offset)
Definition at line 98 of file blkdev.c.
References BLKCACHE_ENTRY_FLAG_DIRTY, blkcache_find(), blk_dev::caches, blkcache_entry::data, blkcache_entry::flags, MAJOR, MINOR, blk_dev::ops, and blk_ops::write.
Referenced by device_block_fetch(), and device_block_write().
void device_block_init ()
Definition at line 23 of file blkdev.c.
References heapmm_alloc(), and memset().
Referenced by i386_kmain().
int device_block_ioctl (dev_t device, int fd, int func, int arg)
Definition at line 143 of file blkdev.c.
References ENODEV, blk_ops::ioctl, MAJOR, MINOR, blk_dev::minor_count, and blk_dev::ops.
Referenced by _sys_ioctl().
int device_block_open (dev_t device, int fd, int options)
Definition at line 156 of file blkdev.c.
References ENODEV, MAJOR, MINOR, blk_dev::minor_count, blk_ops::open, and blk_dev::ops.
Referenced by _sys_open().
int device_block_read (dev_t device, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * read_size)
Definition at line 264 of file blkdev.c.
References blkcache_find(), blk_dev::block_size, blk_dev::caches, blkcache_entry::data, device_block_fetch(), ENODEV, blk_dev::locks, MAJOR, memcpy(), MINOR, blk_dev::minor_count, semaphore_down(), and semaphore_up().
Referenced by ext2_load_bgd(), ext2_load_e2inode(), ext2_mount(), ext2_read_block(), and vfs_read().
int device_block_register (blk_dev_t * driver)
Definition at line 29 of file blkdev.c.
References blkcache_create(), blkcache_free(), blk_dev::block_size, blk_dev::cache_size, blk_dev::caches, heapmm_alloc(), heapmm_free(), blk_dev::locks, blk_dev::major, blk_dev::minor_count, semaphore_alloc(), semaphore_free(), and semaphore_up().
Referenced by ata_initialize().
int device_block_write (dev_t device, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * write_size)
Definition at line 182 of file blkdev.c.
References BLKCACHE_ENOMEM, BLKCACHE_ENTRY_FLAG_DIRTY, blkcache_find(), blkcache_get(), blkcache_get_discard_candidate(), blk_dev::block_size, blk_dev::caches, blkcache_entry::data, debugcon_printf, device_block_fetch(), device_block_flush(), ENODEV, ENOMEM, blkcache_entry::flags, blk_dev::locks, MAJOR, memcpy(), MINOR, blk_dev::minor_count, blkcache_entry::offset, semaphore_down(), and semaphore_up().
Referenced by ext2_write_block(), and vfs_write().
Variable Documentation
blk_dev_t** block_dev_table
kernel/blkdev.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 17-04-2014 - Created
Todo:
: IMPLEMENT BLOCK DEVICES
Definition at line 21 of file blkdev.c.