posnk kernel: kernel/chardev.c File Reference
chardev.c File Reference
#include "kernel/syscall.h"
#include "kernel/device.h"
#include "kernel/heapmm.h"
#include <sys/types.h>
#include <sys/errno.h>
#include <string.h>
Functions
void device_char_init ()
int device_char_register (char_dev_t *driver)
int device_char_ioctl (dev_t device, int fd, int func, int arg)
int device_char_open (dev_t device, int fd, int options)
int device_char_close (dev_t device, int fd)
int device_char_write (dev_t device, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *write_size, int non_block)
int device_char_read (dev_t device, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *read_size, int non_block)
Variables
char_dev_t ** char_dev_table
kernel/chardev.c
Function Documentation
int device_char_close (dev_t device, int fd)
Definition at line 56 of file chardev.c.
References tty_ops::close, ENODEV, MAJOR, and char_dev::ops.
Referenced by _sys_close_int().
void device_char_init ()
Definition at line 20 of file chardev.c.
References heapmm_alloc(), and memset().
Referenced by i386_kmain().
int device_char_ioctl (dev_t device, int fd, int func, int arg)
Definition at line 36 of file chardev.c.
References ENODEV, tty_ops::ioctl, MAJOR, and char_dev::ops.
Referenced by _sys_ioctl().
int device_char_open (dev_t device, int fd, int options)
Definition at line 46 of file chardev.c.
References ENODEV, MAJOR, tty_ops::open, and char_dev::ops.
Referenced by _sys_open().
int device_char_read (dev_t device, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * read_size, int non_block)
Definition at line 76 of file chardev.c.
References ENODEV, MAJOR, char_dev::ops, and tty_ops::read.
Referenced by vfs_read().
int device_char_register (char_dev_t * driver)
Definition at line 26 of file chardev.c.
References char_dev::major.
Referenced by tty_register_driver().
int device_char_write (dev_t device, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * write_size, int non_block)
Definition at line 66 of file chardev.c.
References ENODEV, MAJOR, char_dev::ops, and tty_ops::write.
Referenced by vfs_write().
Variable Documentation
char_dev_t** char_dev_table
kernel/chardev.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 17-04-2014 - Created
Definition at line 18 of file chardev.c.