posnk kernel: include/util/debug.h File Reference
debug.h File Reference
#include <stddef.h>
Functions
void debug_dump_state (void *state, size_t state_size)
util/debug.h
void debug_postmortem_hook (void *state, size_t state_size, void *instr_addr)
Function Documentation
void debug_dump_state (void * state, size_t state_size)
util/debug.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 02-04-2014 - Changed names, added comments
Definition at line 47 of file x86.c.
References earlycon_printf, earlycon_puts, i386_pusha_registers::eax, i386_pusha_registers::ebp, i386_pusha_registers::ebx, i386_pusha_registers::ecx, i386_pusha_registers::edi, i386_pusha_registers::edx, i386_pusha_registers::esi, and i386_pusha_registers::esp.
Referenced by exception_handle(), and exception_panic().
void debug_postmortem_hook (void * state, size_t state_size, void * instr_addr)
Definition at line 61 of file x86.c.
References dbgapi_invoke_kdbg(), earlycon_puts, i386_pusha_registers::ebp, eip, and i386_pusha_registers::esp.
Referenced by exception_panic().