posnk kernel: include/kernel/device.h File Reference
device.h File Reference
#include <sys/types.h>
#include "kernel/blkcache.h"
#include "kernel/synch.h"
Data Structures
struct char_dev
struct blk_dev
struct tty_ops
struct blk_ops
Typedefs
typedef struct char_dev char_dev_t
kernel/device.h
typedef struct blk_dev blk_dev_t
typedef struct tty_ops tty_ops_t
typedef struct blk_ops blk_ops_t
Functions
void device_char_init ()
void device_block_init ()
int device_char_register (char_dev_t *driver)
int device_block_register (blk_dev_t *driver)
int device_block_ioctl (dev_t device, int fd, int func, int arg)
int device_block_open (dev_t device, int fd, int options)
int device_block_close (dev_t device, int fd)
int device_block_write (dev_t device, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *write_size)
int device_block_read (dev_t device, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *read_size)
int device_char_ioctl (dev_t device, int fd, int func, int arg)
int device_char_open (dev_t device, int fd, int options)
int device_char_close (dev_t device, int fd)
int device_char_write (dev_t device, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *write_size, int non_block)
int device_char_read (dev_t device, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *read_size, int non_block)
Typedef Documentation
typedef struct blk_dev blk_dev_t
Definition at line 19 of file device.h.
typedef struct blk_ops blk_ops_t
Definition at line 21 of file device.h.
typedef struct char_dev char_dev_t
kernel/device.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 17-04-2014 - Created
Definition at line 18 of file device.h.
typedef struct tty_ops tty_ops_t
Definition at line 20 of file device.h.
Function Documentation
int device_block_close (dev_t device, int fd)
Definition at line 169 of file blkdev.c.
References blk_ops::close, ENODEV, MAJOR, MINOR, blk_dev::minor_count, and blk_dev::ops.
Referenced by _sys_close_int().
void device_block_init ()
Definition at line 23 of file blkdev.c.
References heapmm_alloc(), and memset().
Referenced by i386_kmain().
int device_block_ioctl (dev_t device, int fd, int func, int arg)
Definition at line 143 of file blkdev.c.
References ENODEV, blk_ops::ioctl, MAJOR, MINOR, blk_dev::minor_count, and blk_dev::ops.
Referenced by _sys_ioctl().
int device_block_open (dev_t device, int fd, int options)
Definition at line 156 of file blkdev.c.
References ENODEV, MAJOR, MINOR, blk_dev::minor_count, blk_ops::open, and blk_dev::ops.
Referenced by _sys_open().
int device_block_read (dev_t device, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * read_size)
Definition at line 264 of file blkdev.c.
References blkcache_find(), blk_dev::block_size, blk_dev::caches, blkcache_entry::data, device_block_fetch(), ENODEV, blk_dev::locks, MAJOR, memcpy(), MINOR, blk_dev::minor_count, semaphore_down(), and semaphore_up().
Referenced by ext2_load_bgd(), ext2_load_e2inode(), ext2_mount(), ext2_read_block(), and vfs_read().
int device_block_register (blk_dev_t * driver)
Definition at line 29 of file blkdev.c.
References blkcache_create(), blkcache_free(), blk_dev::block_size, blk_dev::cache_size, blk_dev::caches, heapmm_alloc(), heapmm_free(), blk_dev::locks, blk_dev::major, blk_dev::minor_count, semaphore_alloc(), semaphore_free(), and semaphore_up().
Referenced by ata_initialize().
int device_block_write (dev_t device, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * write_size)
Definition at line 182 of file blkdev.c.
References BLKCACHE_ENOMEM, BLKCACHE_ENTRY_FLAG_DIRTY, blkcache_find(), blkcache_get(), blkcache_get_discard_candidate(), blk_dev::block_size, blk_dev::caches, blkcache_entry::data, debugcon_printf, device_block_fetch(), device_block_flush(), ENODEV, ENOMEM, blkcache_entry::flags, blk_dev::locks, MAJOR, memcpy(), MINOR, blk_dev::minor_count, blkcache_entry::offset, semaphore_down(), and semaphore_up().
Referenced by ext2_write_block(), and vfs_write().
int device_char_close (dev_t device, int fd)
Definition at line 56 of file chardev.c.
References tty_ops::close, ENODEV, MAJOR, and char_dev::ops.
Referenced by _sys_close_int().
void device_char_init ()
Definition at line 20 of file chardev.c.
References heapmm_alloc(), and memset().
Referenced by i386_kmain().
int device_char_ioctl (dev_t device, int fd, int func, int arg)
Definition at line 36 of file chardev.c.
References ENODEV, tty_ops::ioctl, MAJOR, and char_dev::ops.
Referenced by _sys_ioctl().
int device_char_open (dev_t device, int fd, int options)
Definition at line 46 of file chardev.c.
References ENODEV, MAJOR, tty_ops::open, and char_dev::ops.
Referenced by _sys_open().
int device_char_read (dev_t device, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * read_size, int non_block)
Definition at line 76 of file chardev.c.
References ENODEV, MAJOR, char_dev::ops, and tty_ops::read.
Referenced by vfs_read().
int device_char_register (char_dev_t * driver)
Definition at line 26 of file chardev.c.
References char_dev::major.
Referenced by tty_register_driver().
int device_char_write (dev_t device, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * write_size, int non_block)
Definition at line 66 of file chardev.c.
References ENODEV, MAJOR, char_dev::ops, and tty_ops::write.
Referenced by vfs_write().