var dir_f641b9ad53d8d191242bcadc0d20fb84 =
[
    [ "blkcache.h", "blkcache_8h.html", "blkcache_8h" ],
    [ "device.h", "device_8h.html", "device_8h" ],
    [ "drivermgr.h", "drivermgr_8h.html", "drivermgr_8h" ],
    [ "earlycon.h", "earlycon_8h.html", "earlycon_8h" ],
    [ "elf.h", "elf_8h.html", "elf_8h" ],
    [ "elfloader.h", "elfloader_8h.html", "elfloader_8h" ],
    [ "exception.h", "exception_8h.html", "exception_8h" ],
    [ "heapmm.h", "heapmm_8h.html", "heapmm_8h" ],
    [ "interrupt.h", "interrupt_8h.html", "interrupt_8h" ],
    [ "paging.h", "kernel_2paging_8h.html", "kernel_2paging_8h" ],
    [ "permissions.h", "permissions_8h.html", "permissions_8h" ],
    [ "physmm.h", "physmm_8h.html", "physmm_8h" ],
    [ "pipe.h", "pipe_8h.html", "pipe_8h" ],
    [ "process.h", "process_8h.html", "process_8h" ],
    [ "scheduler.h", "scheduler_8h.html", "scheduler_8h" ],
    [ "signals.h", "signals_8h.html", "signals_8h" ],
    [ "streams.h", "streams_8h.html", "streams_8h" ],
    [ "synch.h", "synch_8h.html", "synch_8h" ],
    [ "syscall.h", "syscall_8h.html", "syscall_8h" ],
    [ "syscall_ids.h", "syscall__ids_8h.html", "syscall__ids_8h" ],
    [ "system.h", "system_8h.html", "system_8h" ],
    [ "tar.h", "tar_8h.html", "tar_8h" ],
    [ "time.h", "time_8h.html", "time_8h" ],
    [ "tty.h", "tty_8h.html", "tty_8h" ],
    [ "vfs.h", "vfs_8h.html", "vfs_8h" ]
];