var dir_456af83f63a9d8b27e10dd059fe0d1e0 =
[
    [ "blkcache.c", "blkcache_8c.html", "blkcache_8c" ],
    [ "blkdev.c", "blkdev_8c.html", "blkdev_8c" ],
    [ "chardev.c", "chardev_8c.html", "chardev_8c" ],
    [ "drivermgr.c", "drivermgr_8c.html", "drivermgr_8c" ],
    [ "earlycon.c", "earlycon_8c.html", "earlycon_8c" ],
    [ "elfloader.c", "elfloader_8c.html", "elfloader_8c" ],
    [ "exception.c", "exception_8c.html", "exception_8c" ],
    [ "heapmm.c", "heapmm_8c.html", "heapmm_8c" ],
    [ "interrupt.c", "interrupt_8c.html", "interrupt_8c" ],
    [ "paging.c", "kernel_2paging_8c.html", "kernel_2paging_8c" ],
    [ "permissions.c", "permissions_8c.html", "permissions_8c" ],
    [ "physmm.c", "physmm_8c.html", "physmm_8c" ],
    [ "pipe.c", "pipe_8c.html", "pipe_8c" ],
    [ "process.c", "process_8c.html", "process_8c" ],
    [ "procvmm.c", "procvmm_8c.html", "procvmm_8c" ],
    [ "sc_perm.c", "sc__perm_8c.html", "sc__perm_8c" ],
    [ "sc_process.c", "sc__process_8c.html", "sc__process_8c" ],
    [ "sc_signals.c", "sc__signals_8c.html", "sc__signals_8c" ],
    [ "sc_streams.c", "sc__streams_8c.html", "sc__streams_8c" ],
    [ "sc_time.c", "sc__time_8c.html", "sc__time_8c" ],
    [ "sc_vfs.c", "sc__vfs_8c.html", "sc__vfs_8c" ],
    [ "scheduler.c", "scheduler_8c.html", "scheduler_8c" ],
    [ "streams.c", "streams_8c.html", "streams_8c" ],
    [ "synch.c", "synch_8c.html", "synch_8c" ],
    [ "syscall.c", "syscall_8c.html", "syscall_8c" ],
    [ "tar.c", "tar_8c.html", "tar_8c" ],
    [ "time.c", "time_8c.html", "time_8c" ],
    [ "tty.c", "tty_8c.html", "tty_8c" ],
    [ "vfs.c", "vfs_8c.html", "vfs_8c" ]
];