posnk kernel: include/kernel/drivermgr.h File Reference
drivermgr.h File Reference
#include <stdint.h>
#include "util/llist.h"
Data Structures
struct drivermgr_device_driver
struct drivermgr_interface_driver
Macros
#define DEVICE_TYPE_PCI (0)
kernel/drivermgr.h
Typedefs
typedef int dev_type_t
typedef struct
drivermgr_device_driver drivermgr_device_driver_t
typedef struct
drivermgr_interface_driver drivermgr_interface_driver_t
Functions
int drivermgr_enumerate_device (dev_type_t type, uint32_t bus_addr, int vendor, int device)
int drivermgr_enumerate_interface (dev_type_t type, uint32_t bus_addr, uint32_t interface)
void drivermgr_register_device_driver (drivermgr_device_driver_t *driver)
void drivermgr_register_interface_driver (drivermgr_interface_driver_t *driver)
Macro Definition Documentation
#define DEVICE_TYPE_PCI (0)
kernel/drivermgr.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 02-07-2014 - Created
Definition at line 18 of file drivermgr.h.
Referenced by pci_enumerate_function().
Typedef Documentation
typedef int dev_type_t
Definition at line 20 of file drivermgr.h.
typedef struct drivermgr_device_driver drivermgr_device_driver_t
Definition at line 38 of file drivermgr.h.
typedef struct drivermgr_interface_driver drivermgr_interface_driver_t
Definition at line 40 of file drivermgr.h.
Function Documentation
int drivermgr_enumerate_device (dev_type_t type, uint32_t bus_addr, int vendor, int device)
Definition at line 34 of file drivermgr.c.
References drivermgr_device_driver::device, drivermgr_enumerate_device_iterator(), llist_iterate_select(), drivermgr_device_driver::probe, drivermgr_device_driver::type, and drivermgr_device_driver::vendor.
Referenced by pci_enumerate_function().
int drivermgr_enumerate_interface (dev_type_t type, uint32_t bus_addr, uint32_t interface)
Definition at line 59 of file drivermgr.c.
References drivermgr_enumerate_interface_iterator(), drivermgr_interface_driver::interface, llist_iterate_select(), drivermgr_interface_driver::probe, and drivermgr_interface_driver::type.
Referenced by pci_enumerate_function().
void drivermgr_register_device_driver (drivermgr_device_driver_t * driver)
Definition at line 72 of file drivermgr.c.
References llist_add_end().
void drivermgr_register_interface_driver (drivermgr_interface_driver_t * driver)
Definition at line 77 of file drivermgr.c.
References llist_add_end().
Referenced by ata_pci_register().