posnk kernel: kernel/drivermgr.c File Reference
drivermgr.c File Reference
#include "kernel/drivermgr.h"
#include "kernel/heapmm.h"
Functions
void drivermgr_init ()
int drivermgr_enumerate_device_iterator (llist_t *node, void *param)
Iterator function that looks up the driver for it.
int drivermgr_enumerate_device (dev_type_t type, uint32_t bus_addr, int vendor, int device)
int drivermgr_enumerate_interface_iterator (llist_t *node, void *param)
Iterator function that looks up the driver for it.
int drivermgr_enumerate_interface (dev_type_t type, uint32_t bus_addr, uint32_t interface)
void drivermgr_register_device_driver (drivermgr_device_driver_t *driver)
void drivermgr_register_interface_driver (drivermgr_interface_driver_t *driver)
Variables
llist_t drivermgr_device_driver_list
kernel/drivermgr.c
llist_t drivermgr_interface_driver_list
Function Documentation
int drivermgr_enumerate_device (dev_type_t type, uint32_t bus_addr, int vendor, int device)
Definition at line 34 of file drivermgr.c.
References drivermgr_device_driver::device, drivermgr_enumerate_device_iterator(), llist_iterate_select(), drivermgr_device_driver::probe, drivermgr_device_driver::type, and drivermgr_device_driver::vendor.
Referenced by pci_enumerate_function().
int drivermgr_enumerate_device_iterator (llist_t * node, void * param)
Iterator function that looks up the driver for it.
Definition at line 27 of file drivermgr.c.
References drivermgr_device_driver::device, drivermgr_device_driver::type, and drivermgr_device_driver::vendor.
Referenced by drivermgr_enumerate_device().
int drivermgr_enumerate_interface (dev_type_t type, uint32_t bus_addr, uint32_t interface)
Definition at line 59 of file drivermgr.c.
References drivermgr_enumerate_interface_iterator(), drivermgr_interface_driver::interface, llist_iterate_select(), drivermgr_interface_driver::probe, and drivermgr_interface_driver::type.
Referenced by pci_enumerate_function().
int drivermgr_enumerate_interface_iterator (llist_t * node, void * param)
Iterator function that looks up the driver for it.
Definition at line 51 of file drivermgr.c.
References drivermgr_interface_driver::interface, drivermgr_interface_driver::interface_mask, and drivermgr_interface_driver::type.
Referenced by drivermgr_enumerate_interface().
void drivermgr_init ()
Definition at line 18 of file drivermgr.c.
References llist_create().
Referenced by i386_kmain().
void drivermgr_register_device_driver (drivermgr_device_driver_t * driver)
Definition at line 72 of file drivermgr.c.
References llist_add_end().
void drivermgr_register_interface_driver (drivermgr_interface_driver_t * driver)
Definition at line 77 of file drivermgr.c.
References llist_add_end().
Referenced by ata_pci_register().
Variable Documentation
llist_t drivermgr_device_driver_list
kernel/drivermgr.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 02-07-2014 - Created
Definition at line 15 of file drivermgr.c.
llist_t drivermgr_interface_driver_list
Definition at line 16 of file drivermgr.c.