posnk kernel: kernel/earlycon.c File Reference
earlycon.c File Reference
#include "kernel/earlycon.h"
#include <stdint.h>
#include <string.h>
Typedefs
typedef int(* printf_helper_t)(char c, uint32_t impl)
Functions
void utoa (unsigned int value, int base, char *str)
void utoa_s (int value, int base, char *str)
int earlycon_ivprintf (printf_helper_t __helper, uint32_t impl, const char *str, va_list args)
int earlycon_sprintf_helper (char tok, uint32_t impl)
int earlycon_vsprintf (char *str, const char *format, va_list args)
int earlycon_sprintf (char *str, const char *format,...)
int earlycon_aprintf (const char *str,...)
int debugcon_aprintf (const char *str,...)
Variables
char earlycon_printf_buffer [256]
Typedef Documentation
typedef int(* printf_helper_t)(char c, uint32_t impl)
Definition at line 10 of file earlycon.c.
Function Documentation
int debugcon_aprintf (const char * str, ...)
Definition at line 109 of file earlycon.c.
References debugcon_aputs(), earlycon_printf_buffer, and earlycon_vsprintf().
Referenced by semaphore_idown(), sys_waitpid(), and vgacon_handle_escape().
int earlycon_aprintf (const char * str, ...)
Definition at line 100 of file earlycon.c.
References earlycon_aputs(), earlycon_printf_buffer, and earlycon_vsprintf().
int earlycon_ivprintf (printf_helper_t __helper, uint32_t impl, const char * str, va_list args)
Definition at line 12 of file earlycon.c.
References strlen(), utoa(), and utoa_s().
Referenced by earlycon_vsprintf().
int earlycon_sprintf (char * str, const char * format, ...)
Definition at line 92 of file earlycon.c.
References earlycon_vsprintf().
int earlycon_sprintf_helper (char tok, uint32_t impl)
Definition at line 75 of file earlycon.c.
Referenced by earlycon_vsprintf().
int earlycon_vsprintf (char * str, const char * format, va_list args)
Definition at line 83 of file earlycon.c.
References earlycon_ivprintf(), and earlycon_sprintf_helper().
Referenced by debugcon_aprintf(), earlycon_aprintf(), and earlycon_sprintf().
void utoa (unsigned int value, int base, char * str)
Definition at line 7 of file stdlib.c.
Referenced by earlycon_ivprintf(), and utoa_s().
void utoa_s (int value, int base, char * str)
Definition at line 57 of file stdlib.c.
Referenced by earlycon_ivprintf().
Variable Documentation
char earlycon_printf_buffer[256]
Definition at line 5 of file earlycon.c.
Referenced by debugcon_aprintf(), and earlycon_aprintf().