posnk kernel: include/kernel/earlycon.h File Reference
earlycon.h File Reference
#include <stddef.h>
#include <stdarg.h>
Macros
#define earlycon_printf earlycon_aprintf
#define earlycon_puts earlycon_aputs
#define debugcon_printf debugcon_aprintf
#define debugcon_puts debugcon_aputs
Functions
void earlycon_init ()
kernel/earlycon.h
void debugcon_init ()
void earlycon_putc (char c)
void earlycon_aputs (const char *string)
int earlycon_vsprintf (char *str, const char *format, va_list args)
int earlycon_sprintf (char *str, const char *format,...)
int earlycon_aprintf (const char *str,...)
int debugcon_aprintf (const char *str,...)
void debugcon_aputs (const char *str)
Macro Definition Documentation
#define debugcon_printf debugcon_aprintf
Definition at line 38 of file earlycon.h.
Referenced by ata_initialize(), ata_pci_probe(), ata_read(), ata_setup_lba_transfer(), ata_write(), device_block_write(), exception_handle(), ext2_e2tovfs_inode(), ext2_mount(), heapmm_free_internal(), interrupt_dispatch(), interrupt_register_handler(), mbr_parse(), paging_handle_fault(), pci_enumerate_all(), pci_enumerate_function(), process_child_event(), process_exec(), process_handle_signals(), process_send_signal(), process_signal_pgroup(), scheduler_exit_signal_handler(), scheduler_invoke_signal_handler(), syscall_dispatch(), and tar_read_record_mem().
#define debugcon_puts debugcon_aputs
Definition at line 39 of file earlycon.h.
Referenced by i386_init_mm().
#define earlycon_printf earlycon_aprintf
Definition at line 35 of file earlycon.h.
Referenced by debug_dump_state(), exception_panic(), heapmm_alloc(), i386_init_mm(), i386_init_stub(), i386_kmain(), paging_handle_out_of_memory(), tar_read_record(), and tar_read_record_mem().
#define earlycon_puts earlycon_aputs
Definition at line 36 of file earlycon.h.
Referenced by debug_dump_state(), debug_postmortem_hook(), debug_uputs(), i386_init_mm(), i386_kmain(), and kdbg_initialize().
Function Documentation
int debugcon_aprintf (const char * str, ...)
Definition at line 109 of file earlycon.c.
References debugcon_aputs(), earlycon_printf_buffer, and earlycon_vsprintf().
Referenced by semaphore_idown(), sys_waitpid(), and vgacon_handle_escape().
void debugcon_aputs (const char * str)
Definition at line 36 of file sercon_debug.c.
References debugcon_putc().
Referenced by debugcon_aprintf(), and heapmm_request_core().
void debugcon_init ()
Definition at line 6 of file sercon_debug.c.
References i386_outb(), and PORT.
Referenced by i386_init_mm().
int earlycon_aprintf (const char * str, ...)
Definition at line 100 of file earlycon.c.
References earlycon_aputs(), earlycon_printf_buffer, and earlycon_vsprintf().
void earlycon_aputs (const char * string)
Definition at line 124 of file vgacon_early.c.
References earlycon_putc().
Referenced by earlycon_aprintf(), and heapmm_request_core().
void earlycon_init ()
kernel/earlycon.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 31-03-2014 - Created
Definition at line 142 of file vgacon_early.c.
References vgacon_vc_info::attrib, vgacon_vc_info::cursor_x, vgacon_vc_info::cursor_y, vgacon_vc_info::escape, vgacon_vc_info::no_scroll, vgacon_vc_info::page_id, vgacon_early_get_text_video_memory(), and vgacon_vc_info::video_buffer.
Referenced by i386_init_mm().
void earlycon_putc (char c)
Definition at line 55 of file vgacon_early.c.
References vgacon_vc_info::cursor_x, vgacon_vc_info::cursor_y, vgacon_vc_info::escape, vgacon_early_move_cursor(), and vgacon_early_putch().
Referenced by earlycon_aputs().
int earlycon_sprintf (char * str, const char * format, ...)
Definition at line 92 of file earlycon.c.
References earlycon_vsprintf().
int earlycon_vsprintf (char * str, const char * format, va_list args)
Definition at line 83 of file earlycon.c.
References earlycon_ivprintf(), and earlycon_sprintf_helper().
Referenced by debugcon_aprintf(), earlycon_aprintf(), and earlycon_sprintf().