posnk kernel: kernel/elfloader.c File Reference
elfloader.c File Reference
#include <sys/errno.h>
#include <sys/stat.h>
#include <string.h>
#include "kernel/earlycon.h"
#include "kernel/vfs.h"
#include "kernel/physmm.h"
#include "kernel/heapmm.h"
#include "kernel/elf.h"
#include "kernel/process.h"
#include "kernel/scheduler.h"
Functions
int elf_load (char *path)
Function Documentation
int elf_load (char * path)
Definition at line 25 of file elfloader.c.
References Elf32_Ehdr::e_entry, Elf32_Ehdr::e_machine, Elf32_Ehdr::e_phentsize, Elf32_Ehdr::e_phnum, Elf32_Ehdr::e_phoff, Elf32_Ehdr::e_type, EACCES, EFAULT, EIO, EM_386, ENOENT, ENOEXEC, ENOMEM, process_info::entry_point, ET_EXEC, heapmm_alloc(), heapmm_free(), process_info::image_end, process_info::image_inode, process_info::image_start, inode::mode, MODE_EXEC, process_info::name, NULL, inode::open_count, Elf32_Phdr::p_filesz, Elf32_Phdr::p_flags, Elf32_Phdr::p_memsz, Elf32_Phdr::p_offset, Elf32_Phdr::p_type, Elf32_Phdr::p_vaddr, PF_W, PHYSMM_PAGE_ADDRESS_MASK, PHYSMM_PAGE_SIZE, PROCESS_MMAP_FLAG_WRITE, procvmm_mmap_file(), PT_LOAD, S_ISREG, scheduler_current_task, strcpy(), strlen(), vfs_find_inode(), vfs_get_filename(), vfs_have_permissions(), vfs_inode_ref(), vfs_inode_release(), and vfs_read().
Referenced by process_exec().