posnk kernel: include/kernel/exception.h File Reference
exception.h File Reference
#include <stddef.h>
Macros
#define EXCEPTION_DIV_ZERO 0
kernel/exception.h
#define EXCEPTION_DEBUG 1
#define EXCEPTION_OVERFLOW 2
#define EXCEPTION_BOUNDS_CHECK 3
#define EXCEPTION_INVALID_OPCODE 4
#define EXCEPTION_NO_FLOAT_UNIT 5
#define EXCEPTION_DOUBLE_FAULT 6
#define EXCEPTION_SEG_FAULT 7
#define EXCEPTION_STACK_EXCEPTION 8
#define EXCEPTION_PROTECTION_FAULT 9
#define EXCEPTION_PAGE_FAULT 10
#define EXCEPTION_FLOAT_UNIT_ERROR 11
Functions
void exception_handle (int exception, void *instr_pointer, void *state, size_t state_size)
Macro Definition Documentation
#define EXCEPTION_BOUNDS_CHECK 3
Definition at line 20 of file exception.h.
#define EXCEPTION_DEBUG 1
Definition at line 18 of file exception.h.
#define EXCEPTION_DIV_ZERO 0
kernel/exception.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 01-04-2014 - Created
Definition at line 17 of file exception.h.
#define EXCEPTION_DOUBLE_FAULT 6
Definition at line 23 of file exception.h.
#define EXCEPTION_FLOAT_UNIT_ERROR 11
Definition at line 28 of file exception.h.
#define EXCEPTION_INVALID_OPCODE 4
Definition at line 21 of file exception.h.
#define EXCEPTION_NO_FLOAT_UNIT 5
Definition at line 22 of file exception.h.
#define EXCEPTION_OVERFLOW 2
Definition at line 19 of file exception.h.
#define EXCEPTION_PAGE_FAULT 10
Definition at line 27 of file exception.h.
Referenced by paging_handle_fault().
#define EXCEPTION_PROTECTION_FAULT 9
Definition at line 26 of file exception.h.
#define EXCEPTION_SEG_FAULT 7
Definition at line 24 of file exception.h.
#define EXCEPTION_STACK_EXCEPTION 8
Definition at line 25 of file exception.h.
Function Documentation
void exception_handle (int exception, void * instr_pointer, void * state, size_t state_size)
Todo:
: Kernel mode exception
Todo:
: Look up appropriate signal for exception
Definition at line 59 of file exception.c.
References debug_dump_state(), debugcon_printf, exception_names, exception_panic(), exception_signals, process_send_signal(), and scheduler_current_task.
Referenced by i386_handle_interrupt(), and paging_handle_fault().