posnk kernel: kernel/exception.c File Reference
exception.c File Reference
#include <stddef.h>
#include <stdint.h>
#include "kernel/earlycon.h"
#include "kernel/system.h"
#include "kernel/signals.h"
#include "kernel/scheduler.h"
#include "util/debug.h"
Functions
void exception_panic (int exception, void *instr_pointer, void *state, size_t state_size)
void exception_handle (int exception, void *instr_pointer, void *state, size_t state_size)
Variables
char * exception_names []
kernel/exception.c
int exception_signals []
Function Documentation
void exception_handle (int exception, void * instr_pointer, void * state, size_t state_size)
Todo:
: Kernel mode exception
Todo:
: Look up appropriate signal for exception
Definition at line 59 of file exception.c.
References debug_dump_state(), debugcon_printf, exception_names, exception_panic(), exception_signals, process_send_signal(), and scheduler_current_task.
Referenced by i386_handle_interrupt(), and paging_handle_fault().
void exception_panic (int exception, void * instr_pointer, void * state, size_t state_size)
Definition at line 48 of file exception.c.
References debug_dump_state(), debug_postmortem_hook(), earlycon_printf, exception_names, and halt().
Referenced by exception_handle().
Variable Documentation
char* exception_names[]
Initial value:
 {
        "Division by zero",
        "Debugger trap",
        "Arithmethic overflow",
        "Bounds check",
        "Invalid opcode",
        "No floating-point unit",
        "Double fault",
        "Segmentation fault",
        "Stack exception",
        "Protection fault",
        "Unresolved page fault",
        "Floating-point unit error"
}
kernel/exception.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 02-04-2014 - Created
Definition at line 20 of file exception.c.
Referenced by exception_handle(), and exception_panic().
int exception_signals[]
Initial value:
 {
        SIGFPE,
        SIGTRAP,
        SIGFPE,
        SIGSEGV,
        SIGILL,
        SIGFPE,
        SIGSEGV,
        SIGSEGV,
        SIGSEGV,
        SIGSEGV,
        SIGSEGV,
        SIGFPE
}
Definition at line 34 of file exception.c.
Referenced by exception_handle().