posnk kernel: fs/ext2.c File Reference
ext2.c File Reference
#include <stdint.h>
#include <string.h>
#include <sys/errno.h>
#include <sys/types.h>
#include "fs/ext2.h"
#include "kernel/heapmm.h"
#include "kernel/device.h"
#include "kernel/vfs.h"
#include "kernel/earlycon.h"
Functions
int ext2_read_block (ext2_device_t *dev, uint32_t block_ptr, uint32_t in_block, void *buffer, aoff_t count, aoff_t *read_size)
fs/ext2.c
int ext2_write_block (ext2_device_t *dev, uint32_t block_ptr, uint32_t in_block, void *buffer, aoff_t count, aoff_t *write_size)
uint32_t ext2_decode_block_id (ext2_device_t *device, ext2_inode_t *inode, uint32_t block_id)
int ext2_read_inode (inode_t *_inode, void *_buffer, aoff_t f_offset, aoff_t length, aoff_t *nread)
int ext2_readdir (inode_t *_inode, void *_buffer, aoff_t f_offset, aoff_t length, aoff_t *nread)
dirent_t * ext2_finddir (inode_t *_inode, char *name)
ext2_block_group_desc_t * ext2_load_bgd (ext2_device_t *device, uint32_t bg_id)
void ext2_free_bgd (ext2_device_t *device, ext2_block_group_desc_t *bgd)
int ext2_load_e2inode (ext2_device_t *device, ext2_inode_t *ino, uint32_t ino_id)
void ext2_e2tovfs_inode (ext2_device_t *device, ext2_vinode_t *_ino, ino_t ino_id)
inode_t * ext2_load_inode (fs_device_t *device, ino_t id)
fs_device_t * ext2_mount (dev_t device, uint32_t flags)
Variables
fs_device_operations_t ext2_ops
Function Documentation
uint32_t ext2_decode_block_id (ext2_device_t * device, ext2_inode_t * inode, uint32_t block_id)
Definition at line 54 of file ext2.c.
References ext2_inode::block, ext2_superblock::block_size_enc, ext2_read_block(), NULL, and ext2_device::superblock.
Referenced by ext2_read_inode().
void ext2_e2tovfs_inode (ext2_device_t * device, ext2_vinode_t * _ino, ino_t ino_id)
Todo:
: Read link path
Definition at line 379 of file ext2.c.
References inode::atime, ext2_inode::atime, ext2_inode::block, ext2_inode::blocks, inode::ctime, ext2_inode::ctime, debugcon_printf, inode::device, ext2_device::device, inode::device_id, EXT2_IFBLK, EXT2_IFCHR, EXT2_IFDIR, EXT2_IFIFO, EXT2_IFLNK, EXT2_IFREG, EXT2_IFSOCK, EXT2_MODE_FMT, inode::gid, ext2_inode::gid, inode::hard_link_count, inode::id, fs_device::id, inode::if_dev, ext2_vinode::inode, ext2_inode::link_count, inode::link_path, inode::lock, inode::mode, ext2_inode::mode, inode::mount, inode::mtime, ext2_inode::mtime, inode::name, NULL, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFREG, S_IFSOCK, semaphore_alloc(), semaphore_up(), inode::size, strcpy(), inode::uid, ext2_inode::uid, inode::usage_count, and ext2_vinode::vfs_ino.
Referenced by ext2_load_inode().
dirent_t* ext2_finddir (inode_t * _inode, char * name)
Definition at line 280 of file ext2.c.
References dirent::d_reclen, ext2_readdir(), heapmm_alloc(), heapmm_free(), memcpy(), dirent::name, NULL, and strcmp().
void ext2_free_bgd (ext2_device_t * device, ext2_block_group_desc_t * bgd)
Definition at line 340 of file ext2.c.
References heapmm_free().
Referenced by ext2_load_e2inode().
ext2_block_group_desc_t* ext2_load_bgd (ext2_device_t * device, uint32_t bg_id)
Todo:
: Cache BGDs
Definition at line 312 of file ext2.c.
References ext2_device::bgdt_block, ext2_superblock::block_size_enc, ext2_device::dev_id, device_block_read(), heapmm_alloc(), heapmm_free(), NULL, and ext2_device::superblock.
Referenced by ext2_load_e2inode().
int ext2_load_e2inode (ext2_device_t * device, ext2_inode_t * ino, uint32_t ino_id)
Definition at line 345 of file ext2.c.
References ext2_superblock::block_size_enc, ext2_device::dev_id, device_block_read(), ext2_free_bgd(), ext2_load_bgd(), ext2_superblock::inode_size, ext2_block_group_desc::inode_table, ext2_superblock::inodes_per_group, and ext2_device::superblock.
Referenced by ext2_load_inode().
inode_t* ext2_load_inode (fs_device_t * device, ino_t id)
Definition at line 439 of file ext2.c.
References ext2_e2tovfs_inode(), ext2_load_e2inode(), heapmm_alloc(), ext2_vinode::inode, and NULL.
fs_device_t* ext2_mount (dev_t device, uint32_t flags)
Todo:
: Implement fallback to alternative superblock
Definition at line 473 of file ext2.c.
References ext2_device::bgdt_block, ext2_superblock::block_size_enc, debugcon_printf, ext2_device::dev_id, ext2_device::device, device_block_read(), EXT2_MOUNT_FLAG_RO, EXT2_NO_EXT_FIRST_INO, EXT2_NO_EXT_INODE_SIZE, ext2_ops, EXT2_ROOT_INODE, EXT2_SUPPORTED_REQ_FEATURES, EXT2_SUPPORTED_ROF_FEATURES, EXT2_VERSION_MAJOR_DYNAMIC, ext2_superblock::first_inode, heapmm_alloc(), heapmm_free(), fs_device::id, ext2_superblock::inode_size, fs_device::inode_size, fs_device::lock, NULL, fs_device::ops, ext2_superblock::required_features, ext2_superblock::ro_force_features, fs_device::root_inode_id, semaphore_alloc(), semaphore_up(), ext2_superblock::signature, ext2_device::superblock, ext2_superblock::version_major, and ext2_superblock::volume_name.
Referenced by vfs_mount().
int ext2_read_block (ext2_device_t * dev, uint32_t block_ptr, uint32_t in_block, void * buffer, aoff_t count, aoff_t * read_size)
fs/ext2.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 09-07-2014 - Created
Definition at line 24 of file ext2.c.
References ext2_superblock::block_size_enc, ext2_device::dev_id, device_block_read(), EFAULT, EIO, and ext2_device::superblock.
Referenced by ext2_decode_block_id(), and ext2_read_inode().
int ext2_read_inode (inode_t * _inode, void * _buffer, aoff_t f_offset, aoff_t length, aoff_t * nread)
Definition at line 108 of file ext2.c.
References ext2_superblock::block_size_enc, inode::device, EFAULT, EIO, ext2_decode_block_id(), ext2_read_block(), inode, ext2_vinode::inode, NULL, and ext2_device::superblock.
Referenced by ext2_readdir().
int ext2_readdir (inode_t * _inode, void * _buffer, aoff_t f_offset, aoff_t length, aoff_t * nread)
Definition at line 157 of file ext2.c.
References dirent::d_reclen, inode::device_id, dirent::device_id, EFAULT, EINVAL, EIO, ENOMEM, ext2_read_inode(), heapmm_alloc(), heapmm_free(), ext2_dirent::inode, dirent::inode_id, name, dirent::name, ext2_dirent::name_len, ext2_dirent::rec_len, and inode::size.
Referenced by ext2_finddir().
int ext2_write_block (ext2_device_t * dev, uint32_t block_ptr, uint32_t in_block, void * buffer, aoff_t count, aoff_t * write_size)
Definition at line 39 of file ext2.c.
References ext2_superblock::block_size_enc, ext2_device::dev_id, device_block_write(), EFAULT, EIO, and ext2_device::superblock.
Variable Documentation
fs_device_operations_t ext2_ops
Initial value:
 {
        &ext2_load_inode,
        NULL,
        NULL,
        NULL,
        &ext2_read_inode,
        NULL,
        &ext2_readdir,
        &ext2_finddir,
        NULL,
        NULL,
        NULL,
        NULL
}
Definition at line 458 of file ext2.c.
Referenced by ext2_mount().