posnk kernel: arch/i386/fpu.c File Reference
fpu.c File Reference
#include <stdint.h>
#include <string.h>
#include "arch/i386/x86.h"
#include "arch/i386/task_context.h"
#include "kernel/process.h"
#include "kernel/scheduler.h"
#include "util/debug.h"
Functions
uint8_t i386_fpu_cs_buf[512] __attribute__ ((aligned(16)))
arch/i386/fpu.c
void i386_fpu_initialize ()
void i386_enable_fpu ()
void i386_disable_fpu ()
void i386_init_fpu ()
void i386_fpu_save (i386_task_context_t *context)
void i386_fpu_load (i386_task_context_t *context)
void i386_fpu_on_cs ()
int i386_fpu_handle_ill ()
Variables
process_info_t * i386_fpu_process = NULL
int i386_fpu_enabled = 0
Function Documentation
uint8_t i386_fpu_cs_buf [512] __attribute__ ((aligned(16)))
arch/i386/fpu.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 01-04-2014 - Created
void i386_disable_fpu ()
Definition at line 39 of file fpu.c.
Referenced by i386_fpu_on_cs().
void i386_enable_fpu ()
Definition at line 31 of file fpu.c.
Referenced by i386_fpu_handle_ill().
int i386_fpu_handle_ill ()
Definition at line 71 of file fpu.c.
References process_info::arch_state, i386_enable_fpu(), i386_fpu_load(), i386_fpu_save(), i386_init_fpu(), and scheduler_current_task.
Referenced by i386_handle_interrupt().
void i386_fpu_initialize ()
Definition at line 26 of file fpu.c.
Referenced by i386_init_mm().
void i386_fpu_load (i386_task_context_t * context)
Definition at line 59 of file fpu.c.
References i386_task_context::fpu_state, and memcpy().
Referenced by i386_fpu_handle_ill().
void i386_fpu_on_cs ()
Definition at line 65 of file fpu.c.
References i386_disable_fpu().
Referenced by scheduler_exsig(), and scheduler_switch_task().
void i386_fpu_save (i386_task_context_t * context)
Definition at line 53 of file fpu.c.
References i386_task_context::fpu_state, and memcpy().
Referenced by i386_fpu_handle_ill().
void i386_init_fpu ()
Definition at line 47 of file fpu.c.
Referenced by i386_fpu_handle_ill().
Variable Documentation
int i386_fpu_enabled = 0
Definition at line 24 of file fpu.c.
process_info_t* i386_fpu_process = NULL
Definition at line 22 of file fpu.c.