posnk kernel: Stream API
Stream API
Implements the UNIX file API (fd streams)
Functions
stream_ptr_t * stream_get_ptr (int fd)
Get the stream pointer object for a file number.
int stream_copy_fd_table (llist_t *target)
Copy the current process's stream ptr table to target.
void stream_do_close_on_exec ()
Close the stream ptrs that are to be closed on execute.
void stream_do_close_all (process_info_t *process)
Close all stream pointers for a process.
ssize_t _sys_read (int fd, void *buffer, size_t count)
Read from a stream.
ssize_t _sys_write (int fd, void *buffer, size_t count)
Write to a stream.
off_t _sys_lseek (int fd, off_t offset, int whence)
Reposition read/write file offset.
int _sys_fchdir (int fd)
Changes the working directory for this process to the dir pointed to by fd
int _sys_fchmod (int fd, mode_t mode)
Change file mode.
int _sys_fchown (int fd, uid_t owner, gid_t group)
Change file owner and group.
int _sys_fcntl (int fd, int cmd, int arg)
Manipulate stream pointer.
int _sys_ioctl (int fd, int cmd, int arg)
Control device.
int _sys_dup2 (int oldfd, int newfd)
Duplicate stream pointer.
int _sys_dup (int oldfd)
Duplicate stream pointer.
int _sys_pipe2 (int pipefd[2], int flags)
Create a pipe.
int _sys_open (char *path, int flags, mode_t mode)
Open a file stream.
int _sys_close (int fd)
Close a stream pointer.
int _sys_fstat (int fd, struct stat *buf)
Get file status.
ssize_t _sys_getdents (int fd, void *buffer, size_t count)
Get directory entries.
int _sys_close_int (process_info_t *process, int fd)
Close a stream pointer on a different process.
int _sys_truncate (int fd, off_t size)
Data Structures
struct stream_ptr
Describes a pointer to a stream.
struct stream_info
Describes a stream A stream object is shared between all pointers to it and thus all processes having such a pointer.
Macros
#define STREAM_TYPE_FILE (0)
This stream refers to a file.
#define STREAM_TYPE_PIPE (1)
This stream is a pipe endpoint.
Typedefs
typedef struct stream_info stream_info_t
Describes a stream.
typedef struct stream_ptr stream_ptr_t
Describes a pointer to a stream.
Detailed Description
Implements the UNIX file API (fd streams)
The streams programming interface provides an unified way of transferring data. It wraps the VFS API and implements pipes. For files it keeps track of the current offset.
Slightly different terminology is used here:
UNIX - POSNK
File description - stream info
File descriptor - stream pointer
File (opened) - stream
Macro Definition Documentation
#define STREAM_TYPE_FILE (0)
This stream refers to a file.
Definition at line 40 of file streams.h.
Referenced by _sys_close_int(), _sys_fchdir(), _sys_fchmod(), _sys_fchown(), _sys_fstat(), _sys_ftruncate(), _sys_getdents(), _sys_ioctl(), _sys_lseek(), _sys_open(), _sys_read(), and _sys_write().
#define STREAM_TYPE_PIPE (1)
This stream is a pipe endpoint.
Definition at line 43 of file streams.h.
Referenced by _sys_close_int(), _sys_ftruncate(), _sys_getdents(), _sys_pipe2(), _sys_read(), and _sys_write().
Typedef Documentation
typedef struct stream_info stream_info_t
Describes a stream.
See Also
stream_info
Definition at line 50 of file streams.h.
typedef struct stream_ptr stream_ptr_t
Describes a pointer to a stream.
See Also
stream_ptr
Definition at line 57 of file streams.h.
Function Documentation
int _sys_close (int fd)
Close a stream pointer.
If the stream pointer was the last pointer for the stream the stream itself will be closed.
Parameters
fd The fd for the stream pointer to close
Returns
If an error occurred -1 is returned, otherwise 0 is returned
Exceptions
EBADF fd does not refer to an open stream pointer
EIO An io error occurred
Definition at line 1498 of file streams.c.
References _sys_close_int(), and scheduler_current_task.
Referenced by _sys_dup2(), stream_do_close_on_exec(), and sys_close().
int _sys_close_int (process_info_t * process, int fd)
Close a stream pointer on a different process.
See Also
_sys_close
Parameters
process The process context to use
fd The fd for the stream pointer to close
Returns
If an error occurred -1 is returned, otherwise 0 is returned
Exceptions
EBADF fd does not refer to an open stream pointer
EIO An io error occurred
Todo:
: Move to stream close
Todo:
: Handle result
Todo:
: Handle result
Definition at line 1515 of file streams.c.
References device_block_close(), device_char_close(), EBADF, inode::fifo, stream_info::flags, heapmm_free(), inode::if_dev, stream_ptr::info, stream_info::inode, llist_unlink(), stream_info::lock, inode::mode, O_ACCMODE, O_RDONLY, O_WRONLY, stream_info::pipe, pipe_close_read(), pipe_close_write(), pipe_free(), stream_info::ref_count, S_ISBLK, S_ISCHR, S_ISFIFO, scheduler_current_task, semaphore_down(), semaphore_up(), stream_get_ptr_o(), STREAM_TYPE_FILE, STREAM_TYPE_PIPE, syscall_errno, stream_info::type, and vfs_inode_release().
Referenced by _sys_close(), and stream_do_close_all().
int _sys_dup (int oldfd)
Duplicate stream pointer.
Parameters
oldfd The stream pointer to duplicate
Returns
The duplicate fd if successful, if an error occurred: -1
Exceptions
EBADF oldfd does not refer to an open stream
EMFILE Maximum number of open stream pointers reached
Call _sys_dup2 with a new fd for newfd
Todo:
: Check for fd_ctr overflow
Definition at line 1116 of file streams.c.
References _sys_dup2(), process_info::fd_ctr, and scheduler_current_task.
Referenced by _sys_fcntl(), i386_init_stub(), and sys_dup().
int _sys_dup2 (int oldfd, int newfd)
Duplicate stream pointer.
If newfd already refers to an open pointer that pointer will be closed
Parameters
oldfd The stream pointer to duplicate
newfd The fd to use for the duplicate
Returns
The duplicate fd if successful, if an error occurred: -1
Exceptions
EBADF oldfd does not refer to an open stream
EBADF newfd is not a valid fd
EMFILE Maximum number of open stream pointers reached
Definition at line 1053 of file streams.c.
References _sys_close(), EBADF, EMFILE, process_info::fd_ctr, stream_ptr::fd_flags, process_info::fd_table, heapmm_alloc(), stream_ptr::id, stream_ptr::info, llist_add_end(), stream_info::ref_count, scheduler_current_task, stream_get_ptr(), and syscall_errno.
Referenced by _sys_dup(), _sys_fcntl(), and sys_dup2().
int _sys_fchdir (int fd)
Changes the working directory for this process to the dir pointed to by fd
Parameters
fd The fd referring to the new working directory
Returns
In case of an error: -1, Otherwise 0
Exceptions
EBADF fd does not refer to an open stream
ENOTDIR fd does not refer to a directory stream
See Also
vfs_chdir for other errors that might occur
Definition at line 742 of file streams.c.
References stream_info::dirc, EBADF, ENOTDIR, stream_ptr::info, stream_info::inode, inode::mode, S_ISDIR, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, stream_info::type, and vfs_chdir().
Referenced by sys_fchdir().
int _sys_fchmod (int fd, mode_t mode)
Change file mode.
Parameters
fd The fd to operate on
mode The new mode to set on the file (is masked with 07777 to prevent type changes)
Returns
In case of an error: -1, Otherwise 0
Exceptions
EBADF fd does not refer to an open stream
EBADF fd does not refer to a file stream
EPERM User does not have permission to change mode on this file
Definition at line 832 of file streams.c.
References EBADF, EPERM, get_effective_uid(), get_perm_class(), inode::gid, stream_ptr::info, stream_info::inode, inode::mode, PERM_CLASS_OWNER, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, stream_info::type, and inode::uid.
Referenced by sys_fchmod().
int _sys_fchown (int fd, uid_t owner, gid_t group)
Change file owner and group.
Parameters
fd The fd to operate on
owner The new owner of the file
group The new group of the file
If either group or owner is -1 then that ID will not be changed. To change the group of a file, the user must both own the file and be in the file's group
Returns
In case of an error: -1, Otherwise 0
Exceptions
EBADF fd does not refer to an open stream
EBADF fd does not refer to a file stream
EPERM User is not the owner of the file
Definition at line 884 of file streams.c.
References EBADF, EPERM, get_perm_class(), inode::gid, stream_ptr::info, stream_info::inode, PERM_CLASS_GROUP, PERM_CLASS_OWNER, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, stream_info::type, and inode::uid.
Referenced by sys_fchown().
int _sys_fcntl (int fd, int cmd, int arg)
Manipulate stream pointer.
Parameters
fd The fd to operate on
cmd The function to execute
arg An argument to the function
Supported functions are:
F_DUPFD Duplicate stream pointer
This differs from dup2 in that it will use the lowest available fd when arg does not refer to an existant fd.
Parameters
arg The fd to assign to the duplicate stream pointer
Returns
The duplicate fd or -1 in case of an error
See Also
_sys_dup For other errors that may occur
F_GETFD Read the stream pointer flags
Parameters
arg IGNORED
Returns
The stream pointer flags or -1 in case of an error
F_SETFD Set the stream pointer flags
Parameters
arg The new stream pointer flags
Returns
In case of an error: -1, Otherwise 0
F_GETFL Read the stream flags
Parameters
arg IGNORED
Returns
The stream flags or -1 in case of an error
F_SETFL Set the stream flags
The stream creation and access flags are ignored
Parameters
arg The new stream pointer flags
Returns
In case of an error: -1, Otherwise 0
Exceptions
EBADF fd does not refer to an open stream
Definition at line 958 of file streams.c.
References _sys_dup(), _sys_dup2(), EBADF, F_DUPFD, F_GETFD, F_GETFL, F_SETFD, F_SETFL, FASYNC, stream_ptr::fd_flags, stream_info::flags, stream_ptr::info, O_APPEND, O_NONBLOCK, stream_get_ptr(), and syscall_errno.
Referenced by sys_fcntl().
int _sys_fstat (int fd, struct stat * buf)
Get file status.
See Also
struct stat
Parameters
fd The fd to get the file status of
buf The buffer to put the status info in
Returns
In case of an error: -1, Otherwise 0
Exceptions
EBADF fd does not refer to an open stream
EBADF fd does not refer to a file stream
Todo:
: FIX
Todo:
: Implement sparse files
Todo:
: Ask FS about block size
Definition at line 783 of file streams.c.
References inode::atime, inode::ctime, inode::device_id, EBADF, inode::gid, inode::hard_link_count, inode::id, inode::if_dev, stream_ptr::info, stream_info::inode, inode::mode, inode::mtime, inode::size, stat::st_atime, stat::st_ctime, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_mtime, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, stream_info::type, and inode::uid.
Referenced by sys_fstat().
ssize_t _sys_getdents (int fd, void * buffer, size_t count)
Get directory entries.
This function implements the getdents(2) system call It will read as many whole dirent's as will fit in count, no partial dirents will be read.
Parameters
fd The directory stream to read from
buffer The buffer to store the dirents in
count The number of bytes to read
Returns
The number of bytes actually read or -1 in case of error
Exceptions
EBADF fd does not refer to an open file stream
EINVAL fd was not opened with READ access mode
ENOTDIR fd does not refer to a directory stream
EFAULT At least one of the parameters was a null pointer
See Also
vfs_getdents for other errors that might occur
Definition at line 203 of file streams.c.
References EBADF, EFAULT, EINVAL, ENOTDIR, stream_info::flags, stream_ptr::info, stream_info::inode, stream_info::lock, O_ACCMODE, O_WRONLY, stream_info::offset, semaphore_down(), semaphore_up(), stream_get_ptr(), STREAM_TYPE_FILE, STREAM_TYPE_PIPE, syscall_errno, stream_info::type, and vfs_getdents().
Referenced by sys_getdents().
int _sys_ioctl (int fd, int cmd, int arg)
Control device.
Parameters
fd The fd to operate on
cmd The function to execute
arg An argument to the function
Returns
Usually 0 on success, and -1 on error.
Exceptions
EBADF fd does not refer to an open stream
ENOTTY fd does not refer to a special file
See Also
tty_ioctls ioctl functions supported by teletypes
ioctl_list List of all ioctl functionsq
Definition at line 1008 of file streams.c.
References device_block_ioctl(), device_char_ioctl(), EBADF, ENOTTY, inode::if_dev, stream_ptr::info, stream_info::inode, inode::mode, S_ISBLK, S_ISCHR, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, and stream_info::type.
Referenced by sys_ioctl().
off_t _sys_lseek (int fd, off_t offset, int whence)
Reposition read/write file offset.
The way the new file offset is calculated is determined by whence:
Whence:
SEEK_SET
The offset is set to offset bytes
SEEK_CUR
The offset is set to its current location plus offset bytes
SEEK_END
The offset is set to the size of the file plus offset bytes
Setting an offset past the end of the file will not grow the file until the next write() to the file
Parameters
fd The file stream to operate on
offset The offset to use when repositioning the file offset
whence The reference offset to use
Returns
The new file offset or -1 in case of an error
Exceptions
EBADF fd does not refer to an open stream
ESPIPE fd does not refer to a file
EINVAL New offset is negative
EINVAL Invalid value for whence
Definition at line 630 of file streams.c.
References EBADF, EINVAL, ESPIPE, stream_ptr::info, stream_info::inode, stream_info::lock, inode::mode, stream_info::offset, S_ISFIFO, SEEK_CUR, SEEK_END, SEEK_SET, semaphore_down(), semaphore_up(), inode::size, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, and stream_info::type.
Referenced by sys_lseek().
int _sys_open (char * path, int flags, mode_t mode)
Open a file stream.
The behaviour of this function is determined by flags
It is required to specify one of the access mode flags:
O_RDONLY Open read-only
O_WRONLY Open write-only
O_RDWR Open read-write
Valid optional flags:
O_APPEND Open the file for appending
Before each sys_write the offset is set to the end of the file
O_CLOEXEC Set this stream pointer to close on execve(2)
When this flag is set this stream pointer will be closed when executing a new program.
O_CREAT Create file
If this flag is set and the file does not exist the file will be created using the mode specified in _mode
O_NONBLOCK Use non-blocking IO
When this flag is set _sys_read and _sys_write will not block if no data is available
O_TRUNC Truncate file
If this file already exists and is a regular file and the open mode allows writing the file will be truncated to length 0
O_EXCL Ensure the file is created
If this flag is set and O_CREAT is set and the file already exists _sys_open
will fail with EEXIST
Parameters
path The path of the file to open
flags The options for opening the file
mode The mode to create the file with
Returns
-1 if an error occurred, if successful the fd of the opened stream is returned
Exceptions
ENOENT The file does not exist and O_CREAT is not set
EEXIST The file exists and O_EXCL is set
ENOMEM Insufficient kernel memory was available
ENOSPC Insufficient room was available to create the file
ENOENT An element in path does not exist
ENXIO Tried to open a FIFO for writing that is not open for reading and O_NONBLOCK | O_WRONLY is set
ENXIO Tried to open a special file that points to an non-existant device
EMFILE Too many files are open
EACCES The requested access is not allowed
EFAULT Path is a null pointer
Todo:
: Make this an assertion
Todo:
: Permission checks
Todo:
: Call on VFS to actually truncate file
Todo:
: Check if this behaviour is correct
Todo:
: Implement non-blocking IO
Todo:
: Fix this
Todo:
: Handle result
Todo:
: Handle result
Definition at line 1323 of file streams.c.
References device_block_open(), device_char_open(), stream_info::dirc, EEXIST, EFAULT, ENOENT, ENOMEM, FD_CLOEXEC, process_info::fd_ctr, stream_ptr::fd_flags, process_info::fd_table, inode::fifo, stream_info::flags, heapmm_alloc(), heapmm_free(), stream_ptr::id, inode::if_dev, stream_ptr::info, stream_info::inode, dir_cache::inode, llist_add_end(), stream_info::lock, inode::mode, O_ACCMODE, O_APPEND, O_CLOEXEC, O_CREAT, O_EXCL, O_NDELAY, O_NONBLOCK, O_RDONLY, O_TRUNC, O_WRONLY, stream_info::offset, pipe_open_read(), pipe_open_write(), stream_info::ref_count, S_IFREG, S_ISBLK, S_ISCHR, S_ISFIFO, scheduler_current_task, semaphore_alloc(), semaphore_up(), inode::size, STREAM_TYPE_FILE, syscall_errno, stream_info::type, inode::usage_count, vfs_find_dirc(), vfs_inode_ref(), and vfs_mknod().
Referenced by i386_init_stub(), and sys_open().
int _sys_pipe2 (int pipefd[2], int flags)
Create a pipe.
Parameters
pipefd The created fd's will be put in this array, the read endpoint will be in pipefd[0], the write endpoint in pipefd[1]
flags Flags to set on the streams
Returns
On success, zero is returned. On error, -1 is returned.
Exceptions
ENOMEM There was not enough memory to create the pipe
Todo:
: Check for fd_ctr overflow
Todo:
: Handle FD_CLOEXEC, verify flags field
Definition at line 1131 of file streams.c.
References ENOMEM, process_info::fd_ctr, stream_ptr::fd_flags, process_info::fd_table, stream_info::flags, heapmm_alloc(), heapmm_free(), stream_ptr::id, stream_ptr::info, llist_add_end(), stream_info::lock, O_RDONLY, O_WRONLY, stream_info::offset, stream_info::pipe, pipe_create(), pipe_free(), pipe_open_read(), pipe_open_write(), stream_info::ref_count, scheduler_current_task, semaphore_alloc(), semaphore_free(), semaphore_up(), STREAM_TYPE_PIPE, syscall_errno, and stream_info::type.
Referenced by sys_pipe(), and sys_pipe2().
ssize_t _sys_read (int fd, void * buffer, size_t count)
Read from a stream.
This function implements the read(2) system call, It attempts to read count number of bytes from the stream
Parameters
fd The stream to read from
buffer The buffer to store the data in
count The number of bytes to read
Returns
The number of bytes actually read or -1 in case of error
Exceptions
EBADF fd does not refer to an open file stream
EBADF fd was not opened with READ access mode
EISDIR fd refers to a directory stream
EFAULT At least one of the parameters was a null pointer
EPIPE The remote end of the pipe has closed and no data remains
See Also
vfs_read for other errors that might occur
Todo:
: Move this past pipe_read(); call
Todo:
: Fix behaviour here
Definition at line 305 of file streams.c.
References EBADF, EFAULT, EINVAL, EPIPE, stream_info::flags, stream_ptr::info, stream_info::inode, stream_info::lock, O_ACCMODE, O_NONBLOCK, O_WRONLY, stream_info::offset, stream_info::pipe, pipe_read(), process_send_signal(), scheduler_current_task, semaphore_down(), semaphore_up(), SIGPIPE, stream_get_ptr(), STREAM_TYPE_FILE, STREAM_TYPE_PIPE, syscall_errno, stream_info::type, and vfs_read().
Referenced by sys_read().
int _sys_truncate (int fd, off_t size)
ssize_t _sys_write (int fd, void * buffer, size_t count)
Write to a stream.
This function implements the write(2) system call, It attempts to write count number of bytes from to stream
Parameters
fd The stream to write to
buffer The buffer to get the data from
count The number of bytes to write
Returns
The number of bytes actually written or -1 in case of error
Exceptions
EBADF fd does not refer to an open file stream
EBADF fd was not opened with WRITE access mode
EISDIR fd refers to a directory stream
EFAULT At least one of the parameters was a null pointer
EPIPE The remote end of the pipe has been closed and there is no room left in the pipe buffer
See Also
vfs_write for other errors that might occur
Todo:
: Move this past pipe_write(); call
Todo:
: Fix behaviour here
Definition at line 427 of file streams.c.
References EBADF, EFAULT, EINVAL, EPIPE, stream_info::flags, stream_ptr::info, stream_info::inode, stream_info::lock, O_ACCMODE, O_NONBLOCK, O_RDONLY, stream_info::offset, stream_info::pipe, pipe_write(), process_send_signal(), scheduler_current_task, semaphore_down(), semaphore_up(), SIGPIPE, stream_get_ptr(), STREAM_TYPE_FILE, STREAM_TYPE_PIPE, syscall_errno, stream_info::type, and vfs_write().
Referenced by sys_write().
int stream_copy_fd_table (llist_t * target)
Copy the current process's stream ptr table to target.
The copied stream ptrs will point to the same stream info and the pointer flags will not be copied.
Parameters
target The head of the linked list to store the copies in
Returns
0 if successful
Definition at line 121 of file streams.c.
References process_info::fd_table, llist_iterate_select(), NULL, scheduler_current_task, and stream_ptr_copy_iterator().
Referenced by scheduler_fork().
void stream_do_close_all (process_info_t * process)
Close all stream pointers for a process.
Parameters
process The process to close the pointers for
Definition at line 173 of file streams.c.
References _sys_close_int(), process_info::fd_table, stream_ptr::id, llist_iterate_select(), NULL, and stream_closeall_iterator().
Referenced by process_reap().
void stream_do_close_on_exec ()
Close the stream ptrs that are to be closed on execute.
See Also
stream_exec_iterator
Definition at line 150 of file streams.c.
References _sys_close(), process_info::fd_table, stream_ptr::id, llist_iterate_select(), NULL, scheduler_current_task, and stream_exec_iterator().
Referenced by process_exec().
stream_ptr_t* stream_get_ptr (int fd)
Get the stream pointer object for a file number.
Parameters
fd The open file number to look up
Returns
The stream pointer or NULL if fd is invalid
Definition at line 52 of file streams.c.
References process_info::fd_table, llist_iterate_select(), scheduler_current_task, and stream_ptr_search_iterator().
Referenced by _sys_dup2(), _sys_fchdir(), _sys_fchmod(), _sys_fchown(), _sys_fcntl(), _sys_fstat(), _sys_ftruncate(), _sys_getdents(), _sys_ioctl(), _sys_lseek(), _sys_read(), and _sys_write().