posnk kernel: VFS
VFS
The Virtual File System layer provides abstraction between the rest of the kernel and the FS drivers, it handles path resolution, filesystem mounts and all special file types.
Functions
int vfs_initialize (fs_device_t *root_device)
Initialize the VFS layer.
Data Structures
struct inode
Describes a file currently cached by the kernel.
struct dirent
Describes a directory entry in a portable FS independent format.
struct dir_cache
An entry in the path element cache The kernel keeps track of these to resolve the .
struct fs_device_operations
Contains callbacks for all filesystem driver functions.
struct fs_device
An instance of a filesystem driver.
Macros
#define MODE_READ 4
Bit definition for inode->mode, this file is readable.
#define MODE_WRITE 2
Bit definition for inode->mode, this file is writable.
#define MODE_EXEC 1
Bit definition for inode->mode, this file is executable/searchable.
VFS API
Public VFS functions
void vfs_inode_release (inode_t *inode)
Release a reference to an inode.
inode_t * vfs_find_parent (char *path)
Look up the inode for the directory containing the file.
inode_t * vfs_find_inode (char *path)
Look up the inode for the file referenced by path.
inode_t * vfs_find_symlink (char *path)
Look up the inode for the file referenced by path, not dereferencing symlinks or mounts.
dirent_t * vfs_find_dirent (inode_t *inode, char *name)
Find a directory entry.
int vfs_rmdir (char *path)
Delete a directory.
int vfs_mkdir (char *path, mode_t mode)
Create a directory.
int vfs_mknod (char *path, mode_t mode, dev_t dev)
Create a file.
int vfs_unlink (char *path)
Delete a file.
int vfs_link (char *oldpath, char *newpath)
Create a hard link.
int vfs_symlink (char *oldpath, char *newpath)
Create a symbolic link.
int vfs_mount (char *device, char *mountpoint, char *fstype, uint32_t flags)
Mount a filesystem.
int vfs_write (inode_t *inode, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *read_size, int non_block)
Write data to a file.
int vfs_read (inode_t *inode, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *read_size, int non_block)
Read data from a file.
int vfs_getdents (inode_t *inode, aoff_t file_offset, dirent_t *buffer, aoff_t count, aoff_t *read_size)
Read directory entries.
int vfs_truncate (inode_t *inode, aoff_t length)
Resize a file.
int vfs_chroot (dir_cache_t *dirc)
Changes the root directory for this process.
int vfs_chdir (dir_cache_t *dirc)
Changes the working directory for this process.
char * vfs_get_filename (const char *path)
Extract the filename part of a path.
VFS Internal
Utility functions for use by VFS functions only
dir_cache_t * vfs_dir_cache_mkroot (inode_t *root_inode)
Create the initial dir cache entry.
void vfs_dir_cache_release (dir_cache_t *dirc)
Release a reference to a directory cache entry.
dir_cache_t * vfs_find_dirc (char *path)
Look up a file referred to by a path.
perm_class_t vfs_get_min_permissions (inode_t *inode, mode_t req_mode)
Returns the minimum privilege level required for access with mode.
int vfs_have_permissions (inode_t *inode, mode_t req_mode)
Check permissions for access with mode.
inode_t * vfs_get_inode (fs_device_t *device, ino_t inode_id)
Get an inode by it's ID.
inode_t * vfs_effective_inode (inode_t *inode)
Get the effective inode for an inode, in other words : Dereference possible symlinks and mounts.
dir_cache_t * vfs_dir_cache_ref (dir_cache_t *dirc)
Create a new reference to a directory cache entry.
dir_cache_t * vfs_dir_cache_new (dir_cache_t *par, ino_t inode_id)
Create a new directory cache entry.
Typedefs
typedef struct inode inode_t
Describes a file currently cached by the kernel.
typedef struct dirent dirent_t
An entry in the path element cache.
typedef struct dir_cache dir_cache_t
An entry in the path element cache.
typedef struct fs_device fs_device_t
An instance of a filesystem driver.
typedef struct fs_device_operations fs_device_operations_t
Contains callbacks for all filesystem driver functions.
Detailed Description
The Virtual File System layer provides abstraction between the rest of the kernel and the FS drivers, it handles path resolution, filesystem mounts and all special file types.
Macro Definition Documentation
#define MODE_EXEC 1
Bit definition for inode->mode, this file is executable/searchable.
Definition at line 50 of file vfs.h.
Referenced by elf_load(), and vfs_find_dirent().
#define MODE_READ 4
Bit definition for inode->mode, this file is readable.
Definition at line 40 of file vfs.h.
Referenced by vfs_getdents(), and vfs_read().
#define MODE_WRITE 2
Bit definition for inode->mode, this file is writable.
Definition at line 45 of file vfs.h.
Referenced by vfs_link(), vfs_mknod(), vfs_symlink(), vfs_truncate(), vfs_unlink(), and vfs_write().
Typedef Documentation
typedef struct dir_cache dir_cache_t
An entry in the path element cache.
See Also
dir_cache
Definition at line 68 of file vfs.h.
typedef struct dirent dirent_t
An entry in the path element cache.
See Also
dirent
Definition at line 62 of file vfs.h.
typedef struct fs_device_operations fs_device_operations_t
Contains callbacks for all filesystem driver functions.
See Also
fs_device_operations
Definition at line 80 of file vfs.h.
typedef struct fs_device fs_device_t
An instance of a filesystem driver.
See Also
fs_device
Definition at line 74 of file vfs.h.
typedef struct inode inode_t
Describes a file currently cached by the kernel.
See Also
inode
Definition at line 56 of file vfs.h.
Function Documentation
int vfs_chdir (dir_cache_t * dirc)
Changes the working directory for this process.
Parameters
dirc The new working directory
Returns
An error code or 0 for success
Definition at line 2254 of file vfs.c.
References process_info::current_directory, EFAULT, ENOTDIR, dir_cache::inode, inode::mode, S_ISDIR, scheduler_current_task, vfs_dir_cache_ref(), and vfs_dir_cache_release().
Referenced by _sys_chdir(), and _sys_fchdir().
int vfs_chroot (dir_cache_t * dirc)
Changes the root directory for this process.
Parameters
dirc The new root directory
Returns
An error code or 0 for success
Definition at line 2278 of file vfs.c.
References EFAULT, ENOTDIR, dir_cache::inode, inode::mode, process_info::root_directory, S_ISDIR, scheduler_current_task, vfs_dir_cache_ref(), and vfs_dir_cache_release().
dir_cache_t* vfs_dir_cache_mkroot (inode_t * root_inode)
Create the initial dir cache entry.
Parameters
root_inode The root inode of the initial root filesystem
Returns
The dir cache entry for the root inode
Definition at line 2150 of file vfs.c.
References heapmm_alloc(), dir_cache::inode, dir_cache::parent, dir_cache::usage_count, and vfs_inode_ref().
Referenced by vfs_initialize().
dir_cache_t* vfs_dir_cache_new (dir_cache_t * par, ino_t inode_id)
Create a new directory cache entry.
Parameters
parent Directory cache entry to use as parent
Returns
The new entry
Definition at line 2210 of file vfs.c.
References inode::device, heapmm_alloc(), heapmm_free(), dir_cache::inode, NULL, dir_cache::parent, dir_cache::usage_count, vfs_dir_cache_ref(), vfs_dir_cache_release(), vfs_effective_inode(), vfs_get_inode(), and vfs_inode_release().
Referenced by vfs_find_dirc(), and vfs_find_dirc_parent().
dir_cache_t* vfs_dir_cache_ref (dir_cache_t * dirc)
Create a new reference to a directory cache entry.
Parameters
dirc The entry to refer to
Returns
The new reference
Definition at line 2198 of file vfs.c.
References dir_cache::usage_count.
Referenced by scheduler_fork(), vfs_chdir(), vfs_chroot(), vfs_dir_cache_new(), vfs_find_dirc(), vfs_find_dirc_parent(), and vfs_initialize().
void vfs_dir_cache_release (dir_cache_t * dirc)
Release a reference to a directory cache entry.
Parameters
dirc The reference to release
Definition at line 2171 of file vfs.c.
References heapmm_free(), dir_cache::inode, dir_cache::parent, dir_cache::usage_count, vfs_dir_cache_release(), and vfs_inode_release().
Referenced by process_reap(), vfs_chdir(), vfs_chroot(), vfs_dir_cache_new(), vfs_dir_cache_release(), vfs_find_dirc(), vfs_find_dirc_parent(), vfs_find_inode(), vfs_find_parent(), and vfs_find_symlink().
inode_t* vfs_effective_inode (inode_t * inode)
Get the effective inode for an inode, in other words : Dereference possible symlinks and mounts.
Parameters
inode The inode that is to be checked
Returns
The inode that the parameter points to.
Definition at line 256 of file vfs.c.
References inode::link_path, inode::mount, NULL, vfs_find_inode(), and vfs_inode_ref().
Referenced by vfs_dir_cache_new(), vfs_getdents(), vfs_read(), vfs_truncate(), and vfs_write().
dir_cache_t* vfs_find_dirc (char * path)
Look up a file referred to by a path.
Parameters
path The path to resolve
Returns
A dir_cache entry on the file referred to by path
Todo:
: Check for errors
Definition at line 2482 of file vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, process_info::current_directory, heapmm_alloc(), heapmm_free(), dir_cache::inode, dirent::inode_id, inode::mode, NULL, dir_cache::parent, process_info::root_directory, S_ISDIR, scheduler_current_task, strchr(), strchrnul(), strncmp(), strncpy(), dir_cache::usage_count, vfs_dir_cache_new(), vfs_dir_cache_ref(), vfs_dir_cache_release(), and vfs_find_dirent().
Referenced by _sys_chdir(), _sys_open(), vfs_find_inode(), and vfs_find_symlink().
dirent_t* vfs_find_dirent (inode_t * inode, char * name)
Find a directory entry.
Parameters
inode The directory to search
name The filename to match
Returns
The directory entry matching name from the directory inode, if none, NULL is returned
Todo:
: Find a way to pass an error from here
Definition at line 295 of file vfs.c.
References inode::device, fs_device_operations::find_dirent, MODE_EXEC, NULL, fs_device::ops, and vfs_have_permissions().
Referenced by vfs_find_dirc(), vfs_find_dirc_parent(), and vfs_find_symlink().
inode_t* vfs_find_inode (char * path)
Look up the inode for the file referenced by path.
Parameters
path The path of the file to resolve
Returns
The file's inode
Definition at line 2680 of file vfs.c.
References dir_cache::inode, NULL, vfs_dir_cache_release(), vfs_find_dirc(), and vfs_inode_ref().
Referenced by _sys_chmod(), _sys_chown(), _sys_stat(), _sys_truncate(), elf_load(), tar_extract(), tar_read_record(), tar_read_record_mem(), vfs_effective_inode(), vfs_link(), vfs_mkdir(), vfs_mknod(), vfs_mount(), vfs_rmdir(), and vfs_symlink().
inode_t* vfs_find_parent (char * path)
Look up the inode for the directory containing the file.
Parameters
path The path of the file to resolve
Returns
The file's parent directory
Todo:
: Check for search permission
Definition at line 2653 of file vfs.c.
References dir_cache::inode, NULL, vfs_dir_cache_release(), vfs_find_dirc_parent(), and vfs_inode_ref().
Referenced by vfs_link(), vfs_mkdir(), vfs_mknod(), vfs_symlink(), and vfs_unlink().
inode_t* vfs_find_symlink (char * path)
Look up the inode for the file referenced by path, not dereferencing symlinks or mounts.
Parameters
path The path of the file to resolve
Returns
The file's inode
Definition at line 2708 of file vfs.c.
References process_info::current_directory, inode::device, heapmm_free(), dir_cache::inode, dirent::inode_id, NULL, dir_cache::parent, process_info::root_directory, scheduler_current_task, strlen(), vfs_dir_cache_release(), vfs_find_dirc(), vfs_find_dirent(), vfs_get_filename(), vfs_get_inode(), and vfs_inode_ref().
Referenced by _sys_lstat(), _sys_readlink(), and vfs_unlink().
char* vfs_get_filename (const char * path)
Extract the filename part of a path.
Warning
This allocates heap for the return value, free with heapmm_free(r, strlen(r) + 1);
Parameters
path The path to analyze
Returns
The file name, see warning!
Todo:
: Come up with a way to do this without tripping heap alloc error
Definition at line 53 of file vfs.c.
References heapmm_alloc(), heapmm_free(), NULL, strcpy(), strlen(), and strrchr().
Referenced by elf_load(), vfs_find_symlink(), vfs_link(), vfs_mknod(), vfs_symlink(), and vfs_unlink().
inode_t* vfs_get_inode (fs_device_t * device, ino_t inode_id)
Get an inode by it's ID.
Parameters
device The device to get the inode from
inode_id The ID of the inode to look up
Returns
The inode with id inode_id from device.
Definition at line 215 of file vfs.c.
References vfs_cache_params::device_id, fs_device::id, vfs_cache_params::inode_id, llist_iterate_select(), fs_device_operations::load_inode, fs_device::ops, vfs_cache_find_iterator(), and vfs_inode_ref().
Referenced by vfs_dir_cache_new(), and vfs_find_symlink().
perm_class_t vfs_get_min_permissions (inode_t * inode, mode_t req_mode)
Returns the minimum privilege level required for access with mode.
Parameters
inode The file to check
req_mode The requested access mode
Returns
The required privilege class : other, group or owner
Definition at line 185 of file vfs.c.
References inode::mode, PERM_CLASS_GROUP, PERM_CLASS_NONE, PERM_CLASS_OTHER, and PERM_CLASS_OWNER.
Referenced by vfs_have_permissions().
int vfs_getdents (inode_t * _inode, aoff_t file_offset, dirent_t * buffer, aoff_t count, aoff_t * read_size)
Read directory entries.
This function will only read whole directory entries, if a directory entry does not fit in count it will return only the amount of bytes read before that entry
Parameters
_inode The inode for the directory
buffer The buffer to store the entries in
file_offset The offset in the directory to start reading at
count The number of bytes to read
read_size A pointer to a variable in which the number of bytes read will be stored
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
EBADF Tried to read from a directory for which we do not have permission
ENOTDIR Can only read directory entries from a directory
EIO An IO error was encountered trying to read from the dir
ENOMEM Could not allocate kernel heap for a temporary structure
Definition at line 932 of file vfs.c.
References inode::atime, EBADF, EFAULT, ENOTDIR, inode::lock, inode::mode, MODE_READ, S_IFDIR, S_IFMT, semaphore_down(), semaphore_up(), inode::size, system_time, vfs_effective_inode(), vfs_have_permissions(), vfs_inode_release(), and vfs_int_read_dir().
Referenced by _sys_getdents().
int vfs_have_permissions (inode_t * inode, mode_t req_mode)
Check permissions for access with mode.
Parameters
inode The file to check
req_mode The requested access mode
Returns
Whether the requested access is allowed
Definition at line 203 of file vfs.c.
References get_perm_class(), inode::gid, inode::uid, and vfs_get_min_permissions().
Referenced by elf_load(), vfs_find_dirent(), vfs_getdents(), vfs_link(), vfs_mknod(), vfs_read(), vfs_symlink(), vfs_truncate(), vfs_unlink(), and vfs_write().
int vfs_initialize (fs_device_t * root_device)
Initialize the VFS layer.
Parameters
root_device The filesystem device to use as root filesystem
Returns
If successful 1, otherwise 0
Todo:
: Track mounted devices
Definition at line 2110 of file vfs.c.
References process_info::current_directory, heapmm_alloc(), llist_add_end(), llist_create(), fs_device_operations::load_inode, fs_device::ops, process_info::root_directory, fs_device::root_inode_id, scheduler_current_task, vfs_dir_cache_mkroot(), and vfs_dir_cache_ref().
Referenced by i386_kmain().
void vfs_inode_release (inode_t * inode)
Release a reference to an inode.
Parameters
inode The reference to release
Definition at line 115 of file vfs.c.
References llist_add_end(), llist_unlink(), inode::mount, and inode::usage_count.
Referenced by elf_load(), vfs_dir_cache_new(), vfs_dir_cache_release(), vfs_getdents(), vfs_link(), vfs_mkdir(), vfs_mknod(), vfs_mount(), vfs_read(), vfs_rmdir(), vfs_symlink(), vfs_truncate(), vfs_unlink(), and vfs_write().
int vfs_link (char * oldpath, char * newpath)
Create a hard link.
Parameters
oldpath The target of the link
newpath The path of the link
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The parent directory or target does not exist
EEXIST A file already exists at the given path
EIO An IO error occurred while creating the link
EACCES User does not have write permission for the parent dir
ENOSPC Not enough disk space was available
ENOMEM Could not allocate kernel heap for a temporary structure
EXDEV Tried to create a cross-device link
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Definition at line 1950 of file vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, inode::ctime, inode::device_id, EACCES, EEXIST, EFAULT, ENAMETOOLONG, ENOENT, EXDEV, inode::hard_link_count, heapmm_free(), inode::id, inode::lock, MODE_WRITE, inode::mtime, semaphore_down(), semaphore_up(), strlen(), system_time, vfs_find_inode(), vfs_find_parent(), vfs_get_filename(), vfs_have_permissions(), vfs_inode_release(), and vfs_int_link().
Referenced by sys_link(), tar_read_record(), and tar_read_record_mem().
int vfs_mkdir (char * path, mode_t mode)
Create a directory.
Parameters
path The path of the directory to create
mode The mode of the directory to create, only access modes are used
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The parent directory does not exist
EEXIST A file already exists at the given path
EIO An IO error occurred while creating the directory
EACCES User does not have write permission for the parent dir
ENOSPC Not enough disk space was available
ENOMEM Could not allocate kernel heap for a temporary structure
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Todo:
: Make this an assertion
Todo:
: Make this an assertion
Definition at line 1201 of file vfs.c.
References EFAULT, inode::lock, inode::mtime, S_IFDIR, semaphore_down(), semaphore_up(), system_time, vfs_find_inode(), vfs_find_parent(), vfs_inode_release(), vfs_int_mkdir(), vfs_mknod(), and vfs_unlink().
Referenced by sys_mkdir(), tar_read_record(), and tar_read_record_mem().
int vfs_mknod (char * path, mode_t mode, dev_t dev)
Create a file.
Parameters
path The path of the file to create
mode The mode of the file to create
dev The device id to use in case of a special file
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The parent directory does not exist
EEXIST A file already exists at the given path
EIO An IO error occurred while creating the file
EACCES User does not have write permission for the parent dir
ENOSPC Not enough disk space was available
ENOMEM Could not allocate kernel heap for a temporary structure
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Definition at line 1296 of file vfs.c.
References inode::atime, CONFIG_FILE_MAX_NAME_LENGTH, inode::ctime, inode::device, inode::device_id, EACCES, EEXIST, EFAULT, ENAMETOOLONG, ENOENT, ENOMEM, inode::fifo, process_info::gid, inode::gid, inode::hard_link_count, heapmm_alloc(), heapmm_free(), inode::id, inode::if_dev, fs_device::inode_size, llist_unlink(), inode::lock, memset(), inode::mode, MODE_WRITE, inode::mtime, inode::name, pipe_create(), S_ISFIFO, scheduler_current_task, semaphore_alloc(), semaphore_down(), semaphore_up(), strcpy(), strlen(), system_time, process_info::uid, inode::uid, process_info::umask, vfs_find_inode(), vfs_find_parent(), vfs_get_filename(), vfs_have_permissions(), vfs_inode_cache(), vfs_inode_release(), vfs_int_link(), vfs_int_mknod(), and vfs_int_rmnod().
Referenced by _sys_open(), i386_kmain(), sys_mknod(), tar_read_record(), tar_read_record_mem(), and vfs_mkdir().
int vfs_mount (char * device, char * mountpoint, char * fstype, uint32_t flags)
Mount a filesystem.
Parameters
device The path of the block special file the fs resides on
mountpoint The directory to mount the fs on
fstype The filesystem driver to use e.g.: ext2, ramfs
flags Options for mounting the fs that are passed to the fs driver
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT A file does not exist
EINVAL An error occurred mounting the filesystem
ENOTDIR The mount point is not a directory
ENOTBLK The special file is not a block special file
Todo:
: Support multiple filesystems
Todo:
: Unmount
Definition at line 1489 of file vfs.c.
References EFAULT, EINVAL, ENOENT, ENOTBLK, ENOTDIR, ext2_mount(), inode::if_dev, fs_device_operations::load_inode, inode::mode, inode::mount, fs_device::ops, fs_device::root_inode_id, S_ISBLK, S_ISDIR, vfs_find_inode(), and vfs_inode_release().
Referenced by sys_mount().
int vfs_read (inode_t * _inode, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * read_size, int non_block)
Read data from a file.
If more data is requested than the file contains this function will successfully complete but read_size will be smaller than count
Parameters
_inode The inode for the file
buffer The buffer to store the data in
file_offset The offset in the file to start reading at
count The number of bytes to read
read_size A pointer to a variable in which the number of bytes read will be stored
non_block Whether to block the call until data is available in the file, this is only supported on FIFO's and character devices
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
EBADF Tried to read from a file for which we do not have permission
EISDIR Direct reads from directories are not allowed
EIO An IO error was encountered trying to read from the file
EPIPE The FIFO has no data left and there are no (open) write endpoints
ENOMEM Could not allocate kernel heap for a temporary structure
Definition at line 760 of file vfs.c.
References inode::atime, device_block_read(), device_char_read(), EBADF, EFAULT, EINVAL, EISDIR, inode::fifo, inode::if_dev, inode::lock, inode::mode, MODE_READ, pipe_write(), S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFMT, S_IFREG, semaphore_down(), semaphore_up(), inode::size, system_time, vfs_effective_inode(), vfs_have_permissions(), vfs_inode_release(), and vfs_int_read().
Referenced by _sys_read(), elf_load(), procvmm_handle_fault(), and tar_read_record().
int vfs_rmdir (char * path)
Delete a directory.
Parameters
path The path of the directory to delete
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The directory does not exist
EEXIST The directory still has files in it
EBUSY The directory is in use
EIO An IO error occurred while deleting the directory
EACCES Tried to delete a directory from a directory for which we do not have write permission
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Definition at line 1142 of file vfs.c.
References EBUSY, EEXIST, EFAULT, ENOENT, dir_cache::inode, inode::lock, inode::mount, process_info::root_directory, scheduler_current_task, semaphore_down(), semaphore_up(), inode::size, vfs_find_inode(), vfs_inode_release(), and vfs_unlink().
Referenced by sys_rmdir().
int vfs_symlink (char * oldpath, char * path)
Create a symbolic link.
Parameters
oldpath The target of the link
path The path of the link
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The parent directory does not exist
EEXIST A file already exists at the given path
EIO An IO error occurred while creating the file
EACCES User does not have write permission for the parent dir
ENOSPC Not enough disk space was available
ENOMEM Could not allocate kernel heap for a temporary structure
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Definition at line 1599 of file vfs.c.
References inode::atime, CONFIG_FILE_MAX_NAME_LENGTH, inode::ctime, inode::device, inode::device_id, EACCES, EEXIST, EFAULT, ENAMETOOLONG, ENOENT, ENOMEM, process_info::gid, inode::gid, inode::hard_link_count, heapmm_alloc(), heapmm_free(), inode::id, inode::if_dev, fs_device::inode_size, inode::link_path, llist_add_end(), llist_unlink(), inode::lock, memset(), inode::mode, MODE_WRITE, inode::mtime, inode::name, scheduler_current_task, semaphore_alloc(), semaphore_down(), semaphore_up(), strcpy(), strlen(), system_time, process_info::uid, inode::uid, vfs_find_inode(), vfs_find_parent(), vfs_get_filename(), vfs_have_permissions(), vfs_inode_cache(), vfs_inode_release(), vfs_int_link(), vfs_int_mknod(), and vfs_int_rmnod().
Referenced by sys_symlink(), and tar_read_record_mem().
int vfs_truncate (inode_t * _inode, aoff_t length)
Resize a file.
If the new size is larger than the file currently is the new room will be filled with zero bytes, if the new size is smaller the data in the truncated part of the file is deleted
Parameters
_inode The inode for the file
length The new size of the file
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
EACCES Tried to resize a file for which we do not have permission
EISDIR Directories can not be resized
EIO An IO error was encountered trying to resize the file
ENOSPC The disk was full when trying to grow the file
ENOMEM Could not allocate kernel heap for a temporary structure
Definition at line 1043 of file vfs.c.
References EACCES, EFAULT, EINVAL, EISDIR, inode::lock, inode::mode, MODE_WRITE, inode::mtime, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFMT, S_IFREG, semaphore_down(), semaphore_up(), inode::size, system_time, vfs_effective_inode(), vfs_have_permissions(), vfs_inode_release(), and vfs_int_truncate().
Referenced by _sys_ftruncate(), _sys_truncate(), and tar_read_record_mem().
int vfs_unlink (char * path)
Delete a file.
Parameters
path The path of the file to delete
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The file does not exist
EEXIST A file already exists at the given path
EBUSY The file is in use
EIO An IO error occurred while deleting the file
EACCES User does not have write permission for the file
ENOMEM Could not allocate kernel heap for a temporary structure
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Definition at line 1789 of file vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, inode::ctime, inode::device, EACCES, EBUSY, EFAULT, ENAMETOOLONG, ENOENT, inode::hard_link_count, heapmm_free(), fs_device::inode_size, llist_unlink(), inode::lock, MODE_WRITE, semaphore_down(), semaphore_up(), strlen(), system_time, inode::usage_count, vfs_find_parent(), vfs_find_symlink(), vfs_get_filename(), vfs_have_permissions(), vfs_inode_release(), vfs_int_rmnod(), and vfs_int_unlink().
Referenced by sys_unlink(), vfs_mkdir(), and vfs_rmdir().
int vfs_write (inode_t * _inode, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * write_size, int non_block)
Write data to a file.
If the data to be written would extend past the end of the file, the file will grow. If file_offset lies past the end of the file, the file will grow and the resulting gap will be filled with zero bytes.
Parameters
_inode The inode for the file
buffer The buffer containing the data to write
file_offset The offset in the file to start writing at
count The number of bytes to write
write_size A pointer to a variable in which the number of bytes written will be stored
non_block Whether to block the call until room is available in the file, this is only supported on FIFO's and character devices
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
EBADF Tried to write to a file for which we do not have permission
EISDIR Direct writes to directories are not allowed
EIO An IO error was encountered trying to write to the file
EPIPE The FIFO has no room left and there are no (open) read endpoints
ENOSPC The disk was full when trying to write to the file
ENOMEM Could not allocate kernel heap for a temporary structure
Todo:
: Make this more efficient, implement sparse files
Definition at line 553 of file vfs.c.
References device_block_write(), device_char_write(), EBADF, EFAULT, EINVAL, EISDIR, inode::fifo, heapmm_alloc(), heapmm_free(), inode::if_dev, inode::lock, memset(), inode::mode, MODE_WRITE, inode::mtime, pipe_write(), S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFMT, S_IFREG, semaphore_down(), semaphore_up(), inode::size, system_time, vfs_effective_inode(), vfs_have_permissions(), vfs_inode_release(), and vfs_int_write().
Referenced by _sys_write(), tar_read_record(), and tar_read_record_mem().