posnk kernel: include/kdbg/heapdbg.h File Reference
heapdbg.h File Reference
#include <stdint.h>
#include <stddef.h>
#include "util/llist.h"
Data Structures
struct kdbg_heap_use
Typedefs
typedef struct kdbg_heap_use kdbg_heap_use_t
Functions
void kdbg_init_memuse ()
void kdbg_enable_memuse ()
void kdbg_print_memuse_brdr (void *addr)
Typedef Documentation
typedef struct kdbg_heap_use kdbg_heap_use_t
Function Documentation
void kdbg_enable_memuse ()
Definition at line 24 of file heapdbg.c.
References heapdbg_up.
Referenced by kdbg_shell().
void kdbg_init_memuse ()
Definition at line 29 of file heapdbg.c.
References llist_create().
Referenced by kdbg_initialize().
void kdbg_print_memuse_brdr (void * addr)
Definition at line 61 of file heapdbg.c.
References kdbg_heap_use::calltrace, kdbg_find_bf_iterator(), kdbg_find_memuse_iterator(), kdbg_print_calltrace(), kdbg_printf, llist_iterate_select(), kdbg_heap_use::size, and kdbg_heap_use::start.
Referenced by kdbg_shell().