posnk kernel: kernel/heapmm.c File Reference
heapmm.c File Reference
#include "kernel/physmm.h"
#include "kernel/heapmm.h"
#include "kernel/earlycon.h"
#include "kernel/scheduler.h"
#include "kdbg/dbgapi.h"
#include <stdint.h>
#include <string.h>
Data Structures
struct heapmm_alignreq
Macros
#define FALSE (0)
kernel/heapmm.c
#define TRUE (1)
Typedefs
typedef struct heapmm_alignreq heapmm_alignreq_t
Functions
void heapmm_free_internal (void *address, size_t size)
Releases a block of memory so it can be reallocated.
void * heapmm_alloc_internal (size_t size, int morecore)
Allocates a new block of memory of given size to the caller.
int heapmm_morecore_iterator (llist_t *node, void *param)
Iterator function that tests for empty blocks.
void heapmm_morecore (size_t size)
Internal function Requests more memory and adds it to the free block table, then cleans up low space markers.
int heapmm_merge_start_iterator (llist_t *node, void *param)
Iterator function that tests for [our block][FREE] mergeable blocks.
int heapmm_merge_end_iterator (llist_t *node, void *param)
Iterator function that tests for [FREE][our block] mergeable blocks.
void * __builtin_return_address (unsigned int level)
int curpid ()
int heapmm_alloc_match_iterator (llist_t *node, void *param)
Iterator function that tests for blocks equal the size in param.
int heapmm_alloc_fit_iterator (llist_t *node, void *param)
Iterator function that tests for blocks able to contain the size in param.
int heapmm_alloc_page_match_iterator (llist_t *node, void *param)
Iterator function that tests for aligned, matching sized blocks.
int heapmm_alloc_page_split_iterator (llist_t *node, void *param)
Iterator function that tests for blocks large enough to contain a whole page.
int heapmm_alloc_page_fit_iterator (llist_t *node, void *param)
Iterator function that tests for page aligned, larger than page sized blocks.
void * heapmm_alloc_page_alligned (size_t size)
Allocates a page alligned block of RAM.
void * heapmm_alloc_alligned (size_t size, uintptr_t alignment)
Allocates an alligned block of RAM.
void * heapmm_alloc (size_t size)
Allocates a new block of memory of given size to the caller.
void * heapmm_alloc_page ()
Allocates a new page of heap space to the caller.
void heapmm_free (void *address, size_t size)
Releases a block of memory so it can be reallocated.
void heapmm_init (void *heap_start, size_t size)
Initializes the heap memory manager.
Variables
llist_t heapmm_free_blocks_list
Heap memory manager free block list head pointer.
void * heapmm_top_of_heap
Pointer to the top of the heap.
size_t heapmm_space_left = 0
Keep track of.
Macro Definition Documentation
#define FALSE (0)
kernel/heapmm.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 28-03-2014 - Created
Definition at line 20 of file heapmm.c.
Referenced by heapmm_free_internal(), and validate_escape_suffix().
#define TRUE (1)
Definition at line 22 of file heapmm.c.
Referenced by heapmm_alloc(), and validate_escape_suffix().
Typedef Documentation
typedef struct heapmm_alignreq heapmm_alignreq_t
Function Documentation
void* __builtin_return_address (unsigned int level)
int curpid ()
Definition at line 125 of file heapmm.c.
References process_info::pid, and scheduler_current_task.
Referenced by paging_handle_fault(), and syscall_dispatch().
void* heapmm_alloc (size_t size)
Allocates a new block of memory of given size to the caller.
Definition at line 552 of file heapmm.c.
References earlycon_printf, heapmm_alloc_internal(), heapmm_top_of_heap, and TRUE.
Referenced by _sys_dup2(), _sys_open(), _sys_pipe2(), ata_global_initialize(), ata_initialize(), ata_pci_probe(), blkcache_create(), blkcache_get(), debug_uputs(), device_block_init(), device_block_register(), device_char_init(), elf_load(), ext2_finddir(), ext2_load_bgd(), ext2_load_inode(), ext2_mount(), ext2_readdir(), interrupt_register_handler(), paging_create_dir(), pipe_create(), pipe_read(), process_child_event(), procvmm_mmap_anon(), procvmm_mmap_copy_iterator(), procvmm_mmap_file(), ramfs_create(), ramfs_link(), ramfs_load_inode(), ramfs_mkdir(), ramfs_mknod(), ramfs_trunc_inode(), ramfs_write_inode(), scheduler_fork(), scheduler_fork_to(), scheduler_init(), scheduler_invoke_signal_handler(), scheduler_switch_task(), semaphore_alloc(), stream_ptr_copy_iterator(), sys_chdir(), sys_chmod(), sys_chown(), sys_execve(), sys_fstat(), sys_getdents(), sys_link(), sys_lstat(), sys_mkdir(), sys_mknod(), sys_mount(), sys_open(), sys_read(), sys_readlink(), sys_rmdir(), sys_stat(), sys_symlink(), sys_truncate(), sys_unlink(), sys_write(), tar_read_record(), tty_init(), tty_register_driver(), vfs_dir_cache_mkroot(), vfs_dir_cache_new(), vfs_find_dirc(), vfs_find_dirc_parent(), vfs_get_filename(), vfs_initialize(), vfs_mknod(), vfs_symlink(), vfs_write(), vterm_init(), and vterm_tty_setup().
void* heapmm_alloc_alligned (size_t size, uintptr_t alignment)
Allocates an alligned block of RAM.
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Definition at line 453 of file heapmm.c.
References heapmm_alignreq::align, dbgapi_register_memuse(), heapmm_alloc_alligned(), heapmm_alloc_page_fit_iterator(), heapmm_alloc_page_match_iterator(), heapmm_alloc_page_split_iterator(), heapmm_free_internal(), heapmm_morecore(), heapmm_space_left, llist_iterate_select(), llist_unlink(), NULL, PHYSMM_PAGE_SIZE, heapmm_block::size, heapmm_alignreq::size, and heapmm_block::start.
Referenced by ata_initialize(), blkcache_get(), heapmm_alloc_alligned(), and heapmm_alloc_page_alligned().
int heapmm_alloc_fit_iterator (llist_t * node, void * param)
Iterator function that tests for blocks able to contain the size in param.
Definition at line 281 of file heapmm.c.
References heapmm_block::size.
Referenced by heapmm_alloc_internal().
void * heapmm_alloc_internal (size_t size, int morecore)
Allocates a new block of memory of given size to the caller.
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Definition at line 291 of file heapmm.c.
References dbgapi_register_memuse(), heapmm_alloc_fit_iterator(), heapmm_alloc_match_iterator(), heapmm_morecore(), heapmm_morecore_iterator(), heapmm_space_left, llist_iterate_select(), llist_unlink(), memset(), NULL, PHYSMM_PAGE_SIZE, heapmm_block::size, and heapmm_block::start.
Referenced by heapmm_alloc(), and heapmm_free_internal().
int heapmm_alloc_match_iterator (llist_t * node, void * param)
Iterator function that tests for blocks equal the size in param.
Definition at line 268 of file heapmm.c.
References heapmm_top_of_heap.
Referenced by heapmm_alloc_internal().
void* heapmm_alloc_page ()
Allocates a new page of heap space to the caller.
Definition at line 566 of file heapmm.c.
References heapmm_alloc_page_alligned(), and PHYSMM_PAGE_SIZE.
Referenced by i386_alloc_page(), i386_init_mm(), and paging_create_dir().
void* heapmm_alloc_page_alligned (size_t size)
Allocates a page alligned block of RAM.
Definition at line 444 of file heapmm.c.
References heapmm_alloc_alligned(), and PHYSMM_PAGE_SIZE.
Referenced by heapmm_alloc_page().
int heapmm_alloc_page_fit_iterator (llist_t * node, void * param)
Iterator function that tests for page aligned, larger than page sized blocks.
Definition at line 432 of file heapmm.c.
References heapmm_alignreq::align, heapmm_block::size, heapmm_alignreq::size, and heapmm_block::start.
Referenced by heapmm_alloc_alligned().
int heapmm_alloc_page_match_iterator (llist_t * node, void * param)
Iterator function that tests for aligned, matching sized blocks.
Definition at line 405 of file heapmm.c.
References heapmm_alignreq::align, heapmm_block::size, heapmm_alignreq::size, and heapmm_block::start.
Referenced by heapmm_alloc_alligned().
int heapmm_alloc_page_split_iterator (llist_t * node, void * param)
Iterator function that tests for blocks large enough to contain a whole page.
Definition at line 418 of file heapmm.c.
References heapmm_alignreq::align, heapmm_block::size, heapmm_alignreq::size, and heapmm_block::start.
Referenced by heapmm_alloc_alligned().
void heapmm_free (void * address, size_t size)
Releases a block of memory so it can be reallocated.
Definition at line 574 of file heapmm.c.
References heapmm_free_internal().
Referenced by _sys_close_int(), _sys_open(), _sys_pipe2(), ata_pci_probe(), blkcache_free(), blkcache_get(), debug_uputs(), device_block_register(), elf_load(), ext2_finddir(), ext2_free_bgd(), ext2_load_bgd(), ext2_mount(), ext2_readdir(), paging_create_dir(), pipe_create(), pipe_free(), pipe_read(), process_absorb_event(), process_reap(), procvmm_mmap_anon(), procvmm_mmap_file(), procvmm_unmmap(), ramfs_trunc_inode(), ramfs_unlink(), scheduler_exsig(), semaphore_free(), sys_chdir(), sys_chmod(), sys_chown(), sys_execve(), sys_fstat(), sys_getdents(), sys_link(), sys_lstat(), sys_mkdir(), sys_mknod(), sys_mount(), sys_open(), sys_read(), sys_readlink(), sys_rmdir(), sys_stat(), sys_symlink(), sys_truncate(), sys_unlink(), sys_write(), tar_read_record(), vfs_dir_cache_new(), vfs_dir_cache_release(), vfs_find_dirc(), vfs_find_dirc_parent(), vfs_find_symlink(), vfs_get_filename(), vfs_link(), vfs_mknod(), vfs_symlink(), vfs_unlink(), vfs_write(), and vterm_destroy().
void heapmm_free_internal (void * address, size_t size)
Releases a block of memory so it can be reallocated.
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Get a lock on the free block table
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Definition at line 134 of file heapmm.c.
References dbgapi_register_memuse(), dbgapi_unreg_memuse(), debugcon_printf, FALSE, heapmm_alloc_internal(), heapmm_merge_end_iterator(), heapmm_merge_start_iterator(), heapmm_morecore(), heapmm_space_left, heapmm_top_of_heap, llist_add_end(), llist_iterate_select(), memset(), NULL, heapmm_block::size, and heapmm_block::start.
Referenced by heapmm_alloc_alligned(), heapmm_free(), heapmm_init(), and heapmm_morecore().
void heapmm_init (void * heap_start, size_t size)
Initializes the heap memory manager.
Parameters
heap_start The start of the heap
Definition at line 583 of file heapmm.c.
References heapmm_free_internal(), heapmm_top_of_heap, and llist_create().
Referenced by i386_init_mm().
int heapmm_merge_end_iterator (llist_t * node, void * param)
Iterator function that tests for [FREE][our block] mergeable blocks.
Definition at line 117 of file heapmm.c.
References heapmm_block::size, and heapmm_block::start.
Referenced by heapmm_free_internal().
int heapmm_merge_start_iterator (llist_t * node, void * param)
Iterator function that tests for [our block][FREE] mergeable blocks.
Definition at line 108 of file heapmm.c.
References heapmm_block::size, and heapmm_block::start.
Referenced by heapmm_free_internal().
void heapmm_morecore (size_t size)
Internal function Requests more memory and adds it to the free block table, then cleans up low space markers.
Todo:
: Get lock on heapmm_top_of_heap
Todo:
: Handle out of memory error
Todo:
: Release lock on heapmm_top_of_heap
Todo:
: Get lock on the free block table
Todo:
: Release lock on the free block table
Todo:
: Release lock on the free block table
Definition at line 57 of file heapmm.c.
References heapmm_free_internal(), heapmm_request_core(), and heapmm_top_of_heap.
Referenced by heapmm_alloc_alligned(), heapmm_alloc_internal(), and heapmm_free_internal().
int heapmm_morecore_iterator (llist_t * node, void * param)
Iterator function that tests for empty blocks.
Definition at line 46 of file heapmm.c.
References heapmm_block::size.
Referenced by heapmm_alloc_internal().
Variable Documentation
llist_t heapmm_free_blocks_list
Heap memory manager free block list head pointer.
Definition at line 27 of file heapmm.c.
size_t heapmm_space_left = 0
Keep track of.
Definition at line 37 of file heapmm.c.
Referenced by heapmm_alloc_alligned(), heapmm_alloc_internal(), and heapmm_free_internal().
void* heapmm_top_of_heap
Pointer to the top of the heap.
Definition at line 32 of file heapmm.c.
Referenced by heapmm_alloc(), heapmm_alloc_match_iterator(), heapmm_free_internal(), heapmm_init(), and heapmm_morecore().