posnk kernel: kdbg/heapdbg.c File Reference
heapdbg.c File Reference
#include <stdint.h>
#include <stddef.h>
#include "util/llist.h"
#include "kdbg/stacktrc.h"
#include "kdbg/kdbgmm.h"
#include "kdbg/kdbgio.h"
#include "kdbg/heapdbg.h"
Functions
void kdbg_enable_memuse ()
void kdbg_init_memuse ()
void dbgapi_register_memuse (void *addr, size_t size)
int kdbg_find_bf_iterator (llist_t *node, void *param)
int kdbg_find_in_iterator (llist_t *node, void *param)
int kdbg_find_memuse_iterator (llist_t *node, void *param)
void kdbg_print_memuse_brdr (void *addr)
void dbgapi_unreg_memuse (void *addr, size_t size)
Variables
llist_t kdbg_heap_use_list
int heapdbg_up = 0
Function Documentation
void dbgapi_register_memuse (void * addr, size_t size)
Definition at line 34 of file heapdbg.c.
References kdbg_heap_use::calltrace, heapdbg_up, kdbg_do_calltrace(), kdbgmm_alloc(), llist_add_end(), kdbg_heap_use::size, and kdbg_heap_use::start.
Referenced by heapmm_alloc_alligned(), heapmm_alloc_internal(), and heapmm_free_internal().
void dbgapi_unreg_memuse (void * addr, size_t size)
Definition at line 80 of file heapdbg.c.
References kdbg_heap_use::calltrace, dbgapi_invoke_kdbg(), heapdbg_up, kdbg_find_memuse_iterator(), kdbg_free_calltrace(), kdbg_printf, kdbgmm_free(), llist_iterate_select(), llist_unlink(), and kdbg_heap_use::size.
Referenced by heapmm_free_internal().
void kdbg_enable_memuse ()
Definition at line 24 of file heapdbg.c.
References heapdbg_up.
Referenced by kdbg_shell().
int kdbg_find_bf_iterator (llist_t * node, void * param)
Definition at line 47 of file heapdbg.c.
Referenced by kdbg_print_memuse_brdr().
int kdbg_find_in_iterator (llist_t * node, void * param)
Definition at line 51 of file heapdbg.c.
References kdbg_heap_use::size, and kdbg_heap_use::start.
int kdbg_find_memuse_iterator (llist_t * node, void * param)
Definition at line 57 of file heapdbg.c.
Referenced by dbgapi_unreg_memuse(), and kdbg_print_memuse_brdr().
void kdbg_init_memuse ()
Definition at line 29 of file heapdbg.c.
References llist_create().
Referenced by kdbg_initialize().
void kdbg_print_memuse_brdr (void * addr)
Definition at line 61 of file heapdbg.c.
References kdbg_heap_use::calltrace, kdbg_find_bf_iterator(), kdbg_find_memuse_iterator(), kdbg_print_calltrace(), kdbg_printf, llist_iterate_select(), kdbg_heap_use::size, and kdbg_heap_use::start.
Referenced by kdbg_shell().
Variable Documentation
int heapdbg_up = 0
Definition at line 22 of file heapdbg.c.
Referenced by dbgapi_register_memuse(), dbgapi_unreg_memuse(), and kdbg_enable_memuse().
llist_t kdbg_heap_use_list
Definition at line 21 of file heapdbg.c.