posnk kernel: include/kernel/heapmm.h File Reference
heapmm.h File Reference
#include "util/llist.h"
#include <stddef.h>
#include <stdint.h>
Data Structures
struct heapmm_block
Heap memory manager free block descriptor typedef: heapmm_block_t.
Typedefs
typedef struct heapmm_block heapmm_block_t
kernel/heapmm.h
Functions
size_t heapmm_request_core (void *address, size_t size)
void heapmm_init (void *heap_start, size_t size)
Initializes the heap memory manager.
void * heapmm_alloc_page ()
Allocates a new page of heap space to the caller.
void * heapmm_alloc_table ()
Allocates a page alligned block of RAM,no call to morecore.
void * heapmm_alloc_page_alligned (size_t size)
Allocates a page alligned block of RAM.
void * heapmm_alloc_alligned (size_t size, uintptr_t alignment)
Allocates an alligned block of RAM.
void * heapmm_alloc (size_t size)
Allocates a new block of memory of given size to the caller.
void heapmm_free (void *address, size_t size)
Releases a block of memory so it can be reallocated.
Typedef Documentation
typedef struct heapmm_block heapmm_block_t
kernel/heapmm.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 28-03-2014 - Created typedef for heapmm_block: Heap memory manager free block descriptor
Definition at line 23 of file heapmm.h.
Function Documentation
void* heapmm_alloc (size_t size)
Allocates a new block of memory of given size to the caller.
Definition at line 552 of file heapmm.c.
References earlycon_printf, heapmm_alloc_internal(), heapmm_top_of_heap, and TRUE.
Referenced by _sys_dup2(), _sys_open(), _sys_pipe2(), ata_global_initialize(), ata_initialize(), ata_pci_probe(), blkcache_create(), blkcache_get(), debug_uputs(), device_block_init(), device_block_register(), device_char_init(), elf_load(), ext2_finddir(), ext2_load_bgd(), ext2_load_inode(), ext2_mount(), ext2_readdir(), interrupt_register_handler(), paging_create_dir(), pipe_create(), pipe_read(), process_child_event(), procvmm_mmap_anon(), procvmm_mmap_copy_iterator(), procvmm_mmap_file(), ramfs_create(), ramfs_link(), ramfs_load_inode(), ramfs_mkdir(), ramfs_mknod(), ramfs_trunc_inode(), ramfs_write_inode(), scheduler_fork(), scheduler_fork_to(), scheduler_init(), scheduler_invoke_signal_handler(), scheduler_switch_task(), semaphore_alloc(), stream_ptr_copy_iterator(), sys_chdir(), sys_chmod(), sys_chown(), sys_execve(), sys_fstat(), sys_getdents(), sys_link(), sys_lstat(), sys_mkdir(), sys_mknod(), sys_mount(), sys_open(), sys_read(), sys_readlink(), sys_rmdir(), sys_stat(), sys_symlink(), sys_truncate(), sys_unlink(), sys_write(), tar_read_record(), tty_init(), tty_register_driver(), vfs_dir_cache_mkroot(), vfs_dir_cache_new(), vfs_find_dirc(), vfs_find_dirc_parent(), vfs_get_filename(), vfs_initialize(), vfs_mknod(), vfs_symlink(), vfs_write(), vterm_init(), and vterm_tty_setup().
void* heapmm_alloc_alligned (size_t size, uintptr_t alignment)
Allocates an alligned block of RAM.
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Definition at line 453 of file heapmm.c.
References heapmm_alignreq::align, dbgapi_register_memuse(), heapmm_alloc_alligned(), heapmm_alloc_page_fit_iterator(), heapmm_alloc_page_match_iterator(), heapmm_alloc_page_split_iterator(), heapmm_free_internal(), heapmm_morecore(), heapmm_space_left, llist_iterate_select(), llist_unlink(), NULL, PHYSMM_PAGE_SIZE, heapmm_block::size, heapmm_alignreq::size, and heapmm_block::start.
Referenced by ata_initialize(), blkcache_get(), heapmm_alloc_alligned(), and heapmm_alloc_page_alligned().
void* heapmm_alloc_page ()
Allocates a new page of heap space to the caller.
Definition at line 566 of file heapmm.c.
References heapmm_alloc_page_alligned(), and PHYSMM_PAGE_SIZE.
Referenced by i386_alloc_page(), i386_init_mm(), and paging_create_dir().
void* heapmm_alloc_page_alligned (size_t size)
Allocates a page alligned block of RAM.
Definition at line 444 of file heapmm.c.
References heapmm_alloc_alligned(), and PHYSMM_PAGE_SIZE.
Referenced by heapmm_alloc_page().
void* heapmm_alloc_table ()
Allocates a page alligned block of RAM,no call to morecore.
void heapmm_free (void * address, size_t size)
Releases a block of memory so it can be reallocated.
Definition at line 574 of file heapmm.c.
References heapmm_free_internal().
Referenced by _sys_close_int(), _sys_open(), _sys_pipe2(), ata_pci_probe(), blkcache_free(), blkcache_get(), debug_uputs(), device_block_register(), elf_load(), ext2_finddir(), ext2_free_bgd(), ext2_load_bgd(), ext2_mount(), ext2_readdir(), paging_create_dir(), pipe_create(), pipe_free(), pipe_read(), process_absorb_event(), process_reap(), procvmm_mmap_anon(), procvmm_mmap_file(), procvmm_unmmap(), ramfs_trunc_inode(), ramfs_unlink(), scheduler_exsig(), semaphore_free(), sys_chdir(), sys_chmod(), sys_chown(), sys_execve(), sys_fstat(), sys_getdents(), sys_link(), sys_lstat(), sys_mkdir(), sys_mknod(), sys_mount(), sys_open(), sys_read(), sys_readlink(), sys_rmdir(), sys_stat(), sys_symlink(), sys_truncate(), sys_unlink(), sys_write(), tar_read_record(), vfs_dir_cache_new(), vfs_dir_cache_release(), vfs_find_dirc(), vfs_find_dirc_parent(), vfs_find_symlink(), vfs_get_filename(), vfs_link(), vfs_mknod(), vfs_symlink(), vfs_unlink(), vfs_write(), and vterm_destroy().
void heapmm_init (void * heap_start, size_t size)
Initializes the heap memory manager.
Parameters
heap_start The start of the heap
Definition at line 583 of file heapmm.c.
References heapmm_free_internal(), heapmm_top_of_heap, and llist_create().
Referenced by i386_init_mm().
size_t heapmm_request_core (void * address, size_t size)
Definition at line 22 of file paging.c.
References debugcon_aputs(), earlycon_aputs(), NULL, paging_map(), PAGING_PAGE_FLAG_RW, PAGING_PAGE_TAG_KERNEL_DATA, paging_tag(), physmm_alloc_frame(), PHYSMM_NO_FRAME, and PHYSMM_PAGE_SIZE.
Referenced by heapmm_morecore(), i386_init_mm(), kdbg_initialize(), and kdbgmm_morecore().