posnk kernel: driver/oldkb/i8042.c File Reference
i8042.c File Reference
#include <stdint.h>
#include "kernel/interrupt.h"
#include "arch/i386/x86.h"
#include "driver/oldkb/i8042.h"
Macros
#define KBD_CPSLCK_BIT 1
#define KBD_SHIFT_BIT 2
#define KBD_CTRL_BIT 4
#define KBD_ALT_BIT 8
#define KBD_WIN_BIT 16
#define KBD_MENU_BIT 32
#define KBD_SCLLCK_BIT 64
#define KBD_NUMLCK_BIT 128
Functions
void uprinti (uint32_t i)
uint8_t kbd_controller_status ()
void kbd_send_controller_command (uint8_t cmd)
uint8_t kbd_encoder_read_buffer ()
void kbd_send_encoder_command (uint8_t cmd)
int kbd_isr (irq_id_t irq_id, void *context)
Variables
uint8_t currently_held_key = 0x00
uint8_t extended = 0
int sigfile_hndl = 0
Macro Definition Documentation
#define KBD_ALT_BIT 8
Definition at line 8 of file i8042.c.
Referenced by kbd_isr().
#define KBD_CPSLCK_BIT 1
Definition at line 5 of file i8042.c.
Referenced by kbd_isr().
#define KBD_CTRL_BIT 4
Definition at line 7 of file i8042.c.
Referenced by kbd_isr().
#define KBD_MENU_BIT 32
Definition at line 10 of file i8042.c.
Referenced by kbd_isr().
#define KBD_NUMLCK_BIT 128
Definition at line 12 of file i8042.c.
Referenced by kbd_isr().
#define KBD_SCLLCK_BIT 64
Definition at line 11 of file i8042.c.
Referenced by kbd_isr().
#define KBD_SHIFT_BIT 2
Definition at line 6 of file i8042.c.
Referenced by kbd_isr().
#define KBD_WIN_BIT 16
Definition at line 9 of file i8042.c.
Referenced by kbd_isr().
Function Documentation
uint8_t kbd_controller_status ()
Definition at line 18 of file i8042.c.
References i386_inb(), and KBD_CTRL_IO_PORT.
Referenced by kb_initialize(), kbd_isr(), kbd_send_controller_command(), and kbd_send_encoder_command().
uint8_t kbd_encoder_read_buffer ()
Definition at line 29 of file i8042.c.
References i386_inb(), and KBD_ENC_IO_PORT.
Referenced by kb_initialize(), and kbd_isr().
int kbd_isr (irq_id_t irq_id, void * context)
Definition at line 40 of file i8042.c.
References currently_held_key, extended, kb_clear_modifier(), kb_pressed(), kb_released(), kb_set_modifier(), kb_toggle_modifier(), kb_typed(), KBD_ALT_BIT, kbd_controller_status(), KBD_CPSLCK_BIT, KBD_CTRL_BIT, KBD_CTRL_STATUS_OUT_BUF_BIT, kbd_encoder_read_buffer(), KBD_MENU_BIT, KBD_NUMLCK_BIT, KBD_SCLLCK_BIT, KBD_SHIFT_BIT, and KBD_WIN_BIT.
Referenced by kb_initialize().
void kbd_send_controller_command (uint8_t cmd)
Definition at line 22 of file i8042.c.
References i386_outb(), kbd_controller_status(), KBD_CTRL_IO_PORT, and KBD_CTRL_STATUS_IN_BUF_BIT.
void kbd_send_encoder_command (uint8_t cmd)
Definition at line 33 of file i8042.c.
References i386_outb(), kbd_controller_status(), KBD_CTRL_STATUS_IN_BUF_BIT, and KBD_ENC_IO_PORT.
Referenced by kb_set_leds().
void uprinti (uint32_t i)
Variable Documentation
uint8_t currently_held_key = 0x00
Definition at line 14 of file i8042.c.
Referenced by kbd_isr().
uint8_t extended = 0
Definition at line 15 of file i8042.c.
Referenced by kbd_isr().
int sigfile_hndl = 0
Definition at line 16 of file i8042.c.