posnk kernel: arch/i386/idt.c File Reference
idt.c File Reference
#include <string.h>
#include "arch/i386/idt.h"
#include "arch/i386/x86.h"
#include "arch/i386/isr_entry.h"
Macros
#define I386_KERNEL_CODE_SEGMENT 0x18
#define ADD_ISR_ENTRY(NO) i386_idt_set_descriptor(NO, &i386_isr_entry_ ## NO, I386_IDT_32BIT_INTERRUPT, I386_KERNEL_CODE_SEGMENT);
Functions
void i386_load_idt ()
void i386_isr_entry_undefined ()
void i386_idt_set_descriptor (uint8_t id, void *isr, uint8_t flags, uint32_t segment)
void i386_idt_initialize ()
Variables
i386_idt_descriptor_t i386_idt [I386_IDT_MAX_DESCRIPTORS]
i386_idtr_t i386_idt_pointer
Macro Definition Documentation
#define ADD_ISR_ENTRY (NO) i386_idt_set_descriptor(NO, &i386_isr_entry_ ## NO, I386_IDT_32BIT_INTERRUPT, I386_KERNEL_CODE_SEGMENT);
Definition at line 8 of file idt.c.
Referenced by i386_idt_initialize().
#define I386_KERNEL_CODE_SEGMENT 0x18
Definition at line 6 of file idt.c.
Referenced by i386_idt_initialize().
Function Documentation
void i386_idt_initialize ()
Definition at line 32 of file idt.c.
References ADD_ISR_ENTRY, I386_IDT_32BIT_INTERRUPT, I386_IDT_MAX_DESCRIPTORS, i386_idt_set_descriptor(), i386_isr_entry_80h(), i386_isr_entry_undefined(), I386_KERNEL_CODE_SEGMENT, i386_load_idt(), i386_idtr::m_base, and i386_idtr::m_limit.
Referenced by i386_kmain().
void i386_idt_set_descriptor (uint8_t id, void * isr, uint8_t flags, uint32_t segment)
Definition at line 22 of file idt.c.
References i386_idt_descriptor::flags, memset(), i386_idt_descriptor::offsetHi, i386_idt_descriptor::offsetLo, and i386_idt_descriptor::segmentOrTSS.
Referenced by i386_idt_initialize().
void i386_isr_entry_undefined ()
Definition at line 17 of file idt.c.
Referenced by i386_idt_initialize().
void i386_load_idt ()
Definition at line 13 of file idt.c.
References i386_idt_pointer.
Referenced by i386_idt_initialize().
Variable Documentation
i386_idt_descriptor_t i386_idt[I386_IDT_MAX_DESCRIPTORS]
Definition at line 10 of file idt.c.
i386_idtr_t i386_idt_pointer
Definition at line 11 of file idt.c.
Referenced by i386_load_idt().