posnk kernel: include/arch/i386/idt.h File Reference
idt.h File Reference
#include <stdint.h>
Data Structures
struct i386_idt_descriptor
struct i386_idtr
Macros
#define I386_IDT_PRESENT_BIT (1<<7)
#define I386_IDT_SUPERVISOR_MASK (0<<5)
#define I386_IDT_DRIVER_0_MASK (1<<5)
#define I386_IDT_DRIVER_1_MASK (2<<5)
#define I386_IDT_USERMODE_MASK (3<<5)
#define I386_IDT_SYSTEM_SEGMENT_BIT (1<<4)
#define I386_IDT_32_BIT_GATE_BIT (1<<3)
#define I386_IDT_RESERVED_BIT (1<<2)
#define I386_IDT_NOT_TASK_GATE (1<<1)
#define I386_IDT_NOT_INTERRUPT_GATE (1<<0)
#define I386_IDT_TRAP_GATE_MASK (IDT_NOT_TASK_GATE | IDT_NOT_INTERRUPT_GATE)
#define I386_IDT_TASK_GATE_MASK (IDT_NOT_INTERRUPT_GATE)
#define I386_IDT_INTERRUPT_GATE_MASK (IDT_NOT_TASK_GATE)
#define I386_IDT_32BIT_INTERRUPT (0x8E)
#define I386_IDT_BS_32 (IDT_PRESENT_BIT | IDT_SUPERVISOR_MASK | IDT_32_BIT_GATE_BIT | IDT_RESERVED_BIT |IDT_INTERRUPT_GATE_MASK)
#define I386_IDT_32BIT_TRAP (IDT_PRESENT_BIT | IDT_SUPERVISOR_MASK | IDT_32_BIT_GATE_BIT | IDT_RESERVED_BIT | IDT_TRAP_GATE_MASK)
#define I386_IDT_MAX_DESCRIPTORS (256)
Typedefs
typedef struct i386_idt_descriptor i386_idt_descriptor_t
typedef struct i386_idtr i386_idtr_t
Functions
struct i386_idt_descriptor __attribute__ ((packed))
void i386_load_idt ()
void i386_idt_initialize ()
void i386_idt_set_descriptor (uint8_t id, void *isr, uint8_t flags, uint32_t segment)
Variables
uint16_t offsetLo
uint16_t segmentOrTSS
uint8_t reserved
uint8_t flags
uint16_t offsetHi
uint16_t m_limit
uint32_t m_base
Macro Definition Documentation
#define I386_IDT_32_BIT_GATE_BIT (1<<3)
Definition at line 24 of file idt.h.
#define I386_IDT_32BIT_INTERRUPT (0x8E)
Definition at line 31 of file idt.h.
Referenced by i386_idt_initialize().
#define I386_IDT_32BIT_TRAP (IDT_PRESENT_BIT | IDT_SUPERVISOR_MASK | IDT_32_BIT_GATE_BIT | IDT_RESERVED_BIT | IDT_TRAP_GATE_MASK)
Definition at line 35 of file idt.h.
#define I386_IDT_BS_32 (IDT_PRESENT_BIT | IDT_SUPERVISOR_MASK | IDT_32_BIT_GATE_BIT | IDT_RESERVED_BIT |IDT_INTERRUPT_GATE_MASK)
Definition at line 33 of file idt.h.
#define I386_IDT_DRIVER_0_MASK (1<<5)
Definition at line 20 of file idt.h.
#define I386_IDT_DRIVER_1_MASK (2<<5)
Definition at line 21 of file idt.h.
#define I386_IDT_INTERRUPT_GATE_MASK (IDT_NOT_TASK_GATE)
Definition at line 30 of file idt.h.
#define I386_IDT_MAX_DESCRIPTORS (256)
Definition at line 37 of file idt.h.
Referenced by i386_idt_initialize().
#define I386_IDT_NOT_INTERRUPT_GATE (1<<0)
Definition at line 27 of file idt.h.
#define I386_IDT_NOT_TASK_GATE (1<<1)
Definition at line 26 of file idt.h.
#define I386_IDT_PRESENT_BIT (1<<7)
Definition at line 18 of file idt.h.
#define I386_IDT_RESERVED_BIT (1<<2)
Definition at line 25 of file idt.h.
#define I386_IDT_SUPERVISOR_MASK (0<<5)
Definition at line 19 of file idt.h.
#define I386_IDT_SYSTEM_SEGMENT_BIT (1<<4)
Definition at line 23 of file idt.h.
#define I386_IDT_TASK_GATE_MASK (IDT_NOT_INTERRUPT_GATE)
Definition at line 29 of file idt.h.
#define I386_IDT_TRAP_GATE_MASK (IDT_NOT_TASK_GATE | IDT_NOT_INTERRUPT_GATE)
Definition at line 28 of file idt.h.
#define I386_IDT_USERMODE_MASK (3<<5)
Definition at line 22 of file idt.h.
Typedef Documentation
typedef struct i386_idt_descriptor i386_idt_descriptor_t
Definition at line 47 of file idt.h.
typedef struct i386_idtr i386_idtr_t
Definition at line 54 of file idt.h.
Function Documentation
struct i386_idt_descriptor __attribute__ ((packed))
void i386_idt_initialize ()
Definition at line 32 of file idt.c.
References ADD_ISR_ENTRY, I386_IDT_32BIT_INTERRUPT, I386_IDT_MAX_DESCRIPTORS, i386_idt_set_descriptor(), i386_isr_entry_80h(), i386_isr_entry_undefined(), I386_KERNEL_CODE_SEGMENT, i386_load_idt(), i386_idtr::m_base, and i386_idtr::m_limit.
Referenced by i386_kmain().
void i386_idt_set_descriptor (uint8_t id, void * isr, uint8_t flags, uint32_t segment)
Definition at line 22 of file idt.c.
References i386_idt_descriptor::flags, flags, memset(), i386_idt_descriptor::offsetHi, i386_idt_descriptor::offsetLo, and i386_idt_descriptor::segmentOrTSS.
Referenced by i386_idt_initialize().
void i386_load_idt ()
Definition at line 13 of file idt.c.
References i386_idt_pointer.
Referenced by i386_idt_initialize().
Variable Documentation
uint8_t flags
Definition at line 49 of file idt.h.
Referenced by _sys_open(), elf_load(), i386_idt_set_descriptor(), i386_set_tss_descriptor(), procvmm_handle_fault(), and vterm_init().
uint32_t m_base
Definition at line 54 of file idt.h.
uint16_t m_limit
Definition at line 53 of file idt.h.
uint16_t offsetHi
Definition at line 50 of file idt.h.
uint16_t offsetLo
Definition at line 46 of file idt.h.
uint8_t reserved
Definition at line 48 of file idt.h.
uint16_t segmentOrTSS
Definition at line 47 of file idt.h.