posnk kernel: arch/i386/init.c File Reference
init.c File Reference
#include "kernel/heapmm.h"
#include "kernel/physmm.h"
#include "kernel/paging.h"
#include "kernel/earlycon.h"
#include "kernel/system.h"
#include "kernel/scheduler.h"
#include "arch/i386/pic.h"
#include "arch/i386/pit.h"
#include "arch/i386/x86.h"
#include "arch/i386/idt.h"
#include "arch/i386/paging.h"
#include "arch/i386/multiboot.h"
#include "arch/i386/protection.h"
#include "driver/bus/pci.h"
#include "kernel/syscall.h"
#include "kernel/streams.h"
#include "kernel/vfs.h"
#include "kernel/tar.h"
#include "kernel/device.h"
#include "kernel/tty.h"
#include "kernel/drivermgr.h"
#include "kernel/interrupt.h"
#include "fs/ramfs.h"
#include <sys/stat.h>
#include <sys/errno.h>
#include <fcntl.h>
#include <string.h>
Functions
uint32_t i386_init_multiboot_memprobe (multiboot_info_t *mbt)
void i386_init_reserve_modules (multiboot_info_t *mbt)
void i386_init_load_modules (multiboot_info_t *mbt)
void i386_init_mm (multiboot_info_t *mbd, unsigned int magic)
void vgacon_clear_video ()
void vterm_vga_init ()
void i386_init_stub ()
void i386_idle_task ()
void ata_pci_register ()
void i386_kmain ()
Once we are here everything is set up properly First 4 MB are both at 0xC000 0000 and 0x0000 0000 to support GDT trick! Task Stack is at 0xBFFF DFFF downwards ISR Stack is at 0xBFFF E000 ------— KERNEL RAM BOUNDARY -------— Code is at 0xC000 0000 Heap is at 0xD000 0000 Pagedir is at 0xFFC0 0000.
Variables
multiboot_info_t * mb_info
arch/i386/paging.c
uint32_t i386_start_kheap
Function Documentation
void ata_pci_register ()
Definition at line 63 of file ata_pci.c.
References drivermgr_register_interface_driver().
Referenced by i386_kmain().
void i386_idle_task ()
Definition at line 225 of file init.c.
References process_info::name, scheduler_current_task, scheduler_set_as_idle(), and strcpy().
Referenced by i386_kmain().
void i386_init_load_modules (multiboot_info_t * mbt)
Definition at line 84 of file init.c.
References I386_PAGE_FLAG_PRESENT, I386_PAGE_FLAG_RW, multiboot_module::mod_end, multiboot_module::mod_start, multiboot_info::mods_addr, multiboot_info::mods_count, paging_map(), paging_unmap(), physmm_free_frame(), PHYSMM_PAGE_SIZE, and tar_extract_mem().
Referenced by i386_kmain().
void i386_init_mm (multiboot_info_t * mbd, unsigned int magic)
Todo:
: PANIC!!!
Definition at line 106 of file init.c.
References page_dir::content, debugcon_init(), debugcon_puts, earlycon_init(), earlycon_printf, earlycon_puts, heapmm_alloc_page(), heapmm_init(), heapmm_request_core(), i386_fpu_initialize(), i386_init_multiboot_memprobe(), i386_init_reserve_modules(), kdbg_initialize(), MULTIBOOT_BOOTLOADER_MAGIC, paging_active_dir, paging_get_physical_address(), paging_init(), paging_map(), PAGING_PAGE_FLAG_RW, PAGING_PAGE_FLAG_USER, PAGING_PAGE_TAG_KERNEL_DATA, PAGING_PAGE_TAG_USER_DATA, paging_tag(), physmm_alloc_frame(), physmm_claim_range(), physmm_free_frame(), physmm_free_range(), and physmm_init().
uint32_t i386_init_multiboot_memprobe (multiboot_info_t * mbt)
Todo:
: Verify page alignment of mmap entries
Definition at line 44 of file init.c.
References multiboot_info::mmap_addr, multiboot_info::mmap_length, and physmm_free_range().
Referenced by i386_init_mm().
void i386_init_reserve_modules (multiboot_info_t * mbt)
Definition at line 73 of file init.c.
References multiboot_info::mods_addr, multiboot_info::mods_count, and physmm_claim_range().
Referenced by i386_init_mm().
void i386_init_stub ()
Definition at line 198 of file init.c.
References _sys_dup(), _sys_open(), earlycon_printf, NULL, O_RDWR, process_exec(), and syscall_errno.
Referenced by i386_kmain().
void i386_kmain ()
Once we are here everything is set up properly First 4 MB are both at 0xC000 0000 and 0x0000 0000 to support GDT trick! Task Stack is at 0xBFFF DFFF downwards ISR Stack is at 0xBFFF E000 ------— KERNEL RAM BOUNDARY -------— Code is at 0xC000 0000 Heap is at 0xD000 0000 Pagedir is at 0xFFC0 0000.
Definition at line 246 of file init.c.
References ata_pci_register(), device_block_init(), device_char_init(), drivermgr_init(), earlycon_printf, earlycon_puts, halt(), i386_idle_task(), i386_idt_initialize(), i386_init_load_modules(), i386_init_stub(), i386_pic_initialize(), I386_PIT_OCW_MODE_RATEGEN, i386_pit_setup(), i386_protection_init(), interrupt_init(), pci_enumerate_all(), physmm_count_free(), ramfs_create(), S_IFCHR, scheduler_fork(), scheduler_init(), sys_waitpid(), syscall_init(), tty_init(), vfs_initialize(), vfs_mknod(), and vterm_vga_init().
void vgacon_clear_video ()
Definition at line 213 of file vgacon.c.
References memset(), and vgacon_vc::video_buffer.
void vterm_vga_init ()
Definition at line 111 of file vga_vterm.c.
References vgacon_vc::cursor_x, vgacon_vc::cursor_y, kb_initialize(), vgacon_vc::page_id, vga_vterm_get_text_video_memory(), vgacon_vc::video_buffer, vterm_tty_setup(), and vterm_vga_switch_vc().
Referenced by i386_kmain().
Variable Documentation
uint32_t i386_start_kheap
multiboot_info_t* mb_info
arch/i386/paging.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 30-03-2014 - Created
Definition at line 40 of file init.c.