posnk kernel: arch/i386/isr.c File Reference
isr.c File Reference
#include <stdint.h>
#include "arch/i386/pic.h"
#include "arch/i386/x86.h"
#include "kernel/exception.h"
#include "kernel/earlycon.h"
#include "kernel/paging.h"
#include "kernel/system.h"
#include "kernel/syscall.h"
#include "kernel/scheduler.h"
#include "kernel/interrupt.h"
#include "kernel/time.h"
#include "util/debug.h"
Functions
void * i386_get_page_fault_addr ()
void sercon_isr ()
Interrupt handler!
void i386_handle_interrupt (uint32_t int_id, uint32_t data_segment, i386_pusha_registers_t registers, uint32_t error_code, uint32_t instr_ptr)
Variables
int i386_exception_table []
arch/i386/isr.c
Function Documentation
void* i386_get_page_fault_addr ()
Definition at line 48 of file isr.c.
Referenced by i386_handle_interrupt().
void i386_handle_interrupt (uint32_t int_id, uint32_t data_segment, i386_pusha_registers_t registers, uint32_t error_code, uint32_t instr_ptr)
Definition at line 62 of file isr.c.
References i386_pusha_registers::eax, exception_handle(), I386_EXCEPTION_INVALID_OPCODE, I386_EXCEPTION_NO_COPROCESSOR, I386_EXCEPTION_PAGE_FAULT, i386_exception_table, i386_fpu_handle_ill(), i386_get_page_fault_addr(), i386_interrupt_done(), interrupt_dispatch(), paging_handle_fault(), sercon_isr(), syscall_dispatch(), and timer_interrupt().
void sercon_isr ()
Interrupt handler!
Definition at line 12 of file sercon.c.
References i386_inb(), PORT, sserial_received(), and tty_input_char().
Referenced by i386_handle_interrupt().
Variable Documentation
int i386_exception_table[]
Initial value:
{
        EXCEPTION_DIV_ZERO,
        EXCEPTION_DEBUG,
        -1,
        EXCEPTION_DEBUG,
        EXCEPTION_OVERFLOW,
        EXCEPTION_BOUNDS_CHECK,
        EXCEPTION_INVALID_OPCODE,
        EXCEPTION_NO_FLOAT_UNIT,
        EXCEPTION_DOUBLE_FAULT,
        EXCEPTION_FLOAT_UNIT_ERROR,
        EXCEPTION_SEG_FAULT,
        EXCEPTION_SEG_FAULT,
        EXCEPTION_STACK_EXCEPTION,
        EXCEPTION_PROTECTION_FAULT,
        EXCEPTION_PAGE_FAULT,
        -1,
        EXCEPTION_FLOAT_UNIT_ERROR
}
arch/i386/isr.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 01-04-2014 - Created
Definition at line 25 of file isr.c.
Referenced by i386_handle_interrupt().