posnk kernel: include/driver/oldkb/kbd.h File Reference
kbd.h File Reference
#include <string.h>
#include <stdint.h>
Functions
void kb_initialize ()
void kb_set_leds (uint8_t leds)
void kb_toggle_modifier (uint8_t mask)
void kb_set_modifier (uint8_t mask)
void kb_clear_modifier (uint8_t mask)
void kb_pressed (uint8_t scan)
void kb_typed (uint8_t scan)
void kb_released (uint8_t scan)
Function Documentation
void kb_clear_modifier (uint8_t mask)
Definition at line 44 of file kbd.c.
References modifiers.
Referenced by kbd_isr().
void kb_initialize ()
Definition at line 9 of file kbd.c.
References interrupt_register_handler(), kb_set_leds(), kbd_controller_status(), KBD_CTRL_STATUS_OUT_BUF_BIT, kbd_encoder_read_buffer(), kbd_isr(), and NULL.
void kb_pressed (uint8_t scan)
Definition at line 48 of file kbd.c.
References kb_typed().
Referenced by kbd_isr().
void kb_released (uint8_t scan)
Definition at line 60 of file kbd.c.
Referenced by kbd_isr().
void kb_set_leds (uint8_t leds)
Definition at line 17 of file kbd.c.
References KBD_CPSLCK_BIT, KBD_NUMLCK_BIT, KBD_SCLLCK_BIT, and kbd_send_encoder_command().
Referenced by kb_initialize().
void kb_set_modifier (uint8_t mask)
Definition at line 40 of file kbd.c.
References modifiers.
Referenced by kbd_isr().
void kb_toggle_modifier (uint8_t mask)
Definition at line 33 of file kbd.c.
References modifiers.
Referenced by kbd_isr().
void kb_typed (uint8_t scan)
Definition at line 54 of file kbd.c.
References con_handle_key(), decode_keystroke(), and modifiers.
Referenced by kb_pressed(), and kbd_isr().