posnk kernel: kdbg/kdbgio.c File Reference
kdbgio.c File Reference
#include "kdbg/kdbgio.h"
#include <string.h>
Functions
char debugcon_getc ()
char * kdbg_gets (char *buf, size_t size)
uintptr_t kdbg_parsehex (char *str)
Function Documentation
char debugcon_getc ()
Definition at line 20 of file sercon_debug.c.
References i386_inb(), PORT, and serial_received().
Referenced by kdbg_gets().
char* kdbg_gets (char * buf, size_t size)
Definition at line 17 of file kdbgio.c.
References buf, debugcon_getc(), debugcon_putc(), and size.
Referenced by kdbg_shell().
uintptr_t kdbg_parsehex (char * str)
Definition at line 39 of file kdbgio.c.
References strlen().
Referenced by kdbg_shell().