posnk kernel: include/kdbg/kdbgmm.h File Reference
kdbgmm.h File Reference
#include "util/llist.h"
#include <stddef.h>
Data Structures
struct kdbgmm_block
Heap memory manager free block descriptor typedef: kdbgmm_block_t.
Typedefs
typedef struct kdbgmm_block kdbgmm_block_t
kdbg/kdbgmm.h
Functions
void kdbgmm_init (void *heap_start, size_t size)
Initializes the heap memory manager.
void * kdbgmm_alloc_page ()
Allocates a new page of heap space to the caller.
void * kdbgmm_alloc_table ()
Allocates a page alligned block of RAM,no call to morecore.
void * kdbgmm_alloc_page_alligned (size_t size)
Allocates a page alligned block of RAM.
void * kdbgmm_alloc (size_t size)
Allocates a new block of memory of given size to the caller.
void kdbgmm_free (void *address, size_t size)
Releases a block of memory so it can be reallocated.
Typedef Documentation
typedef struct kdbgmm_block kdbgmm_block_t
kdbg/kdbgmm.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 28-03-2014 - Created as kernel heap mm 12-05-2014 - Adapted as debugger heap mm typedef for kdbgmm_block: Heap memory manager free block descriptor
Definition at line 23 of file kdbgmm.h.
Function Documentation
void* kdbgmm_alloc (size_t size)
Allocates a new block of memory of given size to the caller.
Definition at line 487 of file kdbgmm.c.
References kdbgmm_alloc_internal(), kdbgmm_top_of_heap, and TRUE.
Referenced by dbgapi_register_memuse(), and kdbg_do_calltrace().
void* kdbgmm_alloc_page ()
Allocates a new page of heap space to the caller.
Definition at line 499 of file kdbgmm.c.
References kdbgmm_alloc_page_alligned(), and PHYSMM_PAGE_SIZE.
Referenced by kdbgmm_alloc_page_alligned().
void* kdbgmm_alloc_page_alligned (size_t size)
Allocates a page alligned block of RAM.
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Definition at line 400 of file kdbgmm.c.
References kdbgmm_alloc_page(), kdbgmm_alloc_page_fit_iterator(), kdbgmm_alloc_page_match_iterator(), kdbgmm_alloc_page_split_iterator(), kdbgmm_free_internal(), kdbgmm_morecore(), llist_iterate_select(), llist_unlink(), NULL, padding, PHYSMM_PAGE_ADDRESS_MASK, PHYSMM_PAGE_SIZE, kdbgmm_block::size, size, and kdbgmm_block::start.
Referenced by kdbgmm_alloc_page().
void* kdbgmm_alloc_table ()
Allocates a page alligned block of RAM,no call to morecore.
void kdbgmm_free (void * address, size_t size)
Releases a block of memory so it can be reallocated.
Definition at line 507 of file kdbgmm.c.
References kdbgmm_free_internal().
Referenced by dbgapi_unreg_memuse(), and kdbg_free_calltrace().
void kdbgmm_init (void * heap_start, size_t size)
Initializes the heap memory manager.
Parameters
heap_start The start of the heap
Definition at line 516 of file kdbgmm.c.
References kdbgmm_free_internal(), kdbgmm_top_of_heap, and llist_create().
Referenced by kdbg_initialize().