posnk kernel: kdbg/kdbgmm.c File Reference
kdbgmm.c File Reference
#include "kernel/physmm.h"
#include "kdbg/kdbgmm.h"
#include "kernel/earlycon.h"
#include "kernel/scheduler.h"
#include <stdint.h>
#include <string.h>
Macros
#define FALSE (0)
kdbg/kdbgmm.c
#define TRUE (1)
Functions
void kdbgmm_free_internal (void *address, size_t size)
Releases a block of memory so it can be reallocated.
void * kdbgmm_alloc_internal (size_t size, int morecore)
Allocates a new block of memory of given size to the caller.
size_t heapmm_request_core (void *address, size_t size)
int kdbgmm_morecore_iterator (llist_t *node, __attribute__((__unused__)) void *param)
Iterator function that tests for empty blocks.
void kdbgmm_morecore (size_t size)
Internal function Requests more memory and adds it to the free block table, then cleans up low space markers.
int kdbgmm_merge_start_iterator (llist_t *node, void *param)
Iterator function that tests for [our block][FREE] mergeable blocks.
int kdbgmm_merge_end_iterator (llist_t *node, void *param)
Iterator function that tests for [FREE][our block] mergeable blocks.
int kdbgmm_alloc_match_iterator (llist_t *node, void *param)
Iterator function that tests for blocks equal the size in param.
int kdbgmm_alloc_fit_iterator (llist_t *node, void *param)
Iterator function that tests for blocks able to contain the size in param.
int kdbgmm_alloc_page_match_iterator (llist_t *node, void *param)
Iterator function that tests for page aligned, page sized blocks.
int kdbgmm_alloc_page_split_iterator (llist_t *node, void *param)
Iterator function that tests for blocks large enough to contain a whole page.
int kdbgmm_alloc_page_fit_iterator (llist_t *node, void *param)
Iterator function that tests for page aligned, larger than page sized blocks.
void * kdbgmm_alloc_page_alligned (size_t size)
Allocates a page alligned block of RAM.
void * kdbgmm_alloc (size_t size)
Allocates a new block of memory of given size to the caller.
void * kdbgmm_alloc_page ()
Allocates a new page of heap space to the caller.
void kdbgmm_free (void *address, size_t size)
Releases a block of memory so it can be reallocated.
void kdbgmm_init (void *heap_start, size_t size)
Initializes the heap memory manager.
Variables
llist_t kdbgmm_free_blocks_list
Heap memory manager free block list head pointer.
void * kdbgmm_top_of_heap
Pointer to the top of the heap.
Macro Definition Documentation
#define FALSE (0)
kdbg/kdbgmm.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 28-03-2014 - Created as kernel heap mm 12-05-2014 - Adapted as debugger heap mm
Definition at line 20 of file kdbgmm.c.
Referenced by kdbgmm_free_internal().
#define TRUE (1)
Definition at line 22 of file kdbgmm.c.
Referenced by kdbgmm_alloc().
Function Documentation
size_t heapmm_request_core (void * address, size_t size)
Definition at line 22 of file paging.c.
void* kdbgmm_alloc (size_t size)
Allocates a new block of memory of given size to the caller.
Definition at line 487 of file kdbgmm.c.
References kdbgmm_alloc_internal(), kdbgmm_top_of_heap, and TRUE.
Referenced by dbgapi_register_memuse(), and kdbg_do_calltrace().
int kdbgmm_alloc_fit_iterator (llist_t * node, void * param)
Iterator function that tests for blocks able to contain the size in param.
Definition at line 257 of file kdbgmm.c.
References block, kdbgmm_block::size, and size.
Referenced by kdbgmm_alloc_internal().
void * kdbgmm_alloc_internal (size_t size, int morecore)
Allocates a new block of memory of given size to the caller.
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Definition at line 267 of file kdbgmm.c.
References kdbgmm_alloc_fit_iterator(), kdbgmm_alloc_match_iterator(), kdbgmm_free_internal(), kdbgmm_morecore(), kdbgmm_morecore_iterator(), llist_iterate_select(), llist_unlink(), memset(), NULL, kdbgmm_block::size, size, and kdbgmm_block::start.
Referenced by kdbgmm_alloc(), and kdbgmm_free_internal().
int kdbgmm_alloc_match_iterator (llist_t * node, void * param)
Iterator function that tests for blocks equal the size in param.
Definition at line 244 of file kdbgmm.c.
References block, kdbgmm_top_of_heap, and size.
Referenced by kdbgmm_alloc_internal().
void* kdbgmm_alloc_page ()
Allocates a new page of heap space to the caller.
Definition at line 499 of file kdbgmm.c.
References kdbgmm_alloc_page_alligned(), and PHYSMM_PAGE_SIZE.
Referenced by kdbgmm_alloc_page_alligned().
void* kdbgmm_alloc_page_alligned (size_t size)
Allocates a page alligned block of RAM.
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Definition at line 400 of file kdbgmm.c.
References kdbgmm_alloc_page(), kdbgmm_alloc_page_fit_iterator(), kdbgmm_alloc_page_match_iterator(), kdbgmm_alloc_page_split_iterator(), kdbgmm_free_internal(), kdbgmm_morecore(), llist_iterate_select(), llist_unlink(), NULL, padding, PHYSMM_PAGE_ADDRESS_MASK, PHYSMM_PAGE_SIZE, kdbgmm_block::size, size, and kdbgmm_block::start.
Referenced by kdbgmm_alloc_page().
int kdbgmm_alloc_page_fit_iterator (llist_t * node, void * param)
Iterator function that tests for page aligned, larger than page sized blocks.
Definition at line 389 of file kdbgmm.c.
References block, PHYSMM_PAGE_ADDRESS_MASK, kdbgmm_block::size, size, and kdbgmm_block::start.
Referenced by kdbgmm_alloc_page_alligned().
int kdbgmm_alloc_page_match_iterator (llist_t * node, void * param)
Iterator function that tests for page aligned, page sized blocks.
Definition at line 362 of file kdbgmm.c.
References block, PHYSMM_PAGE_ADDRESS_MASK, kdbgmm_block::size, size, and kdbgmm_block::start.
Referenced by kdbgmm_alloc_page_alligned().
int kdbgmm_alloc_page_split_iterator (llist_t * node, void * param)
Iterator function that tests for blocks large enough to contain a whole page.
Definition at line 375 of file kdbgmm.c.
References block, PHYSMM_PAGE_ADDRESS_MASK, PHYSMM_PAGE_SIZE, kdbgmm_block::size, size, and kdbgmm_block::start.
Referenced by kdbgmm_alloc_page_alligned().
void kdbgmm_free (void * address, size_t size)
Releases a block of memory so it can be reallocated.
Definition at line 507 of file kdbgmm.c.
References kdbgmm_free_internal().
Referenced by dbgapi_unreg_memuse(), and kdbg_free_calltrace().
void kdbgmm_free_internal (void * address, size_t size)
Releases a block of memory so it can be reallocated.
Todo:
: Release a lock on the free block table
Todo:
: Get a lock on the free block table
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Get a lock on the free block table
Todo:
: Release a lock on the free block table
Todo:
: Release a lock on the free block table
Definition at line 114 of file kdbgmm.c.
References FALSE, kdbgmm_alloc_internal(), kdbgmm_merge_end_iterator(), kdbgmm_merge_start_iterator(), kdbgmm_morecore(), llist_add_end(), llist_iterate_select(), llist_unlink(), memset(), NULL, kdbgmm_block::size, size, and kdbgmm_block::start.
Referenced by kdbgmm_alloc_internal(), kdbgmm_alloc_page_alligned(), kdbgmm_free(), kdbgmm_init(), and kdbgmm_morecore().
void kdbgmm_init (void * heap_start, size_t size)
Initializes the heap memory manager.
Parameters
heap_start The start of the heap
Definition at line 516 of file kdbgmm.c.
References kdbgmm_free_internal(), kdbgmm_top_of_heap, and llist_create().
Referenced by kdbg_initialize().
int kdbgmm_merge_end_iterator (llist_t * node, void * param)
Iterator function that tests for [FREE][our block] mergeable blocks.
Definition at line 104 of file kdbgmm.c.
References block, kdbgmm_block::size, and kdbgmm_block::start.
Referenced by kdbgmm_free_internal().
int kdbgmm_merge_start_iterator (llist_t * node, void * param)
Iterator function that tests for [our block][FREE] mergeable blocks.
Definition at line 95 of file kdbgmm.c.
References block, kdbgmm_block::size, and kdbgmm_block::start.
Referenced by kdbgmm_free_internal().
void kdbgmm_morecore (size_t size)
Internal function Requests more memory and adds it to the free block table, then cleans up low space markers.
Definition at line 58 of file kdbgmm.c.
References heapmm_request_core(), kdbgmm_free_internal(), kdbgmm_morecore_iterator(), kdbgmm_top_of_heap, llist_iterate_select(), llist_unlink(), and NULL.
Referenced by kdbgmm_alloc_internal(), kdbgmm_alloc_page_alligned(), and kdbgmm_free_internal().
int kdbgmm_morecore_iterator (llist_t * node, __attribute__((__unused__)) void * param)
Iterator function that tests for empty blocks.
Definition at line 47 of file kdbgmm.c.
References block, and kdbgmm_block::size.
Referenced by kdbgmm_alloc_internal(), and kdbgmm_morecore().
Variable Documentation
llist_t kdbgmm_free_blocks_list
Heap memory manager free block list head pointer.
Definition at line 27 of file kdbgmm.c.
void* kdbgmm_top_of_heap
Pointer to the top of the heap.
Definition at line 32 of file kdbgmm.c.
Referenced by kdbgmm_alloc(), kdbgmm_alloc_match_iterator(), kdbgmm_init(), and kdbgmm_morecore().