posnk kernel: kernel/paging.c File Reference
paging.c File Reference
#include <stddef.h>
#include "kernel/paging.h"
#include "kernel/physmm.h"
#include "kernel/heapmm.h"
#include "kernel/exception.h"
#include "kernel/earlycon.h"
#include "kernel/process.h"
Functions
size_t heapmm_request_core (void *address, size_t size)
void paging_handle_out_of_memory ()
void paging_handle_fault (void *virt_addr, void *instr_ptr, void *state, size_t state_size, int present, int write, int user)
Variables
page_dir_t * paging_active_dir
kernel/paging.c
Function Documentation
size_t heapmm_request_core (void * address, size_t size)
Definition at line 22 of file paging.c.
References debugcon_aputs(), earlycon_aputs(), NULL, paging_map(), PAGING_PAGE_FLAG_RW, PAGING_PAGE_TAG_KERNEL_DATA, paging_tag(), physmm_alloc_frame(), PHYSMM_NO_FRAME, and PHYSMM_PAGE_SIZE.
Referenced by heapmm_morecore(), i386_init_mm(), kdbg_initialize(), and kdbgmm_morecore().
void paging_handle_fault (void * virt_addr, void * instr_ptr, void * state, size_t state_size, int present, int write, int user)
Todo:
: Dispatch exception, usermode program tried to access kernel space
Todo:
: Assess potential for race conditions
Todo:
: Swapping, for now: PANIC!!!
Todo:
: PANIC!
Todo:
: Check for dynamic libraries, mmapped files and swapped out pages
Todo:
: If no fix was found, dispatch exception
Todo:
: Copy on write,
Definition at line 49 of file paging.c.
References curpid(), debugcon_printf, exception_handle(), EXCEPTION_PAGE_FAULT, paging_handle_out_of_memory(), paging_map(), PAGING_PAGE_FLAG_RW, PAGING_PAGE_FLAG_USER, PAGING_PAGE_TAG_USER_DATA, paging_tag(), physmm_alloc_frame(), PHYSMM_NO_FRAME, PHYSMM_PAGE_ADDRESS_MASK, and procvmm_handle_fault().
Referenced by i386_handle_interrupt().
void paging_handle_out_of_memory ()
Definition at line 44 of file paging.c.
References earlycon_printf.
Referenced by paging_create_dir(), paging_handle_fault(), and paging_map().
Variable Documentation
page_dir_t* paging_active_dir
kernel/paging.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 30-03-2014 - Created
Definition at line 20 of file paging.c.
Referenced by i386_alloc_page(), i386_init_mm(), paging_create_dir(), paging_get_physical_address(), paging_init(), paging_map(), paging_switch_dir(), scheduler_init(), and scheduler_switch_task().