posnk kernel: include/kernel/paging.h File Reference
paging.h File Reference
#include "kernel/physmm.h"
#include <stdint.h>
Data Structures
struct page_dir
Macros
#define PAGING_PAGE_FLAG_USER (0x1)
#define PAGING_PAGE_FLAG_RW (0x2)
#define PAGING_PAGE_FLAG_NOCACHE (0x4)
#define PAGING_PAGE_TAG_KERNEL_DATA (0)
#define PAGING_PAGE_TAG_KERNEL_CODE (1)
#define PAGING_PAGE_TAG_MM_HARDWARE (2)
#define PAGING_PAGE_TAG_DMA_BUFFER (3)
#define PAGING_PAGE_TAG_USER_DATA (4)
#define PAGING_PAGE_TAG_USER_CODE (5)
#define PAGING_PAGE_TAG_USER_MMAP (6)
Typedefs
typedef uint_fast16_t page_flags_t
kernel/paging.h
typedef uint_fast8_t page_tag_t
typedef struct page_dir page_dir_t
Functions
void paging_switch_dir (page_dir_t *new_dir)
page_dir_t * paging_create_dir ()
void paging_free_dir (page_dir_t *dir)
void paging_map (void *virt_addr, physaddr_t phys_addr, page_flags_t flags)
void paging_unmap (void *virt_addr)
page_tag_t paging_get_tag (void *virt_addr)
void paging_tag (void *virt_addr, page_tag_t tag)
void paging_init ()
void paging_handle_out_of_memory ()
void paging_handle_fault (void *virt_addr, void *instr_ptr, void *state, size_t state_size, int present, int write, int user)
int paging_soft_check (void *virt_addr, size_t size)
uintptr_t paging_get_physical_address (void *virt_addr)
Variables
page_dir_t * paging_active_dir
kernel/paging.c
Macro Definition Documentation
#define PAGING_PAGE_FLAG_NOCACHE (0x4)
Definition at line 29 of file paging.h.
Referenced by paging_map().
#define PAGING_PAGE_FLAG_RW (0x2)
Definition at line 28 of file paging.h.
Referenced by heapmm_request_core(), i386_init_mm(), paging_handle_fault(), paging_map(), and procvmm_handle_fault().
#define PAGING_PAGE_FLAG_USER (0x1)
Definition at line 27 of file paging.h.
Referenced by i386_init_mm(), paging_handle_fault(), paging_map(), and procvmm_handle_fault().
#define PAGING_PAGE_TAG_DMA_BUFFER (3)
Definition at line 34 of file paging.h.
#define PAGING_PAGE_TAG_KERNEL_CODE (1)
Definition at line 32 of file paging.h.
#define PAGING_PAGE_TAG_KERNEL_DATA (0)
Definition at line 31 of file paging.h.
Referenced by heapmm_request_core(), and i386_init_mm().
#define PAGING_PAGE_TAG_MM_HARDWARE (2)
Definition at line 33 of file paging.h.
#define PAGING_PAGE_TAG_USER_CODE (5)
Definition at line 36 of file paging.h.
#define PAGING_PAGE_TAG_USER_DATA (4)
Definition at line 35 of file paging.h.
Referenced by i386_init_mm(), and paging_handle_fault().
#define PAGING_PAGE_TAG_USER_MMAP (6)
Definition at line 37 of file paging.h.
Typedef Documentation
typedef struct page_dir page_dir_t
Definition at line 20 of file paging.h.
typedef uint_fast16_t page_flags_t
kernel/paging.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 30-03-2014 - Created
Definition at line 18 of file paging.h.
typedef uint_fast8_t page_tag_t
Definition at line 19 of file paging.h.
Function Documentation
page_dir_t* paging_create_dir ()
Definition at line 55 of file paging.c.
References page_dir::content, i386_page_dir_list::dir, i386_page_dir::directory, process_mmap::flags, heapmm_alloc(), heapmm_alloc_page(), heapmm_free(), i386_alloc_page(), I386_PAGE_FLAG_NOCACHE, I386_PAGE_FLAG_PRESENT, I386_PAGE_FLAG_RW, i386_phys_copy_frame(), I386_PTADDR, llist_add_end(), memset(), NULL, i386_page_table::pages, paging_active_dir, paging_get_physical_address(), paging_handle_out_of_memory(), paging_map(), physmm_alloc_frame(), PHYSMM_NO_FRAME, PHYSMM_PAGE_SIZE, PROCESS_MMAP_FLAG_PUBLIC, and procvmm_get_memory_region().
Referenced by paging_init(), and scheduler_fork_to().
void paging_free_dir (page_dir_t * dir)
uintptr_t paging_get_physical_address (void * virt_addr)
Definition at line 265 of file paging.c.
References page_dir::content, i386_page_dir::directory, I386_ADDR_TO_PD_IDX, I386_ADDR_TO_PTEPTR, I386_PAGE_FLAG_PRESENT, and paging_active_dir.
Referenced by ata_initialize(), ata_read(), ata_write(), i386_init_mm(), paging_create_dir(), paging_switch_dir(), procvmm_unmmap(), scheduler_exsig(), and scheduler_switch_task().
page_tag_t paging_get_tag (void * virt_addr)
Definition at line 214 of file paging.c.
References I386_ADDR_TO_PTEPTR.
void paging_handle_fault (void * virt_addr, void * instr_ptr, void * state, size_t state_size, int present, int write, int user)
Todo:
: Dispatch exception, usermode program tried to access kernel space
Todo:
: Assess potential for race conditions
Todo:
: Swapping, for now: PANIC!!!
Todo:
: PANIC!
Todo:
: Check for dynamic libraries, mmapped files and swapped out pages
Todo:
: If no fix was found, dispatch exception
Todo:
: Copy on write,
Definition at line 49 of file paging.c.
References curpid(), debugcon_printf, exception_handle(), EXCEPTION_PAGE_FAULT, paging_handle_out_of_memory(), paging_map(), PAGING_PAGE_FLAG_RW, PAGING_PAGE_FLAG_USER, PAGING_PAGE_TAG_USER_DATA, paging_tag(), physmm_alloc_frame(), PHYSMM_NO_FRAME, PHYSMM_PAGE_ADDRESS_MASK, and procvmm_handle_fault().
Referenced by i386_handle_interrupt().
void paging_handle_out_of_memory ()
Definition at line 44 of file paging.c.
References earlycon_printf.
Referenced by paging_create_dir(), paging_handle_fault(), and paging_map().
void paging_init ()
Definition at line 230 of file paging.c.
References page_dir::content, i386_page_dir::directory, I386_ADDR_TO_PT_IDX, i386_alloc_page(), i386_init_switch_gdt(), I386_PAGE_FLAG_GLOBAL, I386_PAGE_FLAG_NOCACHE, I386_PAGE_FLAG_PRESENT, I386_PAGE_FLAG_RW, I386_PAGE_FLAG_USER, i386_paging_enable(), llist_create(), memset(), i386_page_table::pages, paging_active_dir, and paging_create_dir().
Referenced by i386_init_mm().
void paging_map (void * virt_addr, physaddr_t phys_addr, page_flags_t flags)
Todo:
: Determine whether we have to free previously mapped frame
Definition at line 142 of file paging.c.
References page_dir::content, i386_page_dir::directory, I386_ADDR_TO_PD_IDX, I386_ADDR_TO_PT_IDX, I386_ADDR_TO_PTEPTR, I386_PAGE_FLAG_GLOBAL, I386_PAGE_FLAG_NOCACHE, I386_PAGE_FLAG_PRESENT, I386_PAGE_FLAG_RW, I386_PAGE_FLAG_USER, i386_set_pd_param::index, llist_iterate_select(), memset(), i386_page_table::pages, paging_active_dir, paging_handle_out_of_memory(), PAGING_PAGE_FLAG_NOCACHE, PAGING_PAGE_FLAG_RW, PAGING_PAGE_FLAG_USER, paging_set_pd_iterator(), physmm_alloc_frame(), PHYSMM_NO_FRAME, and i386_set_pd_param::value.
Referenced by heapmm_request_core(), i386_init_load_modules(), i386_init_mm(), paging_create_dir(), paging_handle_fault(), and procvmm_handle_fault().
int paging_soft_check (void * virt_addr, size_t size)
void paging_switch_dir (page_dir_t * new_dir)
Definition at line 42 of file paging.c.
References page_dir::content, paging_active_dir, and paging_get_physical_address().
void paging_tag (void * virt_addr, page_tag_t tag)
Definition at line 207 of file paging.c.
References I386_ADDR_TO_PTEPTR.
Referenced by heapmm_request_core(), i386_init_mm(), and paging_handle_fault().
void paging_unmap (void * virt_addr)
Definition at line 200 of file paging.c.
References I386_ADDR_TO_PTEPTR, and I386_PAGE_FLAG_PRESENT.
Referenced by i386_init_load_modules(), procvmm_handle_fault(), and procvmm_unmmap().
Variable Documentation
page_dir_t* paging_active_dir
kernel/paging.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 30-03-2014 - Created
Definition at line 20 of file paging.c.
Referenced by i386_alloc_page(), i386_init_mm(), paging_create_dir(), paging_get_physical_address(), paging_init(), paging_map(), paging_switch_dir(), scheduler_init(), and scheduler_switch_task().