posnk kernel: util/llist.c File Reference
llist.c File Reference
#include "util/llist.h"
#include <stddef.h>
Functions
llist_t * llist_get_first (llist_t *list)
util/llist.c
llist_t * llist_get_last (llist_t *list)
Gets the last entry in a doubly linked list.
llist_t * llist_remove_last (llist_t *list)
Gets and removes the last entry in a doubly linked list.
llist_t * llist_remove_first (llist_t *list)
Gets and removes the first entry in a doubly linked list.
void llist_add_end (llist_t *list, llist_t *entry)
Adds a node to the end of the linked list.
void llist_unlink (llist_t *entry)
Unlinks a node from the list it is in.
void llist_create (llist_t *list)
Initializes a new head node (list)
int llist_size (llist_t *list)
Counts the number of nodes in a linked list.
llist_t * llist_iterate_select (llist_t *list, llist_iterator_t iterator, void *param)
Iterates over the list and calls iterator for each node, if iterator returns a true condition iteration will stop and the current node will be returned.
Function Documentation
void llist_add_end (llist_t * list, llist_t * entry)
Adds a node to the end of the linked list.
Parameters
list Pointer to the linked list head node
entry The node to add to the list
Todo:
: Maybe add some checks here
Definition at line 78 of file llist.c.
References llist::next, and llist::prev.
Referenced by _sys_dup2(), _sys_open(), _sys_pipe2(), blkcache_bump(), blkcache_get(), dbgapi_register_memuse(), drivermgr_register_device_driver(), drivermgr_register_interface_driver(), heapmm_free_internal(), interrupt_register_handler(), kdbg_do_calltrace(), kdbgmm_free_internal(), paging_create_dir(), process_child_event(), procvmm_mmap_anon(), procvmm_mmap_copy_iterator(), procvmm_mmap_file(), ramfs_link(), ramfs_trunc_inode(), ramfs_write_inode(), scheduler_fork(), scheduler_init(), stream_ptr_copy_iterator(), vfs_get_inode(), vfs_initialize(), vfs_mknod(), and vfs_symlink().
void llist_create (llist_t * list)
Initializes a new head node (list)
Parameters
list Pointer to the linked list head node
Definition at line 105 of file llist.c.
References llist::next, and llist::prev.
Referenced by blkcache_create(), drivermgr_init(), heapmm_init(), interrupt_init(), kdbg_do_calltrace(), kdbg_init_memuse(), kdbgmm_init(), paging_init(), ramfs_mkdir(), ramfs_mknod(), scheduler_fork(), scheduler_init(), and vfs_initialize().
llist_t* llist_get_first (llist_t * list)
util/llist.c
Gets the first entry in a doubly linked list.
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 2011 - Original version 28-03-2014 - Changed names, added comments Gets the first entry in a doubly linked list
Parameters
list Pointer to the linked list head node
Returns
The first node in the linked list
Definition at line 22 of file llist.c.
References llist::next.
llist_t* llist_get_last (llist_t * list)
Gets the last entry in a doubly linked list.
Parameters
list Pointer top the linked list head node
Returns
The last node in the linked list
Definition at line 34 of file llist.c.
References llist::prev.
Referenced by procvmm_clear_mmaps(), and sys_waitpid().
llist_t* llist_iterate_select (llist_t * list, llist_iterator_t iterator, void * param)
Iterates over the list and calls iterator for each node, if iterator returns a true condition iteration will stop and the current node will be returned.
Parameters
list Pointer to the linked list head node
iterator Function pointer to an iterator int func(llist_t *, void *).
param Parameter to the iterator. (may be NULL)
Returns
The node for which iterator returned true.
Definition at line 139 of file llist.c.
References llist::next, and NULL.
Referenced by blkcache_find(), dbgapi_unreg_memuse(), drivermgr_enumerate_device(), drivermgr_enumerate_interface(), heapmm_alloc_alligned(), heapmm_alloc_internal(), heapmm_free_internal(), kdbg_print_memuse_brdr(), kdbgmm_alloc_internal(), kdbgmm_alloc_page_alligned(), kdbgmm_free_internal(), kdbgmm_morecore(), paging_map(), process_get(), process_get_event(), process_get_event_pg(), process_signal_pgroup(), procvmm_copy_memory_map(), procvmm_get_memory_region(), procvmm_mmap_anon(), procvmm_mmap_file(), procvmm_resize_map(), ramfs_find_dirent(), ramfs_read_inode(), ramfs_readdir(), ramfs_unlink(), ramfs_write_inode(), schedule(), stream_copy_fd_table(), stream_do_close_all(), stream_do_close_on_exec(), stream_get_ptr(), stream_get_ptr_o(), and vfs_get_inode().
llist_t* llist_remove_first (llist_t * list)
Gets and removes the first entry in a doubly linked list.
Parameters
list Pointer to the linked list head node
Returns
The first node in the linked list
Definition at line 62 of file llist.c.
References llist::next, and llist::prev.
llist_t* llist_remove_last (llist_t * list)
Gets and removes the last entry in a doubly linked list.
Parameters
list Pointer to the linked list head node
Returns
The last node in the linked list
Definition at line 46 of file llist.c.
References llist::next, and llist::prev.
int llist_size (llist_t * list)
Counts the number of nodes in a linked list.
Parameters
list Pointer to the linked list head node
Returns
The amount of nodes (excluding the head node)
Definition at line 116 of file llist.c.
References llist::next, and size.
void llist_unlink (llist_t * entry)
Unlinks a node from the list it is in.
Parameters
entry The node to unlink
Definition at line 93 of file llist.c.
References llist::next, and llist::prev.
Referenced by _sys_close_int(), blkcache_bump(), blkcache_free(), blkcache_get(), dbgapi_unreg_memuse(), heapmm_alloc_alligned(), heapmm_alloc_internal(), kdbg_free_calltrace(), kdbgmm_alloc_internal(), kdbgmm_alloc_page_alligned(), kdbgmm_free_internal(), kdbgmm_morecore(), process_absorb_event(), process_reap(), procvmm_unmmap(), ramfs_unlink(), vfs_mknod(), vfs_symlink(), and vfs_unlink().