posnk kernel: include/driver/bus/pci.h File Reference
pci.h File Reference
#include <stdint.h>
Macros
#define PCI_CONFIG_VENDOR_ID (0x00)
driver/bus/pci.h
#define PCI_CONFIG_DEVICE_ID (0x02)
#define PCI_CONFIG_COMMAND (0x04)
#define PCI_CONFIG_STATUS (0x06)
#define PCI_CONFIG_REVISION_ID (0x08)
#define PCI_CONFIG_API_ID (0x09)
#define PCI_CONFIG_SUBCLASS (0x0A)
#define PCI_CONFIG_CLASS (0x0B)
#define PCI_CONFIG_CACHE_SIZE (0x0C)
#define PCI_CONFIG_LATENCY_TMR (0x0D)
#define PCI_CONFIG_HEADER_TYPE (0x0E)
#define PCI_CONFIG_SELF_TEST (0x0F)
#define PCI_CONFIG_MULTIFUNCTION (0x80)
#define PCI_CONFIG_HEADER_TYPE_MASK (0x7F)
#define PCI_CONFIG_BAR0 (0x10)
#define PCI_CONFIG_BAR1 (0x14)
#define PCI_CONFIG_BAR2 (0x18)
#define PCI_CONFIG_BAR3 (0x1C)
#define PCI_CONFIG_BAR4 (0x20)
#define PCI_CONFIG_BAR5 (0x24)
#define PCI_CONFIG_CIS_POINTER (0x28)
#define PCI_CONFIG_SUBSYS_VENDOR_ID (0x2C)
#define PCI_CONFIG_SUBSYS_ID (0x2E)
#define PCI_CONFIG_OPTION_ROM_PTR (0x30)
#define PCI_CONFIG_CAPABILITY_PTR (0x34)
#define PCI_CONFIG_INTERRUPT_LINE (0x3C)
#define PCI_CONFIG_INTERRUPT_PIN (0x3D)
#define PCI_CONFIG_MIN_GRANT (0x3E)
#define PCI_CONFIG_MAX_LATENCY (0x3F)
#define PCI_CONFIG_PRIMARY_BUS (0x18)
#define PCI_CONFIG_SECONDARY_BUS (0x19)
#define PCI_CONFIG_SUBORD_BUS_NUMBER (0x1A)
#define PCI_CONFIG_SEC_LATENCY_TIMER (0x1B)
#define PCI_CONFIG_IO_BASE (0x1C)
#define PCI_CONFIG_IO_LIMIT (0x1D)
#define PCI_CONFIG_SECONDARY_STATUS (0x1E)
#define PCI_CONFIG_MEMORY_BASE (0x20)
#define PCI_CONFIG_MEMORY_LIMIT (0x22)
#define PCI_CONFIG_PREFETCH_MEM_BASE (0x24)
#define PCI_CONFIG_PREFETCH_MEM_LIMIT (0x26)
#define PCI_CONFIG_PREFETCH_MEM_BASE_H (0x28)
#define PCI_CONFIG_PREFETCH_MEM_LIMIT_H (0x2C)
#define PCI_CONFIG_IO_BASE_H (0x30)
#define PCI_CONFIG_IO_LIMIT_H (0x32)
Functions
uint32_t pci_config_read_long (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
driver/bus/pci_intel_host.c
uint16_t pci_config_read_short (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
uint8_t pci_config_read_byte (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
void pci_config_write_long (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint32_t value)
void pci_config_write_short (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint16_t value)
void pci_config_write_byte (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint16_t value)
void pci_enumerate_all ()
void pci_enumerate_bus (uint8_t bus)
void pci_enumerate_function (uint8_t bus, uint8_t device, uint8_t function)
Macro Definition Documentation
#define PCI_CONFIG_API_ID (0x09)
Definition at line 23 of file pci.h.
Referenced by pci_enumerate_function().
#define PCI_CONFIG_BAR0 (0x10)
Definition at line 36 of file pci.h.
Referenced by ata_pci_probe().
#define PCI_CONFIG_BAR1 (0x14)
Definition at line 37 of file pci.h.
Referenced by ata_pci_probe().
#define PCI_CONFIG_BAR2 (0x18)
Definition at line 38 of file pci.h.
Referenced by ata_pci_probe().
#define PCI_CONFIG_BAR3 (0x1C)
Definition at line 39 of file pci.h.
Referenced by ata_pci_probe().
#define PCI_CONFIG_BAR4 (0x20)
Definition at line 40 of file pci.h.
Referenced by ata_pci_probe().
#define PCI_CONFIG_BAR5 (0x24)
Definition at line 41 of file pci.h.
#define PCI_CONFIG_CACHE_SIZE (0x0C)
Definition at line 26 of file pci.h.
#define PCI_CONFIG_CAPABILITY_PTR (0x34)
Definition at line 48 of file pci.h.
#define PCI_CONFIG_CIS_POINTER (0x28)
Definition at line 44 of file pci.h.
#define PCI_CONFIG_CLASS (0x0B)
Definition at line 25 of file pci.h.
#define PCI_CONFIG_COMMAND (0x04)
Definition at line 20 of file pci.h.
#define PCI_CONFIG_DEVICE_ID (0x02)
Definition at line 19 of file pci.h.
Referenced by pci_enumerate_function().
#define PCI_CONFIG_HEADER_TYPE (0x0E)
Definition at line 28 of file pci.h.
Referenced by pci_enumerate_all(), and pci_enumerate_bus().
#define PCI_CONFIG_HEADER_TYPE_MASK (0x7F)
Definition at line 33 of file pci.h.
#define PCI_CONFIG_INTERRUPT_LINE (0x3C)
Definition at line 49 of file pci.h.
Referenced by ata_pci_probe().
#define PCI_CONFIG_INTERRUPT_PIN (0x3D)
Definition at line 50 of file pci.h.
#define PCI_CONFIG_IO_BASE (0x1C)
Definition at line 59 of file pci.h.
#define PCI_CONFIG_IO_BASE_H (0x30)
Definition at line 68 of file pci.h.
#define PCI_CONFIG_IO_LIMIT (0x1D)
Definition at line 60 of file pci.h.
#define PCI_CONFIG_IO_LIMIT_H (0x32)
Definition at line 69 of file pci.h.
#define PCI_CONFIG_LATENCY_TMR (0x0D)
Definition at line 27 of file pci.h.
#define PCI_CONFIG_MAX_LATENCY (0x3F)
Definition at line 52 of file pci.h.
#define PCI_CONFIG_MEMORY_BASE (0x20)
Definition at line 62 of file pci.h.
#define PCI_CONFIG_MEMORY_LIMIT (0x22)
Definition at line 63 of file pci.h.
#define PCI_CONFIG_MIN_GRANT (0x3E)
Definition at line 51 of file pci.h.
#define PCI_CONFIG_MULTIFUNCTION (0x80)
Definition at line 32 of file pci.h.
Referenced by pci_enumerate_all(), and pci_enumerate_bus().
#define PCI_CONFIG_OPTION_ROM_PTR (0x30)
Definition at line 47 of file pci.h.
#define PCI_CONFIG_PREFETCH_MEM_BASE (0x24)
Definition at line 64 of file pci.h.
#define PCI_CONFIG_PREFETCH_MEM_BASE_H (0x28)
Definition at line 66 of file pci.h.
#define PCI_CONFIG_PREFETCH_MEM_LIMIT (0x26)
Definition at line 65 of file pci.h.
#define PCI_CONFIG_PREFETCH_MEM_LIMIT_H (0x2C)
Definition at line 67 of file pci.h.
#define PCI_CONFIG_PRIMARY_BUS (0x18)
Definition at line 55 of file pci.h.
#define PCI_CONFIG_REVISION_ID (0x08)
Definition at line 22 of file pci.h.
#define PCI_CONFIG_SEC_LATENCY_TIMER (0x1B)
Definition at line 58 of file pci.h.
#define PCI_CONFIG_SECONDARY_BUS (0x19)
Definition at line 56 of file pci.h.
Referenced by pci_enumerate_function().
#define PCI_CONFIG_SECONDARY_STATUS (0x1E)
Definition at line 61 of file pci.h.
#define PCI_CONFIG_SELF_TEST (0x0F)
Definition at line 29 of file pci.h.
#define PCI_CONFIG_STATUS (0x06)
Definition at line 21 of file pci.h.
#define PCI_CONFIG_SUBCLASS (0x0A)
Definition at line 24 of file pci.h.
Referenced by pci_enumerate_function().
#define PCI_CONFIG_SUBORD_BUS_NUMBER (0x1A)
Definition at line 57 of file pci.h.
#define PCI_CONFIG_SUBSYS_ID (0x2E)
Definition at line 46 of file pci.h.
#define PCI_CONFIG_SUBSYS_VENDOR_ID (0x2C)
Definition at line 45 of file pci.h.
#define PCI_CONFIG_VENDOR_ID (0x00)
driver/bus/pci.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 01-07-2014 - Created
Definition at line 18 of file pci.h.
Referenced by pci_enumerate_all(), pci_enumerate_bus(), and pci_enumerate_function().
Function Documentation
uint8_t pci_config_read_byte (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
Definition at line 54 of file pci_intel_host.c.
References pci_config_read_long().
Referenced by ata_pci_probe(), pci_enumerate_all(), pci_enumerate_bus(), and pci_enumerate_function().
uint32_t pci_config_read_long (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
driver/bus/pci_intel_host.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 01-07-2014 - Created
Definition at line 15 of file pci_intel_host.c.
References CONFIG_ADDRESS, CONFIG_DATA, CONFIG_ENABLE, i386_inl(), and i386_outl().
Referenced by ata_pci_probe(), pci_config_read_byte(), pci_config_read_short(), pci_config_write_byte(), and pci_config_write_short().
uint16_t pci_config_read_short (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
Definition at line 37 of file pci_intel_host.c.
References pci_config_read_long().
Referenced by pci_enumerate_all(), pci_enumerate_bus(), and pci_enumerate_function().
void pci_config_write_byte (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint16_t value)
Definition at line 61 of file pci_intel_host.c.
References pci_config_read_long(), and pci_config_write_long().
void pci_config_write_long (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint32_t value)
Definition at line 27 of file pci_intel_host.c.
References CONFIG_ADDRESS, CONFIG_DATA, CONFIG_ENABLE, and i386_outl().
Referenced by pci_config_write_byte(), and pci_config_write_short().
void pci_config_write_short (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint16_t value)
Definition at line 44 of file pci_intel_host.c.
References pci_config_read_long(), and pci_config_write_long().
void pci_enumerate_all ()
Definition at line 37 of file pci.c.
References debugcon_printf, PCI_CONFIG_HEADER_TYPE, PCI_CONFIG_MULTIFUNCTION, pci_config_read_byte(), pci_config_read_short(), PCI_CONFIG_VENDOR_ID, and pci_enumerate_bus().
Referenced by i386_kmain().
void pci_enumerate_bus (uint8_t bus)
Definition at line 55 of file pci.c.
References PCI_CONFIG_HEADER_TYPE, PCI_CONFIG_MULTIFUNCTION, pci_config_read_byte(), pci_config_read_short(), PCI_CONFIG_VENDOR_ID, and pci_enumerate_function().
Referenced by pci_enumerate_all(), and pci_enumerate_function().
void pci_enumerate_function (uint8_t bus, uint8_t device, uint8_t function)
Definition at line 77 of file pci.c.
References debugcon_printf, DEVICE_TYPE_PCI, drivermgr_enumerate_device(), drivermgr_enumerate_interface(), PCI_CONFIG_API_ID, PCI_CONFIG_DEVICE_ID, pci_config_read_byte(), pci_config_read_short(), PCI_CONFIG_SECONDARY_BUS, PCI_CONFIG_SUBCLASS, PCI_CONFIG_VENDOR_ID, pci_device_lookup(), pci_enumerate_bus(), and pci_vendor_lookup().
Referenced by pci_enumerate_bus().