posnk kernel: driver/bus/pci_intel_host.c File Reference
pci_intel_host.c File Reference
#include "arch/i386/x86.h"
#include "driver/bus/pci_intel_host.h"
#include "kernel/earlycon.h"
Functions
uint32_t pci_config_read_long (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
driver/bus/pci_intel_host.c
void pci_config_write_long (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint32_t value)
uint16_t pci_config_read_short (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
void pci_config_write_short (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint16_t value)
uint8_t pci_config_read_byte (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
void pci_config_write_byte (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint16_t value)
Function Documentation
uint8_t pci_config_read_byte (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
Definition at line 54 of file pci_intel_host.c.
References pci_config_read_long().
Referenced by ata_pci_probe(), pci_enumerate_all(), pci_enumerate_bus(), and pci_enumerate_function().
uint32_t pci_config_read_long (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
driver/bus/pci_intel_host.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 01-07-2014 - Created
Definition at line 15 of file pci_intel_host.c.
References CONFIG_ADDRESS, CONFIG_DATA, CONFIG_ENABLE, i386_inl(), and i386_outl().
Referenced by ata_pci_probe(), pci_config_read_byte(), pci_config_read_short(), pci_config_write_byte(), and pci_config_write_short().
uint16_t pci_config_read_short (uint8_t bus, uint8_t device, uint8_t function, uint8_t address)
Definition at line 37 of file pci_intel_host.c.
References pci_config_read_long().
Referenced by pci_enumerate_all(), pci_enumerate_bus(), and pci_enumerate_function().
void pci_config_write_byte (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint16_t value)
Definition at line 61 of file pci_intel_host.c.
References pci_config_read_long(), and pci_config_write_long().
void pci_config_write_long (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint32_t value)
Definition at line 27 of file pci_intel_host.c.
References CONFIG_ADDRESS, CONFIG_DATA, CONFIG_ENABLE, and i386_outl().
Referenced by pci_config_write_byte(), and pci_config_write_short().
void pci_config_write_short (uint8_t bus, uint8_t device, uint8_t function, uint8_t address, uint16_t value)
Definition at line 44 of file pci_intel_host.c.
References pci_config_read_long(), and pci_config_write_long().