posnk kernel: driver/bus/pci.c File Reference
pci.c File Reference
#include "kernel/drivermgr.h"
#include "kernel/earlycon.h"
#include "driver/bus/pci.h"
#include "driver/bus/pci_list.h"
Functions
const char * pci_vendor_lookup (unsigned short vendor_id)
driver/bus/pci.c
const char * pci_device_lookup (unsigned short vendor_id, unsigned short device_id)
void pci_enumerate_all ()
void pci_enumerate_bus (uint8_t bus)
void pci_enumerate_function (uint8_t bus, uint8_t device, uint8_t function)
Function Documentation
const char* pci_device_lookup (unsigned short vendor_id, unsigned short device_id)
Definition at line 27 of file pci.c.
References _PCI_DEVTABLE::ChipDesc, PCI_DEVTABLE_LEN, and PciDevTable.
Referenced by pci_enumerate_function().
void pci_enumerate_all ()
Definition at line 37 of file pci.c.
References debugcon_printf, PCI_CONFIG_HEADER_TYPE, PCI_CONFIG_MULTIFUNCTION, pci_config_read_byte(), pci_config_read_short(), PCI_CONFIG_VENDOR_ID, and pci_enumerate_bus().
Referenced by i386_kmain().
void pci_enumerate_bus (uint8_t bus)
Definition at line 55 of file pci.c.
References PCI_CONFIG_HEADER_TYPE, PCI_CONFIG_MULTIFUNCTION, pci_config_read_byte(), pci_config_read_short(), PCI_CONFIG_VENDOR_ID, and pci_enumerate_function().
Referenced by pci_enumerate_all(), and pci_enumerate_function().
void pci_enumerate_function (uint8_t bus, uint8_t device, uint8_t function)
Definition at line 77 of file pci.c.
References debugcon_printf, DEVICE_TYPE_PCI, drivermgr_enumerate_device(), drivermgr_enumerate_interface(), PCI_CONFIG_API_ID, PCI_CONFIG_DEVICE_ID, pci_config_read_byte(), pci_config_read_short(), PCI_CONFIG_SECONDARY_BUS, PCI_CONFIG_SUBCLASS, PCI_CONFIG_VENDOR_ID, pci_device_lookup(), pci_enumerate_bus(), and pci_vendor_lookup().
Referenced by pci_enumerate_bus().
const char* pci_vendor_lookup (unsigned short vendor_id)
driver/bus/pci.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 01-07-2014 - Created
Definition at line 17 of file pci.c.
References PCI_VENTABLE_LEN, PciVenTable, and _PCI_VENTABLE::VenFull.
Referenced by pci_enumerate_function().