posnk kernel: include/kernel/permissions.h File Reference
permissions.h File Reference
#include "kernel/process.h"
Macros
#define PERM_CLASS_NONE 0
kernel/permissions.h
#define PERM_CLASS_OWNER 1
#define PERM_CLASS_GROUP 2
#define PERM_CLASS_OTHER 3
Typedefs
typedef int perm_class_t
Functions
uid_t get_uid ()
kernel/permissions.c
uid_t get_effective_uid ()
gid_t get_gid ()
gid_t get_effective_gid ()
perm_class_t get_perm_class (uid_t resource_uid, gid_t resource_gid)
Macro Definition Documentation
#define PERM_CLASS_GROUP 2
Definition at line 20 of file permissions.h.
Referenced by _sys_chown(), _sys_fchown(), get_perm_class(), and vfs_get_min_permissions().
#define PERM_CLASS_NONE 0
kernel/permissions.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 09-04-2014 - Created
Definition at line 18 of file permissions.h.
Referenced by vfs_get_min_permissions().
#define PERM_CLASS_OTHER 3
Definition at line 21 of file permissions.h.
Referenced by get_perm_class(), and vfs_get_min_permissions().
#define PERM_CLASS_OWNER 1
Definition at line 19 of file permissions.h.
Referenced by _sys_chmod(), _sys_chown(), _sys_fchmod(), _sys_fchown(), get_perm_class(), process_sig_pgrp_iterator(), sys_kill(), and vfs_get_min_permissions().
Typedef Documentation
typedef int perm_class_t
Definition at line 23 of file permissions.h.
Function Documentation
gid_t get_effective_gid ()
Definition at line 30 of file permissions.c.
References process_info::effective_gid, and scheduler_current_task.
Referenced by get_perm_class().
uid_t get_effective_uid ()
Definition at line 20 of file permissions.c.
References process_info::effective_uid, and scheduler_current_task.
Referenced by _sys_chmod(), _sys_fchmod(), get_perm_class(), and sys_stime().
gid_t get_gid ()
Definition at line 25 of file permissions.c.
References scheduler_current_task, and process_info::uid.
Referenced by get_perm_class().
perm_class_t get_perm_class (uid_t resource_uid, gid_t resource_gid)
Definition at line 35 of file permissions.c.
References get_effective_gid(), get_effective_uid(), get_gid(), get_uid(), gid, PERM_CLASS_GROUP, PERM_CLASS_OTHER, PERM_CLASS_OWNER, and uid.
Referenced by _sys_chmod(), _sys_chown(), _sys_fchmod(), _sys_fchown(), process_sig_pgrp_iterator(), sys_kill(), and vfs_have_permissions().
uid_t get_uid ()
kernel/permissions.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 09-04-2014 - Created
Definition at line 15 of file permissions.c.
References scheduler_current_task, and process_info::uid.
Referenced by get_perm_class().