posnk kernel: kernel/physmm.c File Reference
physmm.c File Reference
#include "kernel/physmm.h"
#include "kernel/heapmm.h"
Functions
void physmm_set_bit (physaddr_t address)
void physmm_clear_bit (physaddr_t address)
void physmm_free_range (physaddr_t start, physaddr_t end)
void physmm_claim_range (physaddr_t start, physaddr_t end)
physaddr_t physmm_alloc_frame ()
Allocates a physical frame.
physaddr_t physmm_count_free ()
void physmm_free_frame (physaddr_t address)
Releases a frame to be used again.
void physmm_init ()
Initializes the physical memory manager NOTE: Depends on the heap memory manager!
Variables
uint32_t physmm_bitmap [PHYSMM_BITMAP_SIZE]
kernel/physmm.c
Function Documentation
physaddr_t physmm_alloc_frame ()
Allocates a physical frame.
Todo:
: Lock physmm_bitmap
Todo:
: Release physmm_bitmap
Todo:
: Release physmm_bitmap
Definition at line 45 of file physmm.c.
References physmm_bitmap, PHYSMM_BITMAP_SIZE, physmm_clear_bit(), and PHYSMM_NO_FRAME.
Referenced by heapmm_request_core(), i386_alloc_page(), i386_init_mm(), paging_create_dir(), paging_handle_fault(), paging_map(), and procvmm_handle_fault().
void physmm_claim_range (physaddr_t start, physaddr_t end)
Definition at line 37 of file physmm.c.
References physmm_clear_bit(), and PHYSMM_PAGE_SIZE.
Referenced by i386_init_mm(), and i386_init_reserve_modules().
void physmm_clear_bit (physaddr_t address)
Definition at line 23 of file physmm.c.
References physmm_bitmap.
Referenced by physmm_alloc_frame(), and physmm_claim_range().
physaddr_t physmm_count_free ()
Todo:
: Lock physmm_bitmap
Todo:
: Release physmm_bitmap
Definition at line 67 of file physmm.c.
References physmm_bitmap, PHYSMM_BITMAP_SIZE, and PHYSMM_PAGE_SIZE.
Referenced by i386_kmain().
void physmm_free_frame (physaddr_t address)
Releases a frame to be used again.
Definition at line 84 of file physmm.c.
References physmm_set_bit().
Referenced by i386_init_load_modules(), i386_init_mm(), physmm_free_range(), procvmm_handle_fault(), and procvmm_unmmap().
void physmm_free_range (physaddr_t start, physaddr_t end)
Definition at line 29 of file physmm.c.
References physmm_free_frame(), and PHYSMM_PAGE_SIZE.
Referenced by i386_init_mm(), and i386_init_multiboot_memprobe().
void physmm_init ()
Initializes the physical memory manager NOTE: Depends on the heap memory manager!
Definition at line 89 of file physmm.c.
Referenced by i386_init_mm().
void physmm_set_bit (physaddr_t address)
Definition at line 17 of file physmm.c.
References physmm_bitmap.
Referenced by physmm_free_frame().
Variable Documentation
uint32_t physmm_bitmap[PHYSMM_BITMAP_SIZE]
kernel/physmm.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 29-03-2014 - Created
Definition at line 15 of file physmm.c.
Referenced by physmm_alloc_frame(), physmm_clear_bit(), physmm_count_free(), and physmm_set_bit().