posnk kernel: include/kernel/physmm.h File Reference
physmm.h File Reference
#include <stddef.h>
#include <stdint.h>
#include "config.h"
Macros
#define PHYSMM_BITMAP_SIZE (32768)
kernel/physmm.h
#define PHYSMM_PAGE_ADDRESS_MASK (0xFFF)
#define PHYSMM_PAGE_SIZE (4096)
#define PHYSMM_NO_FRAME (1)
Typedefs
typedef uint32_t physaddr_t
Type guaranteed to be able to contain a physical address.
Functions
void physmm_free_range (physaddr_t start, physaddr_t end)
void physmm_claim_range (physaddr_t start, physaddr_t end)
physaddr_t physmm_count_free ()
physaddr_t physmm_alloc_frame ()
Allocates a physical frame.
void physmm_free_frame (physaddr_t address)
Releases a frame to be used again.
void physmm_init ()
Initializes the physical memory manager NOTE: Depends on the heap memory manager!
Macro Definition Documentation
#define PHYSMM_BITMAP_SIZE (32768)
kernel/physmm.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 29-03-2014 - Created
Definition at line 21 of file physmm.h.
Referenced by physmm_alloc_frame(), and physmm_count_free().
#define PHYSMM_NO_FRAME (1)
Definition at line 31 of file physmm.h.
Referenced by heapmm_request_core(), paging_create_dir(), paging_handle_fault(), paging_map(), and physmm_alloc_frame().
#define PHYSMM_PAGE_ADDRESS_MASK (0xFFF)
Definition at line 22 of file physmm.h.
Referenced by elf_load(), kdbgmm_alloc_page_alligned(), kdbgmm_alloc_page_fit_iterator(), kdbgmm_alloc_page_match_iterator(), kdbgmm_alloc_page_split_iterator(), paging_handle_fault(), procvmm_check(), procvmm_handle_fault(), procvmm_mmap_anon(), procvmm_mmap_file(), and sys_sbrk().
#define PHYSMM_PAGE_SIZE (4096)
Definition at line 23 of file physmm.h.
Referenced by elf_load(), heapmm_alloc_alligned(), heapmm_alloc_internal(), heapmm_alloc_page(), heapmm_alloc_page_alligned(), heapmm_request_core(), i386_init_load_modules(), kdbgmm_alloc_page(), kdbgmm_alloc_page_alligned(), kdbgmm_alloc_page_split_iterator(), paging_create_dir(), physmm_claim_range(), physmm_count_free(), physmm_free_range(), procvmm_check(), procvmm_handle_fault(), procvmm_unmmap(), and sys_sbrk().
Typedef Documentation
typedef uint32_t physaddr_t
Type guaranteed to be able to contain a physical address.
Definition at line 28 of file physmm.h.
Function Documentation
physaddr_t physmm_alloc_frame ()
Allocates a physical frame.
Todo:
: Lock physmm_bitmap
Todo:
: Release physmm_bitmap
Todo:
: Release physmm_bitmap
Definition at line 45 of file physmm.c.
References physmm_bitmap, PHYSMM_BITMAP_SIZE, physmm_clear_bit(), and PHYSMM_NO_FRAME.
Referenced by heapmm_request_core(), i386_alloc_page(), i386_init_mm(), paging_create_dir(), paging_handle_fault(), paging_map(), and procvmm_handle_fault().
void physmm_claim_range (physaddr_t start, physaddr_t end)
Definition at line 37 of file physmm.c.
References physmm_clear_bit(), and PHYSMM_PAGE_SIZE.
Referenced by i386_init_mm(), and i386_init_reserve_modules().
physaddr_t physmm_count_free ()
Todo:
: Lock physmm_bitmap
Todo:
: Release physmm_bitmap
Definition at line 67 of file physmm.c.
References physmm_bitmap, PHYSMM_BITMAP_SIZE, and PHYSMM_PAGE_SIZE.
Referenced by i386_kmain().
void physmm_free_frame (physaddr_t address)
Releases a frame to be used again.
Definition at line 84 of file physmm.c.
References physmm_set_bit().
Referenced by i386_init_load_modules(), i386_init_mm(), physmm_free_range(), procvmm_handle_fault(), and procvmm_unmmap().
void physmm_free_range (physaddr_t start, physaddr_t end)
Definition at line 29 of file physmm.c.
References physmm_free_frame(), and PHYSMM_PAGE_SIZE.
Referenced by i386_init_mm(), and i386_init_multiboot_memprobe().
void physmm_init ()
Initializes the physical memory manager NOTE: Depends on the heap memory manager!
Definition at line 89 of file physmm.c.
Referenced by i386_init_mm().