posnk kernel: arch/i386/pic.c File Reference
pic.c File Reference
#include "arch/i386/pic.h"
#include "arch/i386/x86.h"
Functions
void i386_pic_send_command (uint8_t cmd, uint8_t picNum)
void i386_pic_send_data (uint8_t data, uint8_t picNum)
uint8_t i386_pic_read_data (uint8_t picNum)
void i386_pic_initialize ()
Initialize pic.
void i386_send_end_of_interrupt (int pic_id)
void i386_interrupt_done (int id)
Function Documentation
void i386_interrupt_done (int id)
Definition at line 74 of file pic.c.
References i386_send_end_of_interrupt().
Referenced by i386_handle_interrupt().
void i386_pic_initialize ()
Initialize pic.
Begin initialization of PIC
Send initialization control word 2. This is the base addresses of the irq's
Send initialization control word 3. This is the connection between master and slave. ICW3 for master PIC is the IR that connects to secondary pic in binary format ICW3 for secondary PIC is the IR that connects to master pic in decimal format
Send Initialization control word 4. Enables i86 mode
Definition at line 38 of file pic.c.
References I386_PIC0_IRQ_BASE, I386_PIC1_IRQ_BASE, I386_PIC_ICW1_IC4_EXPECT, I386_PIC_ICW1_INIT_YES, I386_PIC_ICW1_MASK_IC4, I386_PIC_ICW1_MASK_INIT, I386_PIC_ICW4_MASK_UPM, I386_PIC_ICW4_UPM_86MODE, i386_pic_send_command(), and i386_pic_send_data().
Referenced by i386_kmain().
uint8_t i386_pic_read_data (uint8_t picNum)
Definition at line 30 of file pic.c.
References i386_inb(), I386_PIC1_REG_DATA, and I386_PIC2_REG_DATA.
void i386_pic_send_command (uint8_t cmd, uint8_t picNum)
Definition at line 16 of file pic.c.
References i386_outb(), I386_PIC1_REG_COMMAND, and I386_PIC2_REG_COMMAND.
Referenced by i386_pic_initialize(), and i386_send_end_of_interrupt().
void i386_pic_send_data (uint8_t data, uint8_t picNum)
Definition at line 23 of file pic.c.
References i386_outb(), I386_PIC1_REG_DATA, and I386_PIC2_REG_DATA.
Referenced by i386_pic_initialize().
void i386_send_end_of_interrupt (int pic_id)
Definition at line 70 of file pic.c.
References I386_PIC_OCW2_MASK_EOI, and i386_pic_send_command().
Referenced by i386_interrupt_done().