posnk kernel: kernel/pipe.c File Reference
pipe.c File Reference
#include <sys/errno.h>
#include <sys/types.h>
#include <stddef.h>
#include <string.h>
#include <stdint.h>
#include "config.h"
#include "kernel/heapmm.h"
#include "kernel/synch.h"
#include "kernel/pipe.h"
Functions
pipe_info_t * pipe_create ()
kernel/pipe.c
int pipe_free (pipe_info_t *pipe)
void pipe_open_read (pipe_info_t *pipe)
void pipe_open_write (pipe_info_t *pipe)
void pipe_close_read (pipe_info_t *pipe)
void pipe_close_write (pipe_info_t *pipe)
int pipe_write (pipe_info_t *pipe, void *buffer, size_t count, size_t *write_count, int non_block)
int pipe_read (pipe_info_t *pipe, void *buffer, size_t count, size_t *read_count, int non_block)
Function Documentation
void pipe_close_read (pipe_info_t * pipe)
Definition at line 69 of file pipe.c.
References pipe_info::read_usage_count, semaphore_up(), and pipe_info::write_lock.
Referenced by _sys_close_int().
void pipe_close_write (pipe_info_t * pipe)
Definition at line 77 of file pipe.c.
References pipe_info::read_lock, semaphore_up(), and pipe_info::write_usage_count.
Referenced by _sys_close_int().
pipe_info_t* pipe_create ()
kernel/pipe.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 21-04-2014 - Created
Definition at line 22 of file pipe.c.
References pipe_info::buffer, CONFIG_PIPE_BUFFER_SIZE, heapmm_alloc(), heapmm_free(), NULL, pipe_info::read_lock, pipe_info::read_ptr, pipe_info::read_usage_count, semaphore_alloc(), semaphore_free(), pipe_info::write_lock, pipe_info::write_ptr, and pipe_info::write_usage_count.
Referenced by _sys_pipe2(), tty_register_driver(), and vfs_mknod().
int pipe_free (pipe_info_t * pipe)
Definition at line 48 of file pipe.c.
References pipe_info::buffer, CONFIG_PIPE_BUFFER_SIZE, EBUSY, heapmm_free(), pipe_info::read_lock, pipe_info::read_usage_count, semaphore_free(), pipe_info::write_lock, and pipe_info::write_usage_count.
Referenced by _sys_close_int(), and _sys_pipe2().
void pipe_open_read (pipe_info_t * pipe)
Definition at line 59 of file pipe.c.
References pipe_info::read_usage_count.
Referenced by _sys_open(), _sys_pipe2(), and tty_register_driver().
void pipe_open_write (pipe_info_t * pipe)
Definition at line 64 of file pipe.c.
References pipe_info::write_usage_count.
Referenced by _sys_open(), _sys_pipe2(), and tty_register_driver().
int pipe_read (pipe_info_t * pipe, void * buffer, size_t count, size_t * read_count, int non_block)
Definition at line 121 of file pipe.c.
References pipe_info::buffer, CONFIG_PIPE_BUFFER_SIZE, EAGAIN, EINTR, EPIPE, heapmm_alloc(), heapmm_free(), memcpy(), memcpy_o(), NULL, pipe_info::read_lock, pipe_info::read_ptr, semaphore_idown(), semaphore_up(), pipe_info::write_lock, pipe_info::write_ptr, and pipe_info::write_usage_count.
Referenced by _sys_read(), and tty_read().
int pipe_write (pipe_info_t * pipe, void * buffer, size_t count, size_t * write_count, int non_block)
Definition at line 85 of file pipe.c.
References pipe_info::buffer, CONFIG_PIPE_BUFFER_SIZE, EAGAIN, EINTR, EPIPE, memcpy(), pipe_info::read_lock, pipe_info::read_usage_count, semaphore_idown(), semaphore_up(), pipe_info::write_lock, and pipe_info::write_ptr.
Referenced by _sys_write(), tty_buf_out_char(), tty_flush_line_buffer(), vfs_read(), and vfs_write().