posnk kernel: include/arch/i386/pit.h File Reference
pit.h File Reference
#include <stdint.h>
Macros
#define I386_PIT_OCW_BINCOUNT_BINARY 0
#define I386_PIT_OCW_BINCOUNT_BCD 1
#define I386_PIT_OCW_MODE_TERMINALCOUNT 0
#define I386_PIT_OCW_MODE_ONESHOT 0x2
#define I386_PIT_OCW_MODE_RATEGEN 0x4
#define I386_PIT_OCW_MODE_SQUAREWAVEGEN 0x6
#define I386_PIT_OCW_MODE_SOFTWARETRIG 0x8
#define I386_PIT_OCW_MODE_HARDWARETRIG 0xA
#define I386_PIT_OCW_RL_LATCH 0
#define I386_PIT_OCW_RL_LSBONLY 0x10
#define I386_PIT_OCW_RL_MSBONLY 0x20
#define I386_PIT_OCW_RL_DATA 0x30
#define I386_PIT_OCW_COUNTER0 0
#define I386_PIT_OCW_COUNTER1 0x40
#define I386_PIT_OCW_COUNTER2 0x80
#define I386_PIT_REG_COUNTER0 0x40
#define I386_PIT_REG_COUNTER1 0x41
#define I386_PIT_REG_COUNTER2 0x42
#define I386_PIT_REG_COMMAND 0x43
Functions
void i386_pit_setup (uint32_t freq, int counter, uint8_t mode)
Macro Definition Documentation
#define I386_PIT_OCW_BINCOUNT_BCD 1
Definition at line 21 of file pit.h.
#define I386_PIT_OCW_BINCOUNT_BINARY 0
Definition at line 20 of file pit.h.
#define I386_PIT_OCW_COUNTER0 0
Definition at line 32 of file pit.h.
#define I386_PIT_OCW_COUNTER1 0x40
Definition at line 33 of file pit.h.
#define I386_PIT_OCW_COUNTER2 0x80
Definition at line 34 of file pit.h.
#define I386_PIT_OCW_MODE_HARDWARETRIG 0xA
Definition at line 27 of file pit.h.
#define I386_PIT_OCW_MODE_ONESHOT 0x2
Definition at line 23 of file pit.h.
#define I386_PIT_OCW_MODE_RATEGEN 0x4
Definition at line 24 of file pit.h.
#define I386_PIT_OCW_MODE_SOFTWARETRIG 0x8
Definition at line 26 of file pit.h.
#define I386_PIT_OCW_MODE_SQUAREWAVEGEN 0x6
Definition at line 25 of file pit.h.
#define I386_PIT_OCW_MODE_TERMINALCOUNT 0
Definition at line 22 of file pit.h.
#define I386_PIT_OCW_RL_DATA 0x30
Definition at line 31 of file pit.h.
Referenced by i386_pit_setup().
#define I386_PIT_OCW_RL_LATCH 0
Definition at line 28 of file pit.h.
#define I386_PIT_OCW_RL_LSBONLY 0x10
Definition at line 29 of file pit.h.
#define I386_PIT_OCW_RL_MSBONLY 0x20
Definition at line 30 of file pit.h.
#define I386_PIT_REG_COMMAND 0x43
Definition at line 38 of file pit.h.
#define I386_PIT_REG_COUNTER0 0x40
Definition at line 35 of file pit.h.
#define I386_PIT_REG_COUNTER1 0x41
Definition at line 36 of file pit.h.
#define I386_PIT_REG_COUNTER2 0x42
Definition at line 37 of file pit.h.
Function Documentation
void i386_pit_setup (uint32_t freq, int counter, uint8_t mode)
set frequency rate
Definition at line 29 of file pit.c.
References i386_pit_ocw_ctrs, I386_PIT_OCW_RL_DATA, i386_pit_send_command(), i386_pit_send_data(), timer_freq, and timer_mfreq.
Referenced by i386_kmain().