posnk kernel: arch/i386/pit.c File Reference
pit.c File Reference
#include "arch/i386/pit.h"
#include "arch/i386/x86.h"
#include "kernel/time.h"
Functions
void i386_pit_send_command (uint8_t cmd)
void i386_pit_send_data (uint8_t counter, uint8_t data)
void i386_pit_setup (uint32_t freq, int counter, uint8_t mode)
Variables
uint8_t i386_pit_data_ports [] = {I386_PIT_REG_COUNTER0, I386_PIT_REG_COUNTER1, I386_PIT_REG_COUNTER2}
uint8_t i386_pit_ocw_ctrs [] = {I386_PIT_OCW_COUNTER0, I386_PIT_OCW_COUNTER1, I386_PIT_OCW_COUNTER2}
Function Documentation
void i386_pit_send_command (uint8_t cmd)
Definition at line 21 of file pit.c.
References i386_outb(), and I386_PIT_REG_COMMAND.
Referenced by i386_pit_setup().
void i386_pit_send_data (uint8_t counter, uint8_t data)
Definition at line 25 of file pit.c.
References i386_outb(), and i386_pit_data_ports.
Referenced by i386_pit_setup().
void i386_pit_setup (uint32_t freq, int counter, uint8_t mode)
set frequency rate
Definition at line 29 of file pit.c.
References i386_pit_ocw_ctrs, I386_PIT_OCW_RL_DATA, i386_pit_send_command(), i386_pit_send_data(), timer_freq, and timer_mfreq.
Referenced by i386_kmain().
Variable Documentation
uint8_t i386_pit_data_ports[] = {I386_PIT_REG_COUNTER0, I386_PIT_REG_COUNTER1, I386_PIT_REG_COUNTER2}
Definition at line 18 of file pit.c.
Referenced by i386_pit_send_data().
uint8_t i386_pit_ocw_ctrs[] = {I386_PIT_OCW_COUNTER0, I386_PIT_OCW_COUNTER1, I386_PIT_OCW_COUNTER2}
Definition at line 19 of file pit.c.
Referenced by i386_pit_setup().