posnk kernel: include/kernel/process.h File Reference
process.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
#include "kernel/paging.h"
#include "kernel/synch.h"
#include "kernel/time.h"
#include "kernel/vfs.h"
#include "util/llist.h"
Data Structures
struct process_mmap
struct process_child_event
struct process_info
Macros
#define PROCESS_RUNNING 0
kernel/process.h
#define PROCESS_WAITING 1
#define PROCESS_READY 2
#define PROCESS_NO_SCHED 3
#define PROCESS_KILLED 4
#define PROCESS_INTERRUPTED 5
#define SIGNAL_ACTION_ABORT 0
#define SIGNAL_ACTION_TERM 1
#define SIGNAL_ACTION_CONT 2
#define SIGNAL_ACTION_IGNORE 3
#define SIGNAL_ACTION_STOP 4
#define PROCESS_TERM_EXIT 0
#define PROCESS_TERM_SIGNAL 1
#define PROCESS_CHILD_KILLED 0
#define PROCESS_CHILD_STOPPED 1
#define PROCESS_CHILD_CONTD 2
#define PROCESS_MMAP_FLAG_WRITE (1<<1)
#define PROCESS_MMAP_FLAG_FILE (1<<2)
#define PROCESS_MMAP_FLAG_PUBLIC (1<<3)
#define PROCESS_MMAP_FLAG_STACK (1<<4)
#define PROCESS_MMAP_FLAG_HEAP (1<<5)
Typedefs
typedef struct process_info process_info_t
typedef struct process_mmap process_mmap_t
typedef struct process_child_event process_child_event_t
Functions
process_info_t * process_get (pid_t pid)
int process_push_user_data (void *data, size_t size)
void process_send_signal (process_info_t *process, int signal)
void process_set_signal_mask (process_info_t *process, int mask)
int process_was_interrupted (process_info_t *process)
void process_handle_signals ()
void process_reap (process_info_t *)
process_child_event_t * process_get_event (pid_t pid)
process_child_event_t * process_get_event_pg (pid_t pid)
void process_absorb_event (process_child_event_t *ev_info)
void process_child_event (process_info_t *process, int event)
int process_signal_pgroup (pid_t pid, int signal)
process_mmap_t * procvmm_get_memory_region (void *address)
int procvmm_copy_memory_map (llist_t *target)
int procvmm_resize_map (void *start, size_t newsize)
int procvmm_mmap_anon (void *start, size_t size, int flags, char *name)
int procvmm_mmap_file (void *start, size_t size, inode_t *file, off_t offset, off_t file_sz, int flags, char *name)
void procvmm_unmmap (process_mmap_t *region)
int procvmm_handle_fault (void *address)
int procvmm_do_exec_mmaps ()
void procvmm_clear_mmaps ()
kernel/procvmm.c
int procvmm_check (void *dest, size_t size)
void process_user_call (void *entry, void *stack)
int process_exec (char *path, char **args, char **envs)
Macro Definition Documentation
#define PROCESS_CHILD_CONTD 2
Definition at line 43 of file process.h.
Referenced by sys_waitpid().
#define PROCESS_CHILD_KILLED 0
Definition at line 41 of file process.h.
Referenced by process_handle_signals(), sys_exit(), and sys_waitpid().
#define PROCESS_CHILD_STOPPED 1
Definition at line 42 of file process.h.
Referenced by sys_waitpid().
#define PROCESS_INTERRUPTED 5
Definition at line 30 of file process.h.
Referenced by process_handle_signals(), scheduler_next_task_iterator(), scheduler_wait_micros(), scheduler_wait_time(), semaphore_down(), and semaphore_idown().
#define PROCESS_KILLED 4
Definition at line 29 of file process.h.
Referenced by process_handle_signals(), process_signal_handler_default(), schedule(), and sys_exit().
#define PROCESS_MMAP_FLAG_FILE (1<<2)
Definition at line 46 of file process.h.
Referenced by procvmm_handle_fault(), procvmm_mmap_anon(), procvmm_mmap_copy_iterator(), procvmm_mmap_file(), and procvmm_unmmap().
#define PROCESS_MMAP_FLAG_HEAP (1<<5)
Definition at line 49 of file process.h.
Referenced by sys_sbrk().
#define PROCESS_MMAP_FLAG_PUBLIC (1<<3)
Definition at line 47 of file process.h.
Referenced by paging_create_dir().
#define PROCESS_MMAP_FLAG_STACK (1<<4)
Definition at line 48 of file process.h.
Referenced by procvmm_do_exec_mmaps().
#define PROCESS_MMAP_FLAG_WRITE (1<<1)
Definition at line 45 of file process.h.
Referenced by elf_load(), process_exec(), procvmm_do_exec_mmaps(), procvmm_handle_fault(), and sys_sbrk().
#define PROCESS_NO_SCHED 3
Definition at line 28 of file process.h.
Referenced by scheduler_set_as_idle().
#define PROCESS_READY 2
Definition at line 27 of file process.h.
Referenced by schedule(), scheduler_fork(), scheduler_init(), and scheduler_next_task_iterator().
#define PROCESS_RUNNING 0
kernel/process.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 07-04-2014 - Created
Definition at line 25 of file process.h.
Referenced by process_signal_handler_default(), schedule(), scheduler_wait_micros(), scheduler_wait_time(), semaphore_down(), and semaphore_idown().
#define PROCESS_TERM_EXIT 0
Definition at line 38 of file process.h.
Referenced by sys_waitpid().
#define PROCESS_TERM_SIGNAL 1
Definition at line 39 of file process.h.
Referenced by process_signal_handler_default(), and sys_waitpid().
#define PROCESS_WAITING 1
Definition at line 26 of file process.h.
Referenced by process_signal_handler_default(), scheduler_next_task_iterator(), scheduler_wait_micros(), scheduler_wait_on(), and scheduler_wait_time().
#define SIGNAL_ACTION_ABORT 0
Definition at line 32 of file process.h.
Referenced by process_signal_handler_default().
#define SIGNAL_ACTION_CONT 2
Definition at line 34 of file process.h.
Referenced by process_signal_handler_default().
#define SIGNAL_ACTION_IGNORE 3
Definition at line 35 of file process.h.
Referenced by process_signal_handler_default().
#define SIGNAL_ACTION_STOP 4
Definition at line 36 of file process.h.
Referenced by process_signal_handler_default().
#define SIGNAL_ACTION_TERM 1
Definition at line 33 of file process.h.
Referenced by process_signal_handler_default().
Typedef Documentation
typedef struct process_child_event process_child_event_t
Definition at line 139 of file process.h.
typedef struct process_info process_info_t
Definition at line 135 of file process.h.
typedef struct process_mmap process_mmap_t
Definition at line 137 of file process.h.
Function Documentation
void process_absorb_event (process_child_event_t * ev_info)
Definition at line 131 of file process.c.
References heapmm_free(), and llist_unlink().
Referenced by sys_waitpid().
void process_child_event (process_info_t * process, int event)
Todo:
: Handle this shit...
Definition at line 137 of file process.c.
References process_info::child_events, process_child_event::child_pgid, process_child_event::child_pid, process_info::child_sema, debugcon_printf, process_child_event::event, heapmm_alloc(), llist_add_end(), NULL, process_info::parent_pid, process_info::pgid, process_info::pid, process_get(), and semaphore_up().
Referenced by process_handle_signals(), and sys_exit().
int process_exec (char * path, char ** args, char ** envs)
Todo:
: Verify arg and env list sizes
Definition at line 268 of file process.c.
References debugcon_printf, elf_load(), process_info::entry_point, memset(), PROCESS_MMAP_FLAG_WRITE, process_send_signal(), process_user_call(), procvmm_clear_mmaps(), procvmm_do_exec_mmaps(), procvmm_mmap_anon(), scheduler_current_task, process_info::signal_handler_table, process_info::signal_mask_bitmap, SIGSYS, process_info::stack_bottom, strcpy(), stream_do_close_on_exec(), strlen(), and strlistlen().
Referenced by i386_init_stub(), and sys_execve().
process_info_t* process_get (pid_t pid)
Definition at line 218 of file process.c.
References llist_iterate_select(), and process_find_iterator().
Referenced by process_child_event(), sys_kill(), sys_setpgid(), and sys_waitpid().
process_child_event_t* process_get_event (pid_t pid)
Definition at line 112 of file process.c.
References process_info::child_events, llist_iterate_select(), process_find_event_iterator(), and scheduler_current_task.
Referenced by sys_waitpid().
process_child_event_t* process_get_event_pg (pid_t pid)
Definition at line 126 of file process.c.
References process_info::child_events, llist_iterate_select(), process_find_event_pg_iterator(), and scheduler_current_task.
Referenced by sys_waitpid().
void process_handle_signals ()
Definition at line 161 of file process.c.
References debugcon_printf, NULL, process_info::pid, process_child_event(), PROCESS_CHILD_KILLED, PROCESS_INTERRUPTED, PROCESS_KILLED, process_signal_handler_default(), procvmm_clear_mmaps(), schedule(), scheduler_current_task, scheduler_invoke_signal_handler(), process_info::signal_handler_table, process_info::signal_mask_bitmap, process_info::state, and process_info::waiting_signal_bitmap.
Referenced by scheduler_switch_task(), and syscall_dispatch().
int process_push_user_data (void * data, size_t size)
Definition at line 56 of file task_switch.c.
References process_info::arch_state, memcpy(), procvmm_check(), and scheduler_current_task.
Referenced by scheduler_invoke_signal_handler().
void process_reap (process_info_t *)
Todo:
: Implement
Todo:
: Free arch-state
Todo:
: Free page-dir
Definition at line 193 of file process.c.
References process_info::child_sema, CONFIG_PROCESS_MAX_NAME_LENGTH, process_info::current_directory, heapmm_free(), llist_unlink(), process_info::name, process_info::root_directory, semaphore_free(), stream_do_close_all(), and vfs_dir_cache_release().
Referenced by sys_waitpid().
void process_send_signal (process_info_t * process, int signal)
Definition at line 63 of file process.c.
References debugcon_printf, process_info::pid, schedule(), scheduler_current_task, and process_info::waiting_signal_bitmap.
Referenced by _sys_read(), _sys_write(), exception_handle(), process_exec(), process_sig_pgrp_iterator(), sys_kill(), and syscall_dispatch().
void process_set_signal_mask (process_info_t * process, int mask)
Definition at line 73 of file process.c.
References CONFIG_MASKABLE_SIGNAL_BITMAP, and process_info::signal_mask_bitmap.
int process_signal_pgroup (pid_t pid, int signal)
Definition at line 249 of file process.c.
References debugcon_printf, sig_pgrp_param::group, llist_iterate_select(), process_sig_pgrp_iterator(), process_signal_pgroup_numdone, and sig_pgrp_param::signal.
Referenced by sys_kill(), tty_input_char(), and tty_ioctl().
void process_user_call (void * entry, void * stack)
Definition at line 32 of file protection.c.
References i386_protection_user_call().
Referenced by process_exec().
int process_was_interrupted (process_info_t * process)
Definition at line 155 of file process.c.
References process_info::signal_mask_bitmap, and process_info::waiting_signal_bitmap.
Referenced by scheduler_next_task_iterator().
int procvmm_check (void * dest, size_t size)
Definition at line 41 of file procvmm.c.
References PHYSMM_PAGE_ADDRESS_MASK, PHYSMM_PAGE_SIZE, process_info::pid, procvmm_get_memory_region(), and scheduler_current_task.
Referenced by copy_kern_to_user(), copy_user_to_kern(), and process_push_user_data().
void procvmm_clear_mmaps ()
kernel/procvmm.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 23-04-2014 - Created
Definition at line 21 of file procvmm.c.
References llist_get_last(), process_info::memory_map, procvmm_unmmap(), and scheduler_current_task.
Referenced by process_exec(), process_handle_signals(), and sys_exit().
int procvmm_copy_memory_map (llist_t * target)
Definition at line 93 of file procvmm.c.
References llist_iterate_select(), process_info::memory_map, NULL, procvmm_mmap_copy_iterator(), and scheduler_current_task.
Referenced by scheduler_fork().
int procvmm_do_exec_mmaps ()
Todo:
: Implement dynamic stack size
Definition at line 30 of file procvmm.c.
References process_info::heap_end, process_info::heap_max, process_info::heap_start, process_info::image_end, PROCESS_MMAP_FLAG_STACK, PROCESS_MMAP_FLAG_WRITE, procvmm_mmap_anon(), scheduler_current_task, process_info::stack_bottom, and process_info::stack_top.
Referenced by process_exec().
process_mmap_t* procvmm_get_memory_region (void * address)
Definition at line 63 of file procvmm.c.
References llist_iterate_select(), process_info::memory_map, procvmm_get_mmap_iterator(), and scheduler_current_task.
Referenced by paging_create_dir(), procvmm_check(), procvmm_handle_fault(), procvmm_mmap_anon(), procvmm_mmap_file(), and procvmm_resize_map().
int procvmm_handle_fault (void * address)
Todo:
: Implement public mappings
Definition at line 224 of file procvmm.c.
References process_mmap::file, process_mmap::file_sz, process_mmap::flags, memset(), process_mmap::offset, paging_map(), PAGING_PAGE_FLAG_RW, PAGING_PAGE_FLAG_USER, paging_unmap(), physmm_alloc_frame(), physmm_free_frame(), PHYSMM_PAGE_ADDRESS_MASK, PHYSMM_PAGE_SIZE, PROCESS_MMAP_FLAG_FILE, PROCESS_MMAP_FLAG_WRITE, procvmm_get_memory_region(), process_mmap::start, and vfs_read().
Referenced by paging_handle_fault().
int procvmm_mmap_anon (void * start, size_t size, int flags, char * name)
Definition at line 134 of file procvmm.c.
References EINVAL, ENOMEM, process_mmap::flags, heapmm_alloc(), heapmm_free(), llist_add_end(), llist_iterate_select(), process_info::memory_map, process_mmap::name, NULL, PHYSMM_PAGE_ADDRESS_MASK, PROCESS_MMAP_FLAG_FILE, procvmm_collcheck_iterator(), procvmm_get_memory_region(), scheduler_current_task, process_mmap::size, process_mmap::start, strcpy(), and strlen().
Referenced by process_exec(), procvmm_do_exec_mmaps(), and sys_sbrk().
int procvmm_mmap_file (void * start, size_t size, inode_t * file, off_t offset, off_t file_sz, int flags, char * name)
Definition at line 164 of file procvmm.c.
References EINVAL, ENOMEM, process_mmap::file, process_mmap::file_sz, process_mmap::flags, heapmm_alloc(), heapmm_free(), llist_add_end(), llist_iterate_select(), process_info::memory_map, process_mmap::name, inode::name, NULL, process_mmap::offset, PHYSMM_PAGE_ADDRESS_MASK, PROCESS_MMAP_FLAG_FILE, procvmm_collcheck_iterator(), procvmm_get_memory_region(), scheduler_current_task, process_mmap::size, inode::size, process_mmap::start, strcpy(), strlen(), and inode::usage_count.
Referenced by elf_load().
int procvmm_resize_map (void * start, size_t newsize)
Definition at line 119 of file procvmm.c.
References EINVAL, llist_iterate_select(), process_info::memory_map, procvmm_collcheck_iterator(), procvmm_get_memory_region(), scheduler_current_task, and process_mmap::size.
Referenced by sys_sbrk().
void procvmm_unmmap (process_mmap_t * region)
Definition at line 204 of file procvmm.c.
References process_mmap::file, process_mmap::flags, heapmm_free(), llist_unlink(), process_mmap::name, paging_get_physical_address(), paging_unmap(), physmm_free_frame(), PHYSMM_PAGE_SIZE, PROCESS_MMAP_FLAG_FILE, process_mmap::size, process_mmap::start, strlen(), and inode::usage_count.
Referenced by procvmm_clear_mmaps().