posnk kernel: kernel/process.c File Reference
process.c File Reference
#include <string.h>
#include <stddef.h>
#include <sys/errno.h>
#include "kernel/process.h"
#include "kernel/synch.h"
#include "kernel/scheduler.h"
#include "kernel/syscall.h"
#include "kernel/paging.h"
#include "kernel/permissions.h"
#include "kernel/earlycon.h"
#include "kernel/streams.h"
#include "kernel/elfloader.h"
#include "kernel/signals.h"
#include "kernel/heapmm.h"
#include "config.h"
Data Structures
struct sig_pgrp_param
Typedefs
typedef struct sig_pgrp_param sig_pgrp_param_t
Functions
void process_send_signal (process_info_t *process, int signal)
void process_set_signal_mask (process_info_t *process, int mask)
void process_signal_handler_default (int signal)
int process_find_event_iterator (llist_t *node, void *param)
Iterator function that looks up eventwith the given child pid.
process_child_event_t * process_get_event (pid_t pid)
int process_find_event_pg_iterator (llist_t *node, void *param)
Iterator function that looks up eventwith the given child pid.
process_child_event_t * process_get_event_pg (pid_t pid)
void process_absorb_event (process_child_event_t *ev_info)
void process_child_event (process_info_t *process, int event)
int process_was_interrupted (process_info_t *process)
void process_handle_signals ()
void process_reap (process_info_t *process)
int process_find_iterator (llist_t *node, void *param)
Iterator function that looks up process with the given pid.
process_info_t * process_get (pid_t pid)
int process_sig_pgrp_iterator (llist_t *node, void *param)
Iterator function that signals up processes with the given pgid.
int process_signal_pgroup (pid_t pid, int signal)
int strlistlen (char **list)
int process_exec (char *path, char **args, char **envs)
Variables
int signal_default_actions []
kernel/process.c
llist_t * scheduler_task_list
uint32_t process_signal_pgroup_numdone = 0
Typedef Documentation
typedef struct sig_pgrp_param sig_pgrp_param_t
Function Documentation
void process_absorb_event (process_child_event_t * ev_info)
Definition at line 131 of file process.c.
References heapmm_free(), and llist_unlink().
Referenced by sys_waitpid().
void process_child_event (process_info_t * process, int event)
Todo:
: Handle this shit...
Definition at line 137 of file process.c.
References process_info::child_events, process_child_event::child_pgid, process_child_event::child_pid, process_info::child_sema, debugcon_printf, process_child_event::event, heapmm_alloc(), llist_add_end(), NULL, process_info::parent_pid, process_info::pgid, process_info::pid, process_get(), and semaphore_up().
Referenced by process_handle_signals(), and sys_exit().
int process_exec (char * path, char ** args, char ** envs)
Todo:
: Verify arg and env list sizes
Definition at line 268 of file process.c.
References debugcon_printf, elf_load(), process_info::entry_point, memset(), PROCESS_MMAP_FLAG_WRITE, process_send_signal(), process_user_call(), procvmm_clear_mmaps(), procvmm_do_exec_mmaps(), procvmm_mmap_anon(), scheduler_current_task, process_info::signal_handler_table, process_info::signal_mask_bitmap, SIGSYS, process_info::stack_bottom, strcpy(), stream_do_close_on_exec(), strlen(), and strlistlen().
Referenced by i386_init_stub(), and sys_execve().
int process_find_event_iterator (llist_t * node, void * param)
Iterator function that looks up eventwith the given child pid.
Definition at line 106 of file process.c.
References process_child_event::child_pid.
Referenced by process_get_event().
int process_find_event_pg_iterator (llist_t * node, void * param)
Iterator function that looks up eventwith the given child pid.
Definition at line 120 of file process.c.
References process_child_event::child_pgid.
Referenced by process_get_event_pg().
int process_find_iterator (llist_t * node, void * param)
Iterator function that looks up process with the given pid.
Definition at line 212 of file process.c.
References process_info::pid.
Referenced by process_get().
process_info_t* process_get (pid_t pid)
Definition at line 218 of file process.c.
References llist_iterate_select(), and process_find_iterator().
Referenced by process_child_event(), sys_kill(), sys_setpgid(), and sys_waitpid().
process_child_event_t* process_get_event (pid_t pid)
Definition at line 112 of file process.c.
References process_info::child_events, llist_iterate_select(), process_find_event_iterator(), and scheduler_current_task.
Referenced by sys_waitpid().
process_child_event_t* process_get_event_pg (pid_t pid)
Definition at line 126 of file process.c.
References process_info::child_events, llist_iterate_select(), process_find_event_pg_iterator(), and scheduler_current_task.
Referenced by sys_waitpid().
void process_handle_signals ()
Definition at line 161 of file process.c.
References debugcon_printf, NULL, process_info::pid, process_child_event(), PROCESS_CHILD_KILLED, PROCESS_INTERRUPTED, PROCESS_KILLED, process_signal_handler_default(), procvmm_clear_mmaps(), schedule(), scheduler_current_task, scheduler_invoke_signal_handler(), process_info::signal_handler_table, process_info::signal_mask_bitmap, process_info::state, and process_info::waiting_signal_bitmap.
Referenced by scheduler_switch_task(), and syscall_dispatch().
void process_reap (process_info_t * process)
Todo:
: Implement
Todo:
: Free arch-state
Todo:
: Free page-dir
Definition at line 193 of file process.c.
References process_info::child_sema, CONFIG_PROCESS_MAX_NAME_LENGTH, process_info::current_directory, heapmm_free(), llist_unlink(), process_info::name, process_info::root_directory, semaphore_free(), stream_do_close_all(), and dir_cache::usage_count.
Referenced by sys_waitpid().
void process_send_signal (process_info_t * process, int signal)
Definition at line 63 of file process.c.
References debugcon_printf, process_info::pid, schedule(), scheduler_current_task, and process_info::waiting_signal_bitmap.
Referenced by _sys_read(), _sys_write(), exception_handle(), process_exec(), process_sig_pgrp_iterator(), sys_kill(), and syscall_dispatch().
void process_set_signal_mask (process_info_t * process, int mask)
Definition at line 73 of file process.c.
References CONFIG_MASKABLE_SIGNAL_BITMAP, and process_info::signal_mask_bitmap.
int process_sig_pgrp_iterator (llist_t * node, void * param)
Iterator function that signals up processes with the given pgid.
Definition at line 233 of file process.c.
References EPERM, get_perm_class(), process_info::gid, sig_pgrp_param::group, PERM_CLASS_OWNER, process_info::pgid, process_info::pid, process_send_signal(), process_signal_pgroup_numdone, sig_pgrp_param::signal, syscall_errno, and process_info::uid.
Referenced by process_signal_pgroup().
void process_signal_handler_default (int signal)
Definition at line 78 of file process.c.
References process_info::last_signal, NULL, PROCESS_KILLED, PROCESS_RUNNING, PROCESS_TERM_SIGNAL, PROCESS_WAITING, scheduler_current_task, SIGNAL_ACTION_ABORT, SIGNAL_ACTION_CONT, SIGNAL_ACTION_IGNORE, SIGNAL_ACTION_STOP, SIGNAL_ACTION_TERM, signal_default_actions, process_info::state, process_info::term_cause, and process_info::waiting_on.
Referenced by process_handle_signals().
int process_signal_pgroup (pid_t pid, int signal)
Definition at line 249 of file process.c.
References debugcon_printf, sig_pgrp_param::group, llist_iterate_select(), process_sig_pgrp_iterator(), process_signal_pgroup_numdone, and sig_pgrp_param::signal.
Referenced by sys_kill(), tty_input_char(), and tty_ioctl().
int process_was_interrupted (process_info_t * process)
Definition at line 155 of file process.c.
References process_info::signal_mask_bitmap, and process_info::waiting_signal_bitmap.
Referenced by scheduler_next_task_iterator().
int strlistlen (char ** list)
Definition at line 260 of file process.c.
Referenced by process_exec(), and sys_execve().
Variable Documentation
uint32_t process_signal_pgroup_numdone = 0
Definition at line 228 of file process.c.
Referenced by process_sig_pgrp_iterator(), and process_signal_pgroup().
llist_t* scheduler_task_list
Definition at line 25 of file scheduler.c.
int signal_default_actions[]
kernel/process.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 07-04-2014 - Created
Definition at line 27 of file process.c.
Referenced by process_signal_handler_default().