posnk kernel: kernel/procvmm.c File Reference
procvmm.c File Reference
#include "kernel/process.h"
#include "kernel/scheduler.h"
#include "kernel/paging.h"
#include "kernel/heapmm.h"
#include "kernel/physmm.h"
#include "kernel/earlycon.h"
#include <string.h>
#include <sys/errno.h>
Functions
void procvmm_clear_mmaps ()
kernel/procvmm.c
int procvmm_do_exec_mmaps ()
int procvmm_check (void *dest, size_t size)
int procvmm_get_mmap_iterator (llist_t *node, void *param)
Iterator function that finds the mmap for the given address.
process_mmap_t * procvmm_get_memory_region (void *address)
int procvmm_mmap_copy_iterator (llist_t *node, void *param)
int procvmm_copy_memory_map (llist_t *target)
int procvmm_collcheck_iterator (llist_t *node, void *param)
Iterator function that finds the mmap for the given address.
int procvmm_resize_map (void *start, size_t newsize)
int procvmm_mmap_anon (void *start, size_t size, int flags, char *name)
int procvmm_mmap_file (void *start, size_t size, inode_t *file, off_t offset, off_t file_sz, int flags, char *name)
void procvmm_unmmap (process_mmap_t *region)
int procvmm_handle_fault (void *address)
Function Documentation
int procvmm_check (void * dest, size_t size)
Definition at line 41 of file procvmm.c.
References PHYSMM_PAGE_ADDRESS_MASK, PHYSMM_PAGE_SIZE, process_info::pid, procvmm_get_memory_region(), and scheduler_current_task.
Referenced by copy_kern_to_user(), copy_user_to_kern(), and process_push_user_data().
void procvmm_clear_mmaps ()
kernel/procvmm.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 23-04-2014 - Created
Definition at line 21 of file procvmm.c.
References llist_get_last(), process_info::memory_map, procvmm_unmmap(), and scheduler_current_task.
Referenced by process_exec(), process_handle_signals(), and sys_exit().
int procvmm_collcheck_iterator (llist_t * node, void * param)
Iterator function that finds the mmap for the given address.
Definition at line 105 of file procvmm.c.
References process_mmap::size, and process_mmap::start.
Referenced by procvmm_mmap_anon(), procvmm_mmap_file(), and procvmm_resize_map().
int procvmm_copy_memory_map (llist_t * target)
Definition at line 93 of file procvmm.c.
References llist_iterate_select(), process_info::memory_map, NULL, procvmm_mmap_copy_iterator(), and scheduler_current_task.
Referenced by scheduler_fork().
int procvmm_do_exec_mmaps ()
Todo:
: Implement dynamic stack size
Definition at line 30 of file procvmm.c.
References process_info::heap_end, process_info::heap_max, process_info::heap_start, process_info::image_end, PROCESS_MMAP_FLAG_STACK, PROCESS_MMAP_FLAG_WRITE, procvmm_mmap_anon(), scheduler_current_task, process_info::stack_bottom, and process_info::stack_top.
Referenced by process_exec().
process_mmap_t* procvmm_get_memory_region (void * address)
Definition at line 63 of file procvmm.c.
References llist_iterate_select(), process_info::memory_map, procvmm_get_mmap_iterator(), and scheduler_current_task.
Referenced by paging_create_dir(), procvmm_check(), procvmm_handle_fault(), procvmm_mmap_anon(), procvmm_mmap_file(), and procvmm_resize_map().
int procvmm_get_mmap_iterator (llist_t * node, void * param)
Iterator function that finds the mmap for the given address.
Definition at line 54 of file procvmm.c.
References process_mmap::size, and process_mmap::start.
Referenced by procvmm_get_memory_region().
int procvmm_handle_fault (void * address)
Todo:
: Implement public mappings
Definition at line 224 of file procvmm.c.
References process_mmap::file, process_mmap::file_sz, process_mmap::flags, memset(), process_mmap::offset, paging_map(), PAGING_PAGE_FLAG_RW, PAGING_PAGE_FLAG_USER, paging_unmap(), physmm_alloc_frame(), physmm_free_frame(), PHYSMM_PAGE_ADDRESS_MASK, PHYSMM_PAGE_SIZE, PROCESS_MMAP_FLAG_FILE, PROCESS_MMAP_FLAG_WRITE, procvmm_get_memory_region(), process_mmap::start, and vfs_read().
Referenced by paging_handle_fault().
int procvmm_mmap_anon (void * start, size_t size, int flags, char * name)
Definition at line 134 of file procvmm.c.
References EINVAL, ENOMEM, process_mmap::flags, heapmm_alloc(), heapmm_free(), llist_add_end(), llist_iterate_select(), process_info::memory_map, process_mmap::name, NULL, PHYSMM_PAGE_ADDRESS_MASK, PROCESS_MMAP_FLAG_FILE, procvmm_collcheck_iterator(), procvmm_get_memory_region(), scheduler_current_task, process_mmap::size, process_mmap::start, strcpy(), and strlen().
Referenced by process_exec(), procvmm_do_exec_mmaps(), and sys_sbrk().
int procvmm_mmap_copy_iterator (llist_t * node, void * param)
Definition at line 70 of file procvmm.c.
References process_mmap::file, process_mmap::file_sz, process_mmap::flags, heapmm_alloc(), llist_add_end(), process_mmap::name, process_mmap::offset, PROCESS_MMAP_FLAG_FILE, process_mmap::size, process_mmap::start, strcpy(), strlen(), and inode::usage_count.
Referenced by procvmm_copy_memory_map().
int procvmm_mmap_file (void * start, size_t size, inode_t * file, off_t offset, off_t file_sz, int flags, char * name)
Definition at line 164 of file procvmm.c.
References EINVAL, ENOMEM, process_mmap::file, process_mmap::file_sz, process_mmap::flags, heapmm_alloc(), heapmm_free(), llist_add_end(), llist_iterate_select(), process_info::memory_map, process_mmap::name, inode::name, NULL, process_mmap::offset, PHYSMM_PAGE_ADDRESS_MASK, PROCESS_MMAP_FLAG_FILE, procvmm_collcheck_iterator(), procvmm_get_memory_region(), scheduler_current_task, process_mmap::size, inode::size, process_mmap::start, strcpy(), strlen(), and inode::usage_count.
Referenced by elf_load().
int procvmm_resize_map (void * start, size_t newsize)
Definition at line 119 of file procvmm.c.
References EINVAL, llist_iterate_select(), process_info::memory_map, procvmm_collcheck_iterator(), procvmm_get_memory_region(), scheduler_current_task, and process_mmap::size.
Referenced by sys_sbrk().
void procvmm_unmmap (process_mmap_t * region)
Definition at line 204 of file procvmm.c.
References process_mmap::file, process_mmap::flags, heapmm_free(), llist_unlink(), process_mmap::name, paging_get_physical_address(), paging_unmap(), physmm_free_frame(), PHYSMM_PAGE_SIZE, PROCESS_MMAP_FLAG_FILE, process_mmap::size, process_mmap::start, strlen(), and inode::usage_count.
Referenced by procvmm_clear_mmaps().