posnk kernel: include/arch/i386/protection.h File Reference
protection.h File Reference
#include <stdint.h>
Data Structures
struct i386_gdt_descriptor
struct i386_gdtr
struct i386_tss_entry
Macros
#define I386_GDT_ACCESSED_BIT 1<<0
#define I386_GDT_READABLE_BIT 1<<1
#define I386_GDT_WRITABLE_BIT 1<<1
#define I386_GDT_CONFORMING_BIT 1<<2
#define I386_GDT_GROW_DIRECTION_BIT 1<<2
#define I386_GDT_EXECUTABLE_BIT 1<<3
#define I386_GDT_NON_SYSTEM_BIT 1<<4
#define I386_GDT_SUPERVISOR_MASK 0<<5
#define I386_GDT_DRIVER_0_MASK 1<<5
#define I386_GDT_DRIVER_1_MASK 2<<5
#define I386_GDT_USERMODE_MASK 3<<5
#define I386_GDT_PRESENT_BIT 1<<7
#define I386_GDT_OS_DEFINED_BIT 1<<4
#define I386_GDT_RESERVED_BIT 1<<5
#define I386_GDT_32_BIT_SEGMENT 1<<6
#define I386_GDT_GRANULARITY_4K_BIT 1<<7
#define I386_GDT_LIMIT_HIGH_MASK 0x0F
#define I386_GDT_LIMIT_HIGH_SHIFT 0x10
#define I386_GDT_LIMIT_LOW_MASK 0xFFFF
#define I386_GDT_LIMIT_LOW_SHIFT 0x00
#define I386_GDT_BASE_LOW_MASK 0xFFFF
#define I386_GDT_BASE_LOW_SHIFT 0x00
#define I386_GDT_BASE_MID_MASK 0xFF
#define I386_GDT_BASE_MID_SHIFT 0x10
#define I386_GDT_BASE_HIGH_MASK 0xFF
#define I386_GDT_BASE_HIGH_SHIFT 0x18
#define I386_GDT_MAX_DESCRIPTORS 0x06
#define I386_GDT_SELECTOR_MULTIPLIER 0x08
#define I386_RPL_SUPERVISOR_MASK 0x00
#define I386_RPL_DRIVER_0_MASK 0x01
#define I386_RPL_DRIVER_1_MASK 0x02
#define I386_RPL_USERMODE_MASK 0x03
Typedefs
typedef struct i386_gdt_descriptor i386_gdt_descriptor_t
typedef struct i386_gdtr i386_gdt_pointer_t
typedef struct i386_tss_entry i386_tss_entry_t
Functions
void i386_protection_init ()
void i386_protection_user_call (uint32_t eip, uint32_t esp)
void process_user_call (void *entry, void *stack)
Macro Definition Documentation
#define I386_GDT_32_BIT_SEGMENT 1<<6
Definition at line 31 of file protection.h.
#define I386_GDT_ACCESSED_BIT 1<<0
Definition at line 17 of file protection.h.
#define I386_GDT_BASE_HIGH_MASK 0xFF
Definition at line 41 of file protection.h.
Referenced by i386_set_tss_descriptor().
#define I386_GDT_BASE_HIGH_SHIFT 0x18
Definition at line 42 of file protection.h.
Referenced by i386_set_tss_descriptor().
#define I386_GDT_BASE_LOW_MASK 0xFFFF
Definition at line 37 of file protection.h.
Referenced by i386_set_tss_descriptor().
#define I386_GDT_BASE_LOW_SHIFT 0x00
Definition at line 38 of file protection.h.
Referenced by i386_set_tss_descriptor().
#define I386_GDT_BASE_MID_MASK 0xFF
Definition at line 39 of file protection.h.
Referenced by i386_set_tss_descriptor().
#define I386_GDT_BASE_MID_SHIFT 0x10
Definition at line 40 of file protection.h.
Referenced by i386_set_tss_descriptor().
#define I386_GDT_CONFORMING_BIT 1<<2
Definition at line 20 of file protection.h.
#define I386_GDT_DRIVER_0_MASK 1<<5
Definition at line 25 of file protection.h.
#define I386_GDT_DRIVER_1_MASK 2<<5
Definition at line 26 of file protection.h.
#define I386_GDT_EXECUTABLE_BIT 1<<3
Definition at line 22 of file protection.h.
#define I386_GDT_GRANULARITY_4K_BIT 1<<7
Definition at line 32 of file protection.h.
#define I386_GDT_GROW_DIRECTION_BIT 1<<2
Definition at line 21 of file protection.h.
#define I386_GDT_LIMIT_HIGH_MASK 0x0F
Definition at line 33 of file protection.h.
Referenced by i386_set_tss_descriptor().
#define I386_GDT_LIMIT_HIGH_SHIFT 0x10
Definition at line 34 of file protection.h.
Referenced by i386_set_tss_descriptor().
#define I386_GDT_LIMIT_LOW_MASK 0xFFFF
Definition at line 35 of file protection.h.
Referenced by i386_set_tss_descriptor().
#define I386_GDT_LIMIT_LOW_SHIFT 0x00
Definition at line 36 of file protection.h.
Referenced by i386_set_tss_descriptor().
#define I386_GDT_MAX_DESCRIPTORS 0x06
Definition at line 43 of file protection.h.
#define I386_GDT_NON_SYSTEM_BIT 1<<4
Definition at line 23 of file protection.h.
#define I386_GDT_OS_DEFINED_BIT 1<<4
Definition at line 29 of file protection.h.
#define I386_GDT_PRESENT_BIT 1<<7
Definition at line 28 of file protection.h.
#define I386_GDT_READABLE_BIT 1<<1
Definition at line 18 of file protection.h.
#define I386_GDT_RESERVED_BIT 1<<5
Definition at line 30 of file protection.h.
#define I386_GDT_SELECTOR_MULTIPLIER 0x08
Definition at line 44 of file protection.h.
#define I386_GDT_SUPERVISOR_MASK 0<<5
Definition at line 24 of file protection.h.
#define I386_GDT_USERMODE_MASK 3<<5
Definition at line 27 of file protection.h.
#define I386_GDT_WRITABLE_BIT 1<<1
Definition at line 19 of file protection.h.
#define I386_RPL_DRIVER_0_MASK 0x01
Definition at line 46 of file protection.h.
#define I386_RPL_DRIVER_1_MASK 0x02
Definition at line 47 of file protection.h.
#define I386_RPL_SUPERVISOR_MASK 0x00
Definition at line 45 of file protection.h.
#define I386_RPL_USERMODE_MASK 0x03
Definition at line 48 of file protection.h.
Referenced by i386_protection_init().
Typedef Documentation
typedef struct i386_gdt_descriptor i386_gdt_descriptor_t
typedef struct i386_gdtr i386_gdt_pointer_t
typedef struct i386_tss_entry i386_tss_entry_t
Function Documentation
void i386_protection_init ()
Definition at line 20 of file protection.c.
References i386_tss_entry::cs, i386_tss_entry::ds, i386_tss_entry::es, i386_tss_entry::esp0, i386_tss_entry::fs, i386_tss_entry::gs, I386_RPL_USERMODE_MASK, i386_set_tss_descriptor(), i386_tss_flush(), memset(), i386_tss_entry::ss, and i386_tss_entry::ss0.
Referenced by i386_kmain().
void i386_protection_user_call (uint32_t eip, uint32_t esp)
Referenced by process_user_call(), and scheduler_invoke_signal_handler().
void process_user_call (void * entry, void * stack)
Definition at line 32 of file protection.c.