posnk kernel: arch/i386/protection.c File Reference
protection.c File Reference
#include "arch/i386/protection.h"
#include <string.h>
Functions
void i386_set_tss_descriptor (uint32_t base, uint32_t limit, uint8_t flags, uint8_t granularity)
void i386_tss_flush ()
void i386_protection_init ()
void process_user_call (void *entry, void *stack)
Variables
i386_gdt_descriptor_t i386_tss_descriptor
i386_tss_entry_t i386_tss_entry
Function Documentation
void i386_protection_init ()
Definition at line 20 of file protection.c.
References i386_tss_entry::cs, i386_tss_entry::ds, i386_tss_entry::es, i386_tss_entry::esp0, i386_tss_entry::fs, i386_tss_entry::gs, I386_RPL_USERMODE_MASK, i386_set_tss_descriptor(), i386_tss_flush(), memset(), i386_tss_entry::ss, and i386_tss_entry::ss0.
Referenced by i386_kmain().
void i386_set_tss_descriptor (uint32_t base, uint32_t limit, uint8_t flags, uint8_t granularity)
Definition at line 8 of file protection.c.
References i386_gdt_descriptor::baseHi, i386_gdt_descriptor::baseLo, i386_gdt_descriptor::baseMid, i386_gdt_descriptor::flags, i386_gdt_descriptor::granularity, I386_GDT_BASE_HIGH_MASK, I386_GDT_BASE_HIGH_SHIFT, I386_GDT_BASE_LOW_MASK, I386_GDT_BASE_LOW_SHIFT, I386_GDT_BASE_MID_MASK, I386_GDT_BASE_MID_SHIFT, I386_GDT_LIMIT_HIGH_MASK, I386_GDT_LIMIT_HIGH_SHIFT, I386_GDT_LIMIT_LOW_MASK, I386_GDT_LIMIT_LOW_SHIFT, i386_gdt_descriptor::limit, and memset().
Referenced by i386_protection_init().
void i386_tss_flush ()
Referenced by i386_protection_init().
void process_user_call (void * entry, void * stack)
Definition at line 32 of file protection.c.
References i386_protection_user_call().
Referenced by process_exec().
Variable Documentation
i386_gdt_descriptor_t i386_tss_descriptor
i386_tss_entry_t i386_tss_entry
Definition at line 6 of file protection.c.