posnk kernel: include/fs/ramfs.h File Reference
ramfs.h File Reference
#include "kernel/vfs.h"
Data Structures
struct ramfs_inode
struct ramfs_block
struct ramfs_device
struct ramfs_dirent
Typedefs
typedef struct ramfs_inode ramfs_inode_t
fs/ramfs.h
typedef struct ramfs_block ramfs_block_t
typedef struct ramfs_device ramfs_device_t
typedef struct ramfs_dirent ramfs_dirent_t
Functions
fs_device_t * ramfs_create ()
Typedef Documentation
typedef struct ramfs_block ramfs_block_t
Definition at line 19 of file ramfs.h.
typedef struct ramfs_device ramfs_device_t
Definition at line 21 of file ramfs.h.
typedef struct ramfs_dirent ramfs_dirent_t
Definition at line 23 of file ramfs.h.
typedef struct ramfs_inode ramfs_inode_t
fs/ramfs.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 18-04-2014 - Created
Definition at line 17 of file ramfs.h.
Function Documentation
fs_device_t* ramfs_create ()
Definition at line 280 of file ramfs.c.
References ramfs_device::device, fs_device_operations::find_dirent, heapmm_alloc(), fs_device::id, ramfs_device::inode_id_ctr, fs_device::inode_size, fs_device_operations::link, fs_device_operations::load_inode, fs_device::lock, fs_device_operations::mkdir, fs_device_operations::mknod, NULL, fs_device::ops, ramfs_device_ctr, ramfs_find_dirent(), ramfs_link(), ramfs_load_inode(), ramfs_mkdir(), ramfs_mknod(), ramfs_ops, ramfs_read_inode(), ramfs_readdir(), ramfs_rmnod(), ramfs_trunc_inode(), ramfs_unlink(), ramfs_write_inode(), fs_device_operations::read_dir, fs_device_operations::read_inode, fs_device_operations::rmnod, fs_device::root_inode_id, semaphore_alloc(), fs_device_operations::trunc_inode, fs_device_operations::unlink, and fs_device_operations::write_inode.
Referenced by i386_kmain().