posnk kernel: fs/ramfs.c File Reference
ramfs.c File Reference
#include "kernel/heapmm.h"
#include "kernel/vfs.h"
#include "fs/ramfs.h"
#include "util/llist.h"
#include <string.h>
#include <sys/errno.h>
Functions
int ramfs_store_inode (inode_t *inode)
fs/ramfs.c
int ramfs_mknod (inode_t *_inode)
int ramfs_rmnod (inode_t *inode)
int ramfs_rawdir_search_iterator (llist_t *node, void *param)
int ramfs_readdir (inode_t *_inode, void *_buffer, aoff_t f_offset, aoff_t length, aoff_t *nread)
int ramfs_block_search_iterator (llist_t *node, void *param)
int ramfs_read_inode (inode_t *_inode, void *_buffer, aoff_t f_offset, aoff_t length, aoff_t *nread)
int ramfs_write_inode (inode_t *_inode, void *_buffer, aoff_t f_offset, aoff_t length, aoff_t *nwritten)
int ramfs_trunc_inode (inode_t *_inode, aoff_t size)
int ramfs_dirent_search_iterator (llist_t *node, void *param)
dirent_t * ramfs_find_dirent (inode_t *_inode, char *name)
int ramfs_mkdir (inode_t *_inode)
inode_t * ramfs_load_inode (fs_device_t *device, ino_t id)
int ramfs_link (inode_t *_dir, char *_name, ino_t inode_id)
int ramfs_unlink (inode_t *_inode, char *name)
fs_device_t * ramfs_create ()
Variables
uint32_t ramfs_device_ctr = 0xF00F0000
fs_device_operations_t * ramfs_ops
Function Documentation
int ramfs_block_search_iterator (llist_t * node, void * param)
Definition at line 88 of file ramfs.c.
References ramfs_block::length, and ramfs_block::start.
Referenced by ramfs_read_inode(), and ramfs_write_inode().
fs_device_t* ramfs_create ()
Definition at line 280 of file ramfs.c.
References ramfs_device::device, fs_device_operations::find_dirent, heapmm_alloc(), fs_device::id, ramfs_device::inode_id_ctr, fs_device::inode_size, fs_device_operations::link, fs_device_operations::load_inode, fs_device::lock, fs_device_operations::mkdir, fs_device_operations::mknod, NULL, fs_device::ops, ramfs_device_ctr, ramfs_find_dirent(), ramfs_link(), ramfs_load_inode(), ramfs_mkdir(), ramfs_mknod(), ramfs_ops, ramfs_read_inode(), ramfs_readdir(), ramfs_rmnod(), ramfs_trunc_inode(), ramfs_unlink(), ramfs_write_inode(), fs_device_operations::read_dir, fs_device_operations::read_inode, fs_device_operations::rmnod, fs_device::root_inode_id, semaphore_alloc(), fs_device_operations::trunc_inode, fs_device_operations::unlink, and fs_device_operations::write_inode.
Referenced by i386_kmain().
int ramfs_dirent_search_iterator (llist_t * node, void * param)
Definition at line 196 of file ramfs.c.
References ramfs_dirent::dir, dirent::name, and strcmp().
Referenced by ramfs_find_dirent(), and ramfs_unlink().
dirent_t* ramfs_find_dirent (inode_t * _inode, char * name)
Definition at line 202 of file ramfs.c.
References ramfs_dirent::dir, ramfs_inode::dirent_list, llist_iterate_select(), NULL, and ramfs_dirent_search_iterator().
Referenced by ramfs_create().
int ramfs_link (inode_t * _dir, char * _name, ino_t inode_id)
Definition at line 246 of file ramfs.c.
References dirent::d_reclen, inode::device_id, dirent::device_id, ramfs_dirent::dir, ramfs_inode::dirent_list, ENOSPC, heapmm_alloc(), dirent::inode_id, llist_add_end(), dirent::name, inode::size, ramfs_dirent::start, and strcpy().
Referenced by ramfs_create().
inode_t* ramfs_load_inode (fs_device_t * device, ino_t id)
Definition at line 223 of file ramfs.c.
References inode::device, inode::device_id, inode::gid, heapmm_alloc(), fs_device::id, inode::if_dev, ramfs_inode::inode, fs_device::inode_size, inode::link_path, inode::lock, memset(), inode::mode, ramfs_mkdir(), ramfs_mknod(), S_IFDIR, S_IRUSR, S_IWUSR, S_IXUSR, semaphore_alloc(), semaphore_up(), and inode::uid.
Referenced by ramfs_create().
int ramfs_mkdir (inode_t * _inode)
Definition at line 211 of file ramfs.c.
References ramfs_inode::dirent_list, ENOMEM, heapmm_alloc(), and llist_create().
Referenced by ramfs_create(), and ramfs_load_inode().
int ramfs_mknod (inode_t * _inode)
Definition at line 24 of file ramfs.c.
References inode::device, ENOMEM, heapmm_alloc(), inode::id, ramfs_device::inode_id_ctr, and llist_create().
Referenced by ramfs_create(), and ramfs_load_inode().
int ramfs_rawdir_search_iterator (llist_t * node, void * param)
Definition at line 47 of file ramfs.c.
References ramfs_dirent::start.
Referenced by ramfs_readdir().
int ramfs_read_inode (inode_t * _inode, void * _buffer, aoff_t f_offset, aoff_t length, aoff_t * nread)
Definition at line 95 of file ramfs.c.
References ramfs_inode::block_list, ramfs_block::data, EIO, ramfs_block::length, llist_iterate_select(), memcpy(), NULL, ramfs_block_search_iterator(), and ramfs_block::start.
Referenced by ramfs_create().
int ramfs_readdir (inode_t * _inode, void * _buffer, aoff_t f_offset, aoff_t length, aoff_t * nread)
Definition at line 54 of file ramfs.c.
References dirent::d_reclen, inode::device_id, dirent::device_id, ramfs_dirent::dir, ramfs_inode::dirent_list, dirent::inode_id, llist_iterate_select(), memcpy(), dirent::name, NULL, ramfs_rawdir_search_iterator(), and ramfs_dirent::start.
Referenced by ramfs_create().
int ramfs_rmnod (inode_t * inode)
Todo:
: Free blocks
Definition at line 41 of file ramfs.c.
References EFAULT.
Referenced by ramfs_create().
int ramfs_store_inode (inode_t * inode)
fs/ramfs.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 18-04-2014 - Created
Definition at line 19 of file ramfs.c.
int ramfs_trunc_inode (inode_t * _inode, aoff_t size)
Definition at line 165 of file ramfs.c.
References ramfs_inode::block_list, ramfs_block::data, EIO, ENOMEM, heapmm_alloc(), heapmm_free(), ramfs_block::length, llist_add_end(), memset(), inode::size, and ramfs_block::start.
Referenced by ramfs_create().
int ramfs_unlink (inode_t * _inode, char * name)
Definition at line 265 of file ramfs.c.
References ramfs_inode::block_list, ENOENT, heapmm_free(), llist_iterate_select(), llist_unlink(), and ramfs_dirent_search_iterator().
Referenced by ramfs_create().
int ramfs_write_inode (inode_t * _inode, void * _buffer, aoff_t f_offset, aoff_t length, aoff_t * nwritten)
Definition at line 124 of file ramfs.c.
References ramfs_inode::block_list, ramfs_block::data, ENOSPC, heapmm_alloc(), ramfs_block::length, llist_add_end(), llist_iterate_select(), memcpy(), NULL, ramfs_block_search_iterator(), and ramfs_block::start.
Referenced by ramfs_create().
Variable Documentation
uint32_t ramfs_device_ctr = 0xF00F0000
Definition at line 276 of file ramfs.c.
Referenced by ramfs_create().
fs_device_operations_t* ramfs_ops
Definition at line 278 of file ramfs.c.
Referenced by ramfs_create().