posnk kernel: kernel/sc_perm.c File Reference
sc_perm.c File Reference
#include "kernel/heapmm.h"
#include "kernel/physmm.h"
#include "kernel/paging.h"
#include "kernel/process.h"
#include "kernel/scheduler.h"
#include "kernel/permissions.h"
#include "kernel/synch.h"
#include "kernel/syscall.h"
#include <sys/errno.h>
Functions
uint32_t sys_getuid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
kernel/sc_process.c
uint32_t sys_geteuid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_getgid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_getegid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_setuid (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_setgid (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Function Documentation
uint32_t sys_getegid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 39 of file sc_perm.c.
References process_info::effective_gid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_geteuid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 29 of file sc_perm.c.
References process_info::effective_uid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_getgid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 34 of file sc_perm.c.
References process_info::gid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_getuid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
kernel/sc_process.c
Part of P-OS kernel.
Contains process related syscalls
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 07-04-2014 - Created
Definition at line 24 of file sc_perm.c.
References scheduler_current_task, and process_info::uid.
Referenced by syscall_init().
uint32_t sys_setgid (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 55 of file sc_perm.c.
References process_info::effective_gid, EPERM, process_info::gid, scheduler_current_task, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_setuid (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 44 of file sc_perm.c.
References process_info::effective_uid, EPERM, scheduler_current_task, syscall_errno, and process_info::uid.
Referenced by syscall_init().