posnk kernel: kernel/sc_signals.c File Reference
sc_signals.c File Reference
#include <sys/errno.h>
#include "kernel/time.h"
#include "kernel/scheduler.h"
#include "kernel/syscall.h"
#include "kernel/permissions.h"
Macros
#define SIG_ERR (0xFFFFFFFF)
kernel/sc_signals.c
#define SIG_SETMASK 0 /* set mask with sigprocmask() */
#define SIG_BLOCK 1 /* set of signals to block */
#define SIG_UNBLOCK 2 /* set of signals to, well, unblock */
Functions
uint32_t sys_signal (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_ssigex (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_exitsig (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_sigprocmask (uint32_t param[4], uint32_t param_size[4])
Macro Definition Documentation
#define SIG_BLOCK 1 /* set of signals to block */
Definition at line 24 of file sc_signals.c.
Referenced by sys_sigprocmask().
#define SIG_ERR (0xFFFFFFFF)
kernel/sc_signals.c
Part of P-OS kernel.
Contains signals related syscalls
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 26-05-2014 - Created
Definition at line 20 of file sc_signals.c.
Referenced by sys_signal().
#define SIG_SETMASK 0 /* set mask with sigprocmask() */
Definition at line 23 of file sc_signals.c.
Referenced by sys_sigprocmask().
#define SIG_UNBLOCK 2 /* set of signals to, well, unblock */
Definition at line 25 of file sc_signals.c.
Referenced by sys_sigprocmask().
Function Documentation
uint32_t sys_exitsig (uint32_t param[4], uint32_t param_size[4])
Definition at line 47 of file sc_signals.c.
References scheduler_exit_signal_handler().
Referenced by syscall_init().
uint32_t sys_signal (uint32_t param[4], uint32_t param_size[4])
Definition at line 28 of file sc_signals.c.
References EINVAL, scheduler_current_task, SIG_ERR, process_info::signal_handler_table, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_sigprocmask (uint32_t param[4], uint32_t param_size[4])
Definition at line 53 of file sc_signals.c.
References copy_kern_to_user(), copy_user_to_kern(), EFAULT, scheduler_current_task, SIG_BLOCK, SIG_SETMASK, SIG_UNBLOCK, process_info::signal_mask_bitmap, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_ssigex (uint32_t param[4], uint32_t param_size[4])
Definition at line 41 of file sc_signals.c.
References scheduler_current_task, and process_info::signal_handler_exit_func.
Referenced by syscall_init().