posnk kernel: kernel/sc_process.c File Reference
sc_process.c File Reference
#include <sys/errno.h>
#include "kernel/heapmm.h"
#include "kernel/physmm.h"
#include "kernel/paging.h"
#include "kernel/process.h"
#include "kernel/scheduler.h"
#include "kernel/permissions.h"
#include "kernel/synch.h"
#include "kernel/syscall.h"
Macros
#define WNOHANG 1
#define WUNTRACED 2
Functions
uint32_t sys_fork (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
kernel/sc_process.c
uint32_t sys_kill (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_getpid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_getppid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_getpgrp (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_getsid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_setsid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_setpgrp (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_setpgid (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_exit (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_yield (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_waitpid (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_sbrk (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
int strlistlen (char **list)
uint32_t sys_execve (uint32_t param[4], uint32_t param_size[4])
Macro Definition Documentation
#define WNOHANG 1
Definition at line 149 of file sc_process.c.
Referenced by sys_waitpid().
#define WUNTRACED 2
Definition at line 150 of file sc_process.c.
Referenced by sys_waitpid().
Function Documentation
int strlistlen (char ** list)
Definition at line 260 of file process.c.
Referenced by process_exec(), and sys_execve().
uint32_t sys_execve (uint32_t param[4], uint32_t param_size[4])
Definition at line 327 of file sc_process.c.
References CONFIG_FILE_MAX_NAME_LENGTH, CONFIG_MAX_ARGV_LEN, CONFIG_MAX_ENV_LEN, copy_user_to_kern(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), process_exec(), strlistlen(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_exit (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 134 of file sc_process.c.
References process_child_event(), PROCESS_CHILD_KILLED, PROCESS_KILLED, procvmm_clear_mmaps(), schedule(), scheduler_current_task, and process_info::state.
Referenced by syscall_init().
uint32_t sys_fork (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
kernel/sc_process.c
Part of P-OS kernel.
Contains process related syscalls
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 07-04-2014 - Created
Definition at line 23 of file sc_process.c.
References scheduler_fork().
Referenced by syscall_init().
uint32_t sys_getpgrp (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 80 of file sc_process.c.
References process_info::pgid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_getpid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 70 of file sc_process.c.
References process_info::pid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_getppid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 75 of file sc_process.c.
References process_info::parent_pid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_getsid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 85 of file sc_process.c.
References scheduler_current_task, and process_info::sid.
Referenced by syscall_init().
uint32_t sys_kill (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Todo:
: Implement kill all system processes
Definition at line 28 of file sc_process.c.
References EINVAL, EPERM, ESRCH, get_perm_class(), process_info::gid, NULL, PERM_CLASS_OWNER, process_info::pgid, process_get(), process_send_signal(), process_signal_pgroup(), scheduler_current_task, syscall_errno, and process_info::uid.
Referenced by syscall_init().
uint32_t sys_sbrk (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Todo:
: Handle decreasing heap size
Definition at line 287 of file sc_process.c.
References ENOMEM, process_info::heap_end, process_info::heap_max, process_info::heap_start, PHYSMM_PAGE_ADDRESS_MASK, PHYSMM_PAGE_SIZE, PROCESS_MMAP_FLAG_HEAP, PROCESS_MMAP_FLAG_WRITE, procvmm_mmap_anon(), procvmm_resize_map(), scheduler_current_task, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_setpgid (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Todo:
: FIX PERMS
Definition at line 112 of file sc_process.c.
References EINVAL, ESRCH, process_info::pgid, process_info::pid, process_get(), scheduler_current_task, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_setpgrp (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 102 of file sc_process.c.
References EPERM, process_info::pgid, process_info::pid, scheduler_current_task, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_setsid (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 90 of file sc_process.c.
References process_info::ctty, EPERM, process_info::pgid, process_info::pid, scheduler_current_task, process_info::sid, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_waitpid (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Todo:
: Determine whether pgroup exists
Todo:
: Implement this in libc, linux only hehehe
Definition at line 153 of file sc_process.c.
References process_info::child_events, process_child_event::child_pid, process_info::child_sema, copy_kern_to_user(), copy_user_to_kern(), debugcon_aprintf(), ECHILD, EFAULT, EINTR, process_child_event::event, process_info::exit_status, process_info::last_signal, llist_get_last(), process_info::pid, process_absorb_event(), PROCESS_CHILD_CONTD, PROCESS_CHILD_KILLED, PROCESS_CHILD_STOPPED, process_get(), process_get_event(), process_get_event_pg(), process_reap(), PROCESS_TERM_EXIT, PROCESS_TERM_SIGNAL, scheduler_current_task, semaphore_idown(), syscall_errno, process_info::term_cause, WNOHANG, and WUNTRACED.
Referenced by i386_kmain(), and syscall_init().
uint32_t sys_yield (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 143 of file sc_process.c.
References schedule().
Referenced by syscall_init().