posnk kernel: kernel/sc_time.c File Reference
sc_time.c File Reference
#include <sys/errno.h>
#include "kernel/time.h"
#include "kernel/scheduler.h"
#include "kernel/syscall.h"
#include "kernel/permissions.h"
Functions
uint32_t sys_time (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
kernel/sc_time.c
uint32_t sys_sleep (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_usleep (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_stime (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Function Documentation
uint32_t sys_sleep (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 25 of file sc_time.c.
References EINTR, scheduler_wait_time(), syscall_errno, and system_time.
Referenced by syscall_init().
uint32_t sys_stime (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 43 of file sc_time.c.
References copy_user_to_kern(), EFAULT, EPERM, get_effective_uid(), syscall_errno, system_time, and system_time_micros.
Referenced by syscall_init().
uint32_t sys_time (__attribute__((__unused__)) uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
kernel/sc_time.c
Part of P-OS kernel.
Contains process related syscalls
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 24-05-2014 - Created
Definition at line 20 of file sc_time.c.
References system_time.
Referenced by syscall_init().
uint32_t sys_usleep (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 34 of file sc_time.c.
References EINTR, scheduler_wait_micros(), syscall_errno, and system_time_micros.
Referenced by syscall_init().