posnk kernel: kernel/sc_vfs.c File Reference
sc_vfs.c File Reference
#include <stdint.h>
#include "kernel/syscall.h"
#include "kernel/vfs.h"
#include "kernel/heapmm.h"
#include <sys/errno.h>
#include <sys/stat.h>
#include <string.h>
Functions
uint32_t sys_link (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_mount (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_symlink (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_unlink (uint32_t param[4], uint32_t param_size[4])
int _sys_chdir (char *path)
uint32_t sys_chdir (uint32_t param[4], uint32_t param_size[4])
int _sys_chmod (char *path, mode_t mode)
uint32_t sys_chmod (uint32_t param[4], uint32_t param_size[4])
int _sys_chown (char *path, uid_t owner, gid_t group)
uint32_t sys_chown (uint32_t param[4], uint32_t param_size[4])
int _sys_truncate (char *path, off_t length)
uint32_t sys_truncate (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_umask (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_mknod (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_mkdir (uint32_t param[4], uint32_t param_size[4])
int _sys_stat (char *path, struct stat *buf)
uint32_t sys_stat (uint32_t param[4], uint32_t param_size[4])
int _sys_readlink (char *path, char *buf, size_t bufsiz)
uint32_t sys_readlink (uint32_t param[4], uint32_t param_size[4])
int _sys_lstat (char *path, struct stat *buf)
uint32_t sys_lstat (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_rmdir (uint32_t param[4], uint32_t param_size[4])
Function Documentation
int _sys_chdir (char * path)
Definition at line 154 of file sc_vfs.c.
References ENOENT, syscall_errno, vfs_chdir(), and vfs_find_dirc().
Referenced by sys_chdir().
int _sys_chmod (char * path, mode_t mode)
Definition at line 193 of file sc_vfs.c.
References inode::ctime, ENOENT, EPERM, get_effective_uid(), get_perm_class(), inode::gid, inode::mode, PERM_CLASS_OWNER, syscall_errno, system_time, inode::uid, and vfs_find_inode().
Referenced by sys_chmod().
int _sys_chown (char * path, uid_t owner, gid_t group)
Definition at line 233 of file sc_vfs.c.
References inode::ctime, ENOENT, EPERM, get_perm_class(), inode::gid, PERM_CLASS_GROUP, PERM_CLASS_OWNER, syscall_errno, system_time, inode::uid, and vfs_find_inode().
Referenced by sys_chown().
int _sys_lstat (char * path, struct stat * buf)
Todo:
: FIX
Todo:
: Implement sparse files
Todo:
: Ask FS about block size
Definition at line 474 of file sc_vfs.c.
References inode::atime, inode::ctime, inode::device_id, ENOENT, inode::gid, inode::hard_link_count, inode::id, inode::if_dev, inode::link_path, inode::mode, inode::mtime, inode::size, stat::st_atime, stat::st_ctime, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_mtime, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, strlen(), syscall_errno, inode::uid, and vfs_find_symlink().
Referenced by sys_lstat().
int _sys_readlink (char * path, char * buf, size_t bufsiz)
Definition at line 419 of file sc_vfs.c.
References EINVAL, ENOENT, inode::link_path, strlen(), strncpy(), syscall_errno, and vfs_find_symlink().
Referenced by sys_readlink().
int _sys_stat (char * path, struct stat * buf)
Todo:
: FIX
Todo:
: Implement sparse files
Todo:
: Ask FS about block size
Definition at line 363 of file sc_vfs.c.
References inode::atime, inode::ctime, inode::device_id, ENOENT, inode::gid, inode::hard_link_count, inode::id, inode::if_dev, inode::mode, inode::mtime, inode::size, stat::st_atime, stat::st_ctime, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_mtime, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, syscall_errno, inode::uid, and vfs_find_inode().
Referenced by sys_stat().
int _sys_truncate (char * path, off_t length)
Todo:
: Add permission check
Definition at line 275 of file sc_vfs.c.
References inode::ctime, ENOENT, syscall_errno, system_time, vfs_find_inode(), and vfs_truncate().
Referenced by sys_truncate().
uint32_t sys_chdir (uint32_t param[4], uint32_t param_size[4])
Definition at line 174 of file sc_vfs.c.
References _sys_chdir(), CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_chmod (uint32_t param[4], uint32_t param_size[4])
Definition at line 213 of file sc_vfs.c.
References _sys_chmod(), CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_chown (uint32_t param[4], uint32_t param_size[4])
Definition at line 255 of file sc_vfs.c.
References _sys_chown(), CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_link (uint32_t param[4], uint32_t param_size[4])
Definition at line 23 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_link().
Referenced by syscall_init().
uint32_t sys_lstat (uint32_t param[4], uint32_t param_size[4])
Definition at line 501 of file sc_vfs.c.
References _sys_lstat(), buf, CONFIG_FILE_MAX_NAME_LENGTH, copy_kern_to_user(), copy_user_to_kern(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_mkdir (uint32_t param[4], uint32_t param_size[4])
Definition at line 340 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_mkdir().
Referenced by syscall_init().
uint32_t sys_mknod (uint32_t param[4], uint32_t param_size[4])
Definition at line 316 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_mknod().
Referenced by syscall_init().
uint32_t sys_mount (uint32_t param[4], uint32_t param_size[4])
Definition at line 55 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_mount().
Referenced by syscall_init().
uint32_t sys_readlink (uint32_t param[4], uint32_t param_size[4])
Definition at line 438 of file sc_vfs.c.
References _sys_readlink(), buf, CONFIG_FILE_MAX_NAME_LENGTH, copy_kern_to_user(), copy_user_to_kern(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_rmdir (uint32_t param[4], uint32_t param_size[4])
Definition at line 533 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_rmdir().
Referenced by syscall_init().
uint32_t sys_stat (uint32_t param[4], uint32_t param_size[4])
Definition at line 387 of file sc_vfs.c.
References _sys_stat(), buf, CONFIG_FILE_MAX_NAME_LENGTH, copy_kern_to_user(), copy_user_to_kern(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_symlink (uint32_t param[4], uint32_t param_size[4])
Definition at line 98 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_symlink().
Referenced by syscall_init().
uint32_t sys_truncate (uint32_t param[4], uint32_t param_size[4])
Definition at line 289 of file sc_vfs.c.
References _sys_truncate(), CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_umask (uint32_t param[4], uint32_t param_size[4])
Definition at line 308 of file sc_vfs.c.
References scheduler_current_task, and process_info::umask.
Referenced by syscall_init().
uint32_t sys_unlink (uint32_t param[4], uint32_t param_size[4])
Definition at line 131 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_unlink().
Referenced by syscall_init().