posnk kernel: kernel/sc_streams.c File Reference
sc_streams.c File Reference
#include <string.h>
#include <stdint.h>
#include "kernel/syscall.h"
#include "kernel/streams.h"
#include "kernel/heapmm.h"
#include <sys/errno.h>
#include <sys/stat.h>
Functions
uint32_t sys_fchdir (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_fchmod (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_fchown (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_fcntl (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_ioctl (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_fstat (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_dup2 (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_dup (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_open (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_close (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_pipe2 (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_pipe (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_getdents (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_read (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_write (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_lseek (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
uint32_t sys_ftruncate (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Function Documentation
uint32_t sys_close (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 106 of file sc_streams.c.
References _sys_close().
Referenced by syscall_init().
uint32_t sys_dup (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 80 of file sc_streams.c.
References _sys_dup().
Referenced by syscall_init().
uint32_t sys_dup2 (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 74 of file sc_streams.c.
References _sys_dup2().
Referenced by syscall_init().
uint32_t sys_fchdir (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 23 of file sc_streams.c.
References _sys_fchdir().
Referenced by syscall_init().
uint32_t sys_fchmod (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 30 of file sc_streams.c.
References _sys_fchmod().
Referenced by syscall_init().
uint32_t sys_fchown (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 36 of file sc_streams.c.
References _sys_fchown().
Referenced by syscall_init().
uint32_t sys_fcntl (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 42 of file sc_streams.c.
References _sys_fcntl().
Referenced by syscall_init().
uint32_t sys_fstat (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 54 of file sc_streams.c.
References _sys_fstat(), buf, copy_kern_to_user(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_ftruncate (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 206 of file sc_streams.c.
References _sys_ftruncate().
Referenced by syscall_init().
uint32_t sys_getdents (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 138 of file sc_streams.c.
References _sys_getdents(), buf, copy_kern_to_user(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), memset(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_ioctl (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 48 of file sc_streams.c.
References _sys_ioctl().
Referenced by syscall_init().
uint32_t sys_lseek (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 200 of file sc_streams.c.
References _sys_lseek().
Referenced by syscall_init().
uint32_t sys_open (uint32_t param[4], uint32_t param_size[4])
Definition at line 86 of file sc_streams.c.
References _sys_open(), CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_pipe (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 125 of file sc_streams.c.
References _sys_pipe2(), copy_kern_to_user(), EFAULT, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_pipe2 (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 112 of file sc_streams.c.
References _sys_pipe2(), copy_kern_to_user(), EFAULT, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_read (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 159 of file sc_streams.c.
References _sys_read(), buf, copy_kern_to_user(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), memset(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_write (uint32_t param[4], __attribute__((__unused__)) uint32_t param_size[4])
Definition at line 180 of file sc_streams.c.
References _sys_write(), buf, copy_user_to_kern(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().