posnk kernel: kernel/scheduler.c File Reference
scheduler.c File Reference
#include <string.h>
#include <stddef.h>
#include "kernel/heapmm.h"
#include "kernel/process.h"
#include "kernel/synch.h"
#include "kernel/streams.h"
#include "kernel/scheduler.h"
#include "kernel/paging.h"
#include "util/llist.h"
#include "config.h"
Functions
void scheduler_init ()
int scheduler_fork ()
int scheduler_next_task_iterator (llist_t *node, void *param)
Iterator function that tests for running tasks that are not the current.
void schedule ()
void scheduler_set_as_idle ()
int scheduler_wait_micros (ktime_t microtime)
int scheduler_wait_time (ktime_t time)
void scheduler_wait_on (semaphore_t *semaphore)
Variables
pid_t scheduler_pid_counter = 0
kernel/scheduler.c
scheduler_task_t * scheduler_current_task
scheduler_task_t * scheduler_idle_task
llist_t * scheduler_task_list
Function Documentation
void schedule ()
Todo:
: Increment ticks only on preemptive scheduler calls
Definition at line 150 of file scheduler.c.
References process_info::cpu_ticks, llist_iterate_select(), NULL, PROCESS_KILLED, PROCESS_READY, PROCESS_RUNNING, scheduler_next_task_iterator(), scheduler_switch_task(), process_info::state, and process_info::waiting_signal_bitmap.
Referenced by process_handle_signals(), process_send_signal(), scheduler_wait_micros(), scheduler_wait_on(), scheduler_wait_time(), sys_exit(), sys_yield(), and timer_interrupt().
int scheduler_fork ()
Definition at line 66 of file scheduler.c.
References process_info::child_events, process_info::child_sema, CONFIG_PROCESS_MAX_NAME_LENGTH, process_info::current_directory, process_info::effective_gid, process_info::effective_uid, process_info::fd_ctr, process_info::fd_table, process_info::gid, process_info::heap_end, process_info::heap_start, heapmm_alloc(), llist_add_end(), llist_create(), memcpy(), process_info::memory_map, memset(), process_info::name, process_info::parent_pid, process_info::pgid, process_info::pid, PROCESS_READY, procvmm_copy_memory_map(), process_info::root_directory, scheduler_fork_to(), scheduler_pid_counter, semaphore_alloc(), process_info::sid, process_info::signal_handler_table, process_info::signal_mask_bitmap, process_info::stack_bottom, process_info::stack_top, process_info::state, strcpy(), stream_copy_fd_table(), process_info::uid, dir_cache::usage_count, and vfs_dir_cache_ref().
Referenced by i386_kmain(), and sys_fork().
void scheduler_init ()
Definition at line 27 of file scheduler.c.
References process_info::child_events, process_info::child_sema, CONFIG_PROCESS_MAX_NAME_LENGTH, CONFIG_SYSTEM_PROCESS_NAME, process_info::fd_table, process_info::gid, process_info::heap_end, process_info::heap_start, heapmm_alloc(), llist_add_end(), llist_create(), process_info::memory_map, memset(), process_info::name, process_info::page_directory, paging_active_dir, process_info::parent_pid, process_info::pgid, process_info::pid, PROCESS_READY, scheduler_pid_counter, semaphore_alloc(), process_info::sid, process_info::stack_bottom, process_info::stack_top, process_info::state, strcpy(), and process_info::uid.
Referenced by i386_kmain().
int scheduler_next_task_iterator (llist_t * node, void * param)
Iterator function that tests for running tasks that are not the current.
Todo:
: Signal timeout
Todo:
: Signal timeout
Definition at line 122 of file scheduler.c.
References NULL, PROCESS_INTERRUPTED, PROCESS_READY, PROCESS_WAITING, process_was_interrupted(), semaphore_try_down(), process_info::state, system_time, system_time_micros, process_info::wait_timeout_s, process_info::wait_timeout_u, and process_info::waiting_on.
Referenced by schedule().
void scheduler_set_as_idle ()
Definition at line 174 of file scheduler.c.
References PROCESS_NO_SCHED, scheduler_current_task, and process_info::state.
Referenced by i386_idle_task().
int scheduler_wait_micros (ktime_t microtime)
Definition at line 180 of file scheduler.c.
References NULL, PROCESS_INTERRUPTED, PROCESS_RUNNING, PROCESS_WAITING, schedule(), process_info::state, process_info::wait_timeout_s, process_info::wait_timeout_u, and process_info::waiting_on.
Referenced by sys_usleep().
void scheduler_wait_on (semaphore_t * semaphore)
Definition at line 208 of file scheduler.c.
References PROCESS_WAITING, schedule(), process_info::state, process_info::wait_timeout_s, process_info::wait_timeout_u, and process_info::waiting_on.
Referenced by semaphore_down(), and semaphore_idown().
int scheduler_wait_time (ktime_t time)
Definition at line 194 of file scheduler.c.
References NULL, PROCESS_INTERRUPTED, PROCESS_RUNNING, PROCESS_WAITING, schedule(), process_info::state, process_info::wait_timeout_s, process_info::wait_timeout_u, and process_info::waiting_on.
Referenced by sys_sleep().
Variable Documentation
scheduler_task_t* scheduler_current_task
Definition at line 23 of file scheduler.c.
Referenced by _sys_close(), _sys_close_int(), _sys_dup2(), _sys_open(), _sys_pipe2(), _sys_write(), curpid(), elf_load(), exception_handle(), get_effective_gid(), get_effective_uid(), get_gid(), get_uid(), i386_fpu_handle_ill(), i386_idle_task(), process_exec(), process_get_event(), process_get_event_pg(), process_handle_signals(), process_push_user_data(), process_send_signal(), process_signal_handler_default(), procvmm_check(), procvmm_clear_mmaps(), procvmm_copy_memory_map(), procvmm_do_exec_mmaps(), procvmm_get_memory_region(), procvmm_mmap_anon(), procvmm_mmap_file(), procvmm_resize_map(), scheduler_exsig(), scheduler_fork_to(), scheduler_invoke_signal_handler(), scheduler_set_as_idle(), scheduler_switch_task(), semaphore_down(), semaphore_idown(), stream_alloc_fd(), stream_claim_fd(), stream_copy_fd_table(), stream_do_close_on_exec(), stream_get_ptr(), sys_exit(), sys_getegid(), sys_geteuid(), sys_getgid(), sys_getpgrp(), sys_getpid(), sys_getppid(), sys_getsid(), sys_getuid(), sys_kill(), sys_sbrk(), sys_setgid(), sys_setpgid(), sys_setpgrp(), sys_setsid(), sys_setuid(), sys_signal(), sys_sigprocmask(), sys_ssigex(), sys_umask(), sys_waitpid(), syscall_dispatch(), tty_close(), tty_ioctl(), tty_open(), vfs_chdir(), vfs_chroot(), vfs_find_dirc(), vfs_find_dirc_parent(), vfs_find_symlink(), vfs_initialize(), vfs_mknod(), vfs_rmdir(), and vfs_symlink().
scheduler_task_t* scheduler_idle_task
Definition at line 24 of file scheduler.c.
pid_t scheduler_pid_counter = 0
kernel/scheduler.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 03-04-2014 - Created
Definition at line 22 of file scheduler.c.
Referenced by scheduler_fork(), and scheduler_init().
llist_t* scheduler_task_list
Definition at line 25 of file scheduler.c.