posnk kernel: driver/console/sercon.c File Reference
sercon.c File Reference
#include "driver/console/vgacon/vgacon.h"
#include <string.h>
#include <stdint.h>
#include <sys/types.h>
#include "kernel/tty.h"
Macros
#define PORT 0x2f8 /* COM1 */
Functions
int sserial_received ()
void sercon_isr ()
Interrupt handler!
int sis_transmit_empty ()
void sercon_putc (dev_t dev, char a)
void sercon_init ()
Macro Definition Documentation
#define PORT 0x2f8 /* COM1 */
Definition at line 1 of file sercon.c.
Referenced by sercon_init(), sercon_isr(), sercon_putc(), sis_transmit_empty(), and sserial_received().
Function Documentation
void sercon_init ()
Definition at line 27 of file sercon.c.
References i386_outb(), PORT, sercon_putc(), and tty_register_driver().
Referenced by vgacon_init().
void sercon_isr ()
Interrupt handler!
Definition at line 12 of file sercon.c.
References i386_inb(), PORT, sserial_received(), and tty_input_char().
Referenced by i386_handle_interrupt().
void sercon_putc (dev_t dev, char a)
Definition at line 21 of file sercon.c.
References i386_outb(), PORT, and sis_transmit_empty().
Referenced by sercon_init().
int sis_transmit_empty ()
Definition at line 17 of file sercon.c.
References i386_inb(), and PORT.
Referenced by sercon_putc().
int sserial_received ()
Definition at line 8 of file sercon.c.
References i386_inb(), and PORT.
Referenced by sercon_isr().