posnk kernel: include/kdbg/stacktrc.h File Reference
stacktrc.h File Reference
#include "util/llist.h"
#include <stdint.h>
Data Structures
struct kdbg_calltrace
kdbg/stacktrc.h
Typedefs
typedef struct kdbg_calltrace kdbg_calltrace_t
kdbg/stacktrc.h
Functions
llist_t * kdbg_do_calltrace ()
kdbg/stacktrc.c
void kdbg_free_calltrace (llist_t *st)
void kdbg_print_calltrace (llist_t *st)
Typedef Documentation
typedef struct kdbg_calltrace kdbg_calltrace_t
kdbg/stacktrc.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 12-05-2014 - Created
Function Documentation
llist_t* kdbg_do_calltrace ()
kdbg/stacktrc.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 12-05-2014 - Created
Definition at line 15 of file stacktrc.c.
References kdbg_calltrace::frame_addr, kdbg_calltrace::func_addr, kdbg_do_calltrace(), kdbgmm_alloc(), llist_add_end(), and llist_create().
Referenced by dbgapi_register_memuse(), and kdbg_do_calltrace().
void kdbg_free_calltrace (llist_t * st)
Definition at line 62 of file stacktrc.c.
References kdbgmm_free(), llist_unlink(), and llist::next.
Referenced by dbgapi_unreg_memuse().
void kdbg_print_calltrace (llist_t * st)
Definition at line 72 of file stacktrc.c.
References kdbg_calltrace::frame_addr, kdbg_calltrace::func_addr, kdbg_printf, and llist::prev.
Referenced by kdbg_print_memuse_brdr().