posnk kernel: crt/stdlib.c File Reference
stdlib.c File Reference
#include <_stdlib.h>
#include <string.h>
Functions
void utoa (unsigned int value, int base, char *str)
void itoa (int value, int base, char *str)
void itoa_s (int value, int base, char *str)
void utoa_s (int value, int base, char *str)
Variables
char intbuf [32]
char bchars [] = {'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'}
Function Documentation
void itoa (int value, int base, char * str)
Definition at line 29 of file stdlib.c.
References bchars, and intbuf.
Referenced by itoa_s().
void itoa_s (int value, int base, char * str)
Definition at line 52 of file stdlib.c.
References itoa().
void utoa (unsigned int value, int base, char * str)
Definition at line 7 of file stdlib.c.
References bchars, and intbuf.
Referenced by earlycon_ivprintf(), and utoa_s().
void utoa_s (int value, int base, char * str)
Definition at line 57 of file stdlib.c.
References utoa().
Referenced by earlycon_ivprintf().
Variable Documentation
char bchars[] = {'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'}
Definition at line 5 of file stdlib.c.
Referenced by itoa(), and utoa().
char intbuf[32]
Definition at line 4 of file stdlib.c.
Referenced by itoa(), and utoa().