posnk kernel: kernel/streams.c File Reference
streams.c File Reference
Implements the UNIX file API (fd streams)
#include "kernel/syscall.h"
#include "kernel/streams.h"
#include "kernel/scheduler.h"
#include "kernel/vfs.h"
#include "kernel/heapmm.h"
#include "kernel/pipe.h"
#include "kernel/permissions.h"
#include "kernel/device.h"
#include "kernel/process.h"
#include "kernel/signals.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
Functions
int stream_ptr_search_iterator (llist_t *node, void *param)
Iterator to test if stream pointer matches the fd.
stream_ptr_t * stream_get_ptr (int fd)
Get the stream pointer object for a file number.
stream_ptr_t * stream_get_ptr_o (process_info_t *process, int fd)
Get the stream pointer object for a file number on a different process.
int stream_ptr_copy_iterator (llist_t *node, void *param)
Linked list iterator that copies a process's open fds.
int stream_copy_fd_table (llist_t *target)
Copy the current process's stream ptr table to target.
int stream_exec_iterator (llist_t *node, void *param)
Linked list iterator that finds stream ptrs that are to be closed on execution of a new image.
void stream_do_close_on_exec ()
Close the stream ptrs that are to be closed on execute.
int stream_closeall_iterator (llist_t *node, void *param)
Iterator that will select all closeable stream pointers.
void stream_do_close_all (process_info_t *process)
Close all stream pointers for a process.
int stream_alloc_fd ()
Allocate a new fd handle.
void stream_claim_fd (int fd)
Claim a fd handle.
void stream_free_fd (int fd)
Free a fd handles.
ssize_t _sys_getdents (int fd, void *buffer, size_t count)
Get directory entries.
ssize_t _sys_read (int fd, void *buffer, size_t count)
Read from a stream.
ssize_t _sys_write (int fd, void *buffer, size_t count)
Write to a stream.
int _sys_ftruncate (int fd, off_t size)
Resize a file.
off_t _sys_lseek (int fd, off_t offset, int whence)
Reposition read/write file offset.
int _sys_fchdir (int fd)
Changes the working directory for this process to the dir pointed to by fd
int _sys_fstat (int fd, struct stat *buf)
Get file status.
int _sys_fchmod (int fd, mode_t mode)
Change file mode.
int _sys_fchown (int fd, uid_t owner, gid_t group)
Change file owner and group.
int _sys_fcntl (int fd, int cmd, int arg)
Manipulate stream pointer.
int _sys_ioctl (int fd, int cmd, int arg)
Control device.
int _sys_dup2 (int oldfd, int newfd)
Duplicate stream pointer.
int _sys_dup (int oldfd)
Duplicate stream pointer.
int _sys_pipe2 (int pipefd[2], int flags)
Create a pipe.
int _sys_open (char *path, int flags, mode_t mode)
Open a file stream.
int _sys_close (int fd)
Close a stream pointer.
int _sys_close_int (process_info_t *process, int fd)
Close a stream pointer on a different process.
Detailed Description
Implements the UNIX file API (fd streams)
Slightly different terminology is used here:
UNIX - POSNK
File description - stream info
File descriptor - stream pointer
File (opened) - stream
Part of P-OS kernel.
Author
Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog:
20-04-2014 - Created
Definition in file streams.c.
Function Documentation
int _sys_ftruncate (int fd, off_t size)
Resize a file.
If the new size is larger than the file currently is the new room will be filled with zero bytes, if the new size is smaller the data in the truncated part of the file is deleted
Parameters
fd The file stream to operate on
size The new size of the file
Returns
In case of error: -1, Otherwise 0
Exceptions
EBADF fd does not refer to an open stream
EBADF fd was not opened with WRITE access mode
EINVAL fd does not refer to a file
See Also
vfs_truncate for more errors
Definition at line 578 of file streams.c.
References EBADF, EINVAL, stream_info::flags, stream_ptr::info, stream_info::inode, stream_info::lock, O_ACCMODE, O_RDONLY, semaphore_down(), semaphore_up(), stream_get_ptr(), STREAM_TYPE_FILE, STREAM_TYPE_PIPE, syscall_errno, stream_info::type, and vfs_truncate().
Referenced by sys_ftruncate().
int stream_alloc_fd ()
Allocate a new fd handle.
Returns
A unique new handle
Definition at line 187 of file streams.c.
References EMFILE, process_info::fd_ctr, scheduler_current_task, and syscall_errno.
Referenced by _sys_dup(), _sys_open(), and _sys_pipe2().
void stream_claim_fd (int fd)
Claim a fd handle.
Parameters
fd The handle to claim
Definition at line 203 of file streams.c.
References process_info::fd_ctr, and scheduler_current_task.
Referenced by _sys_dup2().
int stream_closeall_iterator (llist_t * node, void * param)
Iterator that will select all closeable stream pointers.
Returns
Whether the stream is closeable
Definition at line 164 of file streams.c.
Referenced by stream_do_close_all().
int stream_exec_iterator (llist_t * node, void * param)
Linked list iterator that finds stream ptrs that are to be closed on execution of a new image.
Whether or not this is the case is determined by the pointer flag FD_CLOEXEC
Parameters
node The pointer to test
param UNUSED
Returns
Whether this ptr is to be closed on exec
Definition at line 138 of file streams.c.
References FD_CLOEXEC, and stream_ptr::fd_flags.
Referenced by stream_do_close_on_exec().
void stream_free_fd (int fd)
Free a fd handles.
Parameters
fd The handle to free
Todo:
: Implement fd reuse
Definition at line 214 of file streams.c.
Referenced by _sys_close_int(), _sys_dup(), _sys_open(), and _sys_pipe2().
stream_ptr_t* stream_get_ptr_o (process_info_t * process, int fd)
Get the stream pointer object for a file number on a different process.
Parameters
process The process context to use when looking up the stream pointer
fd The open file number to look up
Returns
The stream pointer or NULL if fd is invalid
Definition at line 66 of file streams.c.
References process_info::fd_table, llist_iterate_select(), and stream_ptr_search_iterator().
Referenced by _sys_close_int().
int stream_ptr_copy_iterator (llist_t * node, void * param)
Linked list iterator that copies a process's open fds.
This iterator will create a new stream pointer for each fd it is called on that refers to the same stream info
Parameters
node The linked list node we are called on (must be a stream_ptr_t *)
param The parameter for this iterator (must be a llist_t *head)
Returns
Whether to select this item, will always be 0 incase of success
Definition at line 82 of file streams.c.
References stream_ptr::fd_flags, heapmm_alloc(), stream_ptr::id, stream_ptr::info, llist_add_end(), and stream_info::ref_count.
Referenced by stream_copy_fd_table().
int stream_ptr_search_iterator (llist_t * node, void * param)
Iterator to test if stream pointer matches the fd.
Definition at line 40 of file streams.c.
References stream_ptr::id.
Referenced by stream_get_ptr(), and stream_get_ptr_o().