posnk kernel: include/kernel/streams.h File Reference
streams.h File Reference
#include "kernel/vfs.h"
#include "kernel/pipe.h"
#include "util/llist.h"
#include <sys/types.h>
Data Structures
struct stream_ptr
struct stream_info
Macros
#define STREAM_TYPE_FILE (0)
kernel/streams.h
#define STREAM_TYPE_PIPE (1)
Typedefs
typedef struct stream_info stream_info_t
typedef struct stream_ptr stream_ptr_t
Functions
stream_ptr_t * stream_get_ptr (int fd)
int stream_copy_fd_table (llist_t *target)
void stream_do_close_on_exec ()
void stream_do_close_all (process_info_t *process)
ssize_t _sys_read (int fd, void *buffer, size_t count)
ssize_t _sys_write (int fd, void *buffer, size_t count)
off_t _sys_lseek (int fd, off_t offset, int whence)
int _sys_fchdir (int fd)
int _sys_fchmod (int fd, mode_t mode)
int _sys_fchown (int fd, uid_t owner, gid_t group)
int _sys_fcntl (int fd, int cmd, int arg)
int _sys_ioctl (int fd, int cmd, int arg)
int _sys_dup2 (int oldfd, int newfd)
int _sys_dup (int oldfd)
int _sys_pipe2 (int pipefd[2], int flags)
int _sys_open (char *path, int flags, mode_t mode)
int _sys_close (int fd)
int _sys_fstat (int fd, struct stat *buf)
ssize_t _sys_getdents (int fd, void *buffer, size_t count)
int _sys_close_int (process_info_t *process, int fd)
int _sys_truncate (int fd, off_t size)
Macro Definition Documentation
#define STREAM_TYPE_FILE (0)
kernel/streams.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 20-04-2014 - Created
Definition at line 19 of file streams.h.
Referenced by _sys_close_int(), _sys_fchdir(), _sys_fchmod(), _sys_fchown(), _sys_fstat(), _sys_ftruncate(), _sys_getdents(), _sys_ioctl(), _sys_lseek(), _sys_open(), _sys_read(), and _sys_write().
#define STREAM_TYPE_PIPE (1)
Definition at line 20 of file streams.h.
Referenced by _sys_close_int(), _sys_ftruncate(), _sys_getdents(), _sys_pipe2(), _sys_read(), and _sys_write().
Typedef Documentation
typedef struct stream_info stream_info_t
Definition at line 22 of file streams.h.
typedef struct stream_ptr stream_ptr_t
Definition at line 24 of file streams.h.
Function Documentation
int _sys_close (int fd)
Definition at line 676 of file streams.c.
References _sys_close_int(), and scheduler_current_task.
Referenced by _sys_dup2(), stream_do_close_on_exec(), and sys_close().
int _sys_close_int (process_info_t * process, int fd)
Todo:
: Handle result
Todo:
: Handle result
Definition at line 681 of file streams.c.
References device_block_close(), device_char_close(), EBADF, inode::fifo, stream_info::flags, heapmm_free(), inode::if_dev, stream_ptr::info, stream_info::inode, llist_unlink(), stream_info::lock, inode::mode, O_ACCMODE, O_RDONLY, O_WRONLY, stream_info::pipe, pipe_close_read(), pipe_close_write(), pipe_free(), stream_info::ref_count, S_ISBLK, S_ISCHR, S_ISFIFO, scheduler_current_task, semaphore_down(), semaphore_up(), stream_get_ptr_o(), STREAM_TYPE_FILE, STREAM_TYPE_PIPE, syscall_errno, stream_info::type, and inode::usage_count.
Referenced by _sys_close(), and stream_do_close_all().
int _sys_dup (int oldfd)
Definition at line 491 of file streams.c.
References _sys_dup2(), process_info::fd_ctr, and scheduler_current_task.
Referenced by _sys_fcntl(), i386_init_stub(), and sys_dup().
int _sys_dup2 (int oldfd, int newfd)
Definition at line 461 of file streams.c.
References _sys_close(), EBADF, EMFILE, process_info::fd_ctr, stream_ptr::fd_flags, process_info::fd_table, heapmm_alloc(), stream_ptr::id, stream_ptr::info, llist_add_end(), stream_info::ref_count, scheduler_current_task, stream_get_ptr(), and syscall_errno.
Referenced by _sys_dup(), _sys_fcntl(), and sys_dup2().
int _sys_fchdir (int fd)
Definition at line 321 of file streams.c.
References process_info::current_directory, stream_info::dirc, EBADF, ENOTDIR, stream_ptr::info, stream_info::inode, inode::mode, S_ISDIR, scheduler_current_task, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, stream_info::type, and dir_cache::usage_count.
Referenced by sys_fchdir().
int _sys_fchmod (int fd, mode_t mode)
Definition at line 365 of file streams.c.
References EBADF, EPERM, get_effective_uid(), get_perm_class(), inode::gid, stream_ptr::info, stream_info::inode, inode::mode, PERM_CLASS_OWNER, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, stream_info::type, and inode::uid.
Referenced by sys_fchmod().
int _sys_fchown (int fd, uid_t owner, gid_t group)
Definition at line 387 of file streams.c.
References EBADF, EPERM, get_perm_class(), inode::gid, stream_ptr::info, stream_info::inode, PERM_CLASS_GROUP, PERM_CLASS_OWNER, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, stream_info::type, and inode::uid.
Referenced by sys_fchown().
int _sys_fcntl (int fd, int cmd, int arg)
Definition at line 411 of file streams.c.
References _sys_dup(), _sys_dup2(), EBADF, F_DUPFD, F_GETFD, F_GETFL, F_SETFD, F_SETFL, FASYNC, stream_ptr::fd_flags, stream_info::flags, stream_ptr::info, O_APPEND, O_NONBLOCK, stream_get_ptr(), and syscall_errno.
Referenced by sys_fcntl().
int _sys_fstat (int fd, struct stat * buf)
Todo:
: FIX
Todo:
: Implement sparse files
Todo:
: Ask FS about block size
Definition at line 338 of file streams.c.
References inode::atime, inode::ctime, inode::device_id, EBADF, inode::gid, inode::hard_link_count, inode::id, inode::if_dev, stream_ptr::info, stream_info::inode, inode::mode, inode::mtime, inode::size, stat::st_atime, stat::st_ctime, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_mtime, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, stream_info::type, and inode::uid.
Referenced by sys_fstat().
ssize_t _sys_getdents (int fd, void * buffer, size_t count)
Definition at line 98 of file streams.c.
References EBADF, EINVAL, ENOTDIR, stream_info::flags, stream_ptr::info, stream_info::inode, stream_info::lock, memset(), O_ACCMODE, O_WRONLY, stream_info::offset, semaphore_down(), semaphore_up(), inode::size, stream_get_ptr(), STREAM_TYPE_FILE, STREAM_TYPE_PIPE, syscall_errno, stream_info::type, and vfs_getdents().
Referenced by sys_getdents().
int _sys_ioctl (int fd, int cmd, int arg)
Definition at line 440 of file streams.c.
References device_block_ioctl(), device_char_ioctl(), EBADF, ENOTTY, inode::if_dev, stream_ptr::info, stream_info::inode, inode::mode, S_ISBLK, S_ISCHR, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, and stream_info::type.
Referenced by sys_ioctl().
off_t _sys_lseek (int fd, off_t offset, int whence)
Definition at line 270 of file streams.c.
References EBADF, EINVAL, ESPIPE, stream_ptr::info, stream_info::inode, stream_info::lock, inode::mode, stream_info::offset, S_ISFIFO, SEEK_CUR, SEEK_END, SEEK_SET, semaphore_down(), semaphore_up(), inode::size, stream_get_ptr(), STREAM_TYPE_FILE, syscall_errno, and stream_info::type.
Referenced by sys_lseek().
int _sys_open (char * path, int flags, mode_t mode)
Todo:
: Call on VFS to actually truncate file
Todo:
: Implement non-blocking IO
Todo:
: Handle result
Todo:
: Handle result
Definition at line 587 of file streams.c.
References device_block_open(), device_char_open(), stream_info::dirc, EBUSY, ENOENT, ENOMEM, FD_CLOEXEC, process_info::fd_ctr, stream_ptr::fd_flags, process_info::fd_table, inode::fifo, stream_info::flags, flags, heapmm_alloc(), heapmm_free(), stream_ptr::id, inode::if_dev, stream_ptr::info, stream_info::inode, dir_cache::inode, inode, llist_add_end(), stream_info::lock, inode::mode, O_ACCMODE, O_APPEND, O_CLOEXEC, O_CREAT, O_EXCL, O_NDELAY, O_NONBLOCK, O_RDONLY, O_TRUNC, O_WRONLY, stream_info::offset, pipe_open_read(), pipe_open_write(), stream_info::ref_count, S_IFREG, S_ISBLK, S_ISCHR, S_ISFIFO, scheduler_current_task, semaphore_alloc(), semaphore_up(), inode::size, STREAM_TYPE_FILE, syscall_errno, stream_info::type, inode::usage_count, vfs_find_dirc(), and vfs_mknod().
Referenced by i386_init_stub(), and sys_open().
int _sys_pipe2 (int pipefd[2], int flags)
Definition at line 496 of file streams.c.
References ENOMEM, process_info::fd_ctr, stream_ptr::fd_flags, process_info::fd_table, stream_info::flags, heapmm_alloc(), heapmm_free(), stream_ptr::id, stream_ptr::info, llist_add_end(), stream_info::lock, O_RDONLY, O_WRONLY, stream_info::offset, stream_info::pipe, pipe_create(), pipe_free(), pipe_open_read(), pipe_open_write(), stream_info::ref_count, scheduler_current_task, semaphore_alloc(), semaphore_free(), semaphore_up(), STREAM_TYPE_PIPE, syscall_errno, and stream_info::type.
Referenced by sys_pipe(), and sys_pipe2().
ssize_t _sys_read (int fd, void * buffer, size_t count)
Definition at line 142 of file streams.c.
References EBADF, EINVAL, EPIPE, stream_info::flags, stream_ptr::info, stream_info::inode, stream_info::lock, memset(), inode::mode, O_ACCMODE, O_NONBLOCK, O_WRONLY, stream_info::offset, stream_info::pipe, pipe_read(), process_send_signal(), S_ISREG, scheduler_current_task, semaphore_down(), semaphore_up(), SIGPIPE, inode::size, stream_get_ptr(), STREAM_TYPE_FILE, STREAM_TYPE_PIPE, syscall_errno, stream_info::type, and vfs_read().
Referenced by sys_read().
int _sys_truncate (int fd, off_t size)
ssize_t _sys_write (int fd, void * buffer, size_t count)
Definition at line 192 of file streams.c.
References EBADF, EINVAL, EPIPE, stream_info::flags, stream_ptr::info, stream_info::inode, stream_info::lock, O_ACCMODE, O_NONBLOCK, O_RDONLY, stream_info::offset, stream_info::pipe, pipe_write(), process_send_signal(), scheduler_current_task, semaphore_down(), semaphore_up(), SIGPIPE, stream_get_ptr(), STREAM_TYPE_FILE, STREAM_TYPE_PIPE, syscall_errno, stream_info::type, and vfs_write().
Referenced by sys_write().
int stream_copy_fd_table (llist_t * target)
Definition at line 62 of file streams.c.
References process_info::fd_table, llist_iterate_select(), NULL, scheduler_current_task, and stream_ptr_copy_iterator().
Referenced by scheduler_fork().
void stream_do_close_all (process_info_t * process)
Definition at line 86 of file streams.c.
References _sys_close_int(), process_info::fd_table, stream_ptr::id, llist_iterate_select(), NULL, and stream_closeall_iterator().
Referenced by process_reap().
void stream_do_close_on_exec ()
Definition at line 73 of file streams.c.
References _sys_close(), process_info::fd_table, stream_ptr::id, llist_iterate_select(), NULL, scheduler_current_task, and stream_exec_iterator().
Referenced by process_exec().
stream_ptr_t* stream_get_ptr (int fd)
Definition at line 35 of file streams.c.
References process_info::fd_table, llist_iterate_select(), scheduler_current_task, and stream_ptr_search_iterator().
Referenced by _sys_dup2(), _sys_fchdir(), _sys_fchmod(), _sys_fchown(), _sys_fcntl(), _sys_fstat(), _sys_ftruncate(), _sys_getdents(), _sys_ioctl(), _sys_lseek(), _sys_read(), and _sys_write().