posnk kernel: crt/string.c File Reference
string.c File Reference
#include <string.h>
Functions
char * strchr (const char *str, int c)
char * strrchr (const char *str, int c)
char * strchrnul (const char *str, int c)
size_t strlen (const char *str)
void * memset (void *ptr, int value, size_t num)
void * memcpy (void *destination, const void *source, size_t num)
char * strcpy (char *destination, const char *source)
char * strncpy (char *dest, const char *src, size_t n)
void * memcpy_o (void *dst_ptr, const void *src_ptr, size_t count, void *buf)
int strcmp (const char *str1, const char *str2)
int strncmp (const char *str1, const char *str2, size_t num)
int startswith (const char *str1, const char *str2)
char * strcat (char *s, const char *append)
char * strtok (char *s, const char *delim)
Function Documentation
void* memcpy (void * destination, const void * source, size_t num)
Definition at line 55 of file string.c.
Referenced by copy_kern_to_user(), copy_user_to_kern(), device_block_read(), device_block_write(), ext2_finddir(), i386_fpu_load(), i386_fpu_save(), interpret_csi_DL(), interpret_csi_IL(), memcpy_o(), pipe_read(), pipe_write(), process_push_user_data(), ramfs_read_inode(), ramfs_readdir(), ramfs_write_inode(), scheduler_exsig(), scheduler_fork(), scheduler_invoke_signal_handler(), strcpy(), vterm_scroll_down(), and vterm_scroll_up().
void* memcpy_o (void * dst_ptr, const void * src_ptr, size_t count, void * buf)
Definition at line 83 of file string.c.
References memcpy().
Referenced by pipe_read().
void* memset (void * ptr, int value, size_t num)
Definition at line 45 of file string.c.
Referenced by blkcache_get(), device_block_init(), device_char_init(), heapmm_alloc_internal(), heapmm_free_internal(), i386_idt_set_descriptor(), i386_protection_init(), i386_set_tss_descriptor(), kdbgmm_alloc_internal(), kdbgmm_free_internal(), paging_create_dir(), paging_init(), paging_map(), process_exec(), procvmm_handle_fault(), ramfs_load_inode(), ramfs_trunc_inode(), scheduler_fork(), scheduler_fork_to(), scheduler_init(), scheduler_invoke_signal_handler(), sys_getdents(), sys_read(), vfs_mknod(), vfs_symlink(), vfs_write(), vgacon_clear_line(), vgacon_clear_video(), vgacon_early_clear_line(), and vgacon_early_clear_video().
int startswith (const char * str1, const char * str2)
Definition at line 115 of file string.c.
References strlen(), and strncmp().
char* strcat (char * s, const char * append)
Definition at line 119 of file string.c.
char* strchr (const char * str, int c)
Definition at line 4 of file string.c.
References NULL.
Referenced by vfs_find_dirc(), vfs_find_dirc_parent(), and vterm_put_char().
char* strchrnul (const char * str, int c)
Definition at line 29 of file string.c.
Referenced by vfs_find_dirc(), and vfs_find_dirc_parent().
int strcmp (const char * str1, const char * str2)
Definition at line 89 of file string.c.
References strlen().
Referenced by ext2_finddir(), ramfs_dirent_search_iterator(), tar_read_record(), and tar_read_record_mem().
char* strcpy (char * destination, const char * source)
Definition at line 65 of file string.c.
References memcpy(), and strlen().
Referenced by elf_load(), ext2_e2tovfs_inode(), i386_idle_task(), process_exec(), procvmm_mmap_anon(), procvmm_mmap_copy_iterator(), procvmm_mmap_file(), ramfs_link(), scheduler_fork(), scheduler_init(), vfs_get_filename(), vfs_mknod(), and vfs_symlink().
size_t strlen (const char * str)
Definition at line 38 of file string.c.
Referenced by _sys_lstat(), _sys_readlink(), earlycon_ivprintf(), elf_load(), kdbg_parsehex(), process_exec(), procvmm_mmap_anon(), procvmm_mmap_copy_iterator(), procvmm_mmap_file(), procvmm_unmmap(), startswith(), strcmp(), strcpy(), strncmp(), strrchr(), tar_read_record(), tar_read_record_mem(), vfs_find_symlink(), vfs_get_filename(), vfs_link(), vfs_mknod(), vfs_symlink(), vfs_unlink(), vgacon_parse_par(), vterm_write_rxvt(), and vterm_write_vt100().
int strncmp (const char * str1, const char * str2, size_t num)
Definition at line 102 of file string.c.
References strlen().
Referenced by kdbg_shell(), startswith(), vfs_find_dirc(), and vfs_find_dirc_parent().
char* strncpy (char * dest, const char * src, size_t n)
Definition at line 70 of file string.c.
Referenced by _sys_readlink(), vfs_find_dirc(), and vfs_find_dirc_parent().
char* strrchr (const char * str, int c)
Definition at line 17 of file string.c.
References NULL, and strlen().
Referenced by vfs_get_filename().
char* strtok (char * s, const char * delim)
Definition at line 129 of file string.c.