posnk kernel: blk_ops Struct Reference
blk_ops Struct Reference
#include <device.h>
Data Fields
int(* open)(dev_t, int, int)
int(* close)(dev_t, int)
int(* write)(dev_t, aoff_t, void *)
int(* read)(dev_t, aoff_t, void *)
int(* ioctl)(dev_t, int, int, int)
Detailed Description
Definition at line 48 of file device.h.
Field Documentation
int(* blk_ops::close)(dev_t, int)
Definition at line 50 of file device.h.
Referenced by device_block_close().
int(* blk_ops::ioctl)(dev_t, int, int, int)
Definition at line 53 of file device.h.
Referenced by device_block_ioctl().
int(* blk_ops::open)(dev_t, int, int)
Definition at line 49 of file device.h.
Referenced by device_block_open().
int(* blk_ops::read)(dev_t, aoff_t, void *)
Definition at line 52 of file device.h.
Referenced by device_block_fetch().
int(* blk_ops::write)(dev_t, aoff_t, void *)
Definition at line 51 of file device.h.
Referenced by device_block_flush().
The documentation for this struct was generated from the following file:
include/kernel/device.h