posnk kernel: fs_device_operations Struct Reference
fs_device_operations Struct Reference
Contains callbacks for all filesystem driver functions.
#include <vfs.h>
Data Fields
inode_t *(* load_inode)(fs_device_t *, ino_t)
Load an inode from storage.
int(* store_inode)(inode_t *)
Write an inode to storage.
int(* mknod)(inode_t *)
Create an inode.
int(* rmnod)(inode_t *)
Delete an inode.
int(* read_inode)(inode_t *, void *, aoff_t, aoff_t, aoff_t *)
Read data from a file.
int(* write_inode)(inode_t *, void *, aoff_t, aoff_t, aoff_t *)
Write data to a file.
int(* read_dir)(inode_t *, void *, aoff_t, aoff_t, aoff_t *)
Read directory entries from backing storage.
dirent_t *(* find_dirent)(inode_t *, char *)
Find a directory entry.
int(* mkdir)(inode_t *)
Create directory structures.
int(* link)(inode_t *, char *, ino_t)
Create a directory entry.
int(* unlink)(inode_t *, char *)
Delete a directory entry.
int(* trunc_inode)(inode_t *, aoff_t)
Resize a file.
Detailed Description
Contains callbacks for all filesystem driver functions.
This is the structure used to pass the callbacks for a filesystem driver to the kernel, it is referenced by fs_device, which describes an instance of a filesystem driver, implementation hints and requirements are given in the description of each callback, for more info on FS driver implementation see fs_device
Definition at line 104 of file vfs.h.
Field Documentation
dirent_t*(* fs_device_operations::find_dirent)(inode_t *, char *)
Find a directory entry.
REQUIRED
Warning
Implementations must not modify the inode metadata from this function
Parameters
inode The directory to search
name The filename to match
Returns
The directory entry matching name from the directory inode, if none, NULL is returned
Definition at line 221 of file vfs.h.
Referenced by ramfs_create(), and vfs_find_dirent().
int(* fs_device_operations::link)(inode_t *, char *, ino_t)
Create a directory entry.
Warning
Implementations must not modify the inode metadata from this function, except for the size field
Implementations are required to update the directory size field
Parameters
inode The inode for the directory
name The file name for the directory entry
nod_id The inode id that the directory entry will point to
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 250 of file vfs.h.
Referenced by ramfs_create(), and vfs_int_link().
inode_t*(* fs_device_operations::load_inode)(fs_device_t *, ino_t)
Load an inode from storage.
REQUIRED
Implementations of this function must fill ALL inode fields relevant to the file type, this includes instance fields such as lock
Parameters
inode The inode id to load
Returns
The loaded inode
Definition at line 116 of file vfs.h.
Referenced by ramfs_create(), vfs_get_inode(), vfs_initialize(), and vfs_mount().
int(* fs_device_operations::mkdir)(inode_t *)
Create directory structures.
Warning
Implementations must not modify the inode metadata from this function
Implementations are not required to implement this function but must provide a stub to allow directories to be created
Parameters
inode The inode for the new directory
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 234 of file vfs.h.
Referenced by ramfs_create(), and vfs_int_mkdir().
int(* fs_device_operations::mknod)(inode_t *)
Create an inode.
Warning
Implementations must not depend on any fields in inode being valid
Implementations must fill inode->id
Parameters
inode The inode to create
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 139 of file vfs.h.
Referenced by ramfs_create(), and vfs_int_mknod().
int(* fs_device_operations::read_dir)(inode_t *, void *, aoff_t, aoff_t, aoff_t *)
Read directory entries from backing storage.
REQUIRED
Warning
Implementations must not modify the inode metadata from this function
Implementations must only return whole directory entries
Parameters
inode The inode for the directory
buffer The buffer to store the entries in
file_offset The offset in the directory to start reading at
count The number of bytes to read
nread A pointer to a variable in which the number of bytes read will be stored
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 207 of file vfs.h.
Referenced by ramfs_create(), and vfs_int_read_dir().
int(* fs_device_operations::read_inode)(inode_t *, void *, aoff_t, aoff_t, aoff_t *)
Read data from a file.
REQUIRED
Warning
Implementations must not modify the inode metadata from this function
Note
The VFS will adjust count so that the whole requested area is in the file
Parameters
inode The inode for the file
buffer The buffer to store the data in
file_offset The offset in the file to start reading at
count The number of bytes to read
nread A pointer to a variable in which the number of bytes read will be stored
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 171 of file vfs.h.
Referenced by ramfs_create(), and vfs_int_read().
int(* fs_device_operations::rmnod)(inode_t *)
Delete an inode.
Warning
Implementations must not modify the inode metadata from this function
Implementations are recommended to free any data associated with the inode
Parameters
inode The inode to delete
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 152 of file vfs.h.
Referenced by ramfs_create(), and vfs_int_rmnod().
int(* fs_device_operations::store_inode)(inode_t *)
Write an inode to storage.
Warning
Implementations must not modify the inode metadata from this function
Parameters
inode The inode to write
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 127 of file vfs.h.
int(* fs_device_operations::trunc_inode)(inode_t *, aoff_t)
Resize a file.
Warning
Implementations must not modify the inode metadata from this function Implementations must fill the newly created space with zeroes and free any truncated space
Parameters
inode The inode for the file
size The new size of the file
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 276 of file vfs.h.
Referenced by ramfs_create(), and vfs_int_truncate().
int(* fs_device_operations::unlink)(inode_t *, char *)
Delete a directory entry.
Warning
Implementations must not modify the inode metadata from this function, except for the size field
Implementations are required to update the directory size field
Parameters
inode - The inode for the directory
name - The file name of the directory entry to delete
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 263 of file vfs.h.
Referenced by ramfs_create(), and vfs_int_unlink().
int(* fs_device_operations::write_inode)(inode_t *, void *, aoff_t, aoff_t, aoff_t *)
Write data to a file.
Warning
Implementations must not modify the inode metadata from this function
Note
The VFS layer will automatically adjust file size
Parameters
inode The inode for the file
buffer The buffer containing the data to write
file_offset The offset in the file to start writing at
count The number of bytes to write
nwritten A pointer to a variable in which the number of bytes written will be stored
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 188 of file vfs.h.
Referenced by ramfs_create(), and vfs_int_write().
The documentation for this struct was generated from the following file:
include/kernel/vfs.h