posnk kernel: include/kernel/syscall.h File Reference
syscall.h File Reference
#include <stddef.h>
#include <stdint.h>
#include "kernel/scheduler.h"
#include "kernel/syscall_ids.h"
Typedefs
typedef uint32_t(* syscall_func_t)(uint32_t[4], uint32_t[4])
kernel/syscall.h
Functions
void syscall_init ()
void syscall_register (int call_id, syscall_func_t func)
void syscall_dispatch (void *user_param_block, void *instr_ptr)
int copy_user_to_kern (void *src, void *dest, size_t size)
int copy_kern_to_user (void *src, void *dest, size_t size)
uint32_t sys_fork (uint32_t param[4], uint32_t param_size[4])
kernel/sc_process.c
uint32_t sys_kill (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_getpid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_getppid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_getpgrp (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_setsid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_exit (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_yield (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_sbrk (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_getuid (uint32_t param[4], uint32_t param_size[4])
kernel/sc_process.c
uint32_t sys_geteuid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_getgid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_getegid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_link (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_unlink (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_chdir (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_chmod (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_chown (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_mknod (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_mkdir (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_stat (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_fchdir (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_fchmod (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_fchown (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_fstat (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_dup2 (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_dup (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_open (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_close (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_pipe2 (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_pipe (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_read (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_write (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_lseek (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_rmdir (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_execve (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_waitpid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_fcntl (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_umask (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_readlink (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_lstat (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_symlink (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_getdents (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_ioctl (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_getsid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_setpgrp (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_setpgid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_time (uint32_t param[4], uint32_t param_size[4])
kernel/sc_time.c
uint32_t sys_usleep (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_sleep (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_stime (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_setuid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_setgid (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_signal (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_exitsig (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_sigprocmask (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_ssigex (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_dbgdrop (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_mount (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_ftruncate (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_truncate (uint32_t param[4], uint32_t param_size[4])
Typedef Documentation
typedef uint32_t(* syscall_func_t)(uint32_t[4], uint32_t[4])
kernel/syscall.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 07-04-2014 - Created
Definition at line 19 of file syscall.h.
Function Documentation
int copy_kern_to_user (void * src, void * dest, size_t size)
Definition at line 107 of file syscall.c.
References memcpy(), and procvmm_check().
Referenced by sys_fstat(), sys_getdents(), sys_lstat(), sys_pipe(), sys_pipe2(), sys_read(), sys_readlink(), sys_sigprocmask(), sys_stat(), sys_waitpid(), syscall_dispatch(), and tty_ioctl().
int copy_user_to_kern (void * src, void * dest, size_t size)
Definition at line 99 of file syscall.c.
References memcpy(), and procvmm_check().
Referenced by debug_uputs(), sys_chdir(), sys_chmod(), sys_chown(), sys_execve(), sys_link(), sys_lstat(), sys_mkdir(), sys_mknod(), sys_mount(), sys_open(), sys_readlink(), sys_rmdir(), sys_sigprocmask(), sys_stat(), sys_stime(), sys_symlink(), sys_truncate(), sys_unlink(), sys_waitpid(), sys_write(), syscall_dispatch(), and tty_ioctl().
uint32_t sys_chdir (uint32_t param[4], uint32_t param_size[4])
Definition at line 172 of file sc_vfs.c.
References _sys_chdir(), CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_chmod (uint32_t param[4], uint32_t param_size[4])
Definition at line 211 of file sc_vfs.c.
References _sys_chmod(), CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_chown (uint32_t param[4], uint32_t param_size[4])
Definition at line 253 of file sc_vfs.c.
References _sys_chown(), CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_close (uint32_t param[4], uint32_t param_size[4])
Definition at line 106 of file sc_streams.c.
References _sys_close().
Referenced by syscall_init().
uint32_t sys_dbgdrop (uint32_t param[4], uint32_t param_size[4])
Definition at line 130 of file syscall.c.
References dbgapi_invoke_kdbg().
Referenced by syscall_init().
uint32_t sys_dup (uint32_t param[4], uint32_t param_size[4])
Definition at line 80 of file sc_streams.c.
References _sys_dup().
Referenced by syscall_init().
uint32_t sys_dup2 (uint32_t param[4], uint32_t param_size[4])
Definition at line 74 of file sc_streams.c.
References _sys_dup2().
Referenced by syscall_init().
uint32_t sys_execve (uint32_t param[4], uint32_t param_size[4])
Definition at line 327 of file sc_process.c.
References CONFIG_FILE_MAX_NAME_LENGTH, CONFIG_MAX_ARGV_LEN, CONFIG_MAX_ENV_LEN, copy_user_to_kern(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), process_exec(), strlistlen(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_exit (uint32_t param[4], uint32_t param_size[4])
Definition at line 134 of file sc_process.c.
References process_child_event(), PROCESS_CHILD_KILLED, PROCESS_KILLED, procvmm_clear_mmaps(), schedule(), scheduler_current_task, and process_info::state.
Referenced by syscall_init().
uint32_t sys_exitsig (uint32_t param[4], uint32_t param_size[4])
Definition at line 47 of file sc_signals.c.
References scheduler_exit_signal_handler().
Referenced by syscall_init().
uint32_t sys_fchdir (uint32_t param[4], uint32_t param_size[4])
Definition at line 23 of file sc_streams.c.
References _sys_fchdir().
Referenced by syscall_init().
uint32_t sys_fchmod (uint32_t param[4], uint32_t param_size[4])
Definition at line 30 of file sc_streams.c.
References _sys_fchmod().
Referenced by syscall_init().
uint32_t sys_fchown (uint32_t param[4], uint32_t param_size[4])
Definition at line 36 of file sc_streams.c.
References _sys_fchown().
Referenced by syscall_init().
uint32_t sys_fcntl (uint32_t param[4], uint32_t param_size[4])
Definition at line 42 of file sc_streams.c.
References _sys_fcntl().
Referenced by syscall_init().
uint32_t sys_fork (uint32_t param[4], uint32_t param_size[4])
kernel/sc_process.c
Part of P-OS kernel.
Contains process related syscalls
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 07-04-2014 - Created
Definition at line 23 of file sc_process.c.
References scheduler_fork().
Referenced by syscall_init().
uint32_t sys_fstat (uint32_t param[4], uint32_t param_size[4])
Definition at line 54 of file sc_streams.c.
References _sys_fstat(), buf, copy_kern_to_user(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_ftruncate (uint32_t param[4], uint32_t param_size[4])
Definition at line 206 of file sc_streams.c.
References _sys_ftruncate().
Referenced by syscall_init().
uint32_t sys_getdents (uint32_t param[4], uint32_t param_size[4])
Definition at line 138 of file sc_streams.c.
References _sys_getdents(), buf, copy_kern_to_user(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), memset(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_getegid (uint32_t param[4], uint32_t param_size[4])
Definition at line 39 of file sc_perm.c.
References process_info::effective_gid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_geteuid (uint32_t param[4], uint32_t param_size[4])
Definition at line 29 of file sc_perm.c.
References process_info::effective_uid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_getgid (uint32_t param[4], uint32_t param_size[4])
Definition at line 34 of file sc_perm.c.
References process_info::gid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_getpgrp (uint32_t param[4], uint32_t param_size[4])
Definition at line 80 of file sc_process.c.
References process_info::pgid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_getpid (uint32_t param[4], uint32_t param_size[4])
Definition at line 70 of file sc_process.c.
References process_info::pid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_getppid (uint32_t param[4], uint32_t param_size[4])
Definition at line 75 of file sc_process.c.
References process_info::parent_pid, and scheduler_current_task.
Referenced by syscall_init().
uint32_t sys_getsid (uint32_t param[4], uint32_t param_size[4])
Definition at line 85 of file sc_process.c.
References scheduler_current_task, and process_info::sid.
Referenced by syscall_init().
uint32_t sys_getuid (uint32_t param[4], uint32_t param_size[4])
kernel/sc_process.c
Part of P-OS kernel.
Contains process related syscalls
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 07-04-2014 - Created
Definition at line 24 of file sc_perm.c.
References scheduler_current_task, and process_info::uid.
Referenced by syscall_init().
uint32_t sys_ioctl (uint32_t param[4], uint32_t param_size[4])
Definition at line 48 of file sc_streams.c.
References _sys_ioctl().
Referenced by syscall_init().
uint32_t sys_kill (uint32_t param[4], uint32_t param_size[4])
Todo:
: Implement kill all system processes
Definition at line 28 of file sc_process.c.
References EINVAL, EPERM, ESRCH, get_perm_class(), process_info::gid, NULL, PERM_CLASS_OWNER, process_info::pgid, process_get(), process_send_signal(), process_signal_pgroup(), scheduler_current_task, syscall_errno, and process_info::uid.
Referenced by syscall_init().
uint32_t sys_link (uint32_t param[4], uint32_t param_size[4])
Definition at line 23 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_link().
Referenced by syscall_init().
uint32_t sys_lseek (uint32_t param[4], uint32_t param_size[4])
Definition at line 200 of file sc_streams.c.
References _sys_lseek().
Referenced by syscall_init().
uint32_t sys_lstat (uint32_t param[4], uint32_t param_size[4])
Definition at line 499 of file sc_vfs.c.
References _sys_lstat(), buf, CONFIG_FILE_MAX_NAME_LENGTH, copy_kern_to_user(), copy_user_to_kern(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_mkdir (uint32_t param[4], uint32_t param_size[4])
Definition at line 338 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_mkdir().
Referenced by syscall_init().
uint32_t sys_mknod (uint32_t param[4], uint32_t param_size[4])
Definition at line 314 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_mknod().
Referenced by syscall_init().
uint32_t sys_mount (uint32_t param[4], uint32_t param_size[4])
Definition at line 55 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_mount().
Referenced by syscall_init().
uint32_t sys_open (uint32_t param[4], uint32_t param_size[4])
Definition at line 86 of file sc_streams.c.
References _sys_open(), CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_pipe (uint32_t param[4], uint32_t param_size[4])
Definition at line 125 of file sc_streams.c.
References _sys_pipe2(), copy_kern_to_user(), EFAULT, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_pipe2 (uint32_t param[4], uint32_t param_size[4])
Definition at line 112 of file sc_streams.c.
References _sys_pipe2(), copy_kern_to_user(), EFAULT, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_read (uint32_t param[4], uint32_t param_size[4])
Definition at line 159 of file sc_streams.c.
References _sys_read(), buf, copy_kern_to_user(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), memset(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_readlink (uint32_t param[4], uint32_t param_size[4])
Definition at line 436 of file sc_vfs.c.
References _sys_readlink(), buf, CONFIG_FILE_MAX_NAME_LENGTH, copy_kern_to_user(), copy_user_to_kern(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_rmdir (uint32_t param[4], uint32_t param_size[4])
Definition at line 531 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_rmdir().
Referenced by syscall_init().
uint32_t sys_sbrk (uint32_t param[4], uint32_t param_size[4])
Todo:
: Handle decreasing heap size
Definition at line 287 of file sc_process.c.
References ENOMEM, process_info::heap_end, process_info::heap_max, process_info::heap_start, PHYSMM_PAGE_ADDRESS_MASK, PHYSMM_PAGE_SIZE, PROCESS_MMAP_FLAG_HEAP, PROCESS_MMAP_FLAG_WRITE, procvmm_mmap_anon(), procvmm_resize_map(), scheduler_current_task, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_setgid (uint32_t param[4], uint32_t param_size[4])
Definition at line 55 of file sc_perm.c.
References process_info::effective_gid, EPERM, process_info::gid, scheduler_current_task, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_setpgid (uint32_t param[4], uint32_t param_size[4])
Todo:
: FIX PERMS
Definition at line 112 of file sc_process.c.
References EINVAL, ESRCH, process_info::pgid, process_info::pid, process_get(), scheduler_current_task, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_setpgrp (uint32_t param[4], uint32_t param_size[4])
Definition at line 102 of file sc_process.c.
References EPERM, process_info::pgid, process_info::pid, scheduler_current_task, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_setsid (uint32_t param[4], uint32_t param_size[4])
Definition at line 90 of file sc_process.c.
References process_info::ctty, EPERM, process_info::pgid, process_info::pid, scheduler_current_task, process_info::sid, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_setuid (uint32_t param[4], uint32_t param_size[4])
Definition at line 44 of file sc_perm.c.
References process_info::effective_uid, EPERM, scheduler_current_task, syscall_errno, and process_info::uid.
Referenced by syscall_init().
uint32_t sys_signal (uint32_t param[4], uint32_t param_size[4])
Definition at line 28 of file sc_signals.c.
References EINVAL, scheduler_current_task, SIG_ERR, process_info::signal_handler_table, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_sigprocmask (uint32_t param[4], uint32_t param_size[4])
Definition at line 53 of file sc_signals.c.
References copy_kern_to_user(), copy_user_to_kern(), EFAULT, scheduler_current_task, SIG_BLOCK, SIG_SETMASK, SIG_UNBLOCK, process_info::signal_mask_bitmap, and syscall_errno.
Referenced by syscall_init().
uint32_t sys_sleep (uint32_t param[4], uint32_t param_size[4])
Definition at line 25 of file sc_time.c.
References EINTR, scheduler_wait_time(), syscall_errno, and system_time.
Referenced by syscall_init().
uint32_t sys_ssigex (uint32_t param[4], uint32_t param_size[4])
Definition at line 41 of file sc_signals.c.
References scheduler_current_task, and process_info::signal_handler_exit_func.
Referenced by syscall_init().
uint32_t sys_stat (uint32_t param[4], uint32_t param_size[4])
Definition at line 385 of file sc_vfs.c.
References _sys_stat(), buf, CONFIG_FILE_MAX_NAME_LENGTH, copy_kern_to_user(), copy_user_to_kern(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_stime (uint32_t param[4], uint32_t param_size[4])
Definition at line 43 of file sc_time.c.
References copy_user_to_kern(), EFAULT, EPERM, get_effective_uid(), syscall_errno, system_time, and system_time_micros.
Referenced by syscall_init().
uint32_t sys_symlink (uint32_t param[4], uint32_t param_size[4])
Definition at line 98 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_symlink().
Referenced by syscall_init().
uint32_t sys_time (uint32_t param[4], uint32_t param_size[4])
kernel/sc_time.c
Part of P-OS kernel.
Contains process related syscalls
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 24-05-2014 - Created
Definition at line 20 of file sc_time.c.
References system_time.
Referenced by syscall_init().
uint32_t sys_truncate (uint32_t param[4], uint32_t param_size[4])
Definition at line 287 of file sc_vfs.c.
References _sys_truncate(), CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_umask (uint32_t param[4], uint32_t param_size[4])
Definition at line 306 of file sc_vfs.c.
References scheduler_current_task, and process_info::umask.
Referenced by syscall_init().
uint32_t sys_unlink (uint32_t param[4], uint32_t param_size[4])
Definition at line 131 of file sc_vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, copy_user_to_kern(), EFAULT, heapmm_alloc(), heapmm_free(), syscall_errno, and vfs_unlink().
Referenced by syscall_init().
uint32_t sys_usleep (uint32_t param[4], uint32_t param_size[4])
Definition at line 34 of file sc_time.c.
References EINTR, scheduler_wait_micros(), syscall_errno, and system_time_micros.
Referenced by syscall_init().
uint32_t sys_waitpid (uint32_t param[4], uint32_t param_size[4])
Todo:
: Determine whether pgroup exists
Todo:
: Implement this in libc, linux only hehehe
Definition at line 153 of file sc_process.c.
References process_info::child_events, process_child_event::child_pid, process_info::child_sema, copy_kern_to_user(), copy_user_to_kern(), debugcon_aprintf(), ECHILD, EFAULT, EINTR, process_child_event::event, process_info::exit_status, process_info::last_signal, llist_get_last(), process_info::pid, process_absorb_event(), PROCESS_CHILD_CONTD, PROCESS_CHILD_KILLED, PROCESS_CHILD_STOPPED, process_get(), process_get_event(), process_get_event_pg(), process_reap(), PROCESS_TERM_EXIT, PROCESS_TERM_SIGNAL, scheduler_current_task, semaphore_idown(), syscall_errno, process_info::term_cause, WNOHANG, and WUNTRACED.
Referenced by i386_kmain(), and syscall_init().
uint32_t sys_write (uint32_t param[4], uint32_t param_size[4])
Definition at line 180 of file sc_streams.c.
References _sys_write(), buf, copy_user_to_kern(), EFAULT, ENOMEM, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_yield (uint32_t param[4], uint32_t param_size[4])
Definition at line 143 of file sc_process.c.
References schedule().
Referenced by syscall_init().
void syscall_dispatch (void * user_param_block, void * instr_ptr)
Definition at line 137 of file syscall.c.
References syscall_params::call_id, CONFIG_MAX_SYSCALL_COUNT, copy_kern_to_user(), copy_user_to_kern(), curpid(), debugcon_printf, syscall_params::magic, process_info::name, NULL, syscall_params::param, syscall_params::param_size, process_handle_signals(), process_send_signal(), syscall_params::return_val, syscall_params::sc_errno, scheduler_current_task, SIGSEGV, SIGSYS, SYS_OPEN, SYS_STAT, syscall_errno, SYSCALL_MAGIC, syscall_names, and syscall_table.
Referenced by i386_handle_interrupt().
void syscall_init ()
Definition at line 170 of file syscall.c.
References debug_uputs(), SYS_CHDIR, sys_chdir(), SYS_CHMOD, sys_chmod(), SYS_CHOWN, sys_chown(), SYS_CLOSE, sys_close(), SYS_DBGDROP, sys_dbgdrop(), SYS_DUP, sys_dup(), SYS_DUP2, sys_dup2(), SYS_EXECVE, sys_execve(), SYS_EXIT, sys_exit(), sys_exitsig(), SYS_EXITSIG, sys_fchdir(), SYS_FCHDIR, sys_fchmod(), SYS_FCHMOD, sys_fchown(), SYS_FCHOWN, sys_fcntl(), SYS_FCNTL, sys_fork(), SYS_FORK, SYS_FSTAT, sys_fstat(), SYS_FTRUNCATE, sys_ftruncate(), SYS_GETDENTS, sys_getdents(), sys_getegid(), SYS_GETEGID, sys_geteuid(), SYS_GETEUID, sys_getgid(), SYS_GETGID, SYS_GETPGRP, sys_getpgrp(), SYS_GETPID, sys_getpid(), SYS_GETPPID, sys_getppid(), SYS_GETSID, sys_getsid(), sys_getuid(), SYS_GETUID, sys_ioctl(), SYS_IOCTL, sys_kill(), SYS_KILL, sys_link(), SYS_LINK, SYS_LSEEK, sys_lseek(), SYS_LSTAT, sys_lstat(), SYS_MKDIR, sys_mkdir(), SYS_MKNOD, sys_mknod(), sys_mount(), SYS_MOUNT, SYS_OPEN, sys_open(), SYS_PIPE, sys_pipe(), SYS_PIPE2, sys_pipe2(), SYS_READ, sys_read(), SYS_READLINK, sys_readlink(), SYS_RMDIR, sys_rmdir(), SYS_SBRK, sys_sbrk(), sys_setgid(), SYS_SETGID, SYS_SETPGID, sys_setpgid(), SYS_SETPGRP, sys_setpgrp(), SYS_SETSID, sys_setsid(), sys_setuid(), SYS_SETUID, sys_signal(), SYS_SIGNAL, sys_sigprocmask(), SYS_SIGPROCMASK, sys_sleep(), SYS_SLEEP, sys_ssigex(), SYS_SSIGEX, SYS_STAT, sys_stat(), sys_stime(), SYS_STIME, SYS_SYMLINK, sys_symlink(), sys_time(), SYS_TIME, SYS_TRUNCATE, sys_truncate(), SYS_UMASK, sys_umask(), SYS_UNLINK, sys_unlink(), sys_usleep(), SYS_USLEEP, SYS_WAITPID, sys_waitpid(), SYS_WRITE, sys_write(), SYS_YIELD, sys_yield(), and syscall_register().
Referenced by i386_kmain().
void syscall_register (int call_id, syscall_func_t func)
Todo:
: Find way to free syscall buffers after signal kill
Definition at line 94 of file syscall.c.
References syscall_table.
Referenced by syscall_init().