posnk kernel: kernel/syscall.c File Reference
syscall.c File Reference
#include <string.h>
#include <stddef.h>
#include "kernel/heapmm.h"
#include "kernel/process.h"
#include "kernel/scheduler.h"
#include "kernel/signals.h"
#include "kernel/paging.h"
#include "kernel/syscall.h"
#include "kernel/earlycon.h"
#include "kdbg/dbgapi.h"
#include "config.h"
Functions
void syscall_register (int call_id, syscall_func_t func)
int copy_user_to_kern (void *src, void *dest, size_t size)
int copy_kern_to_user (void *src, void *dest, size_t size)
uint32_t debug_uputs (uint32_t param[4], uint32_t param_size[4])
uint32_t sys_dbgdrop (uint32_t param[4], uint32_t param_size[4])
int curpid ()
void syscall_dispatch (void *user_param_block, void *instr_ptr)
void syscall_init ()
Variables
char * syscall_names []
kernel/syscall.c
syscall_func_t syscall_table [CONFIG_MAX_SYSCALL_COUNT]
Function Documentation
int copy_kern_to_user (void * src, void * dest, size_t size)
Definition at line 107 of file syscall.c.
References memcpy(), and procvmm_check().
Referenced by sys_fstat(), sys_getdents(), sys_lstat(), sys_pipe(), sys_pipe2(), sys_read(), sys_readlink(), sys_sigprocmask(), sys_stat(), sys_waitpid(), syscall_dispatch(), and tty_ioctl().
int copy_user_to_kern (void * src, void * dest, size_t size)
Definition at line 99 of file syscall.c.
References memcpy(), and procvmm_check().
Referenced by debug_uputs(), sys_chdir(), sys_chmod(), sys_chown(), sys_execve(), sys_link(), sys_lstat(), sys_mkdir(), sys_mknod(), sys_mount(), sys_open(), sys_readlink(), sys_rmdir(), sys_sigprocmask(), sys_stat(), sys_stime(), sys_symlink(), sys_truncate(), sys_unlink(), sys_waitpid(), sys_write(), syscall_dispatch(), and tty_ioctl().
int curpid ()
Definition at line 125 of file heapmm.c.
References process_info::pid, and scheduler_current_task.
Referenced by paging_handle_fault(), and syscall_dispatch().
uint32_t debug_uputs (uint32_t param[4], uint32_t param_size[4])
Todo:
: ENOMEM
Definition at line 115 of file syscall.c.
References copy_user_to_kern(), earlycon_puts, heapmm_alloc(), heapmm_free(), and syscall_errno.
Referenced by syscall_init().
uint32_t sys_dbgdrop (uint32_t param[4], uint32_t param_size[4])
Definition at line 130 of file syscall.c.
References dbgapi_invoke_kdbg().
Referenced by syscall_init().
void syscall_dispatch (void * user_param_block, void * instr_ptr)
Definition at line 137 of file syscall.c.
References syscall_params::call_id, CONFIG_MAX_SYSCALL_COUNT, copy_kern_to_user(), copy_user_to_kern(), curpid(), debugcon_printf, syscall_params::magic, process_info::name, NULL, syscall_params::param, syscall_params::param_size, process_handle_signals(), process_send_signal(), syscall_params::return_val, syscall_params::sc_errno, scheduler_current_task, SIGSEGV, SIGSYS, SYS_OPEN, SYS_STAT, syscall_errno, SYSCALL_MAGIC, syscall_names, and syscall_table.
Referenced by i386_handle_interrupt().
void syscall_init ()
Definition at line 170 of file syscall.c.
References debug_uputs(), SYS_CHDIR, sys_chdir(), SYS_CHMOD, sys_chmod(), SYS_CHOWN, sys_chown(), SYS_CLOSE, sys_close(), SYS_DBGDROP, sys_dbgdrop(), SYS_DUP, sys_dup(), SYS_DUP2, sys_dup2(), SYS_EXECVE, sys_execve(), SYS_EXIT, sys_exit(), sys_exitsig(), SYS_EXITSIG, sys_fchdir(), SYS_FCHDIR, sys_fchmod(), SYS_FCHMOD, sys_fchown(), SYS_FCHOWN, sys_fcntl(), SYS_FCNTL, sys_fork(), SYS_FORK, SYS_FSTAT, sys_fstat(), SYS_FTRUNCATE, sys_ftruncate(), SYS_GETDENTS, sys_getdents(), sys_getegid(), SYS_GETEGID, sys_geteuid(), SYS_GETEUID, sys_getgid(), SYS_GETGID, SYS_GETPGRP, sys_getpgrp(), SYS_GETPID, sys_getpid(), SYS_GETPPID, sys_getppid(), SYS_GETSID, sys_getsid(), sys_getuid(), SYS_GETUID, sys_ioctl(), SYS_IOCTL, sys_kill(), SYS_KILL, sys_link(), SYS_LINK, SYS_LSEEK, sys_lseek(), SYS_LSTAT, sys_lstat(), SYS_MKDIR, sys_mkdir(), SYS_MKNOD, sys_mknod(), sys_mount(), SYS_MOUNT, SYS_OPEN, sys_open(), SYS_PIPE, sys_pipe(), SYS_PIPE2, sys_pipe2(), SYS_READ, sys_read(), SYS_READLINK, sys_readlink(), SYS_RMDIR, sys_rmdir(), SYS_SBRK, sys_sbrk(), sys_setgid(), SYS_SETGID, SYS_SETPGID, sys_setpgid(), SYS_SETPGRP, sys_setpgrp(), SYS_SETSID, sys_setsid(), sys_setuid(), SYS_SETUID, sys_signal(), SYS_SIGNAL, sys_sigprocmask(), SYS_SIGPROCMASK, sys_sleep(), SYS_SLEEP, sys_ssigex(), SYS_SSIGEX, SYS_STAT, sys_stat(), sys_stime(), SYS_STIME, SYS_SYMLINK, sys_symlink(), sys_time(), SYS_TIME, SYS_TRUNCATE, sys_truncate(), SYS_UMASK, sys_umask(), SYS_UNLINK, sys_unlink(), sys_usleep(), SYS_USLEEP, SYS_WAITPID, sys_waitpid(), SYS_WRITE, sys_write(), SYS_YIELD, sys_yield(), and syscall_register().
Referenced by i386_kmain().
void syscall_register (int call_id, syscall_func_t func)
Todo:
: Find way to free syscall buffers after signal kill
Definition at line 94 of file syscall.c.
References syscall_table.
Referenced by syscall_init().
Variable Documentation
char* syscall_names[]
kernel/syscall.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 07-04-2014 - Created
Definition at line 24 of file syscall.c.
Referenced by syscall_dispatch().
syscall_func_t syscall_table[CONFIG_MAX_SYSCALL_COUNT]
Definition at line 90 of file syscall.c.
Referenced by syscall_dispatch(), and syscall_register().