posnk kernel: kernel/tar.c File Reference
tar.c File Reference
#include <sys/errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include "kernel/earlycon.h"
#include "kernel/vfs.h"
#include "kernel/heapmm.h"
#include "kernel/tar.h"
Functions
int tar_read_record (inode_t *tar_file, off_t *pos)
int tar_read_record_mem (uintptr_t tar_data, off_t *pos)
int tar_extract (char *path)
int tar_extract_mem (void *data)
uint32_t tar_num_dec (char *in, int l)
mode_t tar_get_mode (tar_header_t *header)
dev_t tar_get_dev (tar_header_t *header)
int tar_round_up (int num, int factor)
Function Documentation
int tar_extract (char * path)
Definition at line 26 of file tar.c.
References EACCES, ENOENT, inode::mode, S_ISREG, tar_read_record(), and vfs_find_inode().
int tar_extract_mem (void * data)
Definition at line 41 of file tar.c.
References tar_read_record_mem().
Referenced by i386_init_load_modules().
dev_t tar_get_dev (tar_header_t * header)
Definition at line 90 of file tar.c.
References tar_header::devmajor, tar_header::devminor, MAKEDEV, and tar_num_dec().
Referenced by tar_read_record(), and tar_read_record_mem().
mode_t tar_get_mode (tar_header_t * header)
Todo:
: Implement proper symlinks
Definition at line 62 of file tar.c.
References AREGTYPE, BLKTYPE, CHRTYPE, CONTTYPE, DIRTYPE, FIFOTYPE, LNKTYPE, tar_header::mode, REGTYPE, S_IFBLK, S_IFCHR, S_IFIFO, S_IFREG, SYMTYPE, tar_num_dec(), and tar_header::typeflag.
Referenced by tar_read_record(), and tar_read_record_mem().
uint32_t tar_num_dec (char * in, int l)
Definition at line 48 of file tar.c.
Referenced by tar_get_dev(), tar_get_mode(), tar_read_record(), and tar_read_record_mem().
int tar_read_record (inode_t * tar_file, off_t * pos)
Todo:
: Implement proper symlinks
Definition at line 196 of file tar.c.
References AREGTYPE, BLKTYPE, buf, CHRTYPE, CONTTYPE, DIRTYPE, earlycon_printf, EIO, ENOMEM, ENOSPC, FIFOTYPE, tar_header::gid, inode::gid, heapmm_alloc(), heapmm_free(), tar_header::linkname, LNKTYPE, tar_header::magic, tar_header::name, inode::name, REGTYPE, tar_header::size, inode::size, strcmp(), strlen(), SYMTYPE, tar_get_dev(), tar_get_mode(), tar_num_dec(), TMAGIC, tar_header::typeflag, tar_header::uid, inode::uid, vfs_find_inode(), vfs_link(), vfs_mkdir(), vfs_mknod(), vfs_read(), and vfs_write().
Referenced by tar_extract().
int tar_read_record_mem (uintptr_t tar_data, off_t * pos)
Todo:
: Implement proper symlinks
Definition at line 104 of file tar.c.
References AREGTYPE, inode::atime, BLKTYPE, CHRTYPE, CONTTYPE, inode::ctime, debugcon_printf, DIRTYPE, earlycon_printf, EIO, ENOSPC, FIFOTYPE, tar_header::gid, inode::gid, tar_header::linkname, LNKTYPE, tar_header::magic, tar_header::mtime, inode::mtime, tar_header::name, REGTYPE, tar_header::size, inode::size, strcmp(), strlen(), SYMTYPE, tar_get_dev(), tar_get_mode(), tar_num_dec(), tar_round_up(), TMAGIC, tar_header::typeflag, tar_header::uid, inode::uid, vfs_find_inode(), vfs_link(), vfs_mkdir(), vfs_mknod(), vfs_symlink(), vfs_truncate(), and vfs_write().
Referenced by tar_extract_mem().
int tar_round_up (int num, int factor)
Definition at line 97 of file tar.c.
Referenced by tar_read_record_mem().