posnk kernel: arch/i386/task_switch.c File Reference
task_switch.c File Reference
#include <string.h>
#include <stdint.h>
#include "kernel/heapmm.h"
#include "kernel/paging.h"
#include "kernel/scheduler.h"
#include "kernel/process.h"
#include "kernel/earlycon.h"
#include "arch/i386/task_context.h"
#include "arch/i386/protection.h"
Functions
uint32_t i386_get_return_address (void)
void i386_do_context_switch (uint32_t esp, uint32_t ebp, uint32_t eip, physaddr_t page_dir)
void scheduler_switch_task (scheduler_task_t *new_task)
int process_push_user_data (void *data, size_t size)
int scheduler_invoke_signal_handler (int signal)
void scheduler_exsig ()
void scheduler_exit_signal_handler ()
int scheduler_fork_to (scheduler_task_t *new_task)
Function Documentation
void i386_do_context_switch (uint32_t esp, uint32_t ebp, uint32_t eip, physaddr_t page_dir)
Referenced by scheduler_exsig(), and scheduler_switch_task().
uint32_t i386_get_return_address (void)
Referenced by scheduler_fork_to(), scheduler_invoke_signal_handler(), and scheduler_switch_task().
int process_push_user_data (void * data, size_t size)
Definition at line 56 of file task_switch.c.
References process_info::arch_state, memcpy(), procvmm_check(), and scheduler_current_task.
Referenced by scheduler_invoke_signal_handler().
void scheduler_exit_signal_handler ()
Definition at line 122 of file task_switch.c.
References debugcon_printf.
Referenced by sys_exitsig().
void scheduler_exsig ()
Definition at line 107 of file task_switch.c.
References process_info::arch_state, process_info::arch_state_pre_signal, page_dir::content, heapmm_free(), i386_do_context_switch(), i386_fpu_on_cs(), process_info::isr_stack_pre_signal, process_info::isr_stack_pre_signal_size, memcpy(), process_info::page_directory, paging_get_physical_address(), and scheduler_current_task.
int scheduler_fork_to (scheduler_task_t * new_task)
Definition at line 135 of file task_switch.c.
References process_info::arch_state, heapmm_alloc(), i386_get_return_address(), memset(), process_info::page_directory, paging_create_dir(), and scheduler_current_task.
Referenced by scheduler_fork().
int scheduler_invoke_signal_handler (int signal)
Todo:
: Use current user stack pointer
Definition at line 66 of file task_switch.c.
References process_info::arch_state, process_info::arch_state_pre_signal, debugcon_printf, heapmm_alloc(), i386_get_return_address(), i386_protection_user_call(), process_info::isr_stack_pre_signal, process_info::isr_stack_pre_signal_size, memcpy(), memset(), process_push_user_data(), scheduler_current_task, process_info::signal_handler_exit_func, and process_info::signal_handler_table.
Referenced by process_handle_signals().
void scheduler_switch_task (scheduler_task_t * new_task)
Definition at line 25 of file task_switch.c.
References process_info::arch_state, page_dir::content, heapmm_alloc(), i386_do_context_switch(), i386_fpu_on_cs(), i386_get_return_address(), process_info::page_directory, paging_active_dir, paging_get_physical_address(), process_handle_signals(), and scheduler_current_task.
Referenced by schedule().