posnk kernel: kernel/tty.c File Reference
tty.c File Reference
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/errno.h>
#include <sys/termios.h>
#include <sys/ioctl.h>
#include "kernel/tty.h"
#include "kernel/scheduler.h"
#include "kernel/process.h"
#include "kernel/pipe.h"
#include "kernel/signals.h"
#include "kernel/syscall.h"
#include "kernel/heapmm.h"
#include "kernel/device.h"
#include "config.h"
Functions
void tty_reset_termios (tty_info_t *tty)
void tty_register_driver (char *name, dev_t major, int minor_count, tty_write_out_t write_out)
tty_info_t * tty_get (dev_t device)
int tty_open (dev_t device, __attribute__((__unused__)) int fd, int options)
int tty_close (dev_t device, __attribute__((__unused__)) int fd)
void tty_buf_out_char (tty_info_t *tty, char c)
void tty_flush_line_buffer (tty_info_t *tty)
void tty_buf_line_char (tty_info_t *tty, char c)
void tty_output_char (dev_t device, char c)
void tty_input_char (dev_t device, char c)
int tty_write (dev_t device, void *buf, aoff_t count, aoff_t *write_size, __attribute__((__unused__)) int non_block)
int tty_read (dev_t device, void *buf, aoff_t count, aoff_t *read_size, int non_block)
int tty_ioctl (dev_t device, __attribute__((__unused__)) int fd, int func, int arg)
void tty_init ()
Variables
tty_info_t *** tty_list
kernel/tty.c
tty_ops_t * tty_operations
Function Documentation
void tty_buf_line_char (tty_info_t * tty, char c)
Definition at line 136 of file tty.c.
References tty_info::line_buffer, tty_info::line_buffer_pos, tty_info::line_buffer_size, and tty_flush_line_buffer().
Referenced by tty_input_char().
void tty_buf_out_char (tty_info_t * tty, char c)
Definition at line 124 of file tty.c.
References tty_info::pipe_in, and pipe_write().
Referenced by tty_input_char().
int tty_close (dev_t device, __attribute__((__unused__)) int fd)
Todo:
: process_strip_ctty(device);
Definition at line 112 of file tty.c.
References process_info::ctty, tty_info::ref_count, scheduler_current_task, and tty_get().
Referenced by tty_init().
void tty_flush_line_buffer (tty_info_t * tty)
Definition at line 130 of file tty.c.
References tty_info::line_buffer, tty_info::line_buffer_pos, tty_info::pipe_in, and pipe_write().
Referenced by tty_buf_line_char(), and tty_input_char().
tty_info_t* tty_get (dev_t device)
Definition at line 89 of file tty.c.
References MAJOR, and MINOR.
Referenced by tty_close(), tty_input_char(), tty_ioctl(), tty_open(), tty_output_char(), and tty_read().
void tty_init ()
Definition at line 300 of file tty.c.
References tty_ops::close, heapmm_alloc(), tty_ops::ioctl, tty_ops::open, tty_ops::read, tty_close(), tty_ioctl(), tty_open(), tty_read(), tty_write(), and tty_ops::write.
Referenced by i386_kmain().
void tty_input_char (dev_t device, char c)
Todo:
: Flow control
Definition at line 156 of file tty.c.
References termios::c_cc, termios::c_iflag, termios::c_lflag, ECHO, ECHOE, ECHOK, ECHONL, tty_info::fg_pgid, ICANON, ICRNL, IGNCR, INLCR, ISIG, ISTRIP, tty_info::line_buffer_pos, process_signal_pgroup(), SIGINT, SIGQUIT, SIGTSTP, tty_info::termios, tty_buf_line_char(), tty_buf_out_char(), tty_flush_line_buffer(), tty_get(), VEOL, VERASE, VINTR, VKILL, VQUIT, VSUSP, and tty_info::write_out.
Referenced by sercon_isr(), and vterm_write_tty().
int tty_ioctl (dev_t device, __attribute__((__unused__)) int fd, int func, int arg)
Todo:
: Call driver
Todo:
: Strip pgrp of ctty
Todo:
: process_signal_pgroup(tty->fg_pgid, SIGWINCH);
Definition at line 229 of file tty.c.
References copy_kern_to_user(), copy_user_to_kern(), tty_info::ct_pid, process_info::ctty, EFAULT, tty_info::fg_pgid, process_info::pgid, process_info::pid, process_signal_pgroup(), scheduler_current_task, process_info::sid, SIGCONT, SIGHUP, syscall_errno, TCGETS, TCSETS, TCSETSF, TCSETSW, tty_info::termios, TIOCGPGRP, TIOCGWINSZ, TIOCNOTTY, TIOCSCTTY, TIOCSPGRP, TIOCSWINSZ, tty_get(), and tty_info::win_size.
Referenced by tty_init().
int tty_open (dev_t device, __attribute__((__unused__)) int fd, int options)
Definition at line 97 of file tty.c.
References tty_info::ct_pid, process_info::ctty, tty_info::fg_pgid, O_NOCTTY, process_info::pgid, process_info::pid, tty_info::ref_count, scheduler_current_task, process_info::sid, and tty_get().
Referenced by tty_init().
void tty_output_char (dev_t device, char c)
Todo:
: Flow control
Definition at line 143 of file tty.c.
References termios::c_oflag, OCRNL, ONLCR, OPOST, tty_info::termios, tty_get(), and tty_info::write_out.
Referenced by tty_write().
int tty_read (dev_t device, void * buf, aoff_t count, aoff_t * read_size, int non_block)
Definition at line 223 of file tty.c.
References tty_info::pipe_in, pipe_read(), and tty_get().
Referenced by tty_init().
void tty_register_driver (char * name, dev_t major, int minor_count, tty_write_out_t write_out)
Definition at line 59 of file tty.c.
References CONFIG_TTY_BUFFER, tty_info::ct_pid, tty_info::device, device_char_register(), tty_info::fg_pgid, heapmm_alloc(), tty_info::line_buffer, tty_info::line_buffer_pos, tty_info::line_buffer_size, char_dev::major, MAKEDEV, char_dev::name, name, char_dev::ops, pipe_create(), tty_info::pipe_in, pipe_open_read(), pipe_open_write(), tty_info::ref_count, tty_operations, tty_reset_termios(), and tty_info::write_out.
Referenced by sercon_init(), vgacon_init(), and vterm_tty_setup().
void tty_reset_termios (tty_info_t * tty)
Definition at line 39 of file tty.c.
References B9600, BRKINT, BS0, termios::c_cc, termios::c_cflag, termios::c_iflag, termios::c_ispeed, termios::c_lflag, termios::c_oflag, termios::c_ospeed, CR0, CREAD, CS8, ECHO, ECHOE, ECHOK, FF0, ICANON, ICRNL, ISIG, IXON, NL0, OPOST, TAB0, tty_info::termios, VEOF, VEOL, VERASE, VINTR, VKILL, VQUIT, VSUSP, VT0, tty_info::win_size, winsize::ws_col, and winsize::ws_row.
Referenced by tty_register_driver().
int tty_write (dev_t device, void * buf, aoff_t count, aoff_t * write_size, __attribute__((__unused__)) int non_block)
Definition at line 213 of file tty.c.
References buf, and tty_output_char().
Referenced by tty_init().
Variable Documentation
tty_info_t*** tty_list
kernel/tty.c
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 08-05-2014 - Created
Definition at line 26 of file tty.c.
tty_ops_t* tty_operations
Definition at line 27 of file tty.c.
Referenced by tty_register_driver().