posnk kernel: include/kernel/tty.h File Reference
tty.h File Reference
#include <sys/types.h>
#include <sys/termios.h>
#include <sys/ioctl.h>
#include "kernel/pipe.h"
Data Structures
struct tty_info
Typedefs
typedef struct tty_info tty_info_t
kernel/tty.h
typedef int(* tty_write_out_t)(dev_t, char)
typedef struct winsize winsize_t
Functions
void tty_register_driver (char *name, dev_t major, int minor_count, tty_write_out_t)
void tty_input_char (dev_t device, char c)
void tty_init ()
Typedef Documentation
typedef struct tty_info tty_info_t
kernel/tty.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 08-05-2014 - Created
Definition at line 20 of file tty.h.
typedef int(* tty_write_out_t)(dev_t, char)
Definition at line 21 of file tty.h.
typedef struct winsize winsize_t
Definition at line 22 of file tty.h.
Function Documentation
void tty_init ()
Definition at line 300 of file tty.c.
References tty_ops::close, heapmm_alloc(), tty_ops::ioctl, tty_ops::open, tty_ops::read, tty_close(), tty_ioctl(), tty_open(), tty_read(), tty_write(), and tty_ops::write.
Referenced by i386_kmain().
void tty_input_char (dev_t device, char c)
Todo:
: Flow control
Definition at line 156 of file tty.c.
References termios::c_cc, termios::c_iflag, termios::c_lflag, ECHO, ECHOE, ECHOK, ECHONL, tty_info::fg_pgid, ICANON, ICRNL, IGNCR, INLCR, ISIG, ISTRIP, tty_info::line_buffer_pos, process_signal_pgroup(), SIGINT, SIGQUIT, SIGTSTP, tty_info::termios, tty_buf_line_char(), tty_buf_out_char(), tty_flush_line_buffer(), tty_get(), VEOL, VERASE, VINTR, VKILL, VQUIT, VSUSP, and tty_info::write_out.
Referenced by sercon_isr(), and vterm_write_tty().
void tty_register_driver (char * name, dev_t major, int minor_count, tty_write_out_t)
Definition at line 59 of file tty.c.
References CONFIG_TTY_BUFFER, tty_info::ct_pid, tty_info::device, device_char_register(), tty_info::fg_pgid, heapmm_alloc(), tty_info::line_buffer, tty_info::line_buffer_pos, tty_info::line_buffer_size, char_dev::major, MAKEDEV, char_dev::name, char_dev::ops, pipe_create(), tty_info::pipe_in, pipe_open_read(), pipe_open_write(), tty_info::ref_count, tty_operations, tty_reset_termios(), and tty_info::write_out.
Referenced by sercon_init(), vgacon_init(), and vterm_tty_setup().