posnk kernel: kernel/vfs.c File Reference
vfs.c File Reference
Part of P-OS kernel.
#include <string.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/errno.h>
#include "kernel/heapmm.h"
#include "kernel/vfs.h"
#include "kernel/scheduler.h"
#include "kernel/permissions.h"
#include "kernel/synch.h"
#include "kernel/device.h"
#include "kernel/pipe.h"
#include "config.h"
Data Structures
struct vfs_cache_params
Typedefs
typedef struct vfs_cache_params vfs_cache_params_t
Functions
perm_class_t vfs_get_min_permissions (inode_t *inode, mode_t req_mode)
Returns the minimum privilege level required for access with mode.
int vfs_have_permissions (inode_t *inode, mode_t req_mode)
Check permissions for access with mode.
int vfs_cache_find_iterator (llist_t *node, void *param)
inode_t * vfs_get_inode (fs_device_t *device, ino_t inode_id)
Get an inode by it's ID.
inode_t * vfs_effective_inode (inode_t *inode)
Get the effective inode for an inode, in other words : Dereference possible symlinks and mounts.
dirent_t * vfs_find_dirent (inode_t *inode, char *name)
Find a directory entry.
int vfs_int_mknod (inode_t *inode)
Push a new inode to backing storage.
int vfs_int_rmnod (inode_t *inode)
Remove an inode from backing storage.
int vfs_int_mkdir (inode_t *inode)
Create directory structures on backing storage.
int vfs_int_link (inode_t *inode, char *name, ino_t nod_id)
Create a directory entry on backing storage.
int vfs_int_unlink (inode_t *inode, char *name)
Delete a directory entry from backing storage.
int vfs_int_read_dir (inode_t *inode, void *buffer, aoff_t file_offset, aoff_t count, aoff_t *read_size)
Read directory entries from backing storage.
int vfs_int_read (inode_t *inode, void *buffer, aoff_t file_offset, aoff_t count, aoff_t *read_size)
Read data from a file from backing storage.
int vfs_int_write (inode_t *inode, void *buffer, aoff_t file_offset, aoff_t count, aoff_t *write_size)
Write data to a file from backing storage.
int vfs_int_truncate (inode_t *inode, aoff_t size)
Resize a file on backing storage.
int vfs_write (inode_t *inode, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *write_size, int non_block)
Write data to a file.
int vfs_read (inode_t *inode, aoff_t file_offset, void *buffer, aoff_t count, aoff_t *read_size, int non_block)
Read data from a file.
int vfs_getdents (inode_t *inode, aoff_t file_offset, dirent_t *buffer, aoff_t count, aoff_t *read_size)
Read directory entries.
int vfs_truncate (inode_t *inode, aoff_t length)
Resize a file.
int vfs_rmdir (char *path)
Delete a directory.
int vfs_mkdir (char *path, mode_t mode)
Create a directory.
int vfs_mknod (char *path, mode_t mode, dev_t dev)
Create a file.
fs_device_t * ext2_mount (dev_t device, uint32_t flags)
int vfs_mount (char *device, char *mountpoint, char *fstype, uint32_t flags)
Mount a filesystem.
int vfs_symlink (char *oldpath, char *path)
Create a symbolic link.
int vfs_unlink (char *path)
Delete a file.
int vfs_initialize (fs_device_t *root_device)
Initialize the VFS layer.
int vfs_link (char *oldpath, char *newpath)
Create a hard link.
dir_cache_t * vfs_dir_cache_mkroot (inode_t *root_inode)
void vfs_dir_cache_release (dir_cache_t *dirc)
dir_cache_t * vfs_find_dirc_parent (char *path)
dir_cache_t * vfs_find_dirc (char *path)
inode_t * vfs_find_parent (char *path)
inode_t * vfs_find_inode (char *path)
inode_t * vfs_find_symlink (char *path)
Variables
llist_t * inode_cache
The linked list serving as inode cache.
Detailed Description
Part of P-OS kernel.
Author
Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog:
12-04-2014 - Created
11-07-2014 - Rewrite 1
12-07-2014 - Commented
Definition in file vfs.c.
Typedef Documentation
typedef struct vfs_cache_params vfs_cache_params_t
Function Documentation
fs_device_t* ext2_mount (dev_t device, uint32_t flags)
Todo:
: Implement fallback to alternative superblock
Definition at line 473 of file ext2.c.
Referenced by vfs_mount().
int vfs_cache_find_iterator (llist_t * node, void * param)
Definition at line 75 of file vfs.c.
References vfs_cache_params::device_id, inode::device_id, inode::id, and vfs_cache_params::inode_id.
Referenced by vfs_get_inode().
dir_cache_t* vfs_dir_cache_mkroot (inode_t * root_inode)
Todo:
: Comment dir-cache and path lookup functions
Definition at line 1674 of file vfs.c.
References heapmm_alloc(), dir_cache::inode, dir_cache::parent, inode::usage_count, and dir_cache::usage_count.
Referenced by vfs_initialize().
void vfs_dir_cache_release (dir_cache_t * dirc)
Definition at line 1684 of file vfs.c.
References heapmm_free(), dir_cache::inode, dir_cache::parent, inode::usage_count, dir_cache::usage_count, and vfs_dir_cache_release().
Referenced by vfs_dir_cache_release(), vfs_find_dirc(), vfs_find_dirc_parent(), vfs_find_inode(), vfs_find_parent(), and vfs_find_symlink().
inode_t* vfs_effective_inode (inode_t * inode)
Get the effective inode for an inode, in other words : Dereference possible symlinks and mounts.
Parameters
inode The inode that is to be checked
Returns
The inode that the parameter points to.
Definition at line 126 of file vfs.c.
References inode, inode::link_path, inode::mount, and vfs_find_inode().
Referenced by vfs_find_dirc(), vfs_find_dirc_parent(), vfs_getdents(), vfs_read(), vfs_truncate(), and vfs_write().
dir_cache_t* vfs_find_dirc (char * path)
Todo:
: Check for search permission
Definition at line 1776 of file vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, process_info::current_directory, inode::device, heapmm_alloc(), heapmm_free(), dir_cache::inode, dirent::inode_id, inode::mode, NULL, dir_cache::parent, process_info::root_directory, S_ISDIR, scheduler_current_task, strchr(), strchrnul(), strncmp(), strncpy(), inode::usage_count, dir_cache::usage_count, vfs_dir_cache_release(), vfs_effective_inode(), vfs_find_dirent(), and vfs_get_inode().
Referenced by _sys_chdir(), _sys_open(), vfs_find_inode(), and vfs_find_symlink().
dir_cache_t* vfs_find_dirc_parent (char * path)
Definition at line 1695 of file vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, process_info::current_directory, inode::device, heapmm_alloc(), heapmm_free(), dir_cache::inode, dirent::inode_id, inode::mode, NULL, dir_cache::parent, process_info::root_directory, S_ISDIR, scheduler_current_task, strchr(), strchrnul(), strncmp(), strncpy(), inode::usage_count, dir_cache::usage_count, vfs_dir_cache_release(), vfs_effective_inode(), vfs_find_dirent(), and vfs_get_inode().
Referenced by vfs_find_parent().
dirent_t* vfs_find_dirent (inode_t * inode, char * name)
Find a directory entry.
Parameters
inode The directory to search
name The filename to match
Returns
The directory entry matching name from the directory inode, if none, NULL is returned
Definition at line 153 of file vfs.c.
References inode::device, fs_device_operations::find_dirent, and fs_device::ops.
Referenced by vfs_find_dirc(), vfs_find_dirc_parent(), and vfs_find_symlink().
inode_t* vfs_find_inode (char * path)
Todo:
: Check for search permission
Definition at line 1863 of file vfs.c.
References dir_cache::inode, NULL, vfs_dir_cache_release(), and vfs_find_dirc().
Referenced by _sys_chmod(), _sys_chown(), _sys_stat(), _sys_truncate(), elf_load(), tar_extract(), tar_read_record(), tar_read_record_mem(), vfs_effective_inode(), vfs_link(), vfs_mkdir(), vfs_mknod(), vfs_mount(), vfs_rmdir(), and vfs_symlink().
inode_t* vfs_find_parent (char * path)
Todo:
: Check for search permission
Definition at line 1852 of file vfs.c.
References dir_cache::inode, NULL, vfs_dir_cache_release(), and vfs_find_dirc_parent().
Referenced by vfs_link(), vfs_mkdir(), vfs_mknod(), vfs_symlink(), and vfs_unlink().
inode_t* vfs_find_symlink (char * path)
Todo:
: Check for search permission
Definition at line 1916 of file vfs.c.
References process_info::current_directory, inode::device, dir_cache::inode, dirent::inode_id, name, NULL, dir_cache::parent, process_info::root_directory, scheduler_current_task, strlen(), strrchr(), vfs_dir_cache_release(), vfs_find_dirc(), vfs_find_dirent(), and vfs_get_inode().
Referenced by _sys_lstat(), _sys_readlink(), and vfs_unlink().
inode_t* vfs_get_inode (fs_device_t * device, ino_t inode_id)
Get an inode by it's ID.
Parameters
device The device to get the inode from
inode_id The ID of the inode to look up
Returns
The inode <inode_id> from device.
Definition at line 90 of file vfs.c.
References vfs_cache_params::device_id, fs_device::id, vfs_cache_params::inode_id, inode_id, llist_add_end(), llist_iterate_select(), fs_device_operations::load_inode, fs_device::ops, and vfs_cache_find_iterator().
Referenced by vfs_find_dirc(), vfs_find_dirc_parent(), and vfs_find_symlink().
perm_class_t vfs_get_min_permissions (inode_t * inode, mode_t req_mode)
Returns the minimum privilege level required for access with mode.
Parameters
inode The file to check
mode The requested access mode
Returns
The required privilege class : other, group or owner
Definition at line 47 of file vfs.c.
References inode::mode, PERM_CLASS_GROUP, PERM_CLASS_NONE, PERM_CLASS_OTHER, and PERM_CLASS_OWNER.
Referenced by vfs_have_permissions().
int vfs_getdents (inode_t * inode, aoff_t file_offset, dirent_t * buffer, aoff_t count, aoff_t * read_size)
Read directory entries.
This function will only read whole directory entries, if a directory entry does not fit in count it will return only the amount of bytes read before that entry
Parameters
inode The inode for the directory
buffer The buffer to store the entries in
file_offset The offset in the directory to start reading at
count The number of bytes to read
read_size A pointer to a variable in which the number of bytes read will be stored
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
EBADF Tried to read from a directory for which we do not have permission
ENOTDIR Can only read directory entries from a directory
EIO An IO error was encountered trying to read from the dir
ENOMEM Could not allocate kernel heap for a temporary structure
Definition at line 714 of file vfs.c.
References inode::atime, EBADF, EFAULT, ENOTDIR, inode::lock, inode::mode, MODE_READ, S_IFDIR, S_IFMT, semaphore_down(), semaphore_up(), inode::size, system_time, vfs_effective_inode(), vfs_have_permissions(), and vfs_int_read_dir().
Referenced by _sys_getdents().
int vfs_have_permissions (inode_t * inode, mode_t req_mode)
Check permissions for access with mode.
Parameters
inode The file to check
mode The requested access mode
Returns
Whether the requested access is allowed
Definition at line 65 of file vfs.c.
References get_perm_class(), inode::gid, inode::uid, and vfs_get_min_permissions().
Referenced by elf_load(), vfs_getdents(), vfs_link(), vfs_mknod(), vfs_read(), vfs_symlink(), vfs_truncate(), vfs_unlink(), and vfs_write().
int vfs_initialize (fs_device_t * root_device)
Initialize the VFS layer.
Parameters
root_device The filesystem device to use as root filesystem
Returns
If successful 1, otherwise 0
Todo:
: Track mounted devices
Definition at line 1508 of file vfs.c.
References process_info::current_directory, heapmm_alloc(), llist_add_end(), llist_create(), fs_device_operations::load_inode, fs_device::ops, process_info::root_directory, fs_device::root_inode_id, scheduler_current_task, and vfs_dir_cache_mkroot().
Referenced by i386_kmain().
int vfs_int_link (inode_t * inode, char * name, ino_t nod_id)
Create a directory entry on backing storage.
Warning
INTERNAL FUNCTION
Parameters
inode The inode for the directory
name The file name for the directory entry
nod_id The inode id that the directory entry will point to
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 237 of file vfs.c.
References inode::device, ENOTSUP, fs_device_operations::link, and fs_device::ops.
Referenced by vfs_link(), vfs_mknod(), and vfs_symlink().
int vfs_int_mkdir (inode_t * inode)
Create directory structures on backing storage.
Warning
INTERNAL FUNCTION
Parameters
inode The inode for the new directory
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 213 of file vfs.c.
References inode::device, ENOTSUP, fs_device_operations::mkdir, and fs_device::ops.
Referenced by vfs_mkdir().
int vfs_int_mknod (inode_t * inode)
Push a new inode to backing storage.
Warning
INTERNAL FUNCTION
Parameters
inode The inode that was created
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 169 of file vfs.c.
References inode::device, ENOTSUP, fs_device_operations::mknod, and fs_device::ops.
Referenced by vfs_mknod(), and vfs_symlink().
int vfs_int_read (inode_t * inode, void * buffer, aoff_t file_offset, aoff_t count, aoff_t * read_size)
Read data from a file from backing storage.
Warning
INTERNAL FUNCTION
Parameters
inode The inode for the file
buffer The buffer to store the data in
file_offset The offset in the file to start reading at
count The number of bytes to read
read_size A pointer to a variable in which the number of bytes read will be stored
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 308 of file vfs.c.
References inode::device, fs_device::ops, and fs_device_operations::read_inode.
Referenced by vfs_read().
int vfs_int_read_dir (inode_t * inode, void * buffer, aoff_t file_offset, aoff_t count, aoff_t * read_size)
Read directory entries from backing storage.
Warning
INTERNAL FUNCTION
Parameters
inode The inode for the directory
buffer The buffer to store the entries in
file_offset The offset in the directory to start reading at
count The number of bytes to read
read_size A pointer to a variable in which the number of bytes read will be stored
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 287 of file vfs.c.
References inode::device, fs_device::ops, and fs_device_operations::read_dir.
Referenced by vfs_getdents().
int vfs_int_rmnod (inode_t * inode)
Remove an inode from backing storage.
Warning
INTERNAL FUNCTION
Parameters
inode The inode that was deleted
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 191 of file vfs.c.
References inode::device, ENOTSUP, fs_device::ops, and fs_device_operations::rmnod.
Referenced by vfs_mknod(), vfs_symlink(), and vfs_unlink().
int vfs_int_truncate (inode_t * inode, aoff_t size)
Resize a file on backing storage.
Warning
INTERNAL FUNCTION
Parameters
inode The inode for the file
size The new size of the file
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 352 of file vfs.c.
References inode::device, ENOTSUP, fs_device::ops, and fs_device_operations::trunc_inode.
Referenced by vfs_truncate().
int vfs_int_unlink (inode_t * inode, char * name)
Delete a directory entry from backing storage.
Warning
INTERNAL FUNCTION
Parameters
inode - The inode for the directory
name - The file name of the directory entry to delete
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 260 of file vfs.c.
References inode::device, ENOTSUP, fs_device::ops, and fs_device_operations::unlink.
Referenced by vfs_unlink().
int vfs_int_write (inode_t * inode, void * buffer, aoff_t file_offset, aoff_t count, aoff_t * write_size)
Write data to a file from backing storage.
Warning
INTERNAL FUNCTION
Parameters
inode The inode for the file
buffer The buffer containing the data to write
file_offset The offset in the file to start writing at
count The number of bytes to write
write_size A pointer to a variable in which the number of bytes written will be stored
Returns
In case of error: a valid error code, Otherwise 0
Definition at line 329 of file vfs.c.
References inode::device, ENOTSUP, fs_device::ops, and fs_device_operations::write_inode.
Referenced by vfs_write().
int vfs_link (char * oldpath, char * newpath)
Create a hard link.
Parameters
oldpath The target of the link
newpath The path of the link
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The parent directory or target does not exist
EEXIST A file already exists at the given path
EIO An IO error occurred while creating the link
EACCES User does not have write permission for the parent dir
ENOSPC Not enough disk space was available
ENOMEM Could not allocate kernel heap for a temporary structure
EXDEV Tried to create a cross-device link
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Todo:
: Make a copy of path before doing this
Definition at line 1554 of file vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, inode::ctime, inode::device_id, EACCES, EEXIST, EFAULT, ENAMETOOLONG, ENOENT, EXDEV, inode::hard_link_count, inode::id, inode, inode::lock, MODE_WRITE, inode::mtime, name, semaphore_down(), semaphore_up(), strlen(), strrchr(), system_time, vfs_find_inode(), vfs_find_parent(), vfs_have_permissions(), and vfs_int_link().
Referenced by sys_link(), tar_read_record(), and tar_read_record_mem().
int vfs_mkdir (char * path, mode_t mode)
Create a directory.
Parameters
path The path of the directory to create
mode The mode of the directory to create, only access modes are used
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The parent directory does not exist
EEXIST A file already exists at the given path
EIO An IO error occurred while creating the directory
EACCES User does not have write permission for the parent dir
ENOSPC Not enough disk space was available
ENOMEM Could not allocate kernel heap for a temporary structure
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Todo:
: Make this an assertion
Todo:
: Make this an assertion
Definition at line 945 of file vfs.c.
References EFAULT, inode::lock, inode::mtime, S_IFDIR, semaphore_down(), semaphore_up(), system_time, vfs_find_inode(), vfs_find_parent(), vfs_int_mkdir(), vfs_mknod(), and vfs_unlink().
Referenced by sys_mkdir(), tar_read_record(), and tar_read_record_mem().
int vfs_mknod (char * path, mode_t mode, dev_t dev)
Create a file.
Parameters
path The path of the file to create
mode The mode of the file to create
dev The device id to use in case of a special file
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The parent directory does not exist
EEXIST A file already exists at the given path
EIO An IO error occurred while creating the file
EACCES User does not have write permission for the parent dir
ENOSPC Not enough disk space was available
ENOMEM Could not allocate kernel heap for a temporary structure
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Todo:
: Make a copy of path before doing this
Definition at line 1023 of file vfs.c.
References inode::atime, CONFIG_FILE_MAX_NAME_LENGTH, inode::ctime, inode::device, inode::device_id, EACCES, EEXIST, EFAULT, ENAMETOOLONG, ENOENT, ENOMEM, inode::fifo, inode::gid, process_info::gid, inode::hard_link_count, heapmm_alloc(), heapmm_free(), inode::id, inode::if_dev, inode, fs_device::inode_size, llist_add_end(), llist_unlink(), inode::lock, memset(), inode::mode, MODE_WRITE, inode::mtime, name, inode::name, pipe_create(), S_ISFIFO, scheduler_current_task, semaphore_alloc(), semaphore_up(), strcpy(), strlen(), strrchr(), system_time, inode::uid, process_info::uid, process_info::umask, vfs_find_inode(), vfs_find_parent(), vfs_have_permissions(), vfs_int_link(), vfs_int_mknod(), and vfs_int_rmnod().
Referenced by _sys_open(), i386_kmain(), sys_mknod(), tar_read_record(), tar_read_record_mem(), and vfs_mkdir().
int vfs_mount (char * device, char * mountpoint, char * fstype, uint32_t flags)
Mount a filesystem.
Parameters
device The path of the block special file the fs resides on
mountpoint The directory to mount the fs on
fstype The filesystem driver to use e.g.: ext2, ramfs
flags Options for mounting the fs that are passed to the fs driver
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT A file does not exist
EINVAL An error occurred mounting the filesystem
ENOTDIR The mount point is not a directory
ENOTBLK The special file is not a block special file
Todo:
: Support multiple filesystems
Todo:
: Unmount
Definition at line 1173 of file vfs.c.
References EFAULT, EINVAL, ENOENT, ENOTBLK, ENOTDIR, ext2_mount(), inode::if_dev, fs_device_operations::load_inode, inode::mode, inode::mount, fs_device::ops, fs_device::root_inode_id, S_ISBLK, S_ISDIR, and vfs_find_inode().
Referenced by sys_mount().
int vfs_read (inode_t * inode, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * read_size, int non_block)
Read data from a file.
If more data is requested than the file contains this function will successfully complete but read_size will be smaller than count
Parameters
inode The inode for the file
buffer The buffer to store the data in
file_offset The offset in the file to start reading at
count The number of bytes to read
read_size A pointer to a variable in which the number of bytes read will be stored
non_block Whether to block the call until data is available in the file, this is only supported on FIFO's and character devices
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
EBADF Tried to read from a file for which we do not have permission
EISDIR Direct reads from directories are not allowed
EIO An IO error was encountered trying to read from the file
EPIPE The FIFO has no data left and there are no (open) write endpoints
ENOMEM Could not allocate kernel heap for a temporary structure
Definition at line 570 of file vfs.c.
References inode::atime, device_block_read(), device_char_read(), EBADF, EFAULT, EINVAL, EISDIR, inode::fifo, inode::if_dev, inode::lock, inode::mode, MODE_READ, pipe_write(), S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFMT, S_IFREG, semaphore_down(), semaphore_up(), inode::size, system_time, vfs_effective_inode(), vfs_have_permissions(), and vfs_int_read().
Referenced by _sys_read(), elf_load(), procvmm_handle_fault(), and tar_read_record().
int vfs_rmdir (char * path)
Delete a directory.
Parameters
path The path of the directory to delete
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The directory does not exist
EEXIST The directory still has files in it
EBUSY The directory is in use
EIO An IO error occurred while deleting the directory
EACCES Tried to delete a directory from a directory for which we do not have write permission
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Todo:
: Release the inode
Definition at line 898 of file vfs.c.
References EBUSY, EEXIST, EFAULT, ENOENT, dir_cache::inode, inode::mount, process_info::root_directory, scheduler_current_task, inode::size, vfs_find_inode(), and vfs_unlink().
Referenced by sys_rmdir().
int vfs_symlink (char * oldpath, char * path)
Create a symbolic link.
Parameters
oldpath The target of the link
path The path of the link
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The parent directory does not exist
EEXIST A file already exists at the given path
EIO An IO error occurred while creating the file
EACCES User does not have write permission for the parent dir
ENOSPC Not enough disk space was available
ENOMEM Could not allocate kernel heap for a temporary structure
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Todo:
: Make a copy of path before doing this
Definition at line 1242 of file vfs.c.
References inode::atime, CONFIG_FILE_MAX_NAME_LENGTH, inode::ctime, inode::device, inode::device_id, EACCES, EEXIST, EFAULT, ENAMETOOLONG, ENOENT, ENOMEM, inode::gid, process_info::gid, inode::hard_link_count, heapmm_alloc(), heapmm_free(), inode::id, inode::if_dev, inode, fs_device::inode_size, inode::link_path, llist_add_end(), llist_unlink(), inode::lock, memset(), inode::mode, MODE_WRITE, inode::mtime, name, inode::name, scheduler_current_task, semaphore_alloc(), semaphore_up(), strcpy(), strlen(), strrchr(), system_time, inode::uid, process_info::uid, vfs_find_inode(), vfs_find_parent(), vfs_have_permissions(), vfs_int_link(), vfs_int_mknod(), and vfs_int_rmnod().
Referenced by sys_symlink(), and tar_read_record_mem().
int vfs_truncate (inode_t * inode, aoff_t length)
Resize a file.
If the new size is larger than the file currently is the new room will be filled with zero bytes, if the new size is smaller the data in the truncated part of the file is deleted
Parameters
inode The inode for the file
size The new size of the file
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
EACCES Tried to resize a file for which we do not have permission
EISDIR Directories can not be resized
EIO An IO error was encountered trying to resize the file
ENOSPC The disk was full when trying to grow the file
ENOMEM Could not allocate kernel heap for a temporary structure
Definition at line 812 of file vfs.c.
References EACCES, EFAULT, EINVAL, EISDIR, inode::lock, inode::mode, MODE_WRITE, inode::mtime, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFMT, S_IFREG, semaphore_down(), semaphore_up(), inode::size, system_time, vfs_effective_inode(), vfs_have_permissions(), and vfs_int_truncate().
Referenced by _sys_ftruncate(), _sys_truncate(), and tar_read_record_mem().
int vfs_unlink (char * path)
Delete a file.
Parameters
path The path of the file to delete
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
ENOENT The file does not exist
EEXIST A file already exists at the given path
EBUSY The file is in use
EIO An IO error occurred while deleting the file
EACCES User does not have write permission for the file
ENOMEM Could not allocate kernel heap for a temporary structure
ENAMETOOLONG The name of the file is longer than the maximum allowed number of characters for a file name
Todo:
: Make a copy of path before doing this
Definition at line 1391 of file vfs.c.
References CONFIG_FILE_MAX_NAME_LENGTH, inode::ctime, inode::device, EACCES, EBUSY, EFAULT, ENAMETOOLONG, ENOENT, inode::hard_link_count, heapmm_free(), inode, fs_device::inode_size, llist_unlink(), inode::lock, MODE_WRITE, name, semaphore_down(), semaphore_up(), strlen(), strrchr(), system_time, inode::usage_count, vfs_find_parent(), vfs_find_symlink(), vfs_have_permissions(), vfs_int_rmnod(), and vfs_int_unlink().
Referenced by sys_unlink(), vfs_mkdir(), and vfs_rmdir().
int vfs_write (inode_t * inode, aoff_t file_offset, void * buffer, aoff_t count, aoff_t * write_size, int non_block)
Write data to a file.
If the data to be written would extend past the end of the file, the file will grow. If file_offset lies past the end of the file, the file will grow and the resulting gap will be filled with zero bytes.
Parameters
inode The inode for the file
buffer The buffer containing the data to write
file_offset The offset in the file to start writing at
count The number of bytes to write
write_size A pointer to a variable in which the number of bytes written will be stored
non_block Whether to block the call until room is available in the file, this is only supported on FIFO's and character devices
Returns
In case of error: a valid error code, Otherwise 0
Exceptions
EFAULT Atleast one parameter was a NULL pointer
EBADF Tried to write to a file for which we do not have permission
EISDIR Direct writes to directories are not allowed
EIO An IO error was encountered trying to write to the file
EPIPE The FIFO has no room left and there are no (open) read endpoints
ENOSPC The disk was full when trying to write to the file
ENOMEM Could not allocate kernel heap for a temporary structure
Todo:
: Make this more efficient, implement sparse files
Definition at line 395 of file vfs.c.
References device_block_write(), device_char_write(), EBADF, EFAULT, EINVAL, EISDIR, inode::fifo, heapmm_alloc(), heapmm_free(), inode::if_dev, inode::lock, memset(), inode::mode, MODE_WRITE, inode::mtime, pipe_write(), S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFMT, S_IFREG, semaphore_down(), semaphore_up(), inode::size, system_time, vfs_effective_inode(), vfs_have_permissions(), and vfs_int_write().
Referenced by _sys_write(), tar_read_record(), and tar_read_record_mem().
Variable Documentation
llist_t* inode_cache
The linked list serving as inode cache.
Todo:
: Make this an MRU cache
Definition at line 32 of file vfs.c.