posnk kernel: driver/console/vga_vterm.c File Reference
vga_vterm.c File Reference
#include "driver/console/vgacon/vga_vterm.h"
#include <string.h>
#include <stdint.h>
#include <sys/types.h>
#include "kernel/tty.h"
#include "driver/console/vterm/vterm.h"
#include "driver/console/vterm/vterm_private.h"
Functions
void vterm_tty_setup (char *name, dev_t major, int minor_count, int rows, int cols)
volatile
vga_vterm_screen_character_t * vga_vterm_get_text_video_memory ()
void vga_vterm_move_cursor (vga_vterm_vc_t *vc)
void vterm_vga_position (vga_vterm_vc_t *vc, int x, int y, int move_cursor_)
void vterm_vga_write_crtc_register (char id, char val)
char vga_vterm_map_attr (int attr)
void vterm_invalidate_screen (vterm_t *vt)
void vterm_invalidate_cell (vterm_t *vt, int row, int col)
void vterm_invalidate_cursor (vterm_t *vt)
void vterm_handle_bell (vterm_t *vt)
void vterm_tty_invalidate_screen (dev_t dev)
void vterm_vga_switch_vc (int vc)
void vterm_post_key_tty (dev_t dev, int keycode)
void con_handle_key (int keycode)
void vterm_vga_init ()
Variables
vga_vterm_vc_t vterm_vga_all_vcs [9]
int vterm_vga_current_vc = 0
int vga_vterm_colour_map [8] = {0,4,2,6,1,5,3,7}
Function Documentation
void con_handle_key (int keycode)
Definition at line 103 of file vga_vterm.c.
References KEY_VT, KEY_VT0, MAKEDEV, vterm_post_key_tty(), vterm_vga_current_vc, and vterm_vga_switch_vc().
Referenced by kb_typed().
volatile vga_vterm_screen_character_t* vga_vterm_get_text_video_memory ()
Todo:
: Check for paging init
Definition at line 17 of file vga_vterm.c.
Referenced by vterm_vga_init(), and vterm_vga_switch_vc().
char vga_vterm_map_attr (int attr) inline
Definition at line 41 of file vga_vterm.c.
References A_BOLD, and vga_vterm_colour_map.
Referenced by vterm_invalidate_cell(), vterm_invalidate_cursor(), and vterm_invalidate_screen().
void vga_vterm_move_cursor (vga_vterm_vc_t * vc)
Definition at line 21 of file vga_vterm.c.
References vgacon_vc::cursor_x, vgacon_vc::cursor_y, and vterm_vga_write_crtc_register().
Referenced by vterm_vga_position().
void vterm_handle_bell (vterm_t * vt)
Definition at line 86 of file vga_vterm.c.
Referenced by vterm_render_ctrl_char().
void vterm_invalidate_cell (vterm_t * vt, int row, int col)
Definition at line 67 of file vga_vterm.c.
References _vterm_cell_s::attr, vga_vterm_screen_character::attribute, _vterm_s::cells, _vterm_cell_s::ch, vga_vterm_screen_character::character, _vterm_s::device_id, MINOR, vga_vterm_map_attr(), and vgacon_vc::video_buffer.
Referenced by interpret_csi_DCH(), interpret_csi_DL(), interpret_csi_ECH(), interpret_csi_EL(), interpret_csi_ICH(), vterm_erase(), vterm_erase_col(), vterm_erase_row(), and vterm_put_char().
void vterm_invalidate_cursor (vterm_t * vt)
Definition at line 76 of file vga_vterm.c.
References vga_vterm_screen_character::attribute, _vterm_s::ccol, _vterm_s::crow, _vterm_s::curattr, _vterm_s::device_id, MINOR, vga_vterm_map_attr(), vgacon_vc::video_buffer, vterm_vga_current_vc, and vterm_vga_position().
Referenced by vterm_render().
void vterm_invalidate_screen (vterm_t * vt)
Definition at line 53 of file vga_vterm.c.
References _vterm_cell_s::attr, vga_vterm_screen_character::attribute, _vterm_s::ccol, _vterm_s::cells, _vterm_cell_s::ch, vga_vterm_screen_character::character, _vterm_s::cols, _vterm_s::crow, _vterm_s::device_id, MINOR, _vterm_s::rows, vga_vterm_map_attr(), vgacon_vc::video_buffer, and vterm_vga_position().
Referenced by interpret_csi_ED(), interpret_csi_IL(), vterm_scroll_down(), vterm_scroll_up(), and vterm_tty_invalidate_screen().
void vterm_post_key_tty (dev_t dev, int keycode)
Definition at line 50 of file vterm_tty.c.
References MINOR, and vterm_write_pipe().
Referenced by con_handle_key().
void vterm_tty_invalidate_screen (dev_t dev)
Definition at line 45 of file vterm_tty.c.
References MINOR, and vterm_invalidate_screen().
Referenced by vterm_vga_switch_vc().
void vterm_tty_setup (char * name, dev_t major, int minor_count, int rows, int cols)
Definition at line 69 of file vterm_tty.c.
References _vterm_s::device_id, heapmm_alloc(), MAKEDEV, tty_register_driver(), VTERM_FLAG_VT100, vterm_init(), and vterm_putc().
Referenced by vterm_vga_init().
void vterm_vga_init ()
Definition at line 111 of file vga_vterm.c.
References vgacon_vc::cursor_x, vgacon_vc::cursor_y, kb_initialize(), vgacon_vc::page_id, vga_vterm_get_text_video_memory(), vgacon_vc::video_buffer, vterm_tty_setup(), and vterm_vga_switch_vc().
Referenced by i386_kmain().
void vterm_vga_position (vga_vterm_vc_t * vc, int x, int y, int move_cursor_)
Definition at line 28 of file vga_vterm.c.
References vgacon_vc::cursor_x, vgacon_vc::cursor_y, and vga_vterm_move_cursor().
Referenced by vterm_invalidate_cursor(), and vterm_invalidate_screen().
void vterm_vga_switch_vc (int vc)
Definition at line 91 of file vga_vterm.c.
References MAKEDEV, vga_vterm_get_text_video_memory(), vterm_tty_invalidate_screen(), vterm_vga_current_vc, and vterm_vga_write_crtc_register().
Referenced by con_handle_key(), and vterm_vga_init().
void vterm_vga_write_crtc_register (char id, char val)
Definition at line 36 of file vga_vterm.c.
References i386_outb().
Referenced by vga_vterm_move_cursor(), and vterm_vga_switch_vc().
Variable Documentation
int vga_vterm_colour_map[8] = {0,4,2,6,1,5,3,7}
Definition at line 15 of file vga_vterm.c.
Referenced by vga_vterm_map_attr().
vga_vterm_vc_t vterm_vga_all_vcs[9]
Definition at line 11 of file vga_vterm.c.
int vterm_vga_current_vc = 0
Definition at line 13 of file vga_vterm.c.
Referenced by con_handle_key(), vterm_invalidate_cursor(), and vterm_vga_switch_vc().