posnk kernel: driver/console/vgacon_early.c File Reference
vgacon_early.c File Reference
#include "driver/console/vgacon/vgacon.h"
#include <string.h>
#include <stdint.h>
Functions
volatile
vgacon_screen_character_t * vgacon_early_get_text_video_memory ()
void vgacon_early_putch (char c)
Write character to text buffer and move cursor.
void vgacon_early_move_cursor ()
void earlycon_putc (char c)
void vgacon_early_clear_video ()
void vgacon_early_clear_line ()
void vgacon_early_position (int x, int y, int move_cursor_)
void earlycon_aputs (const char *str)
void vgacon_early_set_attrib (int foreground, int background)
void vgacon_early_disable_scroll (int scroll)
void earlycon_init ()
kernel/earlycon.h
Variables
vgacon_vc_info_t vgacon_early_vc
Function Documentation
void earlycon_aputs (const char * str)
Definition at line 124 of file vgacon_early.c.
References earlycon_putc().
Referenced by earlycon_aprintf(), and heapmm_request_core().
void earlycon_init ()
kernel/earlycon.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 31-03-2014 - Created
Definition at line 142 of file vgacon_early.c.
References vgacon_vc_info::attrib, vgacon_vc_info::cursor_x, vgacon_vc_info::cursor_y, vgacon_vc_info::escape, vgacon_vc_info::no_scroll, vgacon_vc_info::page_id, vgacon_early_get_text_video_memory(), and vgacon_vc_info::video_buffer.
Referenced by i386_init_mm().
void earlycon_putc (char c)
Definition at line 55 of file vgacon_early.c.
References vgacon_vc_info::cursor_x, vgacon_vc_info::cursor_y, vgacon_vc_info::escape, vgacon_early_move_cursor(), and vgacon_early_putch().
Referenced by earlycon_aputs().
void vgacon_early_clear_line ()
Definition at line 107 of file vgacon_early.c.
References vgacon_vc_info::attrib, vgacon_vc_info::cursor_y, memset(), and vgacon_vc_info::video_buffer.
void vgacon_early_clear_video ()
Definition at line 99 of file vgacon_early.c.
References vgacon_vc_info::attrib, memset(), and vgacon_vc_info::video_buffer.
void vgacon_early_disable_scroll (int scroll)
Definition at line 138 of file vgacon_early.c.
References vgacon_vc_info::no_scroll.
volatile vgacon_screen_character_t* vgacon_early_get_text_video_memory ()
Todo:
: Check for paging init
Definition at line 7 of file vgacon_early.c.
Referenced by earlycon_init().
void vgacon_early_move_cursor ()
Definition at line 48 of file vgacon_early.c.
References vgacon_vc_info::cursor_x, vgacon_vc_info::cursor_y, and vgacon_write_crtc_register().
Referenced by earlycon_putc(), and vgacon_early_position().
void vgacon_early_position (int x, int y, int move_cursor_)
Definition at line 116 of file vgacon_early.c.
References vgacon_vc_info::cursor_x, vgacon_vc_info::cursor_y, and vgacon_early_move_cursor().
void vgacon_early_putch (char c)
Write character to text buffer and move cursor.
Definition at line 14 of file vgacon_early.c.
References vgacon_vc_info::attrib, vgacon_screen_character::attribute, vgacon_screen_character::character, vgacon_vc_info::cursor_x, vgacon_vc_info::cursor_y, and vgacon_vc_info::video_buffer.
Referenced by earlycon_putc().
void vgacon_early_set_attrib (int foreground, int background)
Definition at line 133 of file vgacon_early.c.
References vgacon_vc_info::attrib.
Variable Documentation
vgacon_vc_info_t vgacon_early_vc
Definition at line 5 of file vgacon_early.c.