posnk kernel: driver/console/vgacon.c File Reference
vgacon.c File Reference
#include "driver/console/vgacon/vgacon.h"
#include <string.h>
#include <stdint.h>
#include <sys/types.h>
#include "kernel/tty.h"
Macros
#define vgacon_vc vgacon_early_vc
Functions
volatile
vgacon_screen_character_t * vgacon_get_text_video_memory ()
void vgacon_putch (char c)
Write character to text buffer and move cursor.
void vgacon_move_cursor ()
void vgacon_handle_sgr (int par)
int vgacon_parse_par (char *str)
void vgacon_handle_escape (char c)
int vgacon_putc (dev_t dev, char c)
void vgacon_clear_video ()
void vgacon_clear_line ()
void vgacon_position (int x, int y, int move_cursor_)
void vgacon_set_attrib (int foreground, int background)
void vgacon_disable_scroll (int scroll)
void vgacon_write_crtc_register (char id, char val)
void kb_initialize ()
void vgacon_init ()
Variables
vgacon_vc_info_t vgacon_early_vc
int vgacon_colour_map [8] = {0,4,2,6,1,5,3,7}
char vgacon_escape_buf [20]
int vgacon_escape_ptr = 0
int vgacon_escape_spt = 0
int vgacon_escape_ppt = 0
int vgacon_escape_pars [10]
Macro Definition Documentation
#define vgacon_vc vgacon_early_vc
Definition at line 11 of file vgacon.c.
Function Documentation
void kb_initialize ()
Definition at line 9 of file kbd.c.
Referenced by vgacon_init(), and vterm_vga_init().
void vgacon_clear_line ()
Definition at line 221 of file vgacon.c.
References vgacon_vc::cursor_y, memset(), and vgacon_vc::video_buffer.
void vgacon_clear_video ()
Definition at line 213 of file vgacon.c.
References memset(), and vgacon_vc::video_buffer.
void vgacon_disable_scroll (int scroll)
Definition at line 243 of file vgacon.c.
volatile vgacon_screen_character_t* vgacon_get_text_video_memory ()
Todo:
: Check for paging init
Definition at line 13 of file vgacon.c.
void vgacon_handle_escape (char c)
Definition at line 107 of file vgacon.c.
References vgacon_vc::cursor_x, vgacon_vc::cursor_y, debugcon_aprintf(), vgacon_escape_ppt, vgacon_escape_ptr, vgacon_handle_sgr(), and vgacon_parse_par().
Referenced by vgacon_putc().
void vgacon_handle_sgr (int par)
Definition at line 61 of file vgacon.c.
References vgacon_colour_map.
Referenced by vgacon_handle_escape().
void vgacon_init ()
Definition at line 253 of file vgacon.c.
References kb_initialize(), sercon_init(), tty_register_driver(), and vgacon_putc().
void vgacon_move_cursor ()
Definition at line 54 of file vgacon.c.
References vgacon_vc::cursor_x, vgacon_vc::cursor_y, and vgacon_write_crtc_register().
Referenced by vgacon_position(), and vgacon_putc().
int vgacon_parse_par (char * str)
Definition at line 82 of file vgacon.c.
References strlen().
Referenced by vgacon_handle_escape().
void vgacon_position (int x, int y, int move_cursor_)
Definition at line 230 of file vgacon.c.
References vgacon_vc::cursor_x, vgacon_vc::cursor_y, and vgacon_move_cursor().
int vgacon_putc (dev_t dev, char c)
Definition at line 171 of file vgacon.c.
References vgacon_vc::cursor_x, vgacon_vc::cursor_y, vgacon_handle_escape(), vgacon_move_cursor(), and vgacon_putch().
Referenced by vgacon_init().
void vgacon_putch (char c)
Write character to text buffer and move cursor.
Definition at line 20 of file vgacon.c.
References vgacon_screen_character::attribute, vgacon_screen_character::character, vgacon_vc::cursor_x, vgacon_vc::cursor_y, and vgacon_vc::video_buffer.
Referenced by vgacon_putc().
void vgacon_set_attrib (int foreground, int background)
Definition at line 238 of file vgacon.c.
void vgacon_write_crtc_register (char id, char val)
Definition at line 247 of file vgacon.c.
References i386_outb().
Referenced by vgacon_early_move_cursor(), and vgacon_move_cursor().
Variable Documentation
int vgacon_colour_map[8] = {0,4,2,6,1,5,3,7}
Definition at line 9 of file vgacon.c.
Referenced by vgacon_handle_sgr().
vgacon_vc_info_t vgacon_early_vc
Definition at line 5 of file vgacon_early.c.
char vgacon_escape_buf[20]
Definition at line 76 of file vgacon.c.
int vgacon_escape_pars[10]
Definition at line 80 of file vgacon.c.
int vgacon_escape_ppt = 0
Definition at line 79 of file vgacon.c.
Referenced by vgacon_handle_escape().
int vgacon_escape_ptr = 0
Definition at line 77 of file vgacon.c.
Referenced by vgacon_handle_escape().
int vgacon_escape_spt = 0
Definition at line 78 of file vgacon.c.