posnk kernel: include/driver/console/vterm/vterm_csi.h File Reference
vterm_csi.h File Reference
#include "driver/console/vterm/vterm.h"
Macros
#define MAX_CSI_ES_PARAMS 32
Functions
void vterm_interpret_csi (vterm_t *vterm)
void interpret_dec_SM (vterm_t *vterm, int param[], int pcount)
void interpret_dec_RM (vterm_t *vterm, int param[], int pcount)
void interpret_csi_SGR (vterm_t *vterm, int param[], int pcount)
void interpret_csi_ED (vterm_t *vterm, int param[], int pcount)
void interpret_csi_CUP (vterm_t *vterm, int param[], int pcount)
void interpret_csi_EL (vterm_t *vterm, int param[], int pcount)
void interpret_csi_ICH (vterm_t *vterm, int param[], int pcount)
void interpret_csi_DCH (vterm_t *vterm, int param[], int pcount)
void interpret_csi_IL (vterm_t *vterm, int param[], int pcount)
void interpret_csi_DL (vterm_t *vterm, int param[], int pcount)
void interpret_csi_ECH (vterm_t *vterm, int param[], int pcount)
void interpret_csi_CUx (vterm_t *vterm, char verb, int param[], int pcount)
void interpret_csi_DECSTBM (vterm_t *vterm, int param[], int pcount)
void interpret_csi_SAVECUR (vterm_t *vterm, int param[], int pcount)
void interpret_csi_RESTORECUR (vterm_t *vterm, int param[], int pcount)
Macro Definition Documentation
#define MAX_CSI_ES_PARAMS 32
Definition at line 28 of file vterm_csi.h.
Referenced by vterm_interpret_csi().
Function Documentation
void interpret_csi_CUP (vterm_t * vterm, int param[], int pcount)
Definition at line 29 of file vterm_csi_CUP.c.
References _vterm_s::ccol, clamp_cursor_to_bounds(), and _vterm_s::crow.
Referenced by vterm_interpret_csi().
void interpret_csi_CUx (vterm_t * vterm, char verb, int param[], int pcount)
Definition at line 30 of file vterm_csi_CUx.c.
References _vterm_s::ccol, clamp_cursor_to_bounds(), and _vterm_s::crow.
Referenced by vterm_interpret_csi().
void interpret_csi_DCH (vterm_t * vterm, int param[], int pcount)
Definition at line 29 of file vterm_csi_DCH.c.
References _vterm_cell_s::attr, _vterm_s::ccol, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::crow, _vterm_s::curattr, and vterm_invalidate_cell().
Referenced by vterm_interpret_csi().
void interpret_csi_DECSTBM (vterm_t * vterm, int param[], int pcount)
Definition at line 30 of file vterm_csi_DECSTBM.c.
References _vterm_s::rows, _vterm_s::scroll_max, _vterm_s::scroll_min, _vterm_s::state, and STATE_SCROLL_SHORT.
Referenced by vterm_interpret_csi().
void interpret_csi_DL (vterm_t * vterm, int param[], int pcount)
Definition at line 30 of file vterm_csi_DL.c.
References _vterm_cell_s::attr, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::cols, _vterm_s::crow, _vterm_s::curattr, memcpy(), and vterm_invalidate_cell().
Referenced by vterm_interpret_csi().
void interpret_csi_ECH (vterm_t * vterm, int param[], int pcount)
Definition at line 28 of file vterm_csi_ECH.c.
References _vterm_cell_s::attr, _vterm_s::ccol, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::cols, _vterm_s::crow, _vterm_s::curattr, and vterm_invalidate_cell().
Referenced by vterm_interpret_csi().
void interpret_csi_ED (vterm_t * vterm, int param[], int pcount)
Definition at line 28 of file vterm_csi_ED.c.
References _vterm_cell_s::attr, _vterm_s::ccol, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::cols, _vterm_s::crow, _vterm_s::curattr, _vterm_s::rows, and vterm_invalidate_screen().
Referenced by vterm_interpret_csi().
void interpret_csi_EL (vterm_t * vterm, int param[], int pcount)
Definition at line 28 of file vterm_csi_EL.c.
References _vterm_cell_s::attr, _vterm_s::ccol, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::cols, _vterm_s::crow, _vterm_s::curattr, and vterm_invalidate_cell().
Referenced by vterm_interpret_csi().
void interpret_csi_ICH (vterm_t * vterm, int param[], int pcount)
Definition at line 28 of file vterm_csi_ICH.c.
References _vterm_cell_s::attr, _vterm_s::ccol, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::cols, _vterm_s::crow, _vterm_s::curattr, and vterm_invalidate_cell().
Referenced by vterm_interpret_csi().
void interpret_csi_IL (vterm_t * vterm, int param[], int pcount)
Definition at line 28 of file vterm_csi_IL.c.
References _vterm_cell_s::attr, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::cols, _vterm_s::crow, _vterm_s::curattr, memcpy(), _vterm_s::scroll_max, and vterm_invalidate_screen().
Referenced by vterm_interpret_csi().
void interpret_csi_RESTORECUR (vterm_t * vterm, int param[], int pcount)
Definition at line 27 of file vterm_csi_RESTORECUR.c.
References _vterm_s::ccol, _vterm_s::crow, _vterm_s::saved_x, and _vterm_s::saved_y.
Referenced by vterm_interpret_csi().
void interpret_csi_SAVECUR (vterm_t * vterm, int param[], int pcount)
Definition at line 27 of file vterm_csi_SAVECUR.c.
References _vterm_s::ccol, _vterm_s::crow, _vterm_s::saved_x, and _vterm_s::saved_y.
Referenced by vterm_interpret_csi().
void interpret_csi_SGR (vterm_t * vterm, int param[], int pcount)
Definition at line 53 of file vterm_csi_SGR.c.
References A_BLINK, A_BOLD, A_COLOR, A_INVIS, A_NORMAL, A_REVERSE, _vterm_s::bg, _vterm_s::curattr, _vterm_s::fg, find_color_pair(), _vterm_s::state, and STATE_ALT_CHARSET.
Referenced by vterm_interpret_csi().
void interpret_dec_RM (vterm_t * vterm, int param[], int pcount)
Definition at line 28 of file vterm_dec_RM.c.
References _vterm_s::state, and STATE_CURSOR_INVIS.
Referenced by vterm_interpret_csi().
void interpret_dec_SM (vterm_t * vterm, int param[], int pcount)
Definition at line 28 of file vterm_dec_SM.c.
References _vterm_s::state, and STATE_CURSOR_INVIS.
Referenced by vterm_interpret_csi().
void vterm_interpret_csi (vterm_t * vterm)
Definition at line 29 of file vterm_csi.c.
References _vterm_s::esbuf, _vterm_s::esbuf_len, interpret_csi_CUP(), interpret_csi_CUx(), interpret_csi_DCH(), interpret_csi_DECSTBM(), interpret_csi_DL(), interpret_csi_ECH(), interpret_csi_ED(), interpret_csi_EL(), interpret_csi_ICH(), interpret_csi_IL(), interpret_csi_RESTORECUR(), interpret_csi_SAVECUR(), interpret_csi_SGR(), interpret_dec_RM(), interpret_dec_SM(), and MAX_CSI_ES_PARAMS.
Referenced by try_interpret_escape_seq().