posnk kernel: driver/console/vterm/vterm_erase.c File Reference
vterm_erase.c File Reference
#include "driver/console/vterm/vterm.h"
#include "driver/console/vterm/vterm_private.h"
#include "driver/console/vterm/vterm_render.h"
Functions
void vterm_erase (vterm_t *vterm)
void vterm_erase_row (vterm_t *vterm, gint row)
void vterm_erase_rows (vterm_t *vterm, gint start_row)
void vterm_erase_col (vterm_t *vterm, gint col)
void vterm_erase_cols (vterm_t *vterm, gint start_col)
Function Documentation
void vterm_erase (vterm_t * vterm)
Definition at line 26 of file vterm_erase.c.
References A_COLOR, _vterm_cell_s::attr, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::colors, _vterm_s::cols, NULL, _vterm_s::rows, and vterm_invalidate_cell().
Referenced by vterm_init().
void vterm_erase_col (vterm_t * vterm, gint col)
Definition at line 80 of file vterm_erase.c.
References A_COLOR, _vterm_cell_s::attr, _vterm_s::ccol, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::colors, NULL, _vterm_s::rows, and vterm_invalidate_cell().
Referenced by vterm_erase_cols().
void vterm_erase_cols (vterm_t * vterm, gint start_col)
Definition at line 98 of file vterm_erase.c.
References NULL, and vterm_erase_col().
void vterm_erase_row (vterm_t * vterm, gint row)
Definition at line 48 of file vterm_erase.c.
References A_COLOR, _vterm_cell_s::attr, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::colors, _vterm_s::cols, _vterm_s::crow, NULL, and vterm_invalidate_cell().
Referenced by vterm_erase_rows(), vterm_scroll_down(), and vterm_scroll_up().
void vterm_erase_rows (vterm_t * vterm, gint start_row)
Definition at line 66 of file vterm_erase.c.
References NULL, and vterm_erase_row().