posnk kernel: include/driver/console/vterm/vterm.h File Reference
vterm.h File Reference
#include <glib.h>
Macros
#define LIBVTERM_VERSION "0.99.7"
#define VTERM_FLAG_VT100 (1<<1)
Typedefs
typedef struct _vterm_s vterm_t
Functions
void vterm_init (vterm_t *vterm, guint flags, int rows, int cols)
void vterm_destroy (vterm_t *vterm)
const gchar * vterm_get_ttyname (vterm_t *vterm)
ssize_t vterm_read_pipe (vterm_t *vterm)
void vterm_write_pipe (vterm_t *vterm, guint32 keycode)
int vterm_set_colors (vterm_t *vterm, short fg, short bg)
short vterm_get_colors (vterm_t *vterm)
void vterm_erase (vterm_t *vterm)
void vterm_erase_row (vterm_t *vterm, gint row)
void vterm_erase_rows (vterm_t *vterm, gint start_row)
void vterm_erase_col (vterm_t *vterm, gint col)
void vterm_erase_cols (vterm_t *vterm, gint start_cols)
void vterm_scroll_up (vterm_t *vterm)
void vterm_scroll_down (vterm_t *vterm)
void vterm_resize (vterm_t *vterm, guint width, guint height)
Macro Definition Documentation
#define LIBVTERM_VERSION "0.99.7"
Definition at line 30 of file vterm.h.
#define VTERM_FLAG_VT100 (1<<1)
Definition at line 32 of file vterm.h.
Referenced by vterm_init(), and vterm_tty_setup().
Typedef Documentation
typedef struct _vterm_s vterm_t
Definition at line 35 of file vterm.h.
Function Documentation
void vterm_destroy (vterm_t * vterm)
Definition at line 70 of file vterm.c.
References heapmm_free(), and NULL.
void vterm_erase (vterm_t * vterm)
Definition at line 26 of file vterm_erase.c.
References A_COLOR, _vterm_cell_s::attr, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::colors, _vterm_s::cols, NULL, _vterm_s::rows, and vterm_invalidate_cell().
Referenced by vterm_init().
void vterm_erase_col (vterm_t * vterm, gint col)
Definition at line 80 of file vterm_erase.c.
References A_COLOR, _vterm_cell_s::attr, _vterm_s::ccol, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::colors, NULL, _vterm_s::rows, and vterm_invalidate_cell().
Referenced by vterm_erase_cols().
void vterm_erase_cols (vterm_t * vterm, gint start_cols)
Definition at line 98 of file vterm_erase.c.
References NULL, and vterm_erase_col().
void vterm_erase_row (vterm_t * vterm, gint row)
Definition at line 48 of file vterm_erase.c.
References A_COLOR, _vterm_cell_s::attr, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::colors, _vterm_s::cols, _vterm_s::crow, NULL, and vterm_invalidate_cell().
Referenced by vterm_erase_rows(), vterm_scroll_down(), and vterm_scroll_up().
void vterm_erase_rows (vterm_t * vterm, gint start_row)
Definition at line 66 of file vterm_erase.c.
References NULL, and vterm_erase_row().
short vterm_get_colors (vterm_t * vterm)
Definition at line 44 of file vterm_colors.c.
References _vterm_s::colors, and NULL.
const gchar* vterm_get_ttyname (vterm_t * vterm)
Definition at line 78 of file vterm.c.
References NULL, and _vterm_s::ttyname.
void vterm_init (vterm_t * vterm, guint flags, int rows, int cols)
Todo:
:vterm->curattr=COLOR_PAIR(vterm->colors);
Definition at line 32 of file vterm.c.
References _vterm_s::bg, _vterm_s::ccol, _vterm_s::cells, _vterm_s::colors, _vterm_s::cols, _vterm_s::crow, _vterm_s::curattr, _vterm_s::fg, _vterm_s::flags, heapmm_alloc(), _vterm_s::rows, _vterm_s::scroll_max, _vterm_s::scroll_min, _vterm_s::state, vterm_erase(), VTERM_FLAG_VT100, vterm_write_rxvt(), vterm_write_vt100(), and _vterm_s::write.
Referenced by vterm_tty_setup().
ssize_t vterm_read_pipe (vterm_t * vterm)
void vterm_resize (vterm_t * vterm, guint width, guint height)
Definition at line 29 of file vterm_resize.c.
void vterm_scroll_down (vterm_t * vterm)
Definition at line 29 of file vterm_scroll.c.
References A_COLOR, _vterm_s::cells, _vterm_s::colors, _vterm_s::cols, _vterm_s::crow, memcpy(), _vterm_s::scroll_max, _vterm_s::scroll_min, vterm_erase_row(), and vterm_invalidate_screen().
Referenced by vterm_put_char(), and vterm_render_ctrl_char().
void vterm_scroll_up (vterm_t * vterm)
Definition at line 55 of file vterm_scroll.c.
References _vterm_s::cells, _vterm_s::cols, _vterm_s::crow, memcpy(), _vterm_s::scroll_max, _vterm_s::scroll_min, vterm_erase_row(), and vterm_invalidate_screen().
Referenced by try_interpret_escape_seq().
int vterm_set_colors (vterm_t * vterm, short fg, short bg)
Definition at line 29 of file vterm_colors.c.
References _vterm_s::colors, find_color_pair(), and NULL.
void vterm_write_pipe (vterm_t * vterm, guint32 keycode)
Definition at line 33 of file vterm_write.c.
References NULL, and _vterm_s::write.
Referenced by vterm_post_key_tty().