posnk kernel: include/driver/console/vterm/vterm_render.h File Reference
vterm_render.h File Reference
#include "driver/console/vterm/vterm.h"
Functions
void vterm_render (vterm_t *, const char *data, int len)
void vterm_put_char (vterm_t *vterm, chtype c)
void vterm_render_ctrl_char (vterm_t *vterm, char c)
void try_interpret_escape_seq (vterm_t *vterm)
void vterm_handle_bell (vterm_t *vterm)
void vterm_invalidate_cell (vterm_t *vt, int row, int col)
void vterm_invalidate_screen (vterm_t *vt)
void vterm_invalidate_cursor (vterm_t *vt)
Function Documentation
void try_interpret_escape_seq (vterm_t * vterm)
Definition at line 47 of file vterm_escape.c.
References _vterm_s::esbuf, _vterm_s::esbuf_len, ESEQ_BUF_SIZE, validate_escape_suffix(), vterm_escape_cancel(), vterm_interpret_csi(), and vterm_scroll_up().
Referenced by vterm_render().
void vterm_handle_bell (vterm_t * vterm)
Definition at line 86 of file vga_vterm.c.
Referenced by vterm_render_ctrl_char().
void vterm_invalidate_cell (vterm_t * vt, int row, int col)
Definition at line 67 of file vga_vterm.c.
References _vterm_cell_s::attr, vga_vterm_screen_character::attribute, _vterm_s::cells, _vterm_cell_s::ch, vga_vterm_screen_character::character, _vterm_s::device_id, MINOR, vga_vterm_map_attr(), and vgacon_vc::video_buffer.
Referenced by interpret_csi_DCH(), interpret_csi_DL(), interpret_csi_ECH(), interpret_csi_EL(), interpret_csi_ICH(), vterm_erase(), vterm_erase_col(), vterm_erase_row(), and vterm_put_char().
void vterm_invalidate_cursor (vterm_t * vt)
Definition at line 76 of file vga_vterm.c.
References vga_vterm_screen_character::attribute, _vterm_s::ccol, _vterm_s::crow, _vterm_s::curattr, _vterm_s::device_id, MINOR, vga_vterm_map_attr(), vgacon_vc::video_buffer, vterm_vga_current_vc, and vterm_vga_position().
Referenced by vterm_render().
void vterm_invalidate_screen (vterm_t * vt)
Definition at line 53 of file vga_vterm.c.
References _vterm_cell_s::attr, vga_vterm_screen_character::attribute, _vterm_s::ccol, _vterm_s::cells, _vterm_cell_s::ch, vga_vterm_screen_character::character, _vterm_s::cols, _vterm_s::crow, _vterm_s::device_id, MINOR, _vterm_s::rows, vga_vterm_map_attr(), vgacon_vc::video_buffer, and vterm_vga_position().
Referenced by interpret_csi_ED(), interpret_csi_IL(), vterm_scroll_down(), vterm_scroll_up(), and vterm_tty_invalidate_screen().
void vterm_put_char (vterm_t * vterm, chtype c)
Definition at line 31 of file vterm_render.c.
References _vterm_cell_s::attr, _vterm_s::ccol, _vterm_s::cells, _vterm_cell_s::ch, _vterm_s::cols, _vterm_s::crow, _vterm_s::curattr, IS_MODE_ACS, NULL, strchr(), vterm_invalidate_cell(), and vterm_scroll_down().
Referenced by vterm_render(), and vterm_render_ctrl_char().
void vterm_render (vterm_t * , const char * data, int len)
Definition at line 145 of file vterm_render.c.
References _vterm_s::esbuf, _vterm_s::esbuf_len, ESEQ_BUF_SIZE, IS_MODE_ESCAPED, try_interpret_escape_seq(), vterm_invalidate_cursor(), vterm_put_char(), and vterm_render_ctrl_char().
Referenced by vterm_putc().
void vterm_render_ctrl_char (vterm_t * vterm, char c)
Definition at line 60 of file vterm_render.c.
References _vterm_s::ccol, _vterm_s::esbuf, _vterm_s::esbuf_len, _vterm_s::state, STATE_ALT_CHARSET, vterm_escape_cancel(), vterm_escape_start(), vterm_handle_bell(), vterm_put_char(), and vterm_scroll_down().
Referenced by vterm_render().