posnk kernel: driver/console/vterm/vterm_misc.c File Reference
vterm_misc.c File Reference
#include "driver/console/vterm/vterm.h"
#include "driver/console/vterm/vterm_misc.h"
Functions
bool validate_escape_suffix (char c)
void clamp_cursor_to_bounds (vterm_t *vterm)
Function Documentation
void clamp_cursor_to_bounds (vterm_t * vterm)
Definition at line 37 of file vterm_misc.c.
References _vterm_s::ccol, _vterm_s::cols, _vterm_s::crow, and _vterm_s::rows.
Referenced by interpret_csi_CUP(), and interpret_csi_CUx().
bool validate_escape_suffix (char c)
Definition at line 26 of file vterm_misc.c.
References FALSE, and TRUE.
Referenced by try_interpret_escape_seq().