posnk kernel: driver/console/vterm/vterm_tty.c File Reference
vterm_tty.c File Reference
#include <string.h>
#include <glib.h>
#include <sys/types.h>
#include "driver/console/vterm/vterm.h"
#include "driver/console/vterm/vterm_private.h"
#include "driver/console/vterm/vterm_render.h"
#include "kernel/heapmm.h"
#include "kernel/tty.h"
Functions
void vterm_tty_invalidate_screen (dev_t dev)
void vterm_post_key_tty (dev_t dev, int keycode)
void vterm_write_tty (vterm_t *vterm, void *buffer, int size)
int vterm_putc (dev_t dev, char c)
void vterm_tty_setup (char *name, dev_t major, int minor_count, int rows, int cols)
Variables
vterm_t * vterm_minor_terms
driver/console/vterm/vterm_tty.h
Function Documentation
void vterm_post_key_tty (dev_t dev, int keycode)
Definition at line 50 of file vterm_tty.c.
References MINOR, and vterm_write_pipe().
Referenced by con_handle_key().
int vterm_putc (dev_t dev, char c)
Definition at line 63 of file vterm_tty.c.
References MINOR, and vterm_render().
Referenced by vterm_tty_setup().
void vterm_tty_invalidate_screen (dev_t dev)
Definition at line 45 of file vterm_tty.c.
References MINOR, and vterm_invalidate_screen().
Referenced by vterm_vga_switch_vc().
void vterm_tty_setup (char * name, dev_t major, int minor_count, int rows, int cols)
Definition at line 69 of file vterm_tty.c.
References _vterm_s::device_id, heapmm_alloc(), MAKEDEV, tty_register_driver(), VTERM_FLAG_VT100, vterm_init(), and vterm_putc().
Referenced by vterm_vga_init().
void vterm_write_tty (vterm_t * vterm, void * buffer, int size)
Definition at line 55 of file vterm_tty.c.
References _vterm_s::device_id, and tty_input_char().
Referenced by vterm_write_rxvt(), and vterm_write_vt100().
Variable Documentation
vterm_t* vterm_minor_terms
driver/console/vterm/vterm_tty.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 22-05-2014 - Created
Definition at line 43 of file vterm_tty.c.