posnk kernel: include/driver/console/vterm/vterm_write.h File Reference
vterm_write.h File Reference
#include <glib.h>
#include "driver/console/vterm/vterm.h"
Functions
void vterm_write_rxvt (vterm_t *vterm, guint32 keycode)
void vterm_write_vt100 (vterm_t *vterm, guint32 keycode)
Function Documentation
void vterm_write_rxvt (vterm_t * vterm, guint32 keycode)
Definition at line 44 of file vterm_write.c.
References KEY_BACKSPACE, KEY_DC, KEY_DOWN, KEY_END, KEY_F, KEY_HOME, KEY_IC, KEY_LEFT, KEY_NPAGE, KEY_PPAGE, KEY_RIGHT, KEY_SUSPEND, KEY_UP, NULL, strlen(), and vterm_write_tty().
Referenced by vterm_init().
void vterm_write_vt100 (vterm_t * vterm, guint32 keycode)
Definition at line 85 of file vterm_write.c.
References KEY_BACKSPACE, KEY_DC, KEY_DOWN, KEY_END, KEY_F, KEY_HOME, KEY_IC, KEY_LEFT, KEY_NPAGE, KEY_PPAGE, KEY_RIGHT, KEY_SUSPEND, KEY_UP, NULL, strlen(), and vterm_write_tty().
Referenced by vterm_init().