posnk kernel: include/arch/i386/x86.h File Reference
x86.h File Reference
#include <stdint.h>
Data Structures
struct i386_pusha_registers
Macros
#define I386_EXCEPTION_DIV_ZERO 0
#define I386_EXCEPTION_DEBUG 1
#define I386_EXCEPTION_BREAKPOINT 3
#define I386_EXCEPTION_OVERFLOW 4
#define I386_EXCEPTION_BOUNDS_CHECK 5
#define I386_EXCEPTION_INVALID_OPCODE 6
#define I386_EXCEPTION_NO_COPROCESSOR 7
#define I386_EXCEPTION_DOUBLE_FAULT 8
#define I386_EXCEPTION_COPROCESSOR_OVR 9
#define I386_EXCEPTION_INVALID_TSS 10
#define I386_EXCEPTION_SEG_FAULT 11
#define I386_EXCEPTION_STACK_EXCEPTION 12
#define I386_EXCEPTION_GP_FAULT 13
#define I386_EXCEPTION_PAGE_FAULT 14
#define I386_EXCEPTION_COPROCESSOR_ERR 16
Typedefs
typedef struct i386_pusha_registers i386_pusha_registers_t
Functions
uint8_t i386_inb (uint16_t port)
void i386_outb (uint16_t port, uint8_t data)
uint16_t i386_inw (uint16_t port)
void i386_outw (uint16_t port, uint16_t value)
uint32_t i386_inl (uint16_t port)
void i386_outl (uint16_t port, uint32_t value)
void i386_fpu_initialize ()
void i386_fpu_on_cs ()
int i386_fpu_handle_ill ()
Macro Definition Documentation
#define I386_EXCEPTION_BOUNDS_CHECK 5
Definition at line 14 of file x86.h.
#define I386_EXCEPTION_BREAKPOINT 3
Definition at line 12 of file x86.h.
#define I386_EXCEPTION_COPROCESSOR_ERR 16
Definition at line 24 of file x86.h.
#define I386_EXCEPTION_COPROCESSOR_OVR 9
Definition at line 18 of file x86.h.
#define I386_EXCEPTION_DEBUG 1
Definition at line 11 of file x86.h.
#define I386_EXCEPTION_DIV_ZERO 0
Definition at line 10 of file x86.h.
#define I386_EXCEPTION_DOUBLE_FAULT 8
Definition at line 17 of file x86.h.
#define I386_EXCEPTION_GP_FAULT 13
Definition at line 22 of file x86.h.
#define I386_EXCEPTION_INVALID_OPCODE 6
Definition at line 15 of file x86.h.
Referenced by i386_handle_interrupt().
#define I386_EXCEPTION_INVALID_TSS 10
Definition at line 19 of file x86.h.
#define I386_EXCEPTION_NO_COPROCESSOR 7
Definition at line 16 of file x86.h.
Referenced by i386_handle_interrupt().
#define I386_EXCEPTION_OVERFLOW 4
Definition at line 13 of file x86.h.
#define I386_EXCEPTION_PAGE_FAULT 14
Definition at line 23 of file x86.h.
Referenced by i386_handle_interrupt().
#define I386_EXCEPTION_SEG_FAULT 11
Definition at line 20 of file x86.h.
#define I386_EXCEPTION_STACK_EXCEPTION 12
Definition at line 21 of file x86.h.
Typedef Documentation
typedef struct i386_pusha_registers i386_pusha_registers_t
Definition at line 31 of file x86.h.
Function Documentation
int i386_fpu_handle_ill ()
Definition at line 71 of file fpu.c.
References process_info::arch_state, i386_enable_fpu(), i386_fpu_load(), i386_fpu_save(), i386_init_fpu(), and scheduler_current_task.
Referenced by i386_handle_interrupt().
void i386_fpu_initialize ()
Definition at line 26 of file fpu.c.
Referenced by i386_init_mm().
void i386_fpu_on_cs ()
Definition at line 65 of file fpu.c.
References i386_disable_fpu().
Referenced by scheduler_exsig(), and scheduler_switch_task().
uint8_t i386_inb (uint16_t port)
Definition at line 5 of file x86.c.
Referenced by ata_read_port(), debugcon_getc(), i386_pic_read_data(), is_transmit_empty(), kbd_controller_status(), kbd_encoder_read_buffer(), sercon_isr(), serial_received(), sis_transmit_empty(), and sserial_received().
uint32_t i386_inl (uint16_t port)
Definition at line 29 of file x86.c.
Referenced by ata_read_data(), and pci_config_read_long().
uint16_t i386_inw (uint16_t port)
Definition at line 17 of file x86.c.
void i386_outb (uint16_t port, uint8_t data)
Definition at line 12 of file x86.c.
Referenced by ata_write_port(), debugcon_init(), debugcon_putc(), i386_pic_send_command(), i386_pic_send_data(), i386_pit_send_command(), i386_pit_send_data(), kbd_send_controller_command(), kbd_send_encoder_command(), sercon_init(), sercon_putc(), vgacon_write_crtc_register(), and vterm_vga_write_crtc_register().
void i386_outl (uint16_t port, uint32_t value)
Definition at line 36 of file x86.c.
Referenced by ata_write_data(), ata_write_port_long(), pci_config_read_long(), and pci_config_write_long().
void i386_outw (uint16_t port, uint16_t value)
Definition at line 24 of file x86.c.