posnk kernel: arch/i386/x86.c File Reference
x86.c File Reference
#include "arch/i386/x86.h"
#include "kernel/earlycon.h"
#include <stddef.h>
Functions
uint8_t i386_inb (uint16_t port)
void i386_outb (uint16_t port, uint8_t value)
uint16_t i386_inw (uint16_t port)
void i386_outw (uint16_t port, uint16_t value)
uint32_t i386_inl (uint16_t port)
void i386_outl (uint16_t port, uint32_t value)
void halt ()
kernel/system.h
void debug_dump_state (void *state, size_t state_size)
util/debug.h
void debug_postmortem_hook (void *state, size_t state_size, void *instr_addr)
Function Documentation
void debug_dump_state (void * state, size_t state_size)
util/debug.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 02-04-2014 - Changed names, added comments
Definition at line 47 of file x86.c.
References earlycon_printf, earlycon_puts, i386_pusha_registers::eax, i386_pusha_registers::ebp, i386_pusha_registers::ebx, i386_pusha_registers::ecx, i386_pusha_registers::edi, i386_pusha_registers::edx, i386_pusha_registers::esi, and i386_pusha_registers::esp.
Referenced by exception_handle(), and exception_panic().
void debug_postmortem_hook (void * state, size_t state_size, void * instr_addr)
Definition at line 61 of file x86.c.
References dbgapi_invoke_kdbg(), earlycon_puts, i386_pusha_registers::ebp, and i386_pusha_registers::esp.
Referenced by exception_panic().
void halt ()
kernel/system.h
Part of P-OS kernel.
Written by Peter Bosch peter.nosp@m.bosc.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Changelog: 02-04-2014 - Created
Definition at line 42 of file x86.c.
Referenced by exception_panic(), and i386_kmain().
uint8_t i386_inb (uint16_t port)
Definition at line 5 of file x86.c.
Referenced by ata_read_port(), debugcon_getc(), i386_pic_read_data(), is_transmit_empty(), kbd_controller_status(), kbd_encoder_read_buffer(), sercon_isr(), serial_received(), sis_transmit_empty(), and sserial_received().
uint32_t i386_inl (uint16_t port)
Definition at line 29 of file x86.c.
Referenced by ata_read_data(), and pci_config_read_long().
uint16_t i386_inw (uint16_t port)
Definition at line 17 of file x86.c.
void i386_outb (uint16_t port, uint8_t value)
Definition at line 12 of file x86.c.
Referenced by ata_write_port(), debugcon_init(), debugcon_putc(), i386_pic_send_command(), i386_pic_send_data(), i386_pit_send_command(), i386_pit_send_data(), kbd_send_controller_command(), kbd_send_encoder_command(), sercon_init(), sercon_putc(), vgacon_write_crtc_register(), and vterm_vga_write_crtc_register().
void i386_outl (uint16_t port, uint32_t value)
Definition at line 36 of file x86.c.
Referenced by ata_write_data(), ata_write_port_long(), pci_config_read_long(), and pci_config_write_long().
void i386_outw (uint16_t port, uint16_t value)
Definition at line 24 of file x86.c.