#define ARCH_I386

//4MB
#define CONFIG_KERNEL_INITIAL_SIZE	(0x400000)

#define CONFIG_PROCESS_MAX_NAME_LENGTH	((size_t)128)
#define CONFIG_SYSTEM_PROCESS_NAME	("system task")
#define CONFIG_MASKABLE_SIGNAL_BITMAP   (0xFFFFFFFF)
#define CONFIG_MAX_SYSCALL_COUNT	(128)
#define CONFIG_FILE_MAX_NAME_LENGTH	((size_t)128)
#define CONFIG_PIPE_BUFFER_SIZE		(4096)

#define CONFIG_MAX_ARGV_LEN		(4096)
#define CONFIG_MAX_ENV_LEN		(4096)

#define CONFIG_TTY_BUFFER		(4096)
