SRCS_USERLIB=userlib/errno.c	\
	userlib/process/fork.c	\
	userlib/process/exit.c	\
	userlib/process/execve.c\
	userlib/process/kill.c	\
	userlib/process/yield.c	\
	userlib/process/sbrk.c	\
	userlib/process/mmap.c	\
	userlib/process/munmap.c\
	userlib/process/getpid.c\
	userlib/process/getppid.c\
	userlib/process/getsid.c\
	userlib/process/getpgrp.c\
	userlib/process/setsid.c\
	userlib/process/setpgid.c\
	userlib/process/setpgrp.c\
	userlib/process/waitpid.c\
	userlib/process/getuid.c\
	userlib/process/geteuid.c\
	userlib/process/getgid.c\
	userlib/process/getegid.c\
	userlib/signal/signal.c
